include $(pwre_dir_symbols)

-include $(pwre_kroot)/tools/bld/src/$(type_name)_generic.mk

-include special.mk

copy : $(web_dir)/pwr_logohalf.png $(web_dir)/pwr_logohalf2y.png $(doc_dir)/pwr_logoorm.png

$(web_dir)/pwr_logohalf.png : pwr_logohalf.png

$(web_dir)/pwr_logohalf2y.png : pwr_logohalf2y.png

$(doc_dir)/pwr_logoorm.png : pwr_logoorm.png
