/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include <cctype>
#include <sstream>
#include <regex>
#include <iomanip>

#include "co_log_parser.h"
#include "co_time.h"
#include "pwr.h"

std::unique_ptr<LogMessage> LogMessage::create_message(const std::string& line)
{
  LogFormat format = LogParser::detect_format(line);

  switch (format)
  {
  case LogFormat::RFC5424:
  {
    auto msg = std::make_unique<RFC5424Message>();
    msg->parse_from_string(line);
    return msg;
  }
  case LogFormat::PWRLOG:
  {
    auto msg = std::make_unique<PwrLogMessage>();
    msg->parse_from_string(line);
    return msg;
  }
  default:
    return nullptr;
  }
}

LogFormat LogParser::detect_format(const std::string& line)
{
  if (line.empty())
    return LogFormat::UNKNOWN;

  // RFC5424 format detection: use the dedicated function
  if (RFC5424Parser::is_rfc5424_format(line))
    return LogFormat::RFC5424;

  // PWR log format detection: severity character followed by space and program name
  if (line.length() > 2 &&
      (line[0] == 'S' || line[0] == 'I' || line[0] == 'W' || line[0] == 'E' || line[0] == 'F') &&
      line[1] == ' ')
  {
    return LogFormat::PWRLOG;
  }

  return LogFormat::UNKNOWN;
}

std::unique_ptr<LogParser> LogParser::create_parser(const std::string& line)
{
  LogFormat format = detect_format(line);

  switch (format)
  {
  case LogFormat::RFC5424:
    return std::make_unique<RFC5424Parser>();
  case LogFormat::PWRLOG:
    return std::make_unique<PwrLogParser>();
  default:
    return nullptr;
  }
}

// ============================================================================
// RFC5424Message Implementation
// ============================================================================

RFC5424Message::RFC5424Message() : priority(0), version(RFC5424_VERSION), valid_(false)
{
  time_GetTime(&timestamp);
}

RFC5424Facility RFC5424Message::facility() const { return static_cast<RFC5424Facility>(priority >> 3); }

RFC5424Severity RFC5424Message::severity() const { return static_cast<RFC5424Severity>(priority & 0x07); }

pwr_eSeverity RFC5424Message::proview_severity() const
{
  return RFC5424Parser::rfc5424_to_proview_severity(severity());
}

bool RFC5424Message::parse_from_string(const std::string& line)
{
  size_t pos = 0;
  valid_ = false;

  if (!parse_priority(line, pos))
    return false;
  if (!parse_version(line, pos))
    return false;
  if (!parse_timestamp(line, pos))
    return false;
  if (!parse_hostname(line, pos))
    return false;
  if (!parse_app_name(line, pos))
    return false;
  if (!parse_proc_id(line, pos))
    return false;
  if (!parse_msg_id(line, pos))
    return false;
  if (!parse_structured_data(line, pos))
    return false;
  if (!parse_message(line, pos))
    return false;

  valid_ = true;
  return true;
}

bool RFC5424Message::parse_priority(const std::string& line, size_t& pos)
{
  if (pos >= line.length() || line[pos] != '<')
    return false;
  size_t end = line.find('>', pos);
  if (end == std::string::npos)
    return false;
  try
  {
    priority = std::stoi(line.substr(pos + 1, end - pos - 1));
    pos = end + 1;
    return priority >= 0 && priority <= 191;
  }
  catch (...)
  {
    return false;
  }
}

bool RFC5424Message::parse_version(const std::string& line, size_t& pos)
{
  auto version_field = parse_field(line, pos);
  if (!version_field)
    return false;

  try
  {
    version = std::stoi(*version_field);
    // RFC5424 specifies version should be RFC5424_VERSION
    return version == RFC5424_VERSION;
  }
  catch (...)
  {
    return false;
  }
}

bool RFC5424Message::parse_timestamp(const std::string& line, size_t& pos)
{
  auto timestamp_field = parse_field(line, pos);
  if (!timestamp_field)
    return false;
  if (*timestamp_field == "-")
  {
    time_GetTime(&timestamp);
    return true;
  }
  return parse_rfc3339_timestamp(*timestamp_field);
}

bool RFC5424Message::parse_hostname(const std::string& line, size_t& pos)
{
  auto field = parse_field(line, pos);
  if (!field)
    return false;
  hostname = (*field == "-") ? "" : *field;
  return true;
}

bool RFC5424Message::parse_app_name(const std::string& line, size_t& pos)
{
  auto field = parse_field(line, pos);
  if (!field)
    return false;
  app_name = (*field == "-") ? "" : *field;
  return true;
}

bool RFC5424Message::parse_proc_id(const std::string& line, size_t& pos)
{
  auto field = parse_field(line, pos);
  if (!field)
    return false;
  proc_id = (*field == "-") ? "" : *field;
  return true;
}

bool RFC5424Message::parse_msg_id(const std::string& line, size_t& pos)
{
  auto field = parse_field(line, pos);
  if (!field)
    return false;
  msg_id = (*field == "-") ? "" : *field;
  return true;
}

bool RFC5424Message::parse_structured_data(const std::string& line, size_t& pos)
{
  skip_whitespace(line, pos);
  if (pos >= line.length())
    return false;

  if (line[pos] == '-')
  {
    // Nil value
    pos++;
    skip_whitespace(line, pos);
    return true;
  }

  // Parse structured data elements
  while (pos < line.length() && line[pos] == '[')
  {
    pos++; // Skip '['

    RFC5424StructuredDataElement element;

    // Parse SD-ID
    size_t id_end = line.find_first_of(" ]", pos);
    if (id_end == std::string::npos)
      return false;

    element.id = line.substr(pos, id_end - pos);
    pos = id_end;

    // Parse parameters
    while (pos < line.length() && line[pos] == ' ')
    {
      pos++; // Skip space

      // Parse parameter name
      size_t name_end = line.find('=', pos);
      if (name_end == std::string::npos)
        return false;

      std::string param_name = line.substr(pos, name_end - pos);
      pos = name_end + 1;

      // Parse parameter value (quoted)
      if (pos >= line.length() || line[pos] != '"')
        return false;
      pos++; // Skip opening quote

      std::string param_value;
      while (pos < line.length() && line[pos] != '"')
      {
        if (line[pos] == '\\' && pos + 1 < line.length())
        {
          // Handle escaped characters
          pos++;
          switch (line[pos])
          {
          case '"':
          case '\\':
          case ']':
            param_value += line[pos];
            break;
          default:
            param_value += '\\';
            param_value += line[pos];
          }
        }
        else
        {
          param_value += line[pos];
        }
        pos++;
      }

      if (pos >= line.length() || line[pos] != '"')
        return false;
      pos++; // Skip closing quote

      element.params[param_name] = param_value;
    }

    if (pos >= line.length() || line[pos] != ']')
      return false;
    pos++; // Skip ']'

    structured_data.push_back(element);
  }

  skip_whitespace(line, pos);
  return true;
}

bool RFC5424Message::parse_message(const std::string& line, size_t& pos)
{
  if (pos < line.length())
  {
    message = line.substr(pos);
  }
  return true; // Message can be empty
}

std::optional<std::string> RFC5424Message::parse_field(const std::string& line, size_t& pos, char delimiter)
{
  skip_whitespace(line, pos);
  if (pos >= line.length())
    return std::nullopt;

  size_t start = pos;
  while (pos < line.length() && line[pos] != delimiter)
    pos++;

  if (start == pos)
    return std::nullopt;

  std::string field = line.substr(start, pos - start);
  skip_whitespace(line, pos);

  return field;
}

void RFC5424Message::skip_whitespace(const std::string& line, size_t& pos)
{
  while (pos < line.length() && std::isspace(line[pos]))
    pos++;
}

bool RFC5424Message::parse_rfc3339_timestamp(const std::string& timestamp_str)
{
  // RFC3339 parsing with support for Z and timezone offsets (both +02:00 and +0200 formats)
  std::regex rfc3339_regex(
      R"((\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?(Z|[+-](\d{2})(?::?(\d{2}))))");

  std::smatch matches;
  if (!std::regex_match(timestamp_str, matches, rfc3339_regex))
  {
    return false;
  }

  try
  {
    int year = std::stoi(matches[1]);
    int month = std::stoi(matches[2]);
    int day = std::stoi(matches[3]);
    int hour = std::stoi(matches[4]);
    int minute = std::stoi(matches[5]);
    int second = std::stoi(matches[6]);

    // Handle fractional seconds (group 7 if present)
    long nanoseconds = 0;
    if (matches[7].matched)
    {
      std::string frac_str = matches[7].str();
      long frac = std::stol(frac_str);
      // Convert to nanoseconds based on number of digits
      int digits = frac_str.length();
      for (int i = digits; i < 9; i++)
      {
        frac *= 10;
      }
      for (int i = digits; i > 9; i--)
      {
        frac /= 10;
      }
      nanoseconds = frac;
    }

    // Parse timezone (group 8)
    std::string tz = matches[8].str();
    int tz_offset_seconds = 0;
    if (tz != "Z")
    {
      // Parse timezone offset like "+02:00" or "-05:00"
      int tz_hours = std::stoi(matches[9].str());
      int tz_minutes = std::stoi(matches[10].str());
      tz_offset_seconds = (tz_hours * 3600) + (tz_minutes * 60);
      if (tz[0] == '-')
      {
        tz_offset_seconds = -tz_offset_seconds;
      }
    }

    // Convert to UTC time
    struct tm tm_time = {0};
    tm_time.tm_year = year - 1900;
    tm_time.tm_mon = month - 1;
    tm_time.tm_mday = day;
    tm_time.tm_hour = hour;
    tm_time.tm_min = minute;
    tm_time.tm_sec = second;

// Use timegm to get UTC time (or mktime and adjust)
#ifdef __USE_MISC
    time_t unix_time = timegm(&tm_time);
#else
    // Fallback: use mktime and adjust for timezone
    time_t unix_time = mktime(&tm_time);
    // mktime assumes local time, so we need to adjust
    struct tm utc_tm;
    gmtime_r(&unix_time, &utc_tm);
    unix_time = mktime(&utc_tm);
#endif

    // Apply timezone offset (subtract because we want UTC)
    unix_time -= tz_offset_seconds;

    timestamp.tv_sec = unix_time;
    timestamp.tv_nsec = nanoseconds;

    return true;
  }
  catch (...)
  {
    return false;
  }
}

std::string RFC5424Message::get_structured_data_param(const std::string& element_id,
                                                      const std::string& param_name) const
{
  for (const auto& element : structured_data)
  {
    if (element.id == element_id)
    {
      auto it = element.params.find(param_name);
      if (it != element.params.end())
      {
        return it->second;
      }
    }
  }
  return "";
}

std::string RFC5424Message::to_string() const
{
  std::ostringstream oss;
  oss << "<" << priority << ">" << version << " ";

  if (!structured_data.empty())
  {
    for (const auto& element : structured_data)
    {
      oss << "[" << element.id;
      for (const auto& param : element.params)
      {
        oss << " " << param.first << "=\"" << param.second << "\"";
      }
      oss << "]";
    }
  }
  else
  {
    oss << "-";
  }

  if (!message.empty())
  {
    oss << " " << message;
  }

  return oss.str();
}

// ============================================================================
// RFC5424Parser Implementation
// ============================================================================

std::unique_ptr<LogMessage> RFC5424Parser::parse_line(const std::string& line)
{
  auto msg = std::make_unique<RFC5424Message>();
  msg->parse_from_string(line);
  return msg;
}

bool RFC5424Parser::is_format_supported(const std::string& line) { return is_rfc5424_format(line); }

bool RFC5424Parser::is_rfc5424_format(const std::string& line)
{
  if (line.empty() || line[0] != '<')
    return false;

  // Find the end of priority
  size_t pos = 1;
  while (pos < line.length() && std::isdigit(line[pos]))
    pos++;

  if (pos <= 1 || pos >= line.length() || line[pos] != '>')
    return false;

  pos++; // Skip '>'

  // Check for version field (should be RFC5424_VERSION followed by space)
  if (pos >= line.length() || line[pos] != ('0' + RFC5424_VERSION))
    return false;
  pos++;

  return pos < line.length() && line[pos] == ' ';
}

std::string RFC5424Parser::facility_to_string(RFC5424Facility facility)
{
  switch (facility)
  {
  case RFC5424Facility::KERNEL_MESSAGES:
    return "kernel";
  case RFC5424Facility::USER_LEVEL_MESSAGES:
    return "user";
  case RFC5424Facility::MAIL_SYSTEM:
    return "mail";
  case RFC5424Facility::SYSTEM_DAEMONS:
    return "daemon";
  case RFC5424Facility::SECURITY_AUTHORIZATION:
    return "auth";
  case RFC5424Facility::SYSLOGD_MESSAGES:
    return "syslog";
  case RFC5424Facility::LOCAL0:
    return "local0";
  case RFC5424Facility::LOCAL1:
    return "local1";
  case RFC5424Facility::LOCAL2:
    return "local2";
  case RFC5424Facility::LOCAL3:
    return "local3";
  case RFC5424Facility::LOCAL4:
    return "local4";
  case RFC5424Facility::LOCAL5:
    return "local5";
  case RFC5424Facility::LOCAL6:
    return "local6";
  case RFC5424Facility::LOCAL7:
    return "local7";
  default:
    return "unknown";
  }
}

std::string RFC5424Parser::severity_to_string(RFC5424Severity severity)
{
  switch (severity)
  {
  case RFC5424Severity::EMERGENCY:
    return "emerg";
  case RFC5424Severity::ALERT:
    return "alert";
  case RFC5424Severity::CRITICAL:
    return "crit";
  case RFC5424Severity::ERROR:
    return "err";
  case RFC5424Severity::WARNING:
    return "warning";
  case RFC5424Severity::NOTICE:
    return "notice";
  case RFC5424Severity::INFO:
    return "info";
  case RFC5424Severity::DEBUG:
    return "debug";
  default:
    return "unknown";
  }
}

pwr_eSeverity RFC5424Parser::rfc5424_to_proview_severity(RFC5424Severity severity)
{
  switch (severity)
  {
  case RFC5424Severity::EMERGENCY:
  case RFC5424Severity::ALERT:
  case RFC5424Severity::CRITICAL:
    return pwr_eSeverity_Fatal;
  case RFC5424Severity::ERROR:
    return pwr_eSeverity_Error;
  case RFC5424Severity::WARNING:
    return pwr_eSeverity_Warning;
  case RFC5424Severity::NOTICE:
  case RFC5424Severity::INFO:
    return pwr_eSeverity_Info;
  case RFC5424Severity::DEBUG:
    return pwr_eSeverity_Success;
  default:
    return pwr_eSeverity_Info;
  }
}

// ============================================================================
// PwrLogMessage Implementation
// ============================================================================

PwrLogMessage::PwrLogMessage() : severity_char('I'), pid(0), m_valid(false)
{
  time_GetTime(&timestamp);
  hostname = "localhost";
}

bool PwrLogMessage::parse_from_string(const std::string& line)
{
  size_t pos = 0;
  m_valid = false;

  // Parse: "S programName   12345678 25-09-23 14:32:01.00 message"
  if (!parse_severity(line, pos))
    return false;
  if (!parse_program_name(line, pos))
    return false;
  if (!parse_pid(line, pos))
    return false;
  if (!parse_timestamp(line, pos))
    return false;
  if (!parse_message(line, pos))
    return false;

  m_valid = true;
  return true;
}

bool PwrLogMessage::parse_severity(const std::string& line, size_t& pos)
{
  if (pos >= line.length())
    return false;

  severity_char = line[pos];
  if (severity_char != 'S' && severity_char != 'I' && severity_char != 'W' && severity_char != 'E' &&
      severity_char != 'F')
    return false;

  pos++;
  skip_whitespace(line, pos);
  return true;
}

bool PwrLogMessage::parse_program_name(const std::string& line, size_t& pos)
{
  if (pos >= line.length())
    return false;

  // Program name is fixed width, padded with spaces
  size_t start = pos;
  while (pos < line.length() && !std::isdigit(line[pos]))
    pos++;

  if (start == pos)
    return false;

  program_name = line.substr(start, pos - start);
  // Trim trailing spaces
  size_t end = program_name.find_last_not_of(' ');
  if (end != std::string::npos)
    program_name = program_name.substr(0, end + 1);

  skip_whitespace(line, pos);
  return true;
}

bool PwrLogMessage::parse_pid(const std::string& line, size_t& pos)
{
  if (pos >= line.length() || !std::isdigit(line[pos]))
    return false;

  size_t start = pos;
  while (pos < line.length() && std::isdigit(line[pos]))
    pos++;

  try
  {
    pid = std::stoi(line.substr(start, pos - start));
    skip_whitespace(line, pos);
    return true;
  }
  catch (...)
  {
    return false;
  }
}

bool PwrLogMessage::parse_timestamp(const std::string& line, size_t& pos)
{
  // Parse: "25-09-23 14:32:01.00"
  if (pos + 20 > line.length())
    return false;

  std::string timestamp_str = line.substr(pos, 20);
  pos += 20;

  // Simple parsing: YY-MM-DD HH:MM:SS.CC
  if (timestamp_str.length() != 20 || timestamp_str[2] != '-' || timestamp_str[5] != '-' ||
      timestamp_str[8] != ' ' || timestamp_str[11] != ':' || timestamp_str[14] != ':' ||
      timestamp_str[17] != '.')
  {
    return false;
  }

  try
  {
    // Convert YY-MM-DD to YYYY-MM-DD format for time_FormAsciiToA
    int year = std::stoi(timestamp_str.substr(0, 2)) + 2000;
    std::string full_timestamp = "20" + timestamp_str; // Convert YY to 20YY

    // Replace the first two digits with full year
    full_timestamp = std::to_string(year) + timestamp_str.substr(2);

    // Use ProviewR time function to handle timezone correctly (like original code)
    pwr_tStatus sts = time_FormAsciiToA(full_timestamp.c_str(), HUNDRED, GB, &timestamp);

    if (EVEN(sts))
    {
      return false;
    }

    skip_whitespace(line, pos);
    return true;
  }
  catch (...)
  {
    return false;
  }
}

bool PwrLogMessage::parse_message(const std::string& line, size_t& pos)
{
  if (pos < line.length())
  {
    message_text = line.substr(pos);
  }
  return true; // Message can be empty
}

void PwrLogMessage::skip_whitespace(const std::string& line, size_t& pos)
{
  while (pos < line.length() && std::isspace(line[pos]))
    pos++;
}

std::string PwrLogMessage::to_string() const
{
  std::ostringstream oss;
  oss << severity_char << " " << std::setw(16) << std::left << program_name << " " << std::setw(8) << pid
      << " ";

  // Format timestamp
  time_t unix_time = static_cast<time_t>(timestamp.tv_sec);
  struct tm* tm_time = localtime(&unix_time);
  oss << std::setfill('0') << std::setw(2) << (tm_time->tm_year % 100) << "-" << std::setw(2)
      << (tm_time->tm_mon + 1) << "-" << std::setw(2) << tm_time->tm_mday << " " << std::setw(2)
      << tm_time->tm_hour << ":" << std::setw(2) << tm_time->tm_min << ":" << std::setw(2) << tm_time->tm_sec
      << "." << std::setw(2) << (int)(timestamp.tv_nsec / 10000000) << " ";

  oss << message_text;
  return oss.str();
}

pwr_eSeverity PwrLogMessage::get_severity() const { return PwrLogParser::char_to_severity(severity_char); }

// ============================================================================
// PwrLogParser Implementation
// ============================================================================

std::unique_ptr<LogMessage> PwrLogParser::parse_line(const std::string& line)
{
  auto msg = std::make_unique<PwrLogMessage>();
  msg->parse_from_string(line);
  return msg;
}

bool PwrLogParser::is_format_supported(const std::string& line) { return is_pwrlog_format(line); }

bool PwrLogParser::is_pwrlog_format(const std::string& line)
{
  if (line.length() < 2)
    return false;

  char severity = line[0];
  return (severity == 'S' || severity == 'I' || severity == 'W' || severity == 'E' || severity == 'F') &&
         line[1] == ' ';
}

pwr_eSeverity PwrLogParser::char_to_severity(char severity_char)
{
  return pwr_char_to_severity(severity_char);
}

char PwrLogParser::severity_to_char(pwr_eSeverity severity) { return pwr_severity_to_char(severity); }
