/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef CO_LOG_SEVERITY_H
#define CO_LOG_SEVERITY_H

/**
 * @brief ProviewR severity levels for error handling and logging.
 *
 * This enum defines the standard severity levels used throughout ProviewR
 * for error handling, logging, and status reporting.
 */
typedef enum
{
  pwr_eSeverity_Null = 0,    /**< Null/uninitialized severity */
  pwr_eSeverity_Success = 1, /**< Operation successful */
  pwr_eSeverity_Info = 2,    /**< Informational message */
  pwr_eSeverity_Warning = 3, /**< Warning condition */
  pwr_eSeverity_Error = 4,   /**< Error condition */
  pwr_eSeverity_Fatal = 5    /**< Fatal error condition */
} pwr_eSeverity;

/**
 * @brief Convert severity to character representation.
 * @param severity The severity level.
 * @return Character representing the severity ('S', 'I', 'W', 'E', 'F').
 */
char pwr_severity_to_char(pwr_eSeverity severity);

/**
 * @brief Convert character to severity level.
 * @param severity_char Character representation ('S', 'I', 'W', 'E', 'F').
 * @return The corresponding severity level.
 */
pwr_eSeverity pwr_char_to_severity(char severity_char);

/**
 * @brief Convert severity to string representation.
 * @param severity The severity level.
 * @return String representation of the severity.
 */
const char* pwr_severity_to_string(pwr_eSeverity severity);

#endif // CO_LOG_SEVERITY_H