/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef co_log_parser_h
#define co_log_parser_h

#include <string>
#include <memory>
#include <map>
#include <vector>
#include <optional>
#include "co_time.h"
#include "co_log_severity.h"

/**
 * @brief RFC5424 protocol version constant.
 *
 * RFC5424 specifies that the VERSION field should be "1" for compliant messages.
 */
constexpr int RFC5424_VERSION = 1;

enum class LogFormat
{
  RFC5424,
  PWRLOG,
  UNKNOWN
};

// RFC5424 Facility and Severity definitions
enum class RFC5424Facility : int
{
  KERNEL_MESSAGES = 0,
  USER_LEVEL_MESSAGES = 1,
  MAIL_SYSTEM = 2,
  SYSTEM_DAEMONS = 3,
  SECURITY_AUTHORIZATION = 4,
  SYSLOGD_MESSAGES = 5,
  LINE_PRINTER_SUBSYSTEM = 6,
  NETWORK_NEWS_SUBSYSTEM = 7,
  UUCP_SUBSYSTEM = 8,
  CLOCK_DAEMON = 9,
  SECURITY_AUTHORIZATION_2 = 10,
  FTP_DAEMON = 11,
  NTP_SUBSYSTEM = 12,
  LOG_AUDIT = 13,
  LOG_ALERT = 14,
  CLOCK_DAEMON_2 = 15,
  LOCAL0 = 16,
  LOCAL1 = 17,
  LOCAL2 = 18,
  LOCAL3 = 19,
  LOCAL4 = 20,
  LOCAL5 = 21,
  LOCAL6 = 22,
  LOCAL7 = 23
};

enum class RFC5424Severity : int
{
  EMERGENCY = 0, // System is unusable
  ALERT = 1,     // Action must be taken immediately
  CRITICAL = 2,  // Critical conditions
  ERROR = 3,     // Error conditions
  WARNING = 4,   // Warning conditions
  NOTICE = 5,    // Normal but significant condition
  INFO = 6,      // Informational messages
  DEBUG = 7      // Debug-level messages
};

struct RFC5424StructuredDataElement
{
  std::string id;
  std::map<std::string, std::string> params;
};

// Abstract base class for log message parsers
class LogMessage
{
public:
  LogMessage() = default;
  virtual ~LogMessage() = default;

  // Factory method to create appropriate message based on format detection
  static std::unique_ptr<LogMessage> create_message(const std::string& line);

  // Pure virtual methods that derived classes must implement
  virtual bool parse_from_string(const std::string& line) = 0;
  virtual std::string to_string() const = 0;
  virtual bool is_valid() const = 0;
  virtual pwr_eSeverity get_severity() const = 0;
  virtual pwr_tTime get_timestamp() const = 0;
  virtual std::string get_hostname() const = 0;
  virtual std::string get_app_name() const = 0;
  virtual std::string get_message() const = 0;
};

// RFC5424 Message Implementation
class RFC5424Message : public LogMessage
{
public:
  RFC5424Message();
  ~RFC5424Message() override = default;

  int priority;         // PRI part
  int version;          // VERSION (should be 1 for RFC5424)
  pwr_tTime timestamp;  // TIMESTAMP
  std::string hostname; // HOSTNAME
  std::string app_name; // APP-NAME
  std::string proc_id;  // PROCID
  std::string msg_id;   // MSGID
  std::vector<RFC5424StructuredDataElement> structured_data;
  std::string message; // MSG

  RFC5424Facility facility() const;
  RFC5424Severity severity() const;
  pwr_eSeverity proview_severity() const;

  // Implement base class interface
  bool parse_from_string(const std::string& line) override;
  std::string to_string() const override;
  bool is_valid() const override { return valid_; }
  pwr_eSeverity get_severity() const override { return proview_severity(); }
  pwr_tTime get_timestamp() const override { return timestamp; }
  std::string get_hostname() const override { return hostname; }
  std::string get_app_name() const override { return app_name; }
  std::string get_message() const override { return message; }

  // RFC5424 specific methods
  std::string get_structured_data_param(const std::string& element_id, const std::string& param_name) const;

private:
  bool valid_;

  // Internal parsing helpers
  bool parse_priority(const std::string& line, size_t& pos);
  bool parse_version(const std::string& line, size_t& pos);
  bool parse_timestamp(const std::string& line, size_t& pos);
  bool parse_hostname(const std::string& line, size_t& pos);
  bool parse_app_name(const std::string& line, size_t& pos);
  bool parse_proc_id(const std::string& line, size_t& pos);
  bool parse_msg_id(const std::string& line, size_t& pos);
  bool parse_structured_data(const std::string& line, size_t& pos);
  bool parse_message(const std::string& line, size_t& pos);

  std::optional<std::string> parse_field(const std::string& line, size_t& pos, char delimiter = ' ');
  void skip_whitespace(const std::string& line, size_t& pos);
  bool parse_rfc3339_timestamp(const std::string& timestamp_str);
};

// PWR Log Message Implementation
class PwrLogMessage : public LogMessage
{
public:
  PwrLogMessage();
  ~PwrLogMessage() override = default;

  // Log components
  char severity_char;
  std::string program_name;
  int pid;
  pwr_tTime timestamp;
  std::string message_text;
  std::string hostname;

  // Implement base class interface
  bool parse_from_string(const std::string& line) override;
  std::string to_string() const override;
  bool is_valid() const override { return m_valid; }
  pwr_eSeverity get_severity() const override;
  pwr_tTime get_timestamp() const override { return timestamp; }
  std::string get_hostname() const override { return hostname; }
  std::string get_app_name() const override { return program_name; }
  std::string get_message() const override { return message_text; }

private:
  bool m_valid;

  // Parsing helpers
  bool parse_severity(const std::string& line, size_t& pos);
  bool parse_program_name(const std::string& line, size_t& pos);
  bool parse_pid(const std::string& line, size_t& pos);
  bool parse_timestamp(const std::string& line, size_t& pos);
  bool parse_message(const std::string& line, size_t& pos);
  void skip_whitespace(const std::string& line, size_t& pos);
};

// Abstract base parser class
class LogParser
{
public:
  LogParser() = default;
  virtual ~LogParser() = default;

  // Factory method to create appropriate parser based on format detection
  static std::unique_ptr<LogParser> create_parser(const std::string& line);
  static LogFormat detect_format(const std::string& line);

  // Pure virtual methods
  virtual std::unique_ptr<LogMessage> parse_line(const std::string& line) = 0;
  virtual bool is_format_supported(const std::string& line) = 0;
  virtual LogFormat get_format() const = 0;
};

// RFC5424 Parser Implementation
class RFC5424Parser : public LogParser
{
public:
  RFC5424Parser() = default;
  ~RFC5424Parser() override = default;

  // Implement base class interface
  std::unique_ptr<LogMessage> parse_line(const std::string& line) override;
  bool is_format_supported(const std::string& line) override;
  LogFormat get_format() const override { return LogFormat::RFC5424; }

  // Static utility methods
  static bool is_rfc5424_format(const std::string& line);
  static std::string facility_to_string(RFC5424Facility facility);
  static std::string severity_to_string(RFC5424Severity severity);
  static pwr_eSeverity rfc5424_to_proview_severity(RFC5424Severity severity);
};

// PWR Log Parser Implementation
class PwrLogParser : public LogParser
{
public:
  PwrLogParser() = default;
  ~PwrLogParser() override = default;

  std::unique_ptr<LogMessage> parse_line(const std::string& line) override;
  bool is_format_supported(const std::string& line) override;
  LogFormat get_format() const override { return LogFormat::PWRLOG; }

  // Static utility methods
  static bool is_pwrlog_format(const std::string& line);
  static pwr_eSeverity char_to_severity(char severity_char);
  static char severity_to_char(pwr_eSeverity severity);
};

#endif // co_log_parser_h
