/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include "co_log_severity.h"

char pwr_severity_to_char(pwr_eSeverity severity)
{
  switch (severity)
  {
  case pwr_eSeverity_Success:
    return 'S';
  case pwr_eSeverity_Info:
    return 'I';
  case pwr_eSeverity_Warning:
    return 'W';
  case pwr_eSeverity_Error:
    return 'E';
  case pwr_eSeverity_Fatal:
    return 'F';
  default:
    return 'I';
  }
}

pwr_eSeverity pwr_char_to_severity(char severity_char)
{
  switch (severity_char)
  {
  case 'S':
    return pwr_eSeverity_Success;
  case 'I':
    return pwr_eSeverity_Info;
  case 'W':
    return pwr_eSeverity_Warning;
  case 'E':
    return pwr_eSeverity_Error;
  case 'F':
    return pwr_eSeverity_Fatal;
  default:
    return pwr_eSeverity_Info;
  }
}

const char* pwr_severity_to_string(pwr_eSeverity severity)
{
  switch (severity)
  {
  case pwr_eSeverity_Success:
    return "SUCCESS";
  case pwr_eSeverity_Info:
    return "INFO";
  case pwr_eSeverity_Warning:
    return "WARNING";
  case pwr_eSeverity_Error:
    return "ERROR";
  case pwr_eSeverity_Fatal:
    return "FATAL";
  default:
    return "INFO";
  }
}