/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version of ProviewR used to
 * produce the combined work), being distributed under the terms of
 * the GNU General Public License plus this exception.
 */

#ifndef co_rfc5424_c_h
#define co_rfc5424_c_h

#include <stddef.h>

#ifdef __cplusplus
extern "C"
{
#endif

  /**
   * @brief C-compatible RFC5424 header formatter.
   *
   * This function provides RFC5424 syslog header formatting for C code without
   * pulling in C++ dependencies. The formatted header is written to the provided buffer.
   *
   * @param severity_char Character representing severity ('E', 'W', 'I', etc.)
   * @param app_name Application/module name (null-terminated string)
   * @param buffer Output buffer to write the formatted header
   * @param buffer_size Size of the output buffer
   * @return Number of characters written to buffer, or -1 on error
   */
  int co_rfc5424_format_header_c(char severity_char, const char* app_name, char* buffer, size_t buffer_size);

  /**
   * @brief Find the start index of the message in an RFC5424 formatted log entry (C interface).
   *
   * Parses an RFC5424 syslog formatted string to find where the actual message content begins.
   * The RFC5424 format is: <PRI>VERSION TIMESTAMP HOSTNAME APP-NAME PROCID MSGID STRUCTURED-DATA MSG
   *
   * @param log_entry The complete RFC5424 formatted log entry (null-terminated string)
   * @return Index where the message starts, or -1 if not valid RFC5424 format
   */
  int co_rfc5424_find_message_start_c(const char* log_entry);

#ifdef __cplusplus
}
#endif

#endif /* co_rfc5424_c_h */