/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */


#ifndef dataq_backup_h
#define dataq_backup_h

#define QBCK_FILEVERSION 1
#define QBCK_MAX_RECORDS 500

#define QBCK_FILE_EXT1 ".bck1"
#define QBCK_FILE_EXT2 ".bck2"

typedef struct {
  pwr_tTime creationtime;
  int version;
} qbck_tFileHeader;

typedef struct {
  pwr_tTime time;
  char type[32];
} qbck_tRecordHeader;

typedef struct {
  char type[32];
  pwr_tOid objid;
  pwr_tCid class;
  int size;
  int last;
} qbck_tQueueHeader;

typedef struct {
  char type[32];
  pwr_tOid objid;
  char data_name[120];
  pwr_tCid class;
  int size;
  int last;
} qbck_tDataHeader;

#define HEADERTYPE_RECORDSTART "Headertype record start"
#define HEADERTYPE_RECORDEND "Headertype record end"
#define HEADERTYPE_QUEUE "Headertype queue"
#define HEADERTYPE_QUEUEEND "Headertype queue end"
#define HEADERTYPE_DATA "Headertype data"
#define HEADERTYPE_DATAEND "Headertype data end"

#endif

