image: se-oxd-docker-registry.ssab.com/ssab/gitlab-triage-bot:v1

stages:
    - triage
    - run

dry-run:triage:
    stage: triage
    script:
        - export        
        - gitlab-triage --help
        - gitlab-triage --dry-run --token $API_TOKEN --source projects --source-id $CI_PROJECT_PATH
    when: manual
    except:
        - schedules
    tags:
        - docker

policy:run:
    stage: run
    script:        
        - gitlab-triage --token $API_TOKEN --source projects --source-id $CI_PROJECT_PATH
    when: manual
    except:
        - schedules
    tags:
        - docker

schedule:policyrun:
    stage: run
    script:        
        - gitlab-triage --token $API_TOKEN --source projects --source-id $CI_PROJECT_PATH
    only:
        - schedules
    tags:
        - docker