resource_rules:
    issues:
      rules:
        - name: Unlabeled Issues
          conditions:
            state: opened
            labels:
              - None
          actions:
            labels:
              - Needs Triage
        - name: New Issues
          conditions:
            date:
              attribute: created_at
              condition: newer_than
              interval_type: days
              interval: 8
            state: opened
          actions:
            labels:
              - New
        - name: Not New Issues
          conditions:
            date:
              attribute: created_at
              condition: older_than
              interval_type: days
              interval: 8
            state: opened
          actions:
            remove_labels:
              - New
        - name: No Longer Stale Issues
          conditions:
            date:
              attribute: updated_at
              condition: newer_than
              interval_type: months
              interval: 12
            state: opened
            labels:
              - Stale
          actions:
            remove_labels:
              - Stale
            comment: |
              Removing label Stale as this has had updates.
        - name: Stale Issues
          conditions:
            date:
              attribute: updated_at
              condition: older_than
              interval_type: months
              interval: 12
            state: opened
          actions:
            labels:
              - Stale
            comment: |
              This issue haven't had any updates for 12 months and will be marked stale. Please update this issue to keep it alive, otherwise it will be automatically closed in 3 months.
        - name: Auto Close Issues
          conditions:
            date:
              attribute: updated_at
              condition: older_than
              interval_type: months
              interval: 3
            state: opened
            labels:
              - Stale
          actions:
            status: close
            remove_labels:
              - Stale
            comment: |
              Closing this issue due to being stale for 3 months.
        - name: Unassigned
          conditions:            
            state: opened
            ruby: resource["assignees"].length == 0            
          actions:            
            labels:
              - Unassigned
        - name: Assigned
          conditions:            
            state: opened
            ruby: resource["assignees"].length > 0
          actions:            
            remove_labels:
              - Unassigned
            



        




