/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2022 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include "glow_colpalctx.h"
#include "glow_colpalwidget_gtk.h"
#include "glow_draw_gtk.h"

typedef struct _ColPalWidgetGtk ColPalWidgetGtk;
typedef struct _ColPalWidgetGtkClass ColPalWidgetGtkClass;
typedef struct _ColPalWidgetGtkPrivate ColPalWidgetGtkPrivate;

typedef struct {
  GtkWidget* colpal;
  GtkWidget* form;
  GtkWidget* scroll_h;
  GtkWidget* scroll_v;
  int scroll_h_managed;
  int scroll_v_managed;
} colpalwidget_sScroll;

struct _ColPalWidgetGtk {
  GtkDrawingArea bin;
  ColPalWidgetGtkPrivate *priv;
};

struct _ColPalWidgetGtkPrivate {
  GdkWindow *window;
  void* colpal_ctx;
  void* draw_ctx;
  int (*init_proc)(GlowCtx* ctx, void* clien_data);
  int is_navigator;
  void* client_data;
  GtkWidget* main_colpal_widget;
  GtkWidget* scroll_h;
  GtkWidget* scroll_v;
  GtkWidget* form;
  int scroll_h_ignore;
  int scroll_v_ignore;
  gdouble scroll_h_value;
  gdouble scroll_v_value;
  int scroll_h_pagesize;
  int scroll_v_pagesize;
  int scroll_h_upper;
  int scroll_v_upper;
  gint scroll_timerid;
  glow_sScroll scroll_data;
  int scroll_configure;
  int destroyed;
  GtkAdjustment* hadjustment;
  GtkAdjustment* vadjustment;
  guint hscroll_policy : 1;
  guint vscroll_policy : 1;
};

enum {
  PROP_0,
  PROP_HADJUSTMENT,
  PROP_VADJUSTMENT,
  PROP_HSCROLL_POLICY,
  PROP_VSCROLL_POLICY
};

struct _ColPalWidgetGtkClass {
  GtkDrawingAreaClass parent_class;
};

G_DEFINE_TYPE_WITH_CODE(ColPalWidgetGtk, colpalwidgetgtk, GTK_TYPE_DRAWING_AREA,
	      G_ADD_PRIVATE(ColPalWidgetGtk)
	      G_IMPLEMENT_INTERFACE(GTK_TYPE_SCROLLABLE, NULL));

static gboolean scroll_callback_cb(void* d);
static void colpalwidgetgtk_get_property(GObject *object, guint prop_id, 
				       GValue *value, GParamSpec *pspec);
static void colpalwidgetgtk_set_property(GObject *object, guint prop_id, 
				       const GValue *value, GParamSpec *pspec);

static void scroll_callback(glow_sScroll* data)
{
  colpalwidget_sScroll* scroll_data = (colpalwidget_sScroll*)data->scroll_data;
  ColPalWidgetGtkPrivate *colpal = (ColPalWidgetGtkPrivate *)((ColPalWidgetGtk*)scroll_data->colpal)->priv;

  if (colpal->scroll_timerid)
    g_source_remove(colpal->scroll_timerid);

  colpal->scroll_timerid = g_timeout_add(200, scroll_callback_cb, scroll_data->colpal);
  colpal->scroll_data = *data;
}

static gboolean scroll_callback_cb(void* d)
{
  ColPalWidgetGtkPrivate *colpal = ((ColPalWidgetGtk*)d)->priv;
  glow_sScroll* data = &colpal->scroll_data;
  colpalwidget_sScroll* scroll_data = (colpalwidget_sScroll*)data->scroll_data;
  GtkAdjustment *adj;

  colpal->scroll_timerid = 0;

  if (data->total_width <= data->window_width) {
    if (data->offset_x == 0)
      data->total_width = data->window_width;
    if (scroll_data->scroll_h_managed) {
      // Remove horizontal scrollbar
    }
  } else {
    if (!scroll_data->scroll_h_managed) {
      // Insert horizontal scrollbar
    }
  }

  if (data->total_height <= data->window_height) {
    if (data->offset_y == 0)
      data->total_height = data->window_height;
    if (scroll_data->scroll_v_managed) {
      // Remove vertical scrollbar
    }
  } else {
    if (!scroll_data->scroll_v_managed) {
      // Insert vertical scrollbar
    }
  }
  if (data->offset_x < 0) {
    data->total_width += -data->offset_x;
    data->offset_x = 0;
  }
  if (data->offset_y < 0) {
    data->total_height += -data->offset_y;
    data->offset_y = 0;
  }
  if (data->total_height < data->window_height + data->offset_y)
    data->total_height = data->window_height + data->offset_y;
  if (data->total_width < data->window_width + data->offset_x)
    data->total_width = data->window_width + data->offset_x;
  if (data->window_width < 1)
    data->window_width = 1;
  if (data->window_height < 1)
    data->window_height = 1;

  if (scroll_data->scroll_h_managed) {
    colpal->scroll_h_ignore = 1;
    if (data->window_width != colpal->scroll_h_pagesize
        || data->total_width != colpal->scroll_h_upper
        || colpal->scroll_configure) {
      adj = gtk_range_get_adjustment(GTK_RANGE(scroll_data->scroll_h));
      gtk_adjustment_set_value(adj, data->offset_x);
      gtk_adjustment_set_upper(adj, data->total_width);
      gtk_adjustment_set_page_size(adj, data->window_width);
    } else {
      adj = gtk_range_get_adjustment(GTK_RANGE(scroll_data->scroll_h));
      gtk_adjustment_set_value(adj, data->offset_x);
    }
    colpal->scroll_h_value = (gdouble)data->offset_x;
    colpal->scroll_h_pagesize = data->window_width;
    colpal->scroll_h_upper = data->total_width;
  }

  if (scroll_data->scroll_v_managed) {
    colpal->scroll_v_ignore = 1;
    if (data->window_height != colpal->scroll_v_pagesize
        || data->total_height != colpal->scroll_v_upper
        || colpal->scroll_configure) {
      adj = gtk_range_get_adjustment(GTK_RANGE(scroll_data->scroll_v));
      gtk_adjustment_set_upper(adj, data->total_height);
      gtk_adjustment_set_page_size(adj, data->window_height);
      gtk_adjustment_set_value(adj, data->offset_y);
    } else {
      gtk_range_set_value(
          GTK_RANGE(scroll_data->scroll_v), (gdouble)data->offset_y);
    }
    colpal->scroll_v_value = (gdouble)data->offset_y;
    colpal->scroll_h_pagesize = data->window_width;
    colpal->scroll_h_upper = data->total_width;
  }
  colpal->scroll_configure = 0;
  return FALSE;
}

static void scroll_h_action(GtkWidget* w, gpointer data)
{
  ColPalWidgetGtkPrivate* colpalw = ((ColPalWidgetGtk*)data)->priv;
  if (colpalw->scroll_h_ignore) {
    colpalw->scroll_h_ignore = 0;
    return;
  }

  ColPalCtx* ctx = (ColPalCtx*)colpalw->colpal_ctx;
  gdouble value;
  g_object_get(w, "value", &value, NULL);
  glow_scroll_horizontal(ctx, int(value), 0);
}

static void scroll_v_action(GtkWidget* w, gpointer data)
{
  ColPalWidgetGtkPrivate* colpalw = ((ColPalWidgetGtk*)data)->priv;

  if (colpalw->scroll_v_ignore) {
    colpalw->scroll_v_ignore = 0;
    return;
  }

  ColPalCtx* ctx = (ColPalCtx*)colpalw->colpal_ctx;
  gdouble value;
  g_object_get(w, "value", &value, NULL);
  glow_scroll_vertical(ctx, int(value), 0);
}

static int colpal_init_proc(GtkWidget* w, GlowCtx* fctx, void* client_data)
{
  colpalwidget_sScroll* scroll_data;
  ColPalCtx* ctx;

  ctx = (ColPalCtx*)((ColPalWidgetGtk*)w)->priv->colpal_ctx;

  if (((ColPalWidgetGtk*)w)->priv->scroll_h) {
    scroll_data = (colpalwidget_sScroll*)malloc(sizeof(colpalwidget_sScroll));
    scroll_data->colpal = w;
    scroll_data->scroll_h = ((ColPalWidgetGtk*)w)->priv->scroll_h;
    scroll_data->scroll_v = ((ColPalWidgetGtk*)w)->priv->scroll_v;
    scroll_data->form = ((ColPalWidgetGtk*)w)->priv->form;
    scroll_data->scroll_h_managed = 1;
    scroll_data->scroll_v_managed = 1;

    ctx->register_scroll_callback((void*)scroll_data, scroll_callback);
  }

  ctx->set_nodraw();
  ctx->configure();
  ctx->reset_nodraw();

  if (((ColPalWidgetGtk*)w)->priv->init_proc)
    return (((ColPalWidgetGtk*)w)->priv->init_proc)(ctx, client_data);
  else
    return 1;
}

static gboolean colpalwidgetgtk_expose(GtkWidget* widget, cairo_t* cr)
{
  ColPalWidgetGtk* colpal = (ColPalWidgetGtk*)widget;
  ((GlowDrawGtk*)((ColPalCtx*)colpal->priv->colpal_ctx)->gdraw)->
      expose(cr, colpal->priv->is_navigator);
  return TRUE;
}

static void colpalwidgetgtk_destroy(GtkWidget* widget)
{
  ColPalWidgetGtk* colpal = (ColPalWidgetGtk*)widget;

  if (!colpal->priv->destroyed) {
    colpal->priv->destroyed = 1;
    if (colpal->priv->scroll_timerid)
      g_source_remove(colpal->priv->scroll_timerid);
    if (colpal->priv->is_navigator) {
      if (colpal->priv->colpal_ctx
          && !((ColPalWidgetGtk*)colpal->priv->main_colpal_widget)->priv->destroyed)
        ((ColPalCtx*)colpal->priv->colpal_ctx)->no_nav = 1;
    } else
      delete (GlowDrawGtk*)colpal->priv->draw_ctx;
    if (colpal->priv->hadjustment)
      g_object_unref(colpal->priv->hadjustment);
    if (colpal->priv->vadjustment)
      g_object_unref(colpal->priv->vadjustment);
  }
  GTK_WIDGET_CLASS(colpalwidgetgtk_parent_class)->destroy(widget);
}

static gboolean colpalwidgetgtk_event(GtkWidget* colpal, GdkEvent* event)
{
  if (((ColPalWidgetGtk*)colpal)->priv->destroyed)
   return TRUE;

  if (event->type == GDK_MOTION_NOTIFY) {
    GdkEvent* next = gdk_event_peek();
    if (next && next->type == GDK_MOTION_NOTIFY) {
      gdk_event_free(next);
      return TRUE;
    } else if (next)
      gdk_event_free(next);
  }

  ((GlowDrawGtk*)((ColPalCtx*)((ColPalWidgetGtk*)colpal)->priv->colpal_ctx)->gdraw)
      ->event_handler(*event);
  return TRUE;
}

static void colpalwidgetgtk_realize(GtkWidget* widget)
{
  GdkWindowAttr attr;
  gint attr_mask;
  ColPalWidgetGtk* colpal;
  GtkAllocation allocation;

  g_return_if_fail(widget != NULL);
  g_return_if_fail(IS_COLPALWIDGETGTK(widget));

  gtk_widget_set_realized(widget, TRUE);
  colpal = COLPALWIDGETGTK(widget);

  gtk_widget_get_allocation(widget, &allocation);
  attr.x = allocation.x;
  attr.y = allocation.y;
  attr.width = allocation.width;
  attr.height = allocation.height;
  attr.wclass = GDK_INPUT_OUTPUT;
  attr.window_type = GDK_WINDOW_CHILD;
  attr.event_mask = gtk_widget_get_events(widget) | GDK_EXPOSURE_MASK
      | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK
      | GDK_POINTER_MOTION_MASK | GDK_BUTTON_MOTION_MASK | GDK_ENTER_NOTIFY_MASK
      | GDK_LEAVE_NOTIFY_MASK;
  attr.visual = gtk_widget_get_visual(widget);

  attr_mask = GDK_WA_X | GDK_WA_Y | GDK_WA_VISUAL;
  colpal->priv->window = gdk_window_new(gtk_widget_get_parent_window(widget), &attr, attr_mask);
  gtk_widget_set_window(widget, colpal->priv->window);
  gtk_widget_register_window(widget, colpal->priv->window);
  //widget->style = gtk_style_attach(widget->style, widget->window);
  //gtk_style_set_background(widget->style, widget->window, GTK_STATE_ACTIVE);

  gtk_widget_set_can_focus(widget, TRUE);

  if (colpal->priv->is_navigator) {
    if (!colpal->priv->colpal_ctx) {
      ColPalWidgetGtk* main_colpal
          = (ColPalWidgetGtk*)colpal->priv->main_colpal_widget;

      colpal->priv->colpal_ctx = main_colpal->priv->colpal_ctx;
      colpal->priv->draw_ctx = main_colpal->priv->draw_ctx;
      ((GlowDrawGtk*)colpal->priv->draw_ctx)->init_nav(widget);
    }
  } else {
    if (!colpal->priv->colpal_ctx) {
      colpal->priv->draw_ctx = new GlowDrawGtk(widget, &colpal->priv->colpal_ctx,
          colpal_init_proc, colpal->priv->client_data, glow_eCtxType_ColPal);
      ((GlowDrawGtk*)colpal->priv->draw_ctx)->set_anti_aliasing(0);
    }
  }
}

static void colpalwidgetgtk_class_init(ColPalWidgetGtkClass* klass)
{
  GtkWidgetClass* widget_class = GTK_WIDGET_CLASS(klass);
  GObjectClass* gobject_class = G_OBJECT_CLASS(klass);

  widget_class->realize = colpalwidgetgtk_realize;
  widget_class->draw = colpalwidgetgtk_expose;
  widget_class->event = colpalwidgetgtk_event;
  widget_class->destroy = colpalwidgetgtk_destroy;
  gobject_class->set_property = colpalwidgetgtk_set_property;
  gobject_class->get_property = colpalwidgetgtk_get_property;

  gtk_widget_class_set_css_name(widget_class, "colpalwidget");

  // GtkScrollable interface
  g_object_class_override_property(gobject_class, PROP_HADJUSTMENT, "hadjustment");
  g_object_class_override_property(gobject_class, PROP_VADJUSTMENT, "vadjustment");
  g_object_class_override_property(gobject_class, PROP_HSCROLL_POLICY, "hscroll-policy");
  g_object_class_override_property(gobject_class, PROP_VSCROLL_POLICY, "vscroll-policy");
}

static void colpalwidgetgtk_init(ColPalWidgetGtk* colpal)
{
  colpal->priv = (ColPalWidgetGtkPrivate *)colpalwidgetgtk_get_instance_private(colpal);
}

GtkWidget* colpalwidgetgtk_new(
    int (*init_proc)(GlowCtx* ctx, void* client_data), void* client_data)
{
  ColPalWidgetGtk* w;
  w = (ColPalWidgetGtk*)g_object_new(COLPALWIDGETGTK_TYPE, NULL);
  w->priv->init_proc = init_proc;
  w->priv->colpal_ctx = 0;
  w->priv->is_navigator = 0;
  w->priv->client_data = client_data;
  w->priv->scroll_h = 0;
  w->priv->scroll_v = 0;
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_value = 0;
  w->priv->scroll_v_value = 0;
  w->priv->scroll_configure = 0;
  w->priv->hadjustment = NULL;
  w->priv->vadjustment = NULL;
  w->priv->destroyed = 0;
  return (GtkWidget*)w;
}

GtkWidget* scrolledcolpalwidgetgtk_new(
    int (*init_proc)(GlowCtx* ctx, void* client_data), void* client_data,
    GtkWidget** colpalwidget)
{
  ColPalWidgetGtk* w;

  GtkWidget* form = gtk_scrolled_window_new(NULL, NULL);

  w = (ColPalWidgetGtk*)g_object_new(COLPALWIDGETGTK_TYPE, NULL);
  w->priv->init_proc = init_proc;
  w->priv->colpal_ctx = 0;
  w->priv->is_navigator = 0;
  w->priv->client_data = client_data;
  w->priv->scroll_h = gtk_scrolled_window_get_hscrollbar(GTK_SCROLLED_WINDOW(form));
  w->priv->scroll_v = gtk_scrolled_window_get_vscrollbar(GTK_SCROLLED_WINDOW(form));
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_value = 0;
  w->priv->scroll_v_value = 0;
  w->priv->scroll_configure = 0;
  w->priv->form = form;
  w->priv->hadjustment = gtk_adjustment_new(0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
  w->priv->vadjustment = gtk_adjustment_new(0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
  w->priv->destroyed = 0;

  *colpalwidget = GTK_WIDGET(w);

  g_signal_connect(gtk_range_get_adjustment(GTK_RANGE((GtkScrollbar*)w->priv->scroll_h)),
      "value-changed", G_CALLBACK(scroll_h_action), w);
  g_signal_connect(gtk_range_get_adjustment(GTK_RANGE((GtkScrollbar*)w->priv->scroll_v)),
      "value-changed", G_CALLBACK(scroll_v_action), w);

  gtk_container_add(GTK_CONTAINER(form), GTK_WIDGET(w));

  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(form), GTK_POLICY_ALWAYS, GTK_POLICY_ALWAYS);
  return (GtkWidget*)form;
}

GtkWidget* colpalnavwidgetgtk_new(GtkWidget* main_colpal)
{
  ColPalWidgetGtk* w;
  w = (ColPalWidgetGtk*)g_object_new(COLPALWIDGETGTK_TYPE, NULL);
  w->priv->init_proc = 0;
  w->priv->colpal_ctx = 0;
  w->priv->is_navigator = 1;
  w->priv->main_colpal_widget = main_colpal;
  w->priv->client_data = 0;
  w->priv->scroll_h = 0;
  w->priv->scroll_v = 0;
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_value = 0;
  w->priv->scroll_v_value = 0;
  w->priv->scroll_configure = 0;
  w->priv->hadjustment = NULL;
  w->priv->vadjustment = NULL;
  w->priv->destroyed = 0;
  return (GtkWidget*)w;
}

static void colpalwidgetgtk_set_property(GObject *object, guint prop_id, 
				       const GValue *value, GParamSpec *pspec)
{
  //FlowWidgetGtk *flow = (FlowWidgetGtk *)object;

  switch (prop_id) {
  case PROP_HADJUSTMENT:
    break;
  case PROP_VADJUSTMENT:
    break;
  case PROP_HSCROLL_POLICY:
    break;
  case PROP_VSCROLL_POLICY:
    break;
  }
}

static void colpalwidgetgtk_get_property(GObject *object, guint prop_id, 
				       GValue *value, GParamSpec *pspec)
{
  ColPalWidgetGtk *colpal = (ColPalWidgetGtk *)object;

  switch (prop_id) {
  case PROP_HADJUSTMENT:
    g_value_set_object(value, colpal->priv->hadjustment);
    break;
  case PROP_VADJUSTMENT:
    g_value_set_object(value, colpal->priv->vadjustment);
    break;
  case PROP_HSCROLL_POLICY:
    g_value_set_enum(value, colpal->priv->hscroll_policy);
    break;
  case PROP_VSCROLL_POLICY:
    g_value_set_enum(value, colpal->priv->vscroll_policy);
    break;
  }
}

