/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2023 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include <math.h>

#include "glow_draw_gtk.h"
#include "glow_growwidget_gtk.h"

typedef struct _GrowWidgetGtk GrowWidgetGtk;
typedef struct _GrowWidgetGtkClass GrowWidgetGtkClass;
typedef struct _GrowWidgetGtkPrivate GrowWidgetGtkPrivate;

typedef struct {
  GtkWidget* grow;
  GtkWidget* form;
  GtkWidget* scroll_h;
  GtkWidget* scroll_v;
  int scroll_h_managed;
  int scroll_v_managed;
} growwidget_sScroll;

struct _GrowWidgetGtk {
  GtkDrawingArea bin;
  GrowWidgetGtkPrivate *priv;
};

struct _GrowWidgetGtkPrivate {
  GdkWindow *window;
  void* grow_ctx;
  void* draw_ctx;
  int (*init_proc)(GlowCtx* ctx, void* clien_data);
  int is_navigator;
  void* client_data;
  GtkWidget* main_grow_widget;
  GtkWidget* scroll_h;
  GtkWidget* scroll_v;
  GtkWidget* form;
  int scroll_h_ignore;
  int scroll_v_ignore;
  gdouble scroll_h_value;
  gdouble scroll_v_value;
  int scroll_h_pagesize;
  int scroll_v_pagesize;
  int scroll_h_upper;
  int scroll_v_upper;
  gint scroll_timerid;
  glow_sScroll scroll_data;
  int scroll_configure;
  int destroyed;
  GtkAdjustment* hadjustment;
  GtkAdjustment* vadjustment;
  guint hscroll_policy : 1;
  guint vscroll_policy : 1;
};

enum {
  PROP_0,
  PROP_HADJUSTMENT,
  PROP_VADJUSTMENT,
  PROP_HSCROLL_POLICY,
  PROP_VSCROLL_POLICY
};

struct _GrowWidgetGtkClass {
  GtkDrawingAreaClass parent_class;
};

G_DEFINE_TYPE_WITH_CODE(GrowWidgetGtk, growwidgetgtk, GTK_TYPE_DRAWING_AREA,
			G_ADD_PRIVATE(GrowWidgetGtk)
			G_IMPLEMENT_INTERFACE(GTK_TYPE_SCROLLABLE, NULL));

static gboolean scroll_callback_cb(void* d);
static void growwidgetgtk_get_property(GObject *object, guint prop_id, 
				       GValue *value, GParamSpec *pspec);
static void growwidgetgtk_set_property(GObject *object, guint prop_id, 
				       const GValue *value, GParamSpec *pspec);

static void scroll_callback(glow_sScroll* data)
{
  growwidget_sScroll* scroll_data = (growwidget_sScroll*)data->scroll_data;
  GrowWidgetGtkPrivate *grow = (GrowWidgetGtkPrivate *)((GrowWidgetGtk*)scroll_data->grow)->priv;

  if (grow->scroll_timerid)
    g_source_remove(grow->scroll_timerid);

  grow->scroll_timerid = g_timeout_add(200, scroll_callback_cb, scroll_data->grow);
  ((GrowWidgetGtk*)scroll_data->grow)->priv->scroll_data = *data;
}

static gboolean scroll_callback_cb(void* d)
{
  GrowWidgetGtkPrivate *grow = ((GrowWidgetGtk*)d)->priv;
  glow_sScroll* data = &((GrowWidgetGtk*)d)->priv->scroll_data;
  growwidget_sScroll* scroll_data = (growwidget_sScroll*)data->scroll_data;
  GtkAdjustment *adj;

  grow->scroll_timerid = 0;

  if (data->total_width <= data->window_width) {
    if (data->offset_x == 0)
      data->total_width = data->window_width;
    if (scroll_data->scroll_h_managed) {
      // Remove horizontal scrollbar
    }
  } else {
    if (!scroll_data->scroll_h_managed) {
      // Insert horizontal scrollbar
    }
  }

  if (data->total_height <= data->window_height) {
    if (data->offset_y == 0)
      data->total_height = data->window_height;
    if (scroll_data->scroll_v_managed) {
      // Remove vertical scrollbar
    }
  } else {
    if (!scroll_data->scroll_v_managed) {
      // Insert vertical scrollbar
    }
  }
  if (data->offset_x < 0) {
    data->total_width += -data->offset_x;
    data->offset_x = 0;
  }
  if (data->offset_y < 0) {
    data->total_height += -data->offset_y;
    data->offset_y = 0;
  }
  if (data->total_height < data->window_height + data->offset_y)
    data->total_height = data->window_height + data->offset_y;
  if (data->total_width < data->window_width + data->offset_x)
    data->total_width = data->window_width + data->offset_x;
  if (data->window_width < 1)
    data->window_width = 1;
  if (data->window_height < 1)
    data->window_height = 1;

  if (scroll_data->scroll_h_managed) {
    grow->scroll_h_ignore = 1;
    if (data->window_width != grow->scroll_h_pagesize
        || data->total_width != grow->scroll_h_upper
        || grow->scroll_configure) {
      adj = gtk_range_get_adjustment(GTK_RANGE(scroll_data->scroll_h));
      gtk_adjustment_set_value(adj, data->offset_x);
      gtk_adjustment_set_upper(adj, data->total_width);
      gtk_adjustment_set_page_size(adj, data->window_width);
    } else {
      adj = gtk_range_get_adjustment(GTK_RANGE(scroll_data->scroll_h));
      gtk_adjustment_set_value(adj, data->offset_x);
    }
    grow->scroll_h_value = (gdouble)data->offset_x;
    grow->scroll_h_pagesize = data->window_width;
    grow->scroll_h_upper = data->total_width;
  }

  if (scroll_data->scroll_v_managed) {
    grow->scroll_v_ignore = 1;
    if (data->window_height != grow->scroll_v_pagesize
        || data->total_height != grow->scroll_v_upper
        || grow->scroll_configure) {
      adj = gtk_range_get_adjustment(GTK_RANGE(scroll_data->scroll_v));
      gtk_adjustment_set_upper(adj, data->total_height);
      gtk_adjustment_set_page_size(adj, data->window_height);
      gtk_adjustment_set_value(adj, data->offset_y);
    } else {
      gtk_range_set_value(
          GTK_RANGE(scroll_data->scroll_v), (gdouble)data->offset_y);
    }
    grow->scroll_v_value = (gdouble)data->offset_y;
    grow->scroll_v_pagesize = data->window_height;
    grow->scroll_v_upper = data->total_height;
  }
  grow->scroll_configure = 0;
  return FALSE;
}

static void scroll_h_action(GtkWidget* w, gpointer data)
{
  GrowWidgetGtkPrivate* groww = ((GrowWidgetGtk*)data)->priv;
  if (groww->scroll_h_ignore) {
    groww->scroll_h_ignore = 0;
    return;
  }

  GrowCtx* ctx = (GrowCtx*)groww->grow_ctx;
  gdouble value;
  value = gtk_range_get_value(GTK_RANGE(groww->scroll_h));

  if (feq(value, 0.0) && ABS(groww->scroll_h_value) > 2) {
    // Probably a resize that seems to set value to zero, set old value
    ctx->change_scrollbar();
    return;
  }
  groww->scroll_h_value = value;

  glow_scroll_horizontal(ctx, int(value), 0);
}

static void scroll_v_action(GtkWidget* w, gpointer data)
{
  GrowWidgetGtkPrivate* groww = ((GrowWidgetGtk*)data)->priv;

  if (groww->scroll_v_ignore) {
    groww->scroll_v_ignore = 0;
    return;
  }

  GrowCtx* ctx = (GrowCtx*)groww->grow_ctx;
  gdouble value;
  value = gtk_range_get_value(GTK_RANGE(groww->scroll_v));

  if (feq(value, 0.0) && ABS(groww->scroll_v_value) > 2) {
    // Probably a resize that seems to set value to zero, set old value
    ctx->change_scrollbar();
    return;
  }
  groww->scroll_v_value = value;

  glow_scroll_vertical(ctx, int(value), 0);
}

static int grow_init_proc(GtkWidget* w, GlowCtx* fctx, void* client_data)
{
  growwidget_sScroll* scroll_data;
  GrowCtx* ctx;

  ctx = (GrowCtx*)((GrowWidgetGtk*)w)->priv->grow_ctx;

  if (((GrowWidgetGtk*)w)->priv->scroll_h) {
    scroll_data = (growwidget_sScroll*)malloc(sizeof(growwidget_sScroll));
    scroll_data->grow = w;
    scroll_data->scroll_h = ((GrowWidgetGtk*)w)->priv->scroll_h;
    scroll_data->scroll_v = ((GrowWidgetGtk*)w)->priv->scroll_v;
    scroll_data->form = ((GrowWidgetGtk*)w)->priv->form;
    scroll_data->scroll_h_managed = 1;
    scroll_data->scroll_v_managed = 1;

    ctx->register_scroll_callback((void*)scroll_data, scroll_callback);
  }
  return (((GrowWidgetGtk*)w)->priv->init_proc)(ctx, client_data);
}

static gboolean growwidgetgtk_expose(GtkWidget* widget, cairo_t* cr)
{
  GrowWidgetGtk* grow = (GrowWidgetGtk*)widget;

  ((GlowDrawGtk*)((GrowCtx*)grow->priv->grow_ctx)->gdraw)->
      expose(cr, grow->priv->is_navigator);
  return TRUE;
}

static void growwidgetgtk_grab_focus(GtkWidget* glow)
{
  GTK_WIDGET_CLASS(growwidgetgtk_parent_class)->grab_focus(glow);
  gdk_window_focus(((GrowWidgetGtk *)glow)->priv->window, GDK_CURRENT_TIME);
}

static void growwidgetgtk_destroy(GtkWidget* widget)
{
  GrowWidgetGtk* grow = (GrowWidgetGtk*)widget;

  if (!grow->priv->destroyed) {
    grow->priv->destroyed = 1;
    if (grow->priv->scroll_timerid)
      g_source_remove(grow->priv->scroll_timerid);
    if (grow->priv->is_navigator) {
      if (grow->priv->grow_ctx
          && !((GrowWidgetGtk*)grow->priv->main_grow_widget)->priv->destroyed)
        ((GrowCtx*)grow->priv->grow_ctx)->no_nav = 1;
    } else
      delete (GlowDrawGtk*)grow->priv->draw_ctx;
    if (grow->priv->hadjustment)
      g_object_unref(grow->priv->hadjustment);
    if (grow->priv->vadjustment)
      g_object_unref(grow->priv->vadjustment);
  }
  GTK_WIDGET_CLASS(growwidgetgtk_parent_class)->destroy(widget);
}

static gboolean growwidgetgtk_event(GtkWidget* glow, GdkEvent* event)
{
  if (((GrowWidgetGtk*)glow)->priv->destroyed)
    return TRUE;

  if (event->type == GDK_MOTION_NOTIFY) {
    gdk_display_flush(
        ((GlowDrawGtk*)((GrowCtx*)((GrowWidgetGtk*)glow)->priv->grow_ctx)->gdraw)
            ->display);
    GdkEvent* next = gdk_event_peek();
    if (next && next->type == GDK_MOTION_NOTIFY) {
      gdk_event_free(next);
      return TRUE;
    } else if (next)
      gdk_event_free(next);
  } else if (event->type == GDK_CONFIGURE) {
    ((GrowWidgetGtk*)glow)->priv->scroll_configure = 1;
  }

  ((GlowDrawGtk*)((GrowCtx*)((GrowWidgetGtk*)glow)->priv->grow_ctx)->gdraw)
      ->event_handler(*event);
  return TRUE;
}

static void growwidgetgtk_realize(GtkWidget* widget)
{
  GdkWindowAttr attr;
  gint attr_mask;
  GrowWidgetGtk* grow;
  GtkAllocation allocation;

  g_return_if_fail(widget != NULL);
  g_return_if_fail(IS_GROWWIDGETGTK(widget));

  gtk_widget_set_realized(widget, TRUE);
  grow = GROWWIDGETGTK(widget);

  gtk_widget_get_allocation(widget, &allocation);
  attr.x = allocation.x;
  attr.y = allocation.y;
  attr.width = allocation.width;
  attr.height = allocation.height;
  attr.wclass = GDK_INPUT_OUTPUT;
  attr.window_type = GDK_WINDOW_CHILD;
  attr.event_mask = gtk_widget_get_events(widget) | GDK_EXPOSURE_MASK
      | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK
      | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK
      | GDK_BUTTON_MOTION_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK
      | GDK_STRUCTURE_MASK;
  attr.visual = gtk_widget_get_visual(widget);

  attr_mask = GDK_WA_X | GDK_WA_Y | GDK_WA_VISUAL;
  grow->priv->window = gdk_window_new(gtk_widget_get_parent_window(widget), &attr, attr_mask);
  gtk_widget_set_window(widget, grow->priv->window);
  gtk_widget_register_window(widget, grow->priv->window);
  //widget->style = gtk_style_attach(widget->style, widget->window);
  //gtk_style_set_background(widget->style, widget->window, GTK_STATE_ACTIVE);

  gtk_widget_set_can_focus(widget, TRUE);

  if (grow->priv->is_navigator) {
    if (!grow->priv->grow_ctx) {
      GrowWidgetGtk* main_grow = (GrowWidgetGtk*)grow->priv->main_grow_widget;

      grow->priv->grow_ctx = main_grow->priv->grow_ctx;
      grow->priv->draw_ctx = main_grow->priv->draw_ctx;
      ((GlowDrawGtk*)grow->priv->draw_ctx)->init_nav(widget);
    }
  } else {
    if (!grow->priv->grow_ctx) {
      grow->priv->draw_ctx = new GlowDrawGtk(widget, &grow->priv->grow_ctx, grow_init_proc,
          grow->priv->client_data, glow_eCtxType_Grow);
    }
  }
}

static void growwidgetgtk_class_init(GrowWidgetGtkClass* klass)
{
  GtkWidgetClass* widget_class;
  GObjectClass* gobject_class = G_OBJECT_CLASS(klass);

  widget_class = GTK_WIDGET_CLASS(klass);
  widget_class->realize = growwidgetgtk_realize;
  widget_class->draw = growwidgetgtk_expose;
  widget_class->event = growwidgetgtk_event;
  widget_class->grab_focus = growwidgetgtk_grab_focus;
  widget_class->destroy = growwidgetgtk_destroy;
  gobject_class->set_property = growwidgetgtk_set_property;
  gobject_class->get_property = growwidgetgtk_get_property;

  gtk_widget_class_set_css_name(widget_class, "growwidget");

  // GtkScrollable interface
  g_object_class_override_property(gobject_class, PROP_HADJUSTMENT, "hadjustment");
  g_object_class_override_property(gobject_class, PROP_VADJUSTMENT, "vadjustment");
  g_object_class_override_property(gobject_class, PROP_HSCROLL_POLICY, "hscroll-policy");
  g_object_class_override_property(gobject_class, PROP_VSCROLL_POLICY, "vscroll-policy");
}

static void growwidgetgtk_init(GrowWidgetGtk* grow)
{
  grow->priv = (GrowWidgetGtkPrivate *)growwidgetgtk_get_instance_private(grow);
}

GtkWidget* growwidgetgtk_new(
    int (*init_proc)(GlowCtx* ctx, void* client_data), void* client_data)
{
  GrowWidgetGtk* w;
  w = (GrowWidgetGtk*)g_object_new(GROWWIDGETGTK_TYPE, NULL);
  w->priv->init_proc = init_proc;
  w->priv->grow_ctx = 0;
  w->priv->is_navigator = 0;
  w->priv->client_data = client_data;
  w->priv->scroll_h = 0;
  w->priv->scroll_v = 0;
  w->priv->hadjustment = NULL;
  w->priv->vadjustment = NULL;
  w->priv->destroyed = 0;
  return (GtkWidget*)w;
}

GtkWidget* scrolledgrowwidgetgtk_new(
    int (*init_proc)(GlowCtx* ctx, void* client_data), void* client_data,
    GtkWidget** growwidget)
{
  GrowWidgetGtk* w;

  GtkWidget* form = gtk_scrolled_window_new(NULL, NULL);

  w = (GrowWidgetGtk*)g_object_new(GROWWIDGETGTK_TYPE, NULL);
  w->priv->init_proc = init_proc;
  w->priv->grow_ctx = 0;
  w->priv->is_navigator = 0;
  w->priv->client_data = client_data;
  w->priv->scroll_h = gtk_scrolled_window_get_hscrollbar(GTK_SCROLLED_WINDOW(form));
  w->priv->scroll_v = gtk_scrolled_window_get_vscrollbar(GTK_SCROLLED_WINDOW(form));
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_value = 0;
  w->priv->scroll_v_value = 0;
  w->priv->scroll_configure = 0;
  w->priv->destroyed = 0;
  w->priv->form = form;
  w->priv->hadjustment = gtk_adjustment_new(0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
  w->priv->vadjustment = gtk_adjustment_new(0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
  *growwidget = GTK_WIDGET(w);

  g_signal_connect(gtk_range_get_adjustment(GTK_RANGE((GtkScrollbar*)w->priv->scroll_h)),
      "value-changed", G_CALLBACK(scroll_h_action), w);
  g_signal_connect(gtk_range_get_adjustment(GTK_RANGE((GtkScrollbar*)w->priv->scroll_v)),
      "value-changed", G_CALLBACK(scroll_v_action), w);

  gtk_container_add(GTK_CONTAINER(form), GTK_WIDGET(w));

  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(form), GTK_POLICY_ALWAYS, GTK_POLICY_ALWAYS);

  return (GtkWidget*)form;
}

GtkWidget* grownavwidgetgtk_new(GtkWidget* main_grow)
{
  GrowWidgetGtk* w;
  w = (GrowWidgetGtk*)g_object_new(GROWWIDGETGTK_TYPE, NULL);
  w->priv->init_proc = 0;
  w->priv->grow_ctx = 0;
  w->priv->is_navigator = 1;
  w->priv->main_grow_widget = main_grow;
  w->priv->client_data = 0;
  w->priv->scroll_h = 0;
  w->priv->scroll_v = 0;
  w->priv->scroll_h_ignore = 0;
  w->priv->scroll_v_ignore = 0;
  w->priv->scroll_h_value = 0;
  w->priv->scroll_v_value = 0;
  w->priv->scroll_configure = 0;
  w->priv->hadjustment = NULL;
  w->priv->vadjustment = NULL;
  w->priv->destroyed = 0;
  return (GtkWidget*)w;
}

static void growwidgetgtk_set_property(GObject *object, guint prop_id, 
				       const GValue *value, GParamSpec *pspec)
{
  //FlowWidgetGtk *flow = (FlowWidgetGtk *)object;

  switch (prop_id) {
  case PROP_HADJUSTMENT:
    break;
  case PROP_VADJUSTMENT:
    break;
  case PROP_HSCROLL_POLICY:
    break;
  case PROP_VSCROLL_POLICY:
    break;
  }
}

static void growwidgetgtk_get_property(GObject *object, guint prop_id, 
				       GValue *value, GParamSpec *pspec)
{
  GrowWidgetGtk *grow = (GrowWidgetGtk *)object;

  switch (prop_id) {
  case PROP_HADJUSTMENT:
    g_value_set_object(value, grow->priv->hadjustment);
    break;
  case PROP_VADJUSTMENT:
    g_value_set_object(value, grow->priv->vadjustment);
    break;
  case PROP_HSCROLL_POLICY:
    g_value_set_enum(value, grow->priv->hscroll_policy);
    break;
  case PROP_VSCROLL_POLICY:
    g_value_set_enum(value, grow->priv->vscroll_policy);
    break;
  }
}
