/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef wb_vrep_h
#define wb_vrep_h

#include <vector>

#include "wb_srep.h"
#include "wb_orep.h"
#include "wb_oset.h"
#include "wb_cdef.h"
#include "wb_destination.h"
#include "wb_export.h"
#include "wb_treeexport.h"
#include "wb_treeimport.h"

class wb_erep;
class wb_merep;
class wb_srep;
class wb_cdef;
class wb_destination;
class wb_dbs;

/**
 * @class wb_vrep
 * @brief Volume Representation - abstract base for storage backends
 *
 * Provides storage abstraction for workbench volumes. Different implementations
 * support various storage formats:
 *
 * - **wb_vrepdbs**: Class definitions from .dbs files (compiled class metadata)
 * - **wb_vrepdb**: Berkeley DB volumes (.db files with object instances)
 * - **wb_vrepwbl**: Source format (.wb_load files, human-readable)
 * - **wb_vrepmem**: In-memory transient volumes
 *
 * @section storage_backends Storage Backend Types
 *
 * ### Berkeley DB Backend (wb_vrepdb)
 * Used for runtime volumes containing object instances:
 * - **ohead table**: Object metadata (oid, cid, hierarchy, timestamps, body sizes)
 * - **rbody table**: Runtime body attribute data (key=oid, value=binary blob)
 * - **dbody table**: Devbody attribute data (key=oid, value=binary blob)
 * - **chead table**: Cached class metadata from .dbs files
 *
 * File location: $pwrp_db/<volumename>.db
 *
 * ### .dbs Files Backend (wb_vrepdbs)
 * Class definition volumes containing metadata only (no instances):
 * - Contains compiled class definitions from .wb_load files
 * - Generated by: `wb_cmd build <volumename>`
 * - File format: Berkeley DB with class metadata
 * - File location: $pwr_exe/<volumename>.dbs
 *
 * ### .wb_load Source Backend (wb_vrepwbl)
 * Human-readable text format for both classes and instances:
 * - Line-oriented format with indentation for hierarchy
 * - Contains object definitions and attribute values
 * - Can be edited manually or via wb_cmd
 * - File location: $pwr_elib/wbl/<volumename>.wb_load
 *
 * @section lifecycle Volume Lifecycle
 *
 * 1. **Class Development**:
 *    - Edit MyClasses.wb_load (source format)
 *    - Run `wb_cmd build MyClasses` → generates MyClasses.dbs
 *    - wb_vrepdbs loads MyClasses.dbs for class definitions
 *
 * 2. **Runtime Volume Creation**:
 *    - wb_gtk creates objects using classes from .dbs files
 *    - Objects stored in Berkeley DB (ohead/rbody/dbody tables)
 *    - wb_vrepdb provides read/write access to object instances
 *
 * 3. **Load/Save**:
 *    - Export: wb_vrepdb → .wb_load (via wb_export methods)
 *    - Import: .wb_load → wb_vrepdb (via wb_treeimport methods)
 *
 * @section body_storage Body Storage Details
 *
 * Each object has two bodies stored separately from metadata:
 * - **RtBody (bix=0)**: Runtime attributes (process variables, I/O data)
 * - **DevBody (bix=1)**: Development attributes (graphics, documentation)
 *
 * Body sizes come from class definitions (wb_cdef):
 * @code
 * createObject() {
 *   db_sObject o;
 *   o.oid = new_oid;
 *   o.cid = cdef.cid();
 *   o.body[0].size = cdef.rbSize();  // From class .dbs file
 *   o.body[1].size = cdef.dbSize();
 *   ohead_db->insert(o);              // Store in ohead table
 *
 *   // Allocate zeroed bodies in rbody/dbody tables
 *   void* rtbody = calloc(cdef.rbSize(), 1);
 *   void* devbody = calloc(cdef.dbSize(), 1);
 *   rbody_db->insert(oid, rtbody, cdef.rbSize());
 *   dbody_db->insert(oid, devbody, cdef.dbSize());
 * }
 * @endcode
 *
 * @section class_updates Class Updates and Body Size Changes
 *
 * CRITICAL: When class definitions change (body sizes), existing objects must be updated.
 * The checkClass() method (in wb_vrepdb) compares BOTH timestamps AND body sizes:
 * @code
 * if (ohead.body[0].size != cdef.rbSize() ||  // Body size changed!
 *     ohead.body[1].size != cdef.dbSize() ||
 *     ohead.time < cdef.time()) {               // Or timestamp changed
 *     // Object is outdated, needs update
 * }
 * @endcode
 *
 * This prevents buffer overflows when allocating body memory based on class size
 * but reading larger data from database.
 */
class wb_vrep : public wb_export, public wb_treeexport, public wb_treeimport
{
protected:
  typedef std::vector<wb_srep*>::iterator srep_iterator;

  /** @brief Volume name (user-visible name like "MyVolume") */
  char m_name[80];

  /** @brief Volume ID (unique identifier) */
  pwr_tVid m_vid;

  /** @brief Volume class ID (what class this volume is) */
  pwr_tCid m_cid;

  /** @brief Active sessions (wb_srep for each open access point) */
  std::vector<wb_srep*> m_srep;

  /** @brief Node index increment counter (for generating unique NIX values) */
  int m_no_nix_incr;

public:
  virtual ~wb_vrep() {}

  wb_vrep() : m_vid(pwr_cNVid), m_cid(pwr_cNCid), m_no_nix_incr(0) {}
  wb_vrep(pwr_tVid vid) : m_vid(vid), m_cid(pwr_cNCid), m_no_nix_incr(0) {}
  wb_vrep(pwr_tVid vid, pwr_tCid cid) : m_vid(vid), m_cid(cid), m_no_nix_incr(0) {}

  /** @brief Decrement reference count, delete if zero */
  virtual void unref() = 0;

  /** @brief Increment reference count and return this */
  virtual wb_vrep* ref() = 0;

  /** @brief Get volume type (ldh_eVolRep_Db, ldh_eVolRep_Wb, etc.) */
  virtual ldh_eVolRep type() const = 0;

  /**
   * @brief Get database backend type
   * @return ldh_eVolDb_BerkeleyDb for .db files, ldh_eVolDb__ for others
   */
  virtual ldh_eVolDb dbtype() { return ldh_eVolDb__; }

  /** @brief Get environment representation (wb session context) */
  virtual wb_erep* erep() = 0;

  /** @brief Get next volume in environment's volume list */
  virtual wb_vrep* next() = 0;

  virtual pwr_tOid oid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tVid vid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tOix oix(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual pwr_tCid cid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tOid poid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tOid foid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tOid loid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tOid boid(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tOid aoid(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual const char* objectName(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual wb_name longName(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tTime ohTime(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tTime rbTime(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_tTime dbTime(pwr_tStatus* sts, const wb_orep* o) = 0;
  virtual pwr_mClassDef flags(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual bool isOffspringOf(pwr_tStatus* sts, const wb_orep* child, const wb_orep* parent) = 0;

  virtual wb_orep* object(pwr_tStatus* sts) = 0;
  virtual wb_orep* object(pwr_tStatus* sts, pwr_tOid oid) = 0;
  virtual wb_orep* object(pwr_tStatus* sts, wb_name& name) = 0;
  virtual wb_orep* object(pwr_tStatus* sts, const wb_orep* parent, wb_name& name) = 0;
  virtual wb_orep* object(pwr_tStatus* sts, pwr_tCid cid) = 0;

  virtual wb_orep* createObject(pwr_tStatus* sts, wb_cdef cdef, wb_destination& d, wb_name& name,
                                pwr_tOix oix = 0) = 0;

  virtual wb_orep* copyObject(pwr_tStatus* sts, const wb_orep* orep, wb_destination& d, wb_name& name,
                              pwr_tOix oix = 0) = 0;
  virtual bool copyOset(pwr_tStatus* sts, wb_oset* oset, wb_destination& d) = 0;

  virtual bool moveObject(pwr_tStatus* sts, wb_orep* orep, wb_destination& d) = 0;

  virtual bool deleteObject(pwr_tStatus* sts, wb_orep* orep) = 0;
  virtual bool deleteFamily(pwr_tStatus* sts, wb_orep* orep) = 0;
  virtual bool deleteOset(pwr_tStatus* sts, wb_oset* oset) = 0;

  virtual bool renameObject(pwr_tStatus* sts, wb_orep* orep, wb_name& name) = 0;

  virtual bool commit(pwr_tStatus* sts) = 0;
  virtual bool abort(pwr_tStatus* sts) = 0;

  virtual bool writeAttribute(pwr_tStatus* sts, wb_orep* o, pwr_eBix bix, size_t offset, size_t size,
                              void* p) = 0;

  virtual void* readAttribute(pwr_tStatus* sts, const wb_orep* o, pwr_eBix bix, size_t offset, size_t size,
                              void* p) = 0;

  virtual void* readBody(pwr_tStatus* sts, const wb_orep* o, pwr_eBix bix, void* p) = 0;

  virtual bool writeBody(pwr_tStatus* sts, wb_orep* o, pwr_eBix bix, void* p) = 0;

  virtual wb_orep* ancestor(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual wb_orep* parent(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual wb_orep* after(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual wb_orep* before(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual wb_orep* first(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual wb_orep* child(pwr_tStatus* sts, const wb_orep* o, wb_name& name) = 0;

  virtual wb_orep* last(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual wb_orep* next(pwr_tStatus* sts, const wb_orep* o) = 0;

  // virtual wb_orep *nextClass(pwr_tStatus *sts, const wb_orep *o) = 0;

  virtual wb_orep* previous(pwr_tStatus* sts, const wb_orep* o) = 0;

  virtual bool ohTime(pwr_tStatus* sts, const wb_orep* o, pwr_tTime t) { return false; }

  virtual wb_srep* newSession() = 0;

  virtual bool isLocal(const wb_orep* o) = 0;
  pwr_tVid vid() const { return m_vid; }
  pwr_tCid cid() const { return m_cid; }
  void vid(pwr_tVid vid) { m_vid = vid; }
  void cid(pwr_tCid cid) { m_cid = cid; }

  virtual void name(const char* n);
  virtual const char* name() { return m_name; }
  virtual wb_merep* merep() const = 0;

  virtual bool createSnapshot(const char* fileName, const pwr_tTime* time, const int rtonly) = 0;
  virtual pwr_tStatus updateMeta() { return 0; }

  virtual void objectName(const wb_orep* o, char* str) = 0;
  virtual bool isCommonMeta() const { return false; }
  virtual bool isMeta() const { return false; }
  virtual bool accessSupported(ldh_eAccess access) = 0;
  virtual bool duplicateDb() const { return false; }
  virtual void setDuplicateDb(bool duplicate) {}

  void addSrep(wb_srep* srep);
  void removeSrep(wb_srep* srep);
  wb_srep* srep(pwr_tStatus* sts);
  wb_srep* nextSrep(pwr_tStatus* sts, wb_srep* srep);
  void noNixIncr(int incr) { m_no_nix_incr = incr; }

  virtual const char* fileName() = 0;
  virtual bool time(pwr_tTime* t) { return false; }
};

#endif
