#!/bin/bash
#
# ProviewR   Open Source Process Control.
# Copyright (C) 2005-2024 SSAB EMEA AB.
#
# This file is part of ProviewR.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ProviewR. If not, see <http://www.gnu.org/licenses/>
#
# Linking ProviewR statically or dynamically with other modules is
# making a combined work based on ProviewR. Thus, the terms and
# conditions of the GNU General Public License cover the whole
# combination.
#
# In addition, as a special exception, the copyright holders of
# ProviewR give you permission to, from the build function in the
# ProviewR Configurator, combine ProviewR with modules generated by the
# ProviewR PLC Editor to a PLC program, regardless of the license
# terms of these modules. You may copy and distribute the resulting
# combined work under the terms of your choice, provided that every
# copy of the combined work is accompanied by a complete copy of
# the source code of ProviewR (the version used to produce the
# combined work), being distributed under the terms of the GNU
# General Public License plus this exception.
#
#
# pwr_release.sh -- Prepare the ProviewR tree for a new release.
#
# Usage:
#   pwr_release.sh [--dry-run] <new_version>
#
#   <new_version>  Version string in the form "V<major>.<minor>.<patch>",
#                  e.g. V6.2.0
#   --dry-run      Show what would be changed without modifying any files.
#

set -euo pipefail

# ---- helpers ----------------------------------------------------------------

readonly SCRIPT_NAME=$(basename "$0")
readonly ROOT=$(cd "$(dirname "$0")/../../../.." && pwd)
readonly VERSION_H="$ROOT/src/exp/inc/src/pwr_version.h"
readonly CHANGELOG="$ROOT/CHANGELOG.md"
readonly UPGRADE_SH="$ROOT/src/exp/com/src/upgrade.sh"

DRY_RUN=0
NEW_VERSION=""

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [--dry-run] <new_version>

Prepares the ProviewR source tree for a new release:

  1. Bumps the copyright end-year to the current year in every source file.
  2. Updates the version in pwr_version.h (version string, binary version,
     wbdb short string, build time, and copyright macro).
  3. Updates upgrade.sh OLD/NEW version pair.
  4. Stamps CHANGELOG.md: moves [Unreleased] to a dated release heading
     and creates a fresh [Unreleased] section.

Arguments:
  <new_version>   Version in format V<major>.<minor>.<patch>, e.g. V6.2.0
  --dry-run       Print actions without modifying files.

Example:
  $SCRIPT_NAME V6.2.0
  $SCRIPT_NAME --dry-run V6.2.0
EOF
  exit 1
}

info()  { echo "  [INFO]  $*"; }
warn()  { echo "  [WARN]  $*" >&2; }
error() { echo "  [ERROR] $*" >&2; exit 1; }

# Run sed -i, or just report in dry-run mode
do_sed() {
  local desc="$1"; shift
  if [ "$DRY_RUN" -eq 1 ]; then
    info "(dry-run) $desc"
  else
    sed -i "$@"
    info "$desc"
  fi
}

# ---- parse arguments --------------------------------------------------------

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage ;;
    V[0-9]*) NEW_VERSION="$1"; shift ;;
    *) error "Unknown argument: $1" ;;
  esac
done

[ -z "$NEW_VERSION" ] && usage

# Parse version components: V<major>.<minor>.<patch>
if [[ ! "$NEW_VERSION" =~ ^V([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
  error "Version must match V<major>.<minor>.<patch>, e.g. V6.2.0"
fi

VER_MAJOR="${BASH_REMATCH[1]}"
VER_MINOR="${BASH_REMATCH[2]}"
VER_PATCH="${BASH_REMATCH[3]}"
VER_SHORT="V${VER_MAJOR}${VER_MINOR}"  # e.g. V62

# Read current version from pwr_version.h
CUR_VERSION=$(grep 'pwrv_cPwrVersionStr' "$VERSION_H" | head -1 | sed 's/.*"\(V[^"]*\)".*/\1/')
if [ -z "$CUR_VERSION" ]; then
  error "Could not read current version from $VERSION_H"
fi

# Extract old major.minor for upgrade.sh
if [[ "$CUR_VERSION" =~ ^V([0-9]+)\.([0-9]+) ]]; then
  OLD_MAJMIN="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
fi
NEW_MAJMIN="${VER_MAJOR}.${VER_MINOR}"

# Current year for copyright
YEAR=$(date +%Y)

# Release date for changelog
RELEASE_DATE=$(date +%Y-%m-%d)

# Build time stamp matching existing format: DD-MON-YYYY HH:MM:SS
BUILD_TIME=$(date -u +"%d-%^b-%Y %H:%M:%S")

echo "=============================================="
echo " ProviewR Release Preparation"
echo "=============================================="
echo "  Repository root : $ROOT"
echo "  Current version : $CUR_VERSION"
echo "  New version     : $NEW_VERSION"
echo "  Copyright year  : $YEAR"
echo "  Release date    : $RELEASE_DATE"
echo "  Build time      : $BUILD_TIME"
[ "$DRY_RUN" -eq 1 ] && echo "  Mode            : DRY RUN"
echo "=============================================="
echo ""

# ---- Step 1: Bump copyright year -------------------------------------------

echo "== Step 1: Bump copyright year to $YEAR =="

# Match "Copyright (C) 2005-NNNN SSAB EMEA AB" and update end year.
# Covers both "# Copyright" (shell) and " * Copyright" (C/C++) styles,
# and the pwrv_cPwrCopyright macro.
#
# We only touch files tracked by git to avoid binary/vendor files.

FILES_TO_UPDATE=$(cd "$ROOT" && git grep -l "Copyright (C) 2005-" -- \
  '*.cpp' '*.h' '*.sh' '*.java' '*.js' '*.css' '*.py' | wc -l)
info "Files containing copyright header: ~$FILES_TO_UPDATE"

if [ "$DRY_RUN" -eq 1 ]; then
  info "(dry-run) Would update copyright to 2005-$YEAR in ~$FILES_TO_UPDATE files"
else
  (cd "$ROOT" && git grep -l "Copyright (C) 2005-" -- \
    '*.cpp' '*.h' '*.sh' '*.java' '*.js' '*.css' '*.py' | \
    xargs sed -i "s/Copyright (C) 2005-[0-9]\{4\} SSAB EMEA AB/Copyright (C) 2005-${YEAR} SSAB EMEA AB/g")
  info "Copyright updated to 2005-$YEAR"
fi
echo ""

# ---- Step 2: Update pwr_version.h ------------------------------------------

echo "== Step 2: Update $VERSION_H =="

do_sed "pwrv_cPwrVersionStr -> \"$NEW_VERSION\"" \
  "s|#define pwrv_cPwrVersionStr .*|#define pwrv_cPwrVersionStr \"${NEW_VERSION}\"|" \
  "$VERSION_H"

do_sed "pwrv_cPwrVersion -> SET_VERSION('V', $VER_MAJOR, $VER_MINOR, $VER_PATCH)" \
  "s|#define pwrv_cPwrVersion .*|#define pwrv_cPwrVersion SET_VERSION('V', ${VER_MAJOR}, ${VER_MINOR}, ${VER_PATCH})|" \
  "$VERSION_H"

do_sed "pwrv_cWbdbVersionShortStr -> \"$VER_SHORT\"" \
  "s|#define pwrv_cWbdbVersionShortStr .*|#define pwrv_cWbdbVersionShortStr \"${VER_SHORT}\"|" \
  "$VERSION_H"

do_sed "pwrv_cBuildTimeStr -> \"$BUILD_TIME\"" \
  "s|#define pwrv_cBuildTimeStr .*|#define pwrv_cBuildTimeStr \"${BUILD_TIME}\"|" \
  "$VERSION_H"

do_sed "pwrv_cPwrCopyright -> 2005-$YEAR" \
  "s|#define pwrv_cPwrCopyright .*|#define pwrv_cPwrCopyright \"Copyright (C) 2005-${YEAR} SSAB EMEA AB\"|" \
  "$VERSION_H"

echo ""

# ---- Step 3: Update upgrade.sh ---------------------------------------------

echo "== Step 3: Update $UPGRADE_SH =="

do_sed "OLD_PWR_VERSION -> \"$OLD_MAJMIN\"" \
  "s|^OLD_PWR_VERSION=.*|OLD_PWR_VERSION=\"${OLD_MAJMIN}\"|" \
  "$UPGRADE_SH"

do_sed "NEW_PWR_VERSION -> \"$NEW_MAJMIN\"" \
  "s|^NEW_PWR_VERSION=.*|NEW_PWR_VERSION=\"${NEW_MAJMIN}\"|" \
  "$UPGRADE_SH"

echo ""

# ---- Step 4: Stamp CHANGELOG.md --------------------------------------------

echo "== Step 4: Update $CHANGELOG =="

GITLAB_URL="https://gitlab.ssab.com/pwrdev/pwr/-/compare"

if [ "$DRY_RUN" -eq 1 ]; then
  info "(dry-run) Would add release heading [$NEW_VERSION] - $RELEASE_DATE"
  info "(dry-run) Would create fresh [Unreleased] section"
  info "(dry-run) Would update compare links"
else
  # Replace "[Unreleased]" heading with dated release + new Unreleased
  sed -i "/^## \[Unreleased\]/a\\\\n## [$NEW_VERSION] - $RELEASE_DATE" "$CHANGELOG"

  # Update the [unreleased] compare link to point from new version
  sed -i "s|\[unreleased\]:.*|[unreleased]: ${GITLAB_URL}/${NEW_VERSION}...HEAD|" "$CHANGELOG"

  # Add a compare link for this release (old version -> new version)
  sed -i "/^\[unreleased\]:/a\\[$NEW_VERSION]: ${GITLAB_URL}/${CUR_VERSION}...${NEW_VERSION}" "$CHANGELOG"

  info "Changelog stamped with [$NEW_VERSION] - $RELEASE_DATE"
fi

echo ""

# ---- Summary ----------------------------------------------------------------

echo "=============================================="
echo " Release preparation complete"
echo "=============================================="
if [ "$DRY_RUN" -eq 1 ]; then
  echo " (dry-run mode — no files were modified)"
else
  echo ""
  echo " Next steps:"
  echo "   1. Review changes:  git diff"
  echo "   2. Build:           pwre build_all_modules gtk"
  echo "   3. Commit:          git commit -am \"Release $NEW_VERSION\""
  echo "   4. Tag:             git tag $NEW_VERSION"
  echo ""
fi
