/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2025 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef onvif_api_h
#define onvif_api_h

typedef enum {
  onvif_mPTZ_pan = 1,
  onvif_mPTZ_tilt = 2,
  onvif_mPTZ_zoom = 4
} onvif_mPTZ;

class onvif_api {
  void *gsoap;
  pwr_tURL uri;
  char username[80];
  char passwd[80];
  void *PTZ_proxy;
  char manufacturer[80];
  char model[80];
  char firmware_version[80];
  int has_pantilt;
  int has_zoom;

 public:
  double x_range_min;
  double x_range_max;
  double y_range_min;
  double y_range_max;
  double zoom_range_min;
  double zoom_range_max;

  onvif_api(char *uri, char *username, char *passwd, pwr_tStatus *rsts);
  ~onvif_api();

  void report_error();
  void set_credentials();
  void move_absolute(double x, double y, double zoom, unsigned int mask);
  void move_relative(double x, double y, double zoom, unsigned int mask);
  void get_ptz(double *x, double *y, double *zoom);

};

#endif
