/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#pragma once

#include <gtk/gtk.h>
#include <memory>
#include <vector>
#include <string>
#include <thread>

#include "topology_visualization.h"
#include "../src/pn_dcp_tool.h"

// Forward declaration
class TopologyCrawler;

namespace ProfinetDCP
{

class NetworkTopologyWindow
{
public:
  NetworkTopologyWindow(GtkWidget* parent, const std::vector<DCPDeviceInfo>& devices);
  ~NetworkTopologyWindow();

  void show();
  void refreshTopology();

private:
  // GTK widget members
  GtkWidget* m_parent_window;
  GtkWidget* m_topology_window;
  GtkWidget* m_drawing_area;
  GtkWidget* m_toolbar;
  GtkToolItem* m_layout_button;
  GtkWidget* m_log_frame;
  GtkWidget* m_log_scrolled_window;
  GtkWidget* m_log_text_view;
  GtkTextBuffer* m_log_buffer;

  // Topology data
  std::unique_ptr<TopologyCrawler> m_topology_crawler;
  TopologyGraph m_current_graph;
  std::vector<DCPDeviceInfo> m_devices;

  // UI state
  bool m_crawling_in_progress;
  double m_zoom_factor;
  double m_pan_x, m_pan_y;
  double m_canvas_width, m_canvas_height;
  bool m_dragging;
  bool m_dragging_node;
  double m_last_mouse_x, m_last_mouse_y;
  size_t m_selected_node;

  // Tooltip support
  size_t m_hovered_node;
  std::string m_tooltip_text;
  bool m_tooltip_visible;

  // Layout animation state
  int m_current_iteration;
  double m_current_mean_speed;
  bool m_layout_running;
  bool m_layout_stop_requested;
  std::unique_ptr<std::thread> m_layout_thread;

  // Window creation and setup
  void createTopologyWindow();
  void createToolbar();
  void createDrawingArea();
  void createLogPanel();
  void setupEventHandlers();

  // Topology discovery
  void startLLDPDiscovery();
  void buildTopologyFromLLDP();

  // Graph creation and layout
  TopologyGraph createGraphFromTopology() const;
  void applySpringLayout(TopologyGraph& graph, int iterations = 100);
  void updateLayoutButtonLabel();

  // Drawing functions
  void drawTopology(cairo_t* cr);
  void drawNode(cairo_t* cr, const TopologyNode& node, size_t node_index);
  void drawEdgeLine(cairo_t* cr, const TopologyEdge& edge);
  void drawTooltip(cairo_t* cr);

  // Label collision detection structure
  struct LabelInfo
  {
    double x, y;             // Current center position
    double width, height;    // Dimensions
    double line_dx, line_dy; // Line direction vector (normalized)
    double perp_x, perp_y;   // Perpendicular vector for perpendicular offset
    double edge_x, edge_y;   // Edge intersection point (anchor point)
    double label_offset;     // Current offset along the line from edge point
    double text_offset;      // Perpendicular offset from line
    std::string text;        // Label text
    bool is_from;            // True if 'from' port, false if 'to' port
    bool selected_local;     // True if selected node's local port
    bool selected_remote;    // True if remote port connected to selected

    // Update position based on current offsets
    void updatePosition()
    {
      x = edge_x + (is_from ? -line_dx : line_dx) * label_offset + perp_x * text_offset;
      y = edge_y + (is_from ? -line_dy : line_dy) * label_offset + perp_y * text_offset;
    }

    // Get bounding rectangle
    double left() const { return x - width / 2 - 2; }
    double right() const { return x + width / 2 + 2; }
    double top() const { return y - height / 2 - 2; }
    double bottom() const { return y + height / 2 + 2; }

    // Check if this label overlaps with another
    bool overlaps(const LabelInfo& other) const
    {
      return !(right() < other.left() || left() > other.right() || bottom() < other.top() ||
               top() > other.bottom());
    }
  };

  // Helper functions
  static std::string cleanPortLabel(const std::string& raw_port_id);
  std::pair<double, double> calculateNodeEdgeIntersection(const TopologyNode& from, const TopologyNode& to);
  static std::vector<LabelInfo> resolveCollisions(std::vector<LabelInfo>& labels);
  void drawLabel(cairo_t* cr, const LabelInfo& label);

  // Event handlers
  static gboolean onDrawingAreaDraw(GtkWidget* widget, cairo_t* cr, gpointer user_data);
  static gboolean onButtonPress(GtkWidget* widget, GdkEventButton* event, gpointer user_data);
  static gboolean onButtonRelease(GtkWidget* widget, GdkEventButton* event, gpointer user_data);
  static gboolean onMotionNotify(GtkWidget* widget, GdkEventMotion* event, gpointer user_data);
  static gboolean onScrollEvent(GtkWidget* widget, GdkEventScroll* event, gpointer user_data);
  static gboolean onKeyPress(GtkWidget* widget, GdkEventKey* event, gpointer user_data);
  static void onRefreshClicked(GtkButton* button, gpointer user_data);
  static void onZoomInClicked(GtkButton* button, gpointer user_data);
  static void onZoomOutClicked(GtkButton* button, gpointer user_data);
  static void onResetViewClicked(GtkButton* button, gpointer user_data);
  static void onApplyLayoutClicked(GtkButton* button, gpointer user_data);
  static void onExportClicked(GtkButton* button, gpointer user_data);

  // Utility functions
  size_t findNodeUnderMouse(double x, double y) const;
  void zoomAt(double zoom_delta, double center_x, double center_y);
  void resetView();
  void exportToFile();
  void addLogMessage(const std::string& message);
  void addLogMessageWithTimestamp(const std::string& message);
  void addLogMessageThreadSafe(const std::string& message);
};

} // namespace ProfinetDCP