/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include <cairo.h>
#include <cairo-svg.h>
#include <cmath>
#include <iostream>
#include <chrono>
#include <iomanip>
#include <sstream>
#include <thread>
#include <algorithm>
#include <stdexcept>
#include <random>
#include <set>
#include <limits>
#include <cstdlib>
#define _USE_MATH_DEFINES
#include <cmath>

#include "network_topology_window.h"
#include "pn_dcp_tool_gtk.h"
#include "topology_visualization.h"

namespace ProfinetDCP
{

NetworkTopologyWindow::NetworkTopologyWindow(GtkWidget* parent, const std::vector<DCPDeviceInfo>& devices)
    : m_parent_window(parent), m_topology_window(nullptr), m_drawing_area(nullptr), m_toolbar(nullptr),
      m_layout_button(nullptr), m_log_frame(nullptr), m_log_scrolled_window(nullptr),
      m_log_text_view(nullptr), m_log_buffer(nullptr),
      m_topology_crawler(std::make_unique<TopologyCrawler>("public")), m_devices(devices),
      m_crawling_in_progress(false), m_zoom_factor(1.0), m_pan_x(0.0), m_pan_y(0.0), m_canvas_width(1200.0),
      m_canvas_height(800.0), m_dragging(false), m_dragging_node(false), m_last_mouse_x(0.0),
      m_last_mouse_y(0.0), m_selected_node(SIZE_MAX), m_hovered_node(SIZE_MAX), m_tooltip_visible(false),
      m_current_iteration(0), m_current_mean_speed(0.0), m_layout_running(false),
      m_layout_stop_requested(false), m_layout_thread(nullptr)
{
  // Register log callback to redirect crawler messages to activity log (thread-safe)
  m_topology_crawler->set_log_callback([this](const std::string& message)
                                       { this->addLogMessageThreadSafe(message); });

  createTopologyWindow();
}

NetworkTopologyWindow::~NetworkTopologyWindow()
{
  // Stop any running layout algorithm
  m_layout_stop_requested = true;
  m_layout_running = false;

  // Wait for layout thread to finish before destroying the window
  if (m_layout_thread && m_layout_thread->joinable())
  {
    m_layout_thread->join();
  }

  // Process any remaining GTK events to ensure all g_idle_add callbacks are handled
  // before we destroy the widgets
  while (gtk_events_pending())
  {
    gtk_main_iteration();
  }

  if (m_topology_window)
  {
    gtk_widget_destroy(m_topology_window);
  }
}

void NetworkTopologyWindow::show()
{
  if (m_topology_window)
  {
    gtk_widget_show_all(m_topology_window);
    gtk_window_present(GTK_WINDOW(m_topology_window));

    // Auto-start LLDP discovery on first show
    startLLDPDiscovery();
  }
}

void NetworkTopologyWindow::createTopologyWindow()
{
  m_topology_window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title(GTK_WINDOW(m_topology_window), "Network Topology - LLDP Discovery");
  gtk_window_set_default_size(GTK_WINDOW(m_topology_window), 1200, 800);
  gtk_window_set_position(GTK_WINDOW(m_topology_window), GTK_WIN_POS_CENTER);

  if (m_parent_window)
  {
    gtk_window_set_transient_for(GTK_WINDOW(m_topology_window), GTK_WINDOW(m_parent_window));
  }

  // Create main container
  GtkWidget* vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  gtk_container_add(GTK_CONTAINER(m_topology_window), vbox);

  // Create toolbar
  createToolbar();
  gtk_box_pack_start(GTK_BOX(vbox), m_toolbar, FALSE, FALSE, 0);

  // Create paned container for drawing area and log
  GtkWidget* paned = gtk_paned_new(GTK_ORIENTATION_VERTICAL);
  gtk_box_pack_start(GTK_BOX(vbox), paned, TRUE, TRUE, 0);

  // Create drawing area
  createDrawingArea();
  gtk_paned_pack1(GTK_PANED(paned), m_drawing_area, TRUE, TRUE);

  // Create log panel
  createLogPanel();
  gtk_paned_pack2(GTK_PANED(paned), m_log_frame, FALSE, FALSE);

  // Set paned position (70% for drawing, 30% for log)
  gtk_paned_set_position(GTK_PANED(paned), 560);

  setupEventHandlers();

  addLogMessage("Network topology window initialized");
  addLogMessage("Use 'Refresh LLDP' to discover network topology");
}

void NetworkTopologyWindow::createToolbar()
{
  m_toolbar = gtk_toolbar_new();
  gtk_toolbar_set_style(GTK_TOOLBAR(m_toolbar), GTK_TOOLBAR_BOTH);

  // Refresh button
  GtkToolItem* refresh_item = gtk_tool_button_new(
      gtk_image_new_from_icon_name("view-refresh", GTK_ICON_SIZE_LARGE_TOOLBAR), "Refresh LLDP");
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), refresh_item, -1);
  g_signal_connect(refresh_item, "clicked", G_CALLBACK(onRefreshClicked), this);

  // Separator
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), gtk_separator_tool_item_new(), -1);

  // Zoom in
  GtkToolItem* zoom_in_item =
      gtk_tool_button_new(gtk_image_new_from_icon_name("zoom-in", GTK_ICON_SIZE_LARGE_TOOLBAR), "Zoom In");
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), zoom_in_item, -1);
  g_signal_connect(zoom_in_item, "clicked", G_CALLBACK(onZoomInClicked), this);

  // Zoom out
  GtkToolItem* zoom_out_item =
      gtk_tool_button_new(gtk_image_new_from_icon_name("zoom-out", GTK_ICON_SIZE_LARGE_TOOLBAR), "Zoom Out");
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), zoom_out_item, -1);
  g_signal_connect(zoom_out_item, "clicked", G_CALLBACK(onZoomOutClicked), this);

  // Fit view
  GtkToolItem* reset_item = gtk_tool_button_new(
      gtk_image_new_from_icon_name("zoom-fit-best", GTK_ICON_SIZE_LARGE_TOOLBAR), "Fit View");
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), reset_item, -1);
  g_signal_connect(reset_item, "clicked", G_CALLBACK(onResetViewClicked), this);

  // Layout button
  m_layout_button = gtk_tool_button_new(
      gtk_image_new_from_icon_name("view-grid", GTK_ICON_SIZE_LARGE_TOOLBAR), "Apply Layout");
  gtk_tool_item_set_tooltip_text(m_layout_button, "Start/stop spring layout algorithm to reorganize nodes");
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), m_layout_button, -1);
  g_signal_connect(m_layout_button, "clicked", G_CALLBACK(onApplyLayoutClicked), this);

  // Separator
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), gtk_separator_tool_item_new(), -1);

  // Export
  GtkToolItem* export_item = gtk_tool_button_new(
      gtk_image_new_from_icon_name("document-save-as", GTK_ICON_SIZE_LARGE_TOOLBAR), "Export");
  gtk_tool_item_set_tooltip_text(export_item, "Export current topology view to PNG or SVG file");
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), export_item, -1);
  g_signal_connect(export_item, "clicked", G_CALLBACK(onExportClicked), this);
}

void NetworkTopologyWindow::createDrawingArea()
{
  m_drawing_area = gtk_drawing_area_new();
  gtk_widget_set_size_request(m_drawing_area, 1200, 800);
  gtk_widget_set_can_focus(m_drawing_area, TRUE);

  // Enable events
  gtk_widget_add_events(m_drawing_area, GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK |
                                            GDK_POINTER_MOTION_MASK | GDK_SCROLL_MASK | GDK_KEY_PRESS_MASK);
}

void NetworkTopologyWindow::createLogPanel()
{
  m_log_frame = gtk_frame_new("Activity Log");
  gtk_style_context_add_class(gtk_widget_get_style_context(m_log_frame), "log-frame");

  m_log_scrolled_window = gtk_scrolled_window_new(NULL, NULL);
  gtk_style_context_add_class(gtk_widget_get_style_context(m_log_scrolled_window), "log-container");
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(m_log_scrolled_window), GTK_POLICY_AUTOMATIC,
                                 GTK_POLICY_AUTOMATIC);
  gtk_container_add(GTK_CONTAINER(m_log_frame), m_log_scrolled_window);

  m_log_text_view = gtk_text_view_new();
  gtk_text_view_set_editable(GTK_TEXT_VIEW(m_log_text_view), FALSE);
  gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(m_log_text_view), FALSE);
  gtk_container_add(GTK_CONTAINER(m_log_scrolled_window), m_log_text_view);

  m_log_buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(m_log_text_view));
}

void NetworkTopologyWindow::setupEventHandlers()
{
  // Drawing area events
  g_signal_connect(m_drawing_area, "draw", G_CALLBACK(onDrawingAreaDraw), this);
  g_signal_connect(m_drawing_area, "button-press-event", G_CALLBACK(onButtonPress), this);
  g_signal_connect(m_drawing_area, "button-release-event", G_CALLBACK(onButtonRelease), this);
  g_signal_connect(m_drawing_area, "motion-notify-event", G_CALLBACK(onMotionNotify), this);
  g_signal_connect(m_drawing_area, "scroll-event", G_CALLBACK(onScrollEvent), this);

  // Window events
  g_signal_connect(m_topology_window, "key-press-event", G_CALLBACK(onKeyPress), this);
}

void NetworkTopologyWindow::startLLDPDiscovery()
{
  if (m_crawling_in_progress)
  {
    addLogMessage("LLDP discovery already in progress");
    return;
  }

  m_crawling_in_progress = true;
  addLogMessageWithTimestamp("Starting LLDP network discovery...");

  // Run discovery in a separate thread to avoid blocking the UI
  std::thread(
      [this]()
      {
        try
        {
          // Get seed IPs from existing devices
          std::vector<std::string> seed_ips;
          for (const auto& device : m_devices)
          {
            // Use actual IP address from DCP discovery
            std::string ip_addr = device.ip_address.toString();
            if (!ip_addr.empty() && ip_addr != "0.0.0.0")
            {
              seed_ips.push_back(ip_addr);
            }
          }

          // If no devices, use a default range
          if (seed_ips.empty())
          {
            addLogMessageThreadSafe("No devices supplied from DCP tool for LLDP discovery");
            return;
          }

          // Convert PROFINET devices to topology DeviceInfo format for subnet filtering
          std::vector<::TopologyDeviceInfo> topology_devices; // Use global DeviceInfo from topology-crawler.h
          for (const auto& device : m_devices)
          {
            std::string ip_addr = device.ip_address.toString();
            if (!ip_addr.empty() && ip_addr != "0.0.0.0")
            {
              ::TopologyDeviceInfo topo_device; // Use global DeviceInfo
              topo_device.device_name = device.device_name;
              topo_device.ip_address = ip_addr;                        // string to string
              topo_device.subnet_mask = device.subnet_mask.toString(); // string to string
              topo_device.vendor_id = device.vendor_id;
              topo_device.device_id = device.device_id;
              topo_device.mac_address = device.mac_address.toString(); // string to string
              // sys_desc, device_type, device_vendor, neighbors remain empty for seed devices
              topology_devices.push_back(topo_device);
            }
          }

          // Perform LLDP discovery with subnet filtering
          m_topology_crawler->crawl_from_profinet_devices(topology_devices);

          // Create graph from topology data
          TopologyGraph graph = createGraphFromTopology();

          // Apply spring layout for better visualization
          // Use high max iterations - algorithm will converge early when equilibrium is reached
          int max_iterations = 5000;
          applySpringLayout(graph, max_iterations);

          // Update the current graph
          m_current_graph = graph;

          // Update UI from main thread
          g_idle_add(
              [](gpointer user_data) -> gboolean
              {
                NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
                window->m_crawling_in_progress = false;
                window->addLogMessageWithTimestamp("LLDP discovery completed successfully");

                // Automatically reset view to center and frame all discovered nodes
                window->resetView();

                gtk_widget_queue_draw(window->m_drawing_area);
                return G_SOURCE_REMOVE;
              },
              this);
        }
        catch (const std::exception& e)
        {
          // Handle errors
          std::string error_msg = "LLDP discovery failed: " + std::string(e.what());
          g_idle_add(
              [](gpointer user_data) -> gboolean
              {
                NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
                window->m_crawling_in_progress = false;
                window->addLogMessageWithTimestamp("LLDP discovery failed");
                return G_SOURCE_REMOVE;
              },
              this);
        }
      })
      .detach();
}

void NetworkTopologyWindow::buildTopologyFromLLDP() { startLLDPDiscovery(); }

void NetworkTopologyWindow::refreshTopology()
{
  // Create a fresh TopologyCrawler instance to ensure clean discovery
  // This clears any cached topology and visited nodes from previous crawls
  m_topology_crawler = std::make_unique<TopologyCrawler>("public");

  // Register log callback to redirect crawler messages to activity log (thread-safe)
  m_topology_crawler->set_log_callback([this](const std::string& message)
                                       { this->addLogMessageThreadSafe(message); });

  // Clear current graph to show fresh discovery
  m_current_graph.nodes.clear();
  m_current_graph.edges.clear();

  // Start fresh LLDP discovery
  buildTopologyFromLLDP();
}

// Drawing functions
void NetworkTopologyWindow::drawTopology(cairo_t* cr)
{
  // Save transform state
  cairo_save(cr);

  // Clear background with dark theme
  cairo_set_source_rgb(cr, 0.08, 0.09, 0.12);
  cairo_paint(cr);

  // No grid for infinite canvas
  // drawGrid(cr);

  // Apply zoom and pan transforms
  cairo_scale(cr, m_zoom_factor, m_zoom_factor);
  cairo_translate(cr, m_pan_x / m_zoom_factor, m_pan_y / m_zoom_factor);

  // Draw edge lines first (so they appear behind nodes)
  for (const auto& edge : m_current_graph.edges)
  {
    drawEdgeLine(cr, edge);
  }

  // Draw nodes (over the edge lines)
  size_t node_index = 0;
  for (const auto& [ip, node] : m_current_graph.nodes)
  {
    drawNode(cr, node, node_index);
    node_index++;
  }

  // Collect all edge labels first, then resolve collisions and draw
  std::vector<LabelInfo> all_labels;

  // Set up font for text measurements
  cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
  cairo_set_font_size(cr, 8);

  for (const auto& edge : m_current_graph.edges)
  {
    // Find source and destination nodes
    auto from_it = m_current_graph.nodes.find(edge.from_ip);
    auto to_it = m_current_graph.nodes.find(edge.to_ip);

    if (from_it == m_current_graph.nodes.end() || to_it == m_current_graph.nodes.end())
      continue;

    const TopologyNode& from = from_it->second;
    const TopologyNode& to = to_it->second;

    // Determine if this edge is connected to the selected node
    bool is_connected_to_selected = false;
    bool selected_is_from = false;

    if (m_selected_node != SIZE_MAX)
    {
      size_t current_node_index = 0;
      for (const auto& [ip, node] : m_current_graph.nodes)
      {
        if (current_node_index == m_selected_node)
        {
          if (ip == edge.from_ip)
          {
            is_connected_to_selected = true;
            selected_is_from = true;
          }
          else if (ip == edge.to_ip)
          {
            is_connected_to_selected = true;
            selected_is_from = false;
          }
          break;
        }
        current_node_index++;
      }
    }

    // Calculate actual line endpoints
    auto from_edge = calculateNodeEdgeIntersection(from, to);
    auto to_edge = calculateNodeEdgeIntersection(to, from);

    // Calculate vector from edge to edge for positioning
    double dx = to_edge.first - from_edge.first;
    double dy = to_edge.second - from_edge.second;
    double length = std::sqrt(dx * dx + dy * dy);

    if (length > 0)
    {
      // Normalize direction vector
      dx /= length;
      dy /= length;

      // Calculate perpendicular vector for offset (rotated 90 degrees)
      double perp_x = -dy;
      double perp_y = dx;

      // Offset distances
      double label_offset = -5.0; // Distance away from line endpoint
      // No perpendicular offset - labels positioned directly on line vector

      // Add 'from' port label to collection
      if (!edge.from_port.port_id.empty())
      {
        std::string clean_from_label = cleanPortLabel(edge.from_port.port_id);
        cairo_text_extents_t extents;
        cairo_text_extents(cr, clean_from_label.c_str(), &extents);

        LabelInfo label;
        label.width = extents.width;
        label.height = extents.height;
        label.line_dx = dx;
        label.line_dy = dy;
        label.perp_x = perp_x;
        label.perp_y = perp_y;
        label.edge_x = from_edge.first;
        label.edge_y = from_edge.second;
        label.label_offset = label_offset;
        label.text_offset = 0.0;
        label.text = clean_from_label;
        label.is_from = true;
        label.selected_local = (is_connected_to_selected && selected_is_from);
        label.selected_remote = (is_connected_to_selected && !selected_is_from);

        // Calculate initial position
        label.updatePosition();

        all_labels.push_back(label);
      }

      // Add 'to' port label to collection
      if (!edge.to_port.port_id.empty())
      {
        std::string clean_to_label = cleanPortLabel(edge.to_port.port_id);
        cairo_text_extents_t extents;
        cairo_text_extents(cr, clean_to_label.c_str(), &extents);

        LabelInfo label;
        label.width = extents.width;
        label.height = extents.height;
        label.line_dx = dx;
        label.line_dy = dy;
        label.perp_x = perp_x;
        label.perp_y = perp_y;
        label.edge_x = to_edge.first;
        label.edge_y = to_edge.second;
        label.label_offset = label_offset;
        label.text_offset = 0.0; // No perpendicular offset - on line vector
        label.text = clean_to_label;
        label.is_from = false;
        label.selected_local = (is_connected_to_selected && !selected_is_from);
        label.selected_remote = (is_connected_to_selected && selected_is_from);

        // Calculate initial position
        label.updatePosition();

        all_labels.push_back(label);
      }
    }
  }

  // Resolve collisions and draw all labels
  auto resolved_labels = resolveCollisions(all_labels);
  for (const auto& label : resolved_labels)
  {
    drawLabel(cr, label);
  }

  // Restore to widget coordinates
  cairo_restore(cr);

  // Display layout algorithm status information
  if (m_layout_running)
  {
    // Draw semi-transparent background for better text visibility
    cairo_set_source_rgba(cr, 0.0, 0.0, 0.0, 0.7); // Semi-transparent black
    cairo_rectangle(cr, 8, 8, 420, 50);            // Background rectangle
    cairo_fill(cr);

    cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_BOLD);
    cairo_set_font_size(cr, 14);
    cairo_set_source_rgb(cr, 0.9, 0.95, 1.0); // Light text for readability

    // Display iteration, mean speed, and convergence goal (adjust Y for toolbar)
    char buf[192];
    snprintf(buf, sizeof(buf), "Iter: %d   Mean speed: %.3f   Goal: < 0.200", m_current_iteration,
             m_current_mean_speed);
    cairo_move_to(cr, 12, 80); // Moved down from 22 to 30
    cairo_show_text(cr, buf);

    // Show progress towards convergence
    cairo_set_font_size(cr, 12);
    if (m_current_mean_speed < 0.2)
    {
      cairo_set_source_rgb(cr, 0.3, 1.0, 0.3); // Green when converged
      cairo_move_to(cr, 12, 100);              // Moved down from 42 to 50
      cairo_show_text(cr, "✓ CONVERGED - Algorithm Stable!");

      // Green dot indicator
      cairo_arc(cr, 380, 24, 6, 0, 2 * M_PI); // Moved down from 16 to 24
      cairo_fill(cr);
    }
    else
    {
      cairo_set_source_rgb(cr, 1.0, 0.8, 0.3);                             // Yellow while running
      double progress = std::min(1.0, (2.0 - m_current_mean_speed) / 1.8); // Progress from 2.0 to 0.2
      snprintf(buf, sizeof(buf), "Converging... %.1f%% complete", progress * 100);
      cairo_move_to(cr, 12, 50); // Moved down from 42 to 50
      cairo_show_text(cr, buf);
    }
  }

  // Draw tooltip if visible
  if (m_tooltip_visible && !m_tooltip_text.empty())
  {
    drawTooltip(cr);
  }
}

void NetworkTopologyWindow::drawNode(cairo_t* cr, const TopologyNode& node, size_t node_index)
{
  // Node dimensions
  double width = 120.0;
  double height = 80.0;
  double radius = 8.0;
  bool is_selected = (node_index == m_selected_node);

  // Node position
  double x = node.x - width / 2;
  double y = node.y - height / 2;

  // Draw node background (rounded rectangle)
  cairo_new_sub_path(cr);
  cairo_arc(cr, x + width - radius, y + radius, radius, -M_PI / 2, 0);
  cairo_arc(cr, x + width - radius, y + height - radius, radius, 0, M_PI / 2);
  cairo_arc(cr, x + radius, y + height - radius, radius, M_PI / 2, M_PI);
  cairo_arc(cr, x + radius, y + radius, radius, M_PI, 3 * M_PI / 2);
  cairo_close_path(cr);

  // Set node colors based on device type
  if (is_selected)
  {
    cairo_set_source_rgb(cr, 0.3, 0.8, 1.0); // Brighter blue for selected node
  }
  else
  {
    // Standard blue color for PROFINET devices
    cairo_set_source_rgb(cr, 0.2, 0.6, 1.0);
  }
  cairo_fill_preserve(cr);

  // Draw border with enhanced styling for selected node
  if (is_selected)
  {
    cairo_set_source_rgb(cr, 0.0, 0.4, 0.8); // Dark blue border for selected
    cairo_set_line_width(cr, 3.0);           // Thicker border
  }
  else
  {
    cairo_set_source_rgb(cr, 0.3, 0.3, 0.3); // Normal border
    cairo_set_line_width(cr, 2.0);
  }
  cairo_stroke(cr);

  // Draw device name with light text
  cairo_set_source_rgb(cr, 0.85, 0.9, 1.0);
  cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
  cairo_set_font_size(cr, 9);

  cairo_text_extents_t extents;
  std::string display_name = node.device_name.empty() ? node.ip : node.device_name;
  cairo_text_extents(cr, display_name.c_str(), &extents);

  cairo_move_to(cr, node.x - extents.width / 2, node.y - 5);
  cairo_show_text(cr, display_name.c_str());

  // Draw IP address with smaller font
  cairo_set_font_size(cr, 8);
  cairo_text_extents(cr, node.ip.c_str(), &extents);
  cairo_move_to(cr, node.x - extents.width / 2, node.y + 8);
  cairo_show_text(cr, node.ip.c_str());
}

void NetworkTopologyWindow::drawEdgeLine(cairo_t* cr, const TopologyEdge& edge)
{
  // Find source and destination nodes
  auto from_it = m_current_graph.nodes.find(edge.from_ip);
  auto to_it = m_current_graph.nodes.find(edge.to_ip);

  if (from_it == m_current_graph.nodes.end() || to_it == m_current_graph.nodes.end())
  {
    return;
  }

  const TopologyNode& from = from_it->second;
  const TopologyNode& to = to_it->second;

  // Calculate intersection points at node edges
  auto from_edge = calculateNodeEdgeIntersection(from, to);
  auto to_edge = calculateNodeEdgeIntersection(to, from);

  // Draw connection lines with transparency
  cairo_set_source_rgba(cr, 0.7, 0.8, 0.9, 0.25);
  cairo_set_line_width(cr, 1.0);
  cairo_move_to(cr, from_edge.first, from_edge.second);
  cairo_line_to(cr, to_edge.first, to_edge.second);
  cairo_stroke(cr);
}

// Event handlers
gboolean NetworkTopologyWindow::onDrawingAreaDraw(GtkWidget* widget, cairo_t* cr, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
  window->drawTopology(cr);
  return TRUE;
}

gboolean NetworkTopologyWindow::onButtonPress(GtkWidget* widget, GdkEventButton* event, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  if (event->button == 1)
  { // Left click
    window->m_dragging = true;
    window->m_last_mouse_x = event->x;
    window->m_last_mouse_y = event->y;

    // Check if clicking on a node
    size_t clicked_node = window->findNodeUnderMouse(event->x, event->y);
    if (clicked_node != SIZE_MAX)
    {
      // Clicking on a node - select it and enable dragging
      window->m_selected_node = clicked_node;
      window->m_dragging_node = true;
    }
    else
    {
      // Clicking on empty space - deselect any selected node
      window->m_selected_node = SIZE_MAX;
      window->m_dragging_node = false;
    }

    // Redraw to show selection changes
    gtk_widget_queue_draw(widget);
  }

  gtk_widget_grab_focus(widget);
  return TRUE;
}

gboolean NetworkTopologyWindow::onButtonRelease(GtkWidget* widget, GdkEventButton* event, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  window->m_dragging = false;
  window->m_dragging_node = false;
  // Don't clear selection on button release - selection should persist until user clicks elsewhere

  return TRUE;
}

gboolean NetworkTopologyWindow::onMotionNotify(GtkWidget* widget, GdkEventMotion* event, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  if (window->m_dragging && !window->m_dragging_node)
  {
    // Pan the view
    double dx = event->x - window->m_last_mouse_x;
    double dy = event->y - window->m_last_mouse_y;

    window->m_pan_x += dx;
    window->m_pan_y += dy;

    gtk_widget_queue_draw(widget);
  }
  else if (window->m_dragging_node && window->m_selected_node != SIZE_MAX)
  {
    // Move selected node
    double dx = event->x - window->m_last_mouse_x;
    double dy = event->y - window->m_last_mouse_y;

    // Convert to world coordinates
    double world_dx = dx / window->m_zoom_factor;
    double world_dy = dy / window->m_zoom_factor;

    // Find the selected node and update its position
    size_t current_index = 0;
    for (auto& [ip, node] : window->m_current_graph.nodes)
    {
      if (current_index == window->m_selected_node)
      {
        node.x += world_dx;
        node.y += world_dy;

        // No bounds constraints - infinite canvas allows free movement
        break;
      }
      current_index++;
    }

    gtk_widget_queue_draw(widget);
  }

  // Check for node hovering for tooltips (only when not dragging)
  if (!window->m_dragging && !window->m_dragging_node)
  {
    size_t hovered_node = window->findNodeUnderMouse(event->x, event->y);

    if (hovered_node != window->m_hovered_node)
    {
      window->m_hovered_node = hovered_node;

      // Update tooltip text and visibility
      if (hovered_node != SIZE_MAX)
      {
        // Find the device info for the hovered node
        size_t current_index = 0;
        for (const auto& [ip, node] : window->m_current_graph.nodes)
        {
          if (current_index == hovered_node)
          {
            // Use system description from node (much simpler!)
            if (!node.sys_desc.empty())
            {
              window->m_tooltip_text = node.sys_desc;
              window->m_tooltip_visible = true;
            }
            else
            {
              window->m_tooltip_text = "Device: " + (node.device_name.empty() ? ip : node.device_name);
              window->m_tooltip_visible = true;
            }
            break;
          }
          current_index++;
        }
      }
      else
      {
        window->m_tooltip_visible = false;
        window->m_tooltip_text.clear();
      }

      // Queue redraw to show/hide tooltip
      gtk_widget_queue_draw(widget);
    }
  }

  window->m_last_mouse_x = event->x;
  window->m_last_mouse_y = event->y;

  return TRUE;
}

gboolean NetworkTopologyWindow::onScrollEvent(GtkWidget* widget, GdkEventScroll* event, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  double zoom_delta = (event->direction == GDK_SCROLL_UP) ? 1.1 : 0.9;
  window->zoomAt(zoom_delta, event->x, event->y);

  gtk_widget_queue_draw(widget);
  return TRUE;
}

gboolean NetworkTopologyWindow::onKeyPress(GtkWidget* widget, GdkEventKey* event, gpointer user_data)
{
  // Handle keyboard shortcuts
  return FALSE;
}

void NetworkTopologyWindow::onRefreshClicked(GtkButton* button, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
  window->refreshTopology();
}

void NetworkTopologyWindow::onZoomInClicked(GtkButton* button, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  // Use current widget allocation for zoom center
  GtkAllocation allocation;
  gtk_widget_get_allocation(window->m_drawing_area, &allocation);
  window->zoomAt(1.2, allocation.width / 2.0, allocation.height / 2.0);
  gtk_widget_queue_draw(window->m_drawing_area);
}

void NetworkTopologyWindow::onZoomOutClicked(GtkButton* button, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  // Use current widget allocation for zoom center
  GtkAllocation allocation;
  gtk_widget_get_allocation(window->m_drawing_area, &allocation);
  window->zoomAt(0.8, allocation.width / 2.0, allocation.height / 2.0);
  gtk_widget_queue_draw(window->m_drawing_area);
}

void NetworkTopologyWindow::onResetViewClicked(GtkButton* button, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
  window->resetView();
}

void NetworkTopologyWindow::onApplyLayoutClicked(GtkButton* button, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);

  // Toggle between start and stop
  if (window->m_layout_running)
  {
    // Stop the running layout
    window->m_layout_stop_requested = true;
    window->addLogMessage("Layout algorithm stopped by user");
    return;
  }

  if (window->m_current_graph.nodes.empty())
  {
    window->addLogMessage("No topology available for layout. Please discover network topology first.");
    return;
  }

  // Join any existing thread before starting a new one
  if (window->m_layout_thread && window->m_layout_thread->joinable())
  {
    window->m_layout_thread->join();
  }

  // Reset stop flag and start layout
  window->m_layout_stop_requested = false;
  window->addLogMessage("Starting spring layout algorithm...");

  // Create and store the layout thread
  window->m_layout_thread = std::make_unique<std::thread>(
      [window]()
      {
        try
        {
          // Make a copy of the current graph for layout
          TopologyGraph graph = window->m_current_graph;

          // Apply spring layout with high max iterations - algorithm converges when equilibrium is reached
          int max_iterations = 5000;
          window->applySpringLayout(graph, max_iterations);

          // Update the current graph and redraw from main thread (only if not stopped)
          if (!window->m_layout_stop_requested)
          {
            g_idle_add(
                [](gpointer user_data) -> gboolean
                {
                  auto* data = static_cast<std::pair<NetworkTopologyWindow*, TopologyGraph*>*>(user_data);
                  NetworkTopologyWindow* win = data->first;
                  TopologyGraph* layoutGraph = data->second;

                  // Update the current graph with the laid-out positions
                  win->m_current_graph = *layoutGraph;
                  win->addLogMessage("Spring layout completed successfully");
                  gtk_widget_queue_draw(win->m_drawing_area);

                  delete layoutGraph;
                  delete data;
                  return G_SOURCE_REMOVE;
                },
                new std::pair<NetworkTopologyWindow*, TopologyGraph*>(window, new TopologyGraph(graph)));
          }
        }
        catch (const std::exception& e)
        {
          g_idle_add(
              [](gpointer user_data) -> gboolean
              {
                NetworkTopologyWindow* win = static_cast<NetworkTopologyWindow*>(user_data);
                win->addLogMessage("Layout application failed");
                win->m_layout_running = false;
                return G_SOURCE_REMOVE;
              },
              window);
        }
      });
}

void NetworkTopologyWindow::onExportClicked(GtkButton* button, gpointer user_data)
{
  NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
  window->exportToFile();
}

// Utility functions
size_t NetworkTopologyWindow::findNodeUnderMouse(double x, double y) const
{
  // Transform mouse coordinates to world coordinates
  double world_x = (x - m_pan_x) / m_zoom_factor;
  double world_y = (y - m_pan_y) / m_zoom_factor;

  // Check each node
  size_t index = 0;
  for (const auto& [ip, node] : m_current_graph.nodes)
  {
    double node_width = 120.0;
    double node_height = 80.0;

    if (world_x >= node.x - node_width / 2 && world_x <= node.x + node_width / 2 &&
        world_y >= node.y - node_height / 2 && world_y <= node.y + node_height / 2)
    {
      return index;
    }
    index++;
  }

  return SIZE_MAX;
}

void NetworkTopologyWindow::zoomAt(double zoom_delta, double center_x, double center_y)
{
  double old_zoom = m_zoom_factor;
  m_zoom_factor *= zoom_delta;

  // Clamp zoom factor
  if (m_zoom_factor < 0.1)
    m_zoom_factor = 0.1;
  if (m_zoom_factor > 5.0)
    m_zoom_factor = 5.0;

  // Adjust pan to zoom at center point
  double zoom_change = m_zoom_factor / old_zoom;
  m_pan_x = center_x - (center_x - m_pan_x) * zoom_change;
  m_pan_y = center_y - (center_y - m_pan_y) * zoom_change;
}

void NetworkTopologyWindow::resetView()
{
  // If no nodes, just reset to origin
  if (m_current_graph.nodes.empty())
  {
    m_zoom_factor = 1.0;
    m_pan_x = 0.0;
    m_pan_y = 0.0;
    gtk_widget_queue_draw(m_drawing_area);
    return;
  }

  // Get current widget size for viewport
  GtkAllocation allocation;
  gtk_widget_get_allocation(m_drawing_area, &allocation);
  double viewport_width = allocation.width;
  double viewport_height = allocation.height;
  
  // Account for widget position offset in viewport height calculation
  if (allocation.y < 0) {
    viewport_height = std::max(100.0, viewport_height + allocation.y);
  }

  // Calculate bounding box of all nodes
  double min_x = std::numeric_limits<double>::max();
  double max_x = std::numeric_limits<double>::lowest();
  double min_y = std::numeric_limits<double>::max();
  double max_y = std::numeric_limits<double>::lowest();

  for (const auto& [ip, node] : m_current_graph.nodes)
  {
    double node_margin = 60.0; // Half node width for padding
    min_x = std::min(min_x, node.x - node_margin);
    max_x = std::max(max_x, node.x + node_margin);
    min_y = std::min(min_y, node.y - node_margin);
    max_y = std::max(max_y, node.y + node_margin);
  }

  // Calculate center of all nodes
  double nodes_center_x = (min_x + max_x) / 2.0;
  double nodes_center_y = (min_y + max_y) / 2.0;

  // Calculate bounding box dimensions
  double nodes_width = max_x - min_x;
  double nodes_height = max_y - min_y;
  
  // Ensure we have reasonable node dimensions
  if (nodes_width <= 0) nodes_width = 120.0; // Default node width
  if (nodes_height <= 0) nodes_height = 120.0; // Default node height

  // Calculate zoom to fit all nodes with some padding
  double zoom_x = viewport_width / (nodes_width * 1.2);   // 20% padding
  double zoom_y = viewport_height / (nodes_height * 1.2); // 20% padding
  double fit_zoom = std::min(zoom_x, zoom_y);

  // Clamp zoom to reasonable range
  m_zoom_factor = std::max(0.1, std::min(3.0, fit_zoom));

  // Calculate the effective visible area center
  double effective_center_x = viewport_width / 2.0;
  double effective_center_y = viewport_height / 2.0;
  
  // Adjust for toolbar offset - shift the effective center down by full offset
  if (allocation.y < 0) {
    effective_center_y += (-allocation.y);
  }
  
  // Center the view on the nodes within the effective visible area
  m_pan_x = effective_center_x - (nodes_center_x * m_zoom_factor);
  m_pan_y = effective_center_y - (nodes_center_y * m_zoom_factor);
  
  // Force a redraw
  gtk_widget_queue_draw(m_drawing_area);
}

void NetworkTopologyWindow::addLogMessage(const std::string& message)
{
  if (!m_log_buffer || !GTK_IS_TEXT_BUFFER(m_log_buffer))
    return;

  GtkTextIter iter;
  gtk_text_buffer_get_end_iter(m_log_buffer, &iter);
  gtk_text_buffer_insert(m_log_buffer, &iter, message.c_str(), -1);
  gtk_text_buffer_insert(m_log_buffer, &iter, "\n", -1);

  // Auto-scroll to bottom (with widget validity check)
  if (m_log_text_view && GTK_IS_TEXT_VIEW(m_log_text_view))
  {
    GtkTextMark* mark = gtk_text_buffer_get_insert(m_log_buffer);
    gtk_text_view_scroll_mark_onscreen(GTK_TEXT_VIEW(m_log_text_view), mark);
  }
}

void NetworkTopologyWindow::addLogMessageWithTimestamp(const std::string& message)
{
  auto now = std::chrono::system_clock::now();
  auto time_t = std::chrono::system_clock::to_time_t(now);

  std::stringstream ss;
  ss << "[" << std::put_time(std::localtime(&time_t), "%H:%M:%S") << "] " << message;

  addLogMessage(ss.str());
}

std::string NetworkTopologyWindow::cleanPortLabel(const std::string& raw_port_id)
{
  // Parse LLDP data formats
  // "STRING: \"port-001\"" -> "port-001"
  // "Hex-STRING: AA 00 04 00 22 14" -> "AA:00:04:00:22:14"

  std::string cleaned = raw_port_id;

  // Handle STRING format: STRING: "port-name"
  size_t string_pos = cleaned.find("STRING: \"");
  if (string_pos != std::string::npos)
  {
    size_t start = string_pos + 9; // Length of "STRING: \""
    size_t end = cleaned.find("\"", start);
    if (end != std::string::npos)
    {
      return cleaned.substr(start, end - start);
    }
  }

  // Handle Hex-STRING format: Hex-STRING: AA 00 04 00 22 14
  size_t hex_pos = cleaned.find("Hex-STRING: ");
  if (hex_pos != std::string::npos)
  {
    size_t start = hex_pos + 12; // Length of "Hex-STRING: "
    std::string hex_part = cleaned.substr(start);
    // Replace spaces with colons for MAC address format
    std::replace(hex_part.begin(), hex_part.end(), ' ', ':');
    return hex_part;
  }

  // If no special format detected, return as-is (already clean)
  return cleaned;
}

std::vector<NetworkTopologyWindow::LabelInfo>
NetworkTopologyWindow::resolveCollisions(std::vector<LabelInfo>& labels)
{
  const int max_iterations = 10;
  const double offset_step = 5.0; // How much to adjust label_offset when they collide

  for (int iteration = 0; iteration < max_iterations; ++iteration)
  {
    bool had_collisions = false;

    // Check each label against all others
    for (size_t i = 0; i < labels.size(); ++i)
    {
      for (size_t j = i + 1; j < labels.size(); ++j)
      {
        if (labels[i].overlaps(labels[j]))
        {
          had_collisions = true;

          // Only move the second label (j) further away from its node along its line
          // Keep the first label (i) in its original position
          // Decrease label_offset (more negative) to move further from node
          labels[j].label_offset -= offset_step;

          // Update position based on new offset
          labels[j].updatePosition();
        }
      }
    }

    // If no collisions detected, we're done
    if (!had_collisions)
      break;
  }

  return labels;
}

void NetworkTopologyWindow::drawLabel(cairo_t* cr, const LabelInfo& label)
{
  // Get precise text metrics for proper centering
  cairo_text_extents_t extents;
  cairo_text_extents(cr, label.text.c_str(), &extents);

  // Draw background rectangle with dark theme colors
  if (label.selected_local)
  {
    // Darker background for selected node's local port
    cairo_set_source_rgba(cr, 0.2, 0.4, 0.6, 0.8);
  }
  else if (label.selected_remote)
  {
    // Darker background for remote port connected to selected
    cairo_set_source_rgba(cr, 0.2, 0.6, 0.2, 0.8);
  }
  else
  {
    // Dark background for non-selected connections
    cairo_set_source_rgba(cr, 0.15, 0.15, 0.2, 0.8);
  }

  cairo_rectangle(cr, label.left(), label.top(), label.width + 4, label.height + 4);
  cairo_fill(cr);

  // Draw text with light colors for dark background
  if (label.selected_local)
  {
    cairo_set_source_rgb(cr, 0.8, 0.9, 1.0); // Light blue text
  }
  else if (label.selected_remote)
  {
    cairo_set_source_rgb(cr, 0.8, 1.0, 0.8); // Light green text
  }
  else
  {
    cairo_set_source_rgb(cr, 0.85, 0.9, 1.0); // Light text for dark background
  }

  // Center text alignment for precise positioning
  // Use simple approach: center horizontally and position baseline slightly below center
  double text_x = label.x - extents.width / 2;
  double text_y = label.y - extents.y_bearing - extents.height / 2;

  cairo_move_to(cr, text_x, text_y);
  cairo_show_text(cr, label.text.c_str());
}

void NetworkTopologyWindow::drawTooltip(cairo_t* cr)
{
  if (m_tooltip_text.empty() || m_hovered_node == SIZE_MAX)
    return;

  // Position tooltip centered horizontally above mouse cursor
  double tooltip_x, tooltip_y;

  // Measure text dimensions for tooltip sizing
  cairo_text_extents_t extents;
  cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
  cairo_set_font_size(cr, 11.0);
  cairo_text_extents(cr, m_tooltip_text.c_str(), &extents);

  // Tooltip dimensions with padding
  double padding = 8.0;
  double tooltip_width = extents.width + 2.0 * padding;
  double tooltip_height = extents.height + 2.0 * padding;

  // Position tooltip in upper right corner (widget coordinates)
  GtkAllocation allocation;
  gtk_widget_get_allocation(m_drawing_area, &allocation);

  double margin = 10.0;                 // Margin from edge (increased for visibility)
  double effective_top_margin = margin; // Adjusted if allocation.y < 0

  // If allocation has negative Y, we need to add extra margin to avoid clipping
  if (allocation.y < 0)
  {
    effective_top_margin = margin + std::abs(allocation.y);
  }

  tooltip_x = allocation.width - tooltip_width - margin; // Right side with margin
  tooltip_y = effective_top_margin;                      // Top edge of rectangle (not bottom)

  // Draw tooltip background
  cairo_set_source_rgba(cr, 1.0, 1.0, 0.9, 0.95); // Light yellow background
  cairo_rectangle(cr, tooltip_x, tooltip_y, tooltip_width, tooltip_height);
  cairo_fill(cr);

  // Draw tooltip border
  cairo_set_source_rgb(cr, 0.6, 0.6, 0.6);
  cairo_set_line_width(cr, 1.0);
  cairo_rectangle(cr, tooltip_x, tooltip_y, tooltip_width, tooltip_height);
  cairo_stroke(cr);

  // Draw tooltip text (position baseline properly within rectangle)
  cairo_set_source_rgb(cr, 0.0, 0.0, 0.0);
  double text_x = tooltip_x + padding;
  double text_y = tooltip_y + padding + extents.height; // padding from top + text height
  cairo_move_to(cr, text_x, text_y);
  cairo_show_text(cr, m_tooltip_text.c_str());
}

std::pair<double, double> NetworkTopologyWindow::calculateNodeEdgeIntersection(const TopologyNode& from,
                                                                               const TopologyNode& to)
{
  // Node dimensions (accounting for rounded corners)
  double width = 120.0;
  double height = 80.0;
  double radius = 8.0; // Same radius as used in drawNode

  // Use smaller rectangle to avoid rounded corners
  double effective_width = width - 2.0 * radius;
  double effective_height = height - 2.0 * radius;

  // Calculate direction vector
  double dx = to.x - from.x;
  double dy = to.y - from.y;
  double length = std::sqrt(dx * dx + dy * dy);

  if (length == 0)
  {
    return {from.x, from.y};
  }

  // Normalize direction
  dx /= length;
  dy /= length;

  // Calculate intersection with smaller rectangle edge (avoids rounded corners)
  double half_width = effective_width / 2.0;
  double half_height = effective_height / 2.0;

  // Calculate the intersection with each edge and find the closest one
  double t_right = (dx > 0) ? half_width / dx : std::numeric_limits<double>::infinity();
  double t_left = (dx < 0) ? -half_width / dx : std::numeric_limits<double>::infinity();
  double t_bottom = (dy > 0) ? half_height / dy : std::numeric_limits<double>::infinity();
  double t_top = (dy < 0) ? -half_height / dy : std::numeric_limits<double>::infinity();

  // Find the minimum positive t (closest intersection)
  double t = std::min({t_right, t_left, t_bottom, t_top});

  // Calculate intersection point
  double intersect_x = from.x + t * dx;
  double intersect_y = from.y + t * dy;

  return {intersect_x, intersect_y};
}

void NetworkTopologyWindow::addLogMessageThreadSafe(const std::string& message)
{
  // Create a copy of the message and window pointer for the idle callback
  struct CallbackData
  {
    std::string message;
    NetworkTopologyWindow* window;
  };

  CallbackData* data = new CallbackData{message, this};

  g_idle_add(
      [](gpointer user_data) -> gboolean
      {
        CallbackData* cb_data = static_cast<CallbackData*>(user_data);
        cb_data->window->addLogMessage(cb_data->message);
        delete cb_data;
        return G_SOURCE_REMOVE;
      },
      data);
}

void NetworkTopologyWindow::exportToFile()
{
  // Check if there's a topology to export
  if (m_current_graph.nodes.empty())
  {
    addLogMessage("No topology available to export. Please discover network topology first.");
    return;
  }

  // Show file chooser dialog
  GtkWidget* dialog = gtk_file_chooser_dialog_new("Export Topology", GTK_WINDOW(m_topology_window),
                                                  GTK_FILE_CHOOSER_ACTION_SAVE, "Cancel", GTK_RESPONSE_CANCEL,
                                                  "Save", GTK_RESPONSE_ACCEPT, NULL);

  // Set default filename
  gtk_file_chooser_set_current_name(GTK_FILE_CHOOSER(dialog), "topology.png");

  // Add PNG filter
  GtkFileFilter* png_filter = gtk_file_filter_new();
  gtk_file_filter_set_name(png_filter, "PNG Images (*.png)");
  gtk_file_filter_add_pattern(png_filter, "*.png");
  gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(dialog), png_filter);

  // Add SVG filter
  GtkFileFilter* svg_filter = gtk_file_filter_new();
  gtk_file_filter_set_name(svg_filter, "SVG Images (*.svg)");
  gtk_file_filter_add_pattern(svg_filter, "*.svg");
  gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(dialog), svg_filter);

  // Add "All files" filter
  GtkFileFilter* all_filter = gtk_file_filter_new();
  gtk_file_filter_set_name(all_filter, "All files");
  gtk_file_filter_add_pattern(all_filter, "*");
  gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(dialog), all_filter);

  gint result = gtk_dialog_run(GTK_DIALOG(dialog));

  if (result == GTK_RESPONSE_ACCEPT)
  {
    gchar* filename = gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(dialog));
    std::string export_filename = filename;

    // Determine format from file extension or filter
    bool is_svg = false;
    if (export_filename.find(".svg") != std::string::npos)
    {
      is_svg = true;
    }
    else if (export_filename.find(".png") == std::string::npos)
    {
      // No extension found, check active filter
      GtkFileFilter* active_filter = gtk_file_chooser_get_filter(GTK_FILE_CHOOSER(dialog));
      if (active_filter == svg_filter)
      {
        export_filename += ".svg";
        is_svg = true;
      }
      else
      {
        export_filename += ".png";
        is_svg = false;
      }
    }

    try
    {
      // Get the drawing area allocation
      GtkAllocation allocation;
      gtk_widget_get_allocation(m_drawing_area, &allocation);

      cairo_surface_t* surface;
      cairo_t* cr;

      if (is_svg)
      {
        // Create SVG surface
        surface = cairo_svg_surface_create(export_filename.c_str(), allocation.width, allocation.height);
        cr = cairo_create(surface);

        // Draw the topology
        drawTopology(cr);

        // SVG surface saves automatically when destroyed
        addLogMessage("Topology exported to SVG: " + export_filename);
      }
      else
      {
        // Create PNG surface
        surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, allocation.width, allocation.height);
        cr = cairo_create(surface);

        // Draw the topology
        drawTopology(cr);

        // Save to PNG file
        cairo_surface_write_to_png(surface, export_filename.c_str());
        addLogMessage("Topology exported to PNG: " + export_filename);
      }

      // Cleanup
      cairo_destroy(cr);
      cairo_surface_destroy(surface);
    }
    catch (const std::exception& e)
    {
      addLogMessage("Export failed: " + std::string(e.what()));
    }

    g_free(filename);
  }

  gtk_widget_destroy(dialog);
}

TopologyGraph NetworkTopologyWindow::createGraphFromTopology() const
{
  TopologyGraph graph;
  std::set<std::pair<std::string, std::string>> processed_edges;

  const auto& topology = m_topology_crawler->get_topology();

  // Create nodes
  for (const auto& [ip, device_info] : topology)
  {
    TopologyNode node;
    node.ip = ip;
    node.device_name = device_info.device_name;

    // Treat all nodes as I/O Devices with consistent styling
    node.device_type = "device";

    // Set system description from device info (LLDP Local System Description)
    node.sys_desc = device_info.sys_desc;

    // Collect all unique local ports
    std::map<int, PortInfo> unique_ports;
    for (const auto& neighbor : device_info.neighbors)
    {
      if (!neighbor.local_port.port_id.empty())
        unique_ports[neighbor.local_port.port_num] = neighbor.local_port;
    }
    for (const auto& [port_num, port_info] : unique_ports)
    {
      node.ports.push_back(port_info);
    }

    graph.nodes[ip] = node;
  }

  // Create edges (avoid duplicates)
  for (const auto& [ip, device_info] : topology)
  {
    for (const auto& neighbor : device_info.neighbors)
    {
      // Find the target IP from management addresses
      for (const auto& mgmt_addr : neighbor.mgmt_addrs)
      {
        // Create edge key to avoid duplicates
        std::pair<std::string, std::string> edge_key =
            (ip < mgmt_addr) ? std::make_pair(ip, mgmt_addr) : std::make_pair(mgmt_addr, ip);

        if (processed_edges.find(edge_key) == processed_edges.end())
        {
          TopologyEdge edge;
          edge.from_ip = ip;
          edge.to_ip = mgmt_addr;
          edge.from_port = neighbor.local_port;
          edge.to_port = neighbor.remote_port;
          edge.mgmt_addrs = neighbor.mgmt_addrs;
          edge.connection_type = "ethernet";

          graph.edges.push_back(edge);
          processed_edges.insert(edge_key);
        }
      }
    }
  }

  return graph;
}

void NetworkTopologyWindow::applySpringLayout(TopologyGraph& graph, int iterations)
{
  if (graph.nodes.empty())
    return;

  // Mark layout as starting
  m_layout_running = true;
  m_current_iteration = 0;
  m_current_mean_speed = 0.0;

  // Update button label to show "Stop Layout"
  g_idle_add(
      [](gpointer user_data) -> gboolean
      {
        NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
        window->updateLayoutButtonLabel();
        return G_SOURCE_REMOVE;
      },
      this);

  // Physics simulation parameters
  const double dt = 0.016;            // Time step for integration (16ms)
  const double k = 0.8;               // Spring force constant
  const double repulsion = 2400000.0; // Node repulsion force constant
  const double damping = 2.20;        // Velocity damping coefficient
  const double max_speed = 12000.0;   // Maximum node velocity limit

  // Node physics state
  std::map<std::string, std::pair<double, double>> vel; // velocities
  std::map<std::string, std::pair<double, double>> acc; // accelerations

  // Initialize physics state
  for (const auto& [ip, node] : graph.nodes)
  {
    vel[ip] = {0.0, 0.0};
    acc[ip] = {0.0, 0.0};
  }

  // Initialize positions randomly if needed
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_real_distribution<> pos_dist(-300.0, 300.0);

  for (auto& [ip, node] : graph.nodes)
  {
    if (node.x == 0.0 && node.y == 0.0)
    {
      node.x = pos_dist(gen);
      node.y = pos_dist(gen);
    }
  }

  // Main physics simulation loop
  for (int iter = 0; iter < iterations && !m_layout_stop_requested; ++iter)
  {
    m_current_iteration = iter;

    // Clear accelerations
    for (auto& [ip, a] : acc)
    {
      a = {0.0, 0.0};
    }

    // Apply spring forces between connected nodes
    for (const auto& edge : graph.edges)
    {
      auto node_a = graph.nodes.find(edge.from_ip);
      auto node_b = graph.nodes.find(edge.to_ip);

      if (node_a == graph.nodes.end() || node_b == graph.nodes.end())
        continue;

      // Calculate spring force between connected nodes
      double dx = node_b->second.x - node_a->second.x;
      double dy = node_b->second.y - node_a->second.y;
      double len = std::sqrt(dx * dx + dy * dy);

      if (len > 1e-9)
      {
        double dir_x = dx / len;
        double dir_y = dy / len;

        // Spring force calculation: F = k * (current_length - rest_length) * strength
        // Standard spring parameters for network topology visualization
        double rest_length = 70.0;
        double strength = 1.0;
        double force = k * (len - rest_length) * strength;

        double fx = dir_x * force;
        double fy = dir_y * force;

        // Apply equal and opposite forces
        acc[edge.from_ip].first += fx;
        acc[edge.from_ip].second += fy;
        acc[edge.to_ip].first -= fx;
        acc[edge.to_ip].second -= fy;
      }
    }

    // Apply repulsion forces between all node pairs
    for (auto it1 = graph.nodes.begin(); it1 != graph.nodes.end(); ++it1)
    {
      for (auto it2 = std::next(it1); it2 != graph.nodes.end(); ++it2)
      {
        double dx = it1->second.x - it2->second.x;
        double dy = it1->second.y - it2->second.y;
        double dist_sq = dx * dx + dy * dy + 1.0; // Add small offset to prevent division by zero
        double dist = std::sqrt(dist_sq);

        if (dist > 1e-9)
        {
          double dir_x = dx / dist;
          double dir_y = dy / dist;

          // Inverse square law repulsion force
          double force = repulsion / dist_sq;
          double fx = dir_x * force;
          double fy = dir_y * force;

          // Apply repulsion forces
          acc[it1->first].first += fx;
          acc[it1->first].second += fy;
          acc[it2->first].first -= fx;
          acc[it2->first].second -= fy;
        }
      }
    }

    // Numerical integration using Velocity Verlet method
    double total_speed = 0.0;
    int node_count = 0;

    for (auto& [ip, node] : graph.nodes)
    {
      // Update velocity: v = v + a * dt
      vel[ip].first += acc[ip].first * dt;
      vel[ip].second += acc[ip].second * dt;

      // Apply damping: v = v / (1 + damping * dt)
      double damp_factor = 1.0 / (1.0 + damping * dt);
      vel[ip].first *= damp_factor;
      vel[ip].second *= damp_factor;

      // Limit maximum speed
      double speed = std::sqrt(vel[ip].first * vel[ip].first + vel[ip].second * vel[ip].second);
      if (speed > max_speed)
      {
        vel[ip].first = (vel[ip].first / speed) * max_speed;
        vel[ip].second = (vel[ip].second / speed) * max_speed;
        speed = max_speed;
      }

      // Update position: x = x + v * dt
      node.x += vel[ip].first * dt;
      node.y += vel[ip].second * dt;

      total_speed += speed;
      node_count++;
    }

    // Calculate mean speed for convergence
    m_current_mean_speed = (node_count > 0) ? (total_speed / node_count) : 0.0;

    // Check for convergence (low mean speed indicates equilibrium)
    if (m_current_mean_speed < 0.5)
    {
      break; // Physics has reached equilibrium
    }

    // Update display every 10 iterations for smooth animation
    if (iter % 10 == 0)
    {
      g_idle_add(
          [](gpointer user_data) -> gboolean
          {
            auto* data = static_cast<std::pair<NetworkTopologyWindow*, TopologyGraph*>*>(user_data);
            NetworkTopologyWindow* win = data->first;
            TopologyGraph* graph = data->second;

            win->m_current_graph = *graph;
            gtk_widget_queue_draw(win->m_drawing_area);

            delete graph;
            delete data;
            return G_SOURCE_REMOVE;
          },
          new std::pair<NetworkTopologyWindow*, TopologyGraph*>(this, new TopologyGraph(graph)));

      // Small delay for animation
      std::this_thread::sleep_for(std::chrono::milliseconds(16));
    }
  }

  // Mark layout as finished
  m_layout_running = false;

  // Update button label back to "Apply Layout"
  g_idle_add(
      [](gpointer user_data) -> gboolean
      {
        NetworkTopologyWindow* window = static_cast<NetworkTopologyWindow*>(user_data);
        window->updateLayoutButtonLabel();
        return G_SOURCE_REMOVE;
      },
      this);

  // Final redraw to show completed layout
  if (m_drawing_area && GTK_IS_WIDGET(m_drawing_area))
    gtk_widget_queue_draw(m_drawing_area);
}

void NetworkTopologyWindow::updateLayoutButtonLabel()
{
  if (!m_layout_button || !GTK_IS_TOOL_ITEM(m_layout_button))
    return;

  if (m_layout_running)
  {
    gtk_tool_button_set_label(GTK_TOOL_BUTTON(m_layout_button), "Stop Layout");
    gtk_tool_item_set_tooltip_text(m_layout_button, "Stop the running spring layout algorithm");
  }
  else
  {
    gtk_tool_button_set_label(GTK_TOOL_BUTTON(m_layout_button), "Apply Layout");
    gtk_tool_item_set_tooltip_text(m_layout_button, "Start spring layout algorithm to reorganize nodes");
  }
}

} // namespace ProfinetDCP