/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/* profinet_viewer2_gtk.cpp -- PROFINET DCP Tool GTK main */

#include "pn_dcp_tool_gtk.h"
#include <iostream>

// Load CSS styling for modern UI
static void loadCSS()
{
  GtkCssProvider* provider = gtk_css_provider_new();
  GdkDisplay* display = gdk_display_get_default();
  GdkScreen* screen = gdk_display_get_default_screen(display);

  // Try to load from file first
  GError* error = nullptr;
  if (!gtk_css_provider_load_from_path(
          provider, "/data0/pwr/profibus/exe/profinet_viewer2/gtk/pn_dcp_tool_style.css", &error))
  {
    if (error)
    {
      std::cerr << "Warning: Failed to load CSS file: " << error->message << std::endl;
      g_error_free(error);
    }
    // Note: CSS file not found, using default GTK theme
  }
  else
  {
    gtk_style_context_add_provider_for_screen(screen, GTK_STYLE_PROVIDER(provider),
                                              GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    std::cout << "Loaded custom CSS styling" << std::endl;
  }

  g_object_unref(provider);
}

int main(int argc, char* argv[])
{
  gtk_init(&argc, &argv);

  // Load custom CSS styling
  loadCSS();

  ProfinetDCP::ProfinetDCPWindow window;
  if (!window.create())
  {
    std::cerr << "Failed to create main window" << std::endl;
    return 1;
  }

  window.show();
  window.run();

  return 0;
}