/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef TOPOLOGY_VISUALIZATION_H
#define TOPOLOGY_VISUALIZATION_H

#include <string>
#include <vector>
#include <map>
#include "../src/topology-crawler.h" // For core network structures

// GTK visualization structures for topology display
// These structures extend core network discovery with visualization properties

struct TopologyNode
{
  // Core network data
  std::string ip;
  std::string device_name;
  std::string sys_desc; // System description from LLDP
  std::vector<PortInfo> ports;

  // GTK visualization properties
  double x{0.0}, y{0.0};             // Position for drawing
  double width{120.0}, height{80.0}; // Drawing dimensions
  std::string device_type;           // Device type from the DCP tool
  std::string device_vendor;         // Vendor identifier from the DCP tool
  bool selected{false};
};

struct TopologyEdge
{
  // Core network data
  std::string from_ip;
  std::string to_ip;
  PortInfo from_port;
  PortInfo to_port;
  std::vector<std::string> mgmt_addrs; // Management addresses on this link

  // GTK visualization properties
  bool highlighted{false};
  std::string connection_type; // "ethernet", "management", etc.
};

struct TopologyGraph
{
  std::map<std::string, TopologyNode> nodes;
  std::vector<TopologyEdge> edges;

  // Infinite canvas - no fixed dimensions
  double width{2000.0};                   // Initial working area (can be expanded)
  double height{2000.0};                  // Initial working area (can be expanded)
  std::string layout_algorithm{"spring"}; // "spring", "hierarchical", "circular"
};

#endif // TOPOLOGY_VISUALIZATION_H