/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef cow_wutl_gtk_h
#define cow_wutl_gtk_h

#include "cow_gtk.h"

GtkToolItem* wutl_tools_item(GtkToolbar *tools, const char *img, GCallback cb, 
    const char* tooltip, void *ctx, int disable_focus = 1, int translate = 1);
GtkToolItem* wutl_tools_toggle_button(GtkToolbar *tools, const char *img, GCallback cb, 
    const char* tooltip, void *ctx, int disable_focus = 1, int translate = 1);
void wutl_widget_name_suffix_add(GtkWidget *w, const char *suffix);
void wutl_widget_name_suffix_sub(GtkWidget *w);
int wutl_get_dark_theme(GtkWidget *toplevel);
int wutl_dark_theme();
#endif
