/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/* pwr_version.c -- create pwr_version.h
   Creates the file pwr_version.h which is used to
   define common version variables.  */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "rt_load.h"
#include "wb_pwrs.h"
#include "wb_pwrb.h"

typedef char pwr_tVersionStr[32];

/* Parse a version string "V<major>.<minor>.<patch>" into integer components.
   Returns 0 on success, -1 on failure. */
static int parse_version(const char* str, char* prefix, int* major, int* minor, int* patch)
{
  if (sscanf(str, "%c%d.%d.%d", prefix, major, minor, patch) != 4)
    return -1;
  return 0;
}

/* Write SET_VERSION and string macros for a given version.
   Handles multi-digit version components (e.g., V7.11.13). */
static void write_version_macros(FILE* fp, const char* name, const char* verstr)
{
  char prefix;
  int major, minor, patch;

  if (parse_version(verstr, &prefix, &major, &minor, &patch) != 0)
  {
    fprintf(stderr, "Warning: cannot parse version string '%s'\n", verstr);
    return;
  }

  fprintf(fp,
          "#define pwrv_c%sVersion         "
          "SET_VERSION('%c', %d, %d, %d)\n",
          name, prefix, major, minor, patch);
  fprintf(fp, "#define pwrv_c%sVersionStr      \"%s\"\n", name, verstr);
}

int main(int argc, char* argv[])
{
  time_t tp;
  struct tm* time_tm;
  char timestr[80];
  char buildtimestr[80];
  FILE* fp;
  char prefix;
  int major, minor, patch;

  pwr_tVersionStr SmdVersion;
  pwr_tVersionStr BmdVersion;
  pwr_tVersionStr WbdbVersion;
  pwr_tVersionStr LffVersion;
  pwr_tVersionStr Version;

  /* get arguments */
  if (argc < 2)
  {
    printf("Error creating pwr_version.h: wrong number of arguments\n");
    exit(0);
  }

  strcpy(Version, *++argv);
  strcpy(SmdVersion, pwrs_cSmdVersionStr);
  strcpy(BmdVersion, pwrb_cBmdVersionStr);
  strcpy(WbdbVersion, ldh_cWbdbVersionStr);
  strcpy(LffVersion, load_cLffVersionStr);

  /* get build time */
  time(&tp);
  time_tm = localtime(&tp);
  strftime(timestr, sizeof(timestr), "%d %B %Y", time_tm);
  strftime(buildtimestr, sizeof(buildtimestr), "%d-%b-%Y %H:%M:%S", time_tm);

  /* Parse the main version for WbdbVersionShortStr */
  if (parse_version(WbdbVersion, &prefix, &major, &minor, &patch) != 0)
  {
    fprintf(stderr, "Error: cannot parse WbdbVersion '%s'\n", WbdbVersion);
    exit(1);
  }

  fp = fopen("pwr_version.h", "w");
  fprintf(fp, "\n");
  fprintf(fp, "#ifndef pwr_version_h\n");
  fprintf(fp, "#define pwr_version_h\n");
  fprintf(fp, "\n");
  fprintf(fp, "/*\n");
  fprintf(fp, "  File: pwr_version.h\n");
  fprintf(fp, "\n");
  fprintf(fp, "  NOTE  !!!\n");
  fprintf(fp, "    This file is generated by the build procedure\n");
  fprintf(fp, "    and should not be edited.\n");
  fprintf(fp, "\n");
  fprintf(fp, "  Description:\n");
  fprintf(fp, "    Defines version varibles to use in messages to user.\n");
  fprintf(fp, "\n");
  fprintf(fp, "*/\n");
  fprintf(fp, "\n");
  fprintf(fp, "#include <time.h>\n");
  fprintf(fp, "\n");
  fprintf(fp, "#include \"pwr.h\"\n");
  fprintf(fp, "\n");
  fprintf(fp, "#if (pwr_dHost_byteOrder == pwr_dLittleEndian)\n");
  fprintf(fp, "#define SET_VERSION(a, b, c, d) "
              "((pwr_tVersion)((d << 24) + (c << 16) + (b << 8) + a))\n");
  fprintf(fp, "#else\n");
  fprintf(fp, "#define SET_VERSION(a, b, c, d) "
              "((pwr_tVersion)((a << 24) + (b << 16) + (c << 8) + d))\n");
  fprintf(fp, "#endif\n");
  fprintf(fp, "\n");
  fprintf(fp, "#define pwrv_cOpSys              \"Unknown Operating System\"\n");
  fprintf(fp, "\n");
  fprintf(fp, "#if defined VAX || defined __VAX\n");
  fprintf(fp, "#define pwrv_cHardware           \"VAX\"\n");
  fprintf(fp, "#else\n");
  fprintf(fp, "#define pwrv_cHardware           \"Unknown Hardware\"\n");
  fprintf(fp, "#endif\n");
  fprintf(fp, "\n");
  fprintf(fp, "#define pwrv_cBuildTime          ((time_t) %d)\n", (int)tp);
  fprintf(fp, "#define pwrv_cBuildTimeStr       \"%s\"\n", buildtimestr);
  fprintf(fp, "\n");

  write_version_macros(fp, "Pwr", Version);
  fprintf(fp, "\n");
  write_version_macros(fp, "Smd", SmdVersion);
  fprintf(fp, "\n");
  write_version_macros(fp, "Bmd", BmdVersion);
  fprintf(fp, "\n");
  write_version_macros(fp, "Wbdb", WbdbVersion);
  fprintf(fp, "#define pwrv_cWbdbVersionShortStr \"%c%d%d\"\n", prefix, major, minor);
  fprintf(fp, "\n");
  write_version_macros(fp, "Lff", LffVersion);
  fprintf(fp, "\n");
  fprintf(fp, "#endif\n");
  fclose(fp);

  return 0;
}
