/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2021 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef glow_exportscript_h
#define glow_exportscript_h

#include "glow_ctx.h"

class GrowCtx;
class GrowRect;
class GrowRectRounded;
class GrowLine;
class GrowPolyLine;
class GrowConPoint;
class GrowText;
class GrowSubAnnot;
class GrowArc;
class GrowBar;
class GrowTrend;
class GrowPie;
class GrowAxis;
class GrowImage;
class GrowGroup;
class GrowWindow;
class GrowToolbar;

class GlowExportScript {
public:
  GlowExportScript(GrowCtx* glow_ctx) : ctx(glow_ctx)
  {
  }
  int export_script(char* filename,
		    int (*userdata_cb)(void*, void*, std::ofstream&, char*));
  int array(GlowArray* o);
  int rect(GrowRect* o);
  int rectrounded(GrowRectRounded* o);
  int line(GrowLine* o);
  int polyline(GrowPolyLine* o);
  int conpoint(GrowConPoint* o);
  int text(GrowText* o);
  int annot(GrowSubAnnot* o);
  int arc(GrowArc* o);
  int node(GrowNode* o);
  int bar(GrowBar* o);
  int trend(GrowTrend* o);
  int pie(GrowPie* o);
  int axis(GrowAxis* o);
  int point(GlowPoint* o, GlowTransform* trf);
  int image(GrowImage* o);
  int group(GrowGroup* o);
  int toolbar(GrowToolbar* o);
  int window(GrowWindow* o);

  std::ofstream fp;
  GrowCtx* ctx;
  int (*userdata_script_cb)(void*, void*, std::ofstream&, char*);
};

#endif
