/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2025 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef glow_exportscript_h
#define glow_exportscript_h

#include "glow_ctx.h"

class GrowCtx;
class GrowRect;
class GrowRectRounded;
class GrowLine;
class GrowPolyLine;
class GrowConPoint;
class GrowText;
class GrowSubAnnot;
class GrowArc;
class GrowBar;
class GrowTrend;
class GrowPie;
class GrowAxis;
class GrowImage;
class GrowGroup;
class GrowLayer;
class GrowWindow;
class GrowToolbar;
class GrowScriptModule;

class GlowExportScript {
public:
  GlowExportScript(GrowCtx* glow_ctx) : ctx(glow_ctx)
  {
    strcpy(ind,"");
    strcpy(cind, "# ");
  }
  int export_script(char* filename,
		    int (*userdata_cb)(void*, void*, std::ofstream&, char*));
  int array(GlowArray* o, void* e, void* m);
  int rect(GrowRect* o, void* e, void* m);
  int rectrounded(GrowRectRounded* o, void* e, void* m);
  int line(GrowLine* o, void* e, void* m);
  int polyline(GrowPolyLine* o, void* e, void* m);
  int conpoint(GrowConPoint* o, void* e, void* m);
  int text(GrowText* o, void* e, void* m);
  int annot(GrowSubAnnot* o, void* e, void* m);
  int arc(GrowArc* o, void* e, void* m);
  int node(GrowNode* o, void* e, void* m);
  int bar(GrowBar* o, void* e, void* m);
  int trend(GrowTrend* o, void* e, void* m);
  int pie(GrowPie* o, void* e, void* m);
  int axis(GrowAxis* o, void* e, void* m);
  int point(GlowPoint* o, GlowTransform* trf);
  int image(GrowImage* o, void* e, void* m);
  int group(GrowGroup* o, void* e, void* m);
  int layer(GrowLayer* o, void* e, void* m);
  int toolbar(GrowToolbar* o, void* e, void* m);
  int window(GrowWindow* o, void* e, void* m);
  int scriptmodule(GrowScriptModule* o, void* e, void* m);
  GrowScriptModule* get_scriptmodule(GlowArrayElem *o, double *x, double *y);
  int scriptmodule_count();
  void ind_incr() {
    if (strlen(ind) > 1)
      strcat(cind, "  ");
    strcat(ind, "  ");
  }
  void ind_decr() {
    if (strlen(ind) >= 4)
      cind[strlen(ind) - 2] = 0;
    if (strlen(ind) >= 2)
      ind[strlen(ind) - 2] = 0;
  }

  std::ofstream fp;
  GrowCtx* ctx;
  int (*userdata_script_cb)(void*, void*, std::ofstream&, char*);
  char ind[80];
  char cind[80];
};

#endif
