/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef configured_devices_h
#define configured_devices_h

#include <string>
#include <functional>
#include "co_pugixml.hpp"

namespace ProfinetDCP
{

class ConfiguredDeviceReader
{
public:
  // Callback function type for activity logging
  using ActivityLogCallback = std::function<void(const std::string&)>;
  
  ConfiguredDeviceReader();
  ~ConfiguredDeviceReader();

  // Load configured devices from XML file based on interface name
  bool loadConfiguredDevices(const std::string& interface_name);
  
  // Get the XML document (contains all device nodes)
  const pugi::xml_document& getXMLDocument() const { return m_xml_doc; }
  
  // Get the configuration file path for an interface
  static std::string getConfigFilePath(const std::string& interface_name);
  
  // Check if devices are loaded
  bool hasLoadedDevices() const { return m_devices_loaded; }
  
  // Get current interface name
  const std::string& getCurrentInterface() const { return m_current_interface; }
  
  // Set activity log callback
  void setActivityLogCallback(ActivityLogCallback callback) { m_activity_log_callback = callback; }

private:
  pugi::xml_document m_xml_doc;
  std::string m_current_interface;
  bool m_devices_loaded;
  ActivityLogCallback m_activity_log_callback;
  
  // Log missing file message
  void logMissingFileMessage(const std::string& interface_name) const;
};

} // namespace ProfinetDCP

#endif // configured_devices_h