/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#pragma once

#include <cstdint>
#include <vector>
#include <array>
#include <string>
#include <memory>

namespace ProfinetDCP
{

// Constants
constexpr std::array<uint8_t, 6> PROFINET_MULTICAST_MAC_IDENTIFY = {0x01, 0x0e, 0xcf, 0x00, 0x00, 0x00};
constexpr uint16_t RESPONSE_DELAY = 0x0080;
constexpr uint16_t ETHER_TYPE = 0x8892;
constexpr std::array<uint8_t, 2> LED_BLINK_VALUE = {0x01, 0x00};

// DCP Protocol Constants
constexpr uint16_t ETHERTYPE_8021Q = 0x8100;
constexpr uint16_t ETHERTYPE_PROFINET = 0x8892;
constexpr size_t MAX_FRAME_SIZE = 1518;

// DCP Block Error Codes
constexpr uint8_t DCP_BLOCK_ERROR_OK = 0x00;
constexpr uint8_t DCP_BLOCK_ERROR_OPTION_UNSUPP = 0x01;
constexpr uint8_t DCP_BLOCK_ERROR_SUBOPTION_UNSUPP = 0x02;
constexpr uint8_t DCP_BLOCK_ERROR_SUBOPTION_NOT_SET = 0x03;
constexpr uint8_t DCP_BLOCK_ERROR_RESOURCE_ERROR = 0x04;
constexpr uint8_t DCP_BLOCK_ERROR_SET_NOT_POSSIBLE = 0x05;

/**
 * Constants for the different DCP frame IDs
 */
enum class FrameID : uint16_t
{
  GET_SET = 0xfefd,
  IDENTIFY_REQUEST = 0xfefe,
  IDENTIFY_RESPONSE = 0xfeff
};

/**
 * DCP block qualifiers
 */
class BlockQualifier
{
public:
  // Indicate that a value should be stored permanently
  static constexpr std::array<uint8_t, 2> STORE_PERMANENT = {0x00, 0x01};

  // Reset to factory with mode communication
  static constexpr std::array<uint8_t, 2> RESET_COMMUNICATION = {0x00, 0x04};

  // Indicate that a value should be stored temporary (value will be discarded after power reset)
  static constexpr std::array<uint8_t, 2> STORE_TEMPORARY = {0x00, 0x00};

  // Used for ControlOption with Suboption other than SuboptionResetToFactory (eg. when flashing LED)
  static constexpr std::array<uint8_t, 2> RESERVED = {0x00, 0x00};
};

/**
 * Reset to factory modes
 */
class ResetFactoryModes
{
public:
  static constexpr std::array<uint8_t, 2> RESET_APPLICATION_DATA = {0x00, 0x02};
  static constexpr std::array<uint8_t, 2> RESET_COMMUNICATION = {0x00, 0x04};
  static constexpr std::array<uint8_t, 2> RESET_ENGENEERING = {0x00, 0x06};
  static constexpr std::array<uint8_t, 2> RESET_ALL_DATA = {0x00, 0x08};
  static constexpr std::array<uint8_t, 2> RESET_DEVICE = {0x00, 0x10};
  static constexpr std::array<uint8_t, 2> RESET_AND_RESTORE = {0x00, 0x12};
};

/**
 * Service type of a DCP packet
 */
enum class ServiceType : uint8_t
{
  REQUEST = 0,
  RESPONSE = 1
};

/**
 * Service ID of a DCP packet
 */
enum class ServiceID : uint8_t
{
  GET = 3,
  SET = 4,
  IDENTIFY = 5
};

/**
 * Option and suboption pairs for DCP blocks
 */
class Option
{
public:
  static constexpr uint8_t IP_OPTION = 1;
  static constexpr uint8_t IP_ADDRESS_SUBOPTION = 2;

  static constexpr uint8_t DEVICE_PROPERTIES_OPTION = 2;
  static constexpr uint8_t DEVICE_FAMILY_SUBOPTION = 1;
  static constexpr uint8_t NAME_OF_STATION_SUBOPTION = 2;
  static constexpr uint8_t DEVICE_ID_SUBOPTION = 3;

  static constexpr uint8_t CONTROL_OPTION = 5;
  static constexpr uint8_t START_TRANSACTION_SUBOPTION = 1;
  static constexpr uint8_t END_TRANSACTION_SUBOPTION = 2;
  static constexpr uint8_t BLINK_LED_SUBOPTION = 3;
  static constexpr uint8_t RESET_FACTORY_SUBOPTION = 5;
  static constexpr uint8_t RESET_TO_FACTORY_SUBOPTION = 6;

  static constexpr uint8_t ALL_OPTION = 0xFF;
  static constexpr uint8_t ALL_SUBOPTION = 0xFF;
};

/**
 * Abstract base class for DCP data blocks
 */
class DCPDataBlock
{
public:
  DCPDataBlock(uint8_t option, uint8_t suboption) : option_(option), suboption_(suboption) {}

  virtual ~DCPDataBlock() = default;

  uint8_t getOption() const { return option_; }
  uint8_t getSuboption() const { return suboption_; }

  virtual std::vector<uint8_t> serialize() const = 0;

protected:
  uint8_t option_;
  uint8_t suboption_;
};

/**
 * Name of Station data block
 */
class NameOfStationBlock : public DCPDataBlock
{
public:
  NameOfStationBlock() : DCPDataBlock(Option::DEVICE_PROPERTIES_OPTION, Option::NAME_OF_STATION_SUBOPTION) {}

  explicit NameOfStationBlock(const std::string& name)
      : DCPDataBlock(Option::DEVICE_PROPERTIES_OPTION, Option::NAME_OF_STATION_SUBOPTION), name_(name)
  {
  }

  void setName(const std::string& name) { name_ = name; }
  const std::string& getName() const { return name_; }

  std::vector<uint8_t> serialize() const override;

  void setBlockQualifier(const std::array<uint8_t, 2>& qualifier) { block_qualifier_ = qualifier; }

private:
  std::string name_;
  std::array<uint8_t, 2> block_qualifier_ = BlockQualifier::STORE_PERMANENT;
};

/**
 * IP Address data block
 */
class IPAddressBlock : public DCPDataBlock
{
public:
  IPAddressBlock() : DCPDataBlock(Option::IP_OPTION, Option::IP_ADDRESS_SUBOPTION) {}

  IPAddressBlock(uint32_t ip, uint32_t subnet, uint32_t gateway)
      : DCPDataBlock(Option::IP_OPTION, Option::IP_ADDRESS_SUBOPTION), ip_address_(ip), subnet_mask_(subnet),
        default_gateway_(gateway)
  {
  }

  void setIP(uint32_t ip) { ip_address_ = ip; }
  void setSubnet(uint32_t subnet) { subnet_mask_ = subnet; }
  void setGateway(uint32_t gateway) { default_gateway_ = gateway; }

  uint32_t getIP() const { return ip_address_; }
  uint32_t getSubnet() const { return subnet_mask_; }
  uint32_t getGateway() const { return default_gateway_; }

  std::vector<uint8_t> serialize() const override;

  void setBlockQualifier(const std::array<uint8_t, 2>& qualifier) { block_qualifier_ = qualifier; }

private:
  uint32_t ip_address_ = 0;
  uint32_t subnet_mask_ = 0;
  uint32_t default_gateway_ = 0;
  std::array<uint8_t, 2> block_qualifier_ = BlockQualifier::STORE_PERMANENT;
};

/**
 * LED Blink control block
 */
class BlinkLEDBlock : public DCPDataBlock
{
public:
  BlinkLEDBlock() : DCPDataBlock(Option::CONTROL_OPTION, Option::BLINK_LED_SUBOPTION) {}

  std::vector<uint8_t> serialize() const override;

private:
  std::array<uint8_t, 2> block_qualifier_ = BlockQualifier::RESERVED;
  std::array<uint8_t, 2> led_value_ = LED_BLINK_VALUE;
};

/**
 * Reset to Factory control block
 */
class ResetToFactoryBlock : public DCPDataBlock
{
public:
  explicit ResetToFactoryBlock(
      const std::array<uint8_t, 2>& reset_mode = ResetFactoryModes::RESET_COMMUNICATION)
      : DCPDataBlock(Option::CONTROL_OPTION, Option::RESET_TO_FACTORY_SUBOPTION), reset_mode_(reset_mode)
  {
  }

  void setResetMode(const std::array<uint8_t, 2>& mode) { reset_mode_ = mode; }

  std::vector<uint8_t> serialize() const override;

private:
  std::array<uint8_t, 2> block_qualifier_ = BlockQualifier::RESET_COMMUNICATION;
  std::array<uint8_t, 2> reset_mode_;
};

/**
 * End Transaction control block
 */
class EndTransactionBlock : public DCPDataBlock
{
public:
  EndTransactionBlock() : DCPDataBlock(Option::CONTROL_OPTION, Option::END_TRANSACTION_SUBOPTION) {}

  void setBlockQualifier(const std::array<uint8_t, 2>& qualifier) { block_qualifier_ = qualifier; }

  std::vector<uint8_t> serialize() const override;

private:
  std::array<uint8_t, 2> block_qualifier_ = BlockQualifier::RESERVED;
};

/**
 * All option block (used for identify requests)
 */
class AllOptionBlock : public DCPDataBlock
{
public:
  AllOptionBlock() : DCPDataBlock(Option::ALL_OPTION, Option::ALL_SUBOPTION) {}

  std::vector<uint8_t> serialize() const override;
};

/**
 * Response DCP Data Blocks - these parse received response data
 */

/**
 * Name of Station response block
 */
class NameOfStationResponseBlock : public DCPDataBlock
{
public:
  NameOfStationResponseBlock()
      : DCPDataBlock(Option::DEVICE_PROPERTIES_OPTION, Option::NAME_OF_STATION_SUBOPTION)
  {
  }

  bool parseFromData(const uint8_t* data, uint16_t length);

  const std::string& getName() const { return name_; }
  uint16_t getBlockInfo() const { return block_info_; }

  std::vector<uint8_t> serialize() const override { return {}; } // Not used for response blocks

private:
  std::string name_;
  uint16_t block_info_ = 0;
};

/**
 * IP Address response block
 */
class IPAddressResponseBlock : public DCPDataBlock
{
public:
  IPAddressResponseBlock() : DCPDataBlock(Option::IP_OPTION, Option::IP_ADDRESS_SUBOPTION) {}

  bool parseFromData(const uint8_t* data, uint16_t length);

  uint32_t getIP() const { return ip_address_; }
  uint32_t getSubnet() const { return subnet_mask_; }
  uint32_t getGateway() const { return default_gateway_; }
  const std::array<uint8_t, 2>& getBlockQualifier() const { return block_qualifier_; }
  uint8_t getBlockError() const { return block_error_; }
  uint8_t getBlockInfo() const { return block_info_; }

  std::vector<uint8_t> serialize() const override { return {}; } // Not used for response blocks

private:
  uint32_t ip_address_ = 0;
  uint32_t subnet_mask_ = 0;
  uint32_t default_gateway_ = 0;
  std::array<uint8_t, 2> block_qualifier_{};
  uint8_t block_error_ = 0;
  uint8_t block_info_ = 0;
};

/**
 * Device Family response block (contains type of station/device family). Not used since we take it from
 * device ID and the xml file (data from profibus foundation)
 */
class DeviceFamilyResponseBlock : public DCPDataBlock
{
public:
  DeviceFamilyResponseBlock()
      : DCPDataBlock(Option::DEVICE_PROPERTIES_OPTION, Option::DEVICE_FAMILY_SUBOPTION)
  {
  }

  bool parseFromData(const uint8_t* data, uint16_t length);

  const std::string& getDeviceFamily() const { return device_family_; }
  uint16_t getBlockInfo() const { return block_info_; }

  std::vector<uint8_t> serialize() const override { return {}; } // Not used for response blocks

private:
  std::string device_family_;
  uint16_t block_info_ = 0;
};

/**
 * Device ID response block (contains vendor ID and device ID)
 */
class DeviceIDResponseBlock : public DCPDataBlock
{
public:
  DeviceIDResponseBlock() : DCPDataBlock(Option::DEVICE_PROPERTIES_OPTION, Option::DEVICE_ID_SUBOPTION) {}

  bool parseFromData(const uint8_t* data, uint16_t length);

  uint16_t getVendorID() const { return vendor_id_; }
  uint16_t getDeviceID() const { return device_id_; }
  uint16_t getBlockInfo() const { return block_info_; }

  std::vector<uint8_t> serialize() const override { return {}; } // Not used for response blocks

private:
  uint16_t vendor_id_ = 0;
  uint16_t device_id_ = 0;
  uint16_t block_info_ = 0;
};

/**
 * Control response block (for set/reset operations)
 */
class ControlResponseBlock : public DCPDataBlock
{
public:
  explicit ControlResponseBlock(uint8_t suboption) : DCPDataBlock(Option::CONTROL_OPTION, suboption) {}

  bool parseFromData(const uint8_t* data, uint16_t length);

  uint8_t getBlockError() const { return m_block_error; }
  uint8_t getBlockOption() const { return m_block_option; }
  uint8_t getBlockSuboption() const { return m_block_suboption; }

  std::vector<uint8_t> serialize() const override { return {}; } // Not used for response blocks

private:
  uint8_t m_block_error = 0;
  uint8_t m_block_option = 0;
  uint8_t m_block_suboption = 0;
};

// Basic protocol types
struct MacAddress
{
  std::array<uint8_t, 6> addr;

  MacAddress() : addr{0} {}
  explicit MacAddress(const std::array<uint8_t, 6>& a) : addr(a) {}
  MacAddress(uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e, uint8_t f) : addr{a, b, c, d, e, f} {}

  std::string toString() const;
  bool fromString(const std::string& str);
  bool operator==(const MacAddress& other) const { return addr == other.addr; }
  bool operator<(const MacAddress& other) const { return addr < other.addr; }
};

struct IPAddress
{
  uint32_t addr;

  IPAddress() : addr(0) {}
  explicit IPAddress(uint32_t a) : addr(a) {}
  IPAddress(uint8_t a, uint8_t b, uint8_t c, uint8_t d) : addr((a << 24) | (b << 16) | (c << 8) | d) {}

  std::string toString() const;
  bool fromString(const std::string& str);
  bool operator==(const IPAddress& other) const { return addr == other.addr; }

  bool isValid() const { return addr != 0; }
};

// DCP Options
constexpr uint8_t DCP_OPTION_IP = 0x01;
constexpr uint8_t DCP_OPTION_IP_SUB_FULL_IP = 0x02;

constexpr uint8_t DCP_OPTION_DEVICE_PROPERTIES = 0x02;
constexpr uint8_t DCP_OPTION_DEVICE_PROPERTIES_SUB_NAMEOFSTATION = 0x02;
constexpr uint8_t DCP_OPTION_DEVICE_PROPERTIES_SUB_DEVICEID = 0x03;

constexpr uint8_t DCP_OPTION_CONTROL = 0x05;
constexpr uint8_t DCP_OPTION_CONTROL_SUB_RESPONSE = 0x04;

constexpr uint8_t DCP_OPTION_ALL = 0xFF;
constexpr uint8_t DCP_OPTION_ALL_SUB_ALL = 0xFF;

/**
 * DCP Frame - handles serialization/deserialization of PROFINET DCP frames
 */
class DCPFrame
{
public:
  enum class FrameType : uint8_t
  {
    Request = 0x00,
    Response = 0x01
  };

  enum class ServiceType : uint8_t
  {
    Identify = 0x05,
    Get = 0x03,
    Set = 0x04
  };

  DCPFrame();

  void setDestination(const MacAddress& mac);
  void setSource(const MacAddress& mac);
  void setFrameType(FrameType type);
  void setServiceType(ServiceType service);
  void setTransactionId(uint32_t id);

  void addIPOption(const IPAddress& ip, const IPAddress& subnet, const IPAddress& gateway);
  void addNameOption(const std::string& name);
  void addAllOption();
  void addBlinkLEDOption();
  void addEndTransactionOption();
  void
  addResetToFactoryOption(const std::array<uint8_t, 2>& reset_mode = ResetFactoryModes::RESET_COMMUNICATION);

  std::vector<uint8_t> serialize() const;
  bool deserialize(const std::vector<uint8_t>& data);

  uint32_t getTransactionId() const { return m_transaction_id; }
  MacAddress getSourceMAC() const;
  FrameType getFrameType() const { return m_frame_type; }
  ServiceType getServiceType() const { return m_service_type; }
  FrameID getDetectedFrameId() const { return m_detected_frame_id; }
  const std::vector<std::unique_ptr<DCPDataBlock>>& getParsedBlocks() const { return m_parsed_blocks; }

  // Convenience methods to get specific block types
  std::vector<const ControlResponseBlock*> getControlBlocks() const;

  // Check for control block errors
  bool hasControlBlockErrors() const;
  std::vector<std::string> getControlBlockErrors() const;

private:
  MacAddress m_dest_mac, m_src_mac;
  FrameType m_frame_type;
  ServiceType m_service_type;
  uint32_t m_transaction_id;
  FrameID m_detected_frame_id;
  std::vector<uint8_t> m_block_data;
  std::vector<std::unique_ptr<DCPDataBlock>> m_parsed_blocks;

  void addDCPBlock(uint8_t option, uint8_t suboption, const std::vector<uint8_t>& data);
  bool parseDCPBlocksToObjects(const uint8_t* data, size_t length);
};

} // namespace ProfinetDCP