/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include "dcp_protocol.h"
#include <algorithm>
#include <arpa/inet.h>
#include <cstring>
#include <iostream>

namespace ProfinetDCP
{

// NameOfStationBlock implementation
std::vector<uint8_t> NameOfStationBlock::serialize() const
{
  std::vector<uint8_t> data;

  // Add block qualifier first
  data.insert(data.end(), block_qualifier_.begin(), block_qualifier_.end());

  // Add name data
  data.insert(data.end(), name_.begin(), name_.end());

  return data;
}

// IPAddressBlock implementation
std::vector<uint8_t> IPAddressBlock::serialize() const
{
  std::vector<uint8_t> data;

  // Add block qualifier first
  data.insert(data.end(), block_qualifier_.begin(), block_qualifier_.end());

  // Add IP address (network byte order)
  uint32_t ip_be = htonl(ip_address_);
  data.insert(data.end(), reinterpret_cast<uint8_t*>(&ip_be), reinterpret_cast<uint8_t*>(&ip_be) + 4);

  // Add subnet mask (network byte order)
  uint32_t subnet_be = htonl(subnet_mask_);
  data.insert(data.end(), reinterpret_cast<uint8_t*>(&subnet_be), reinterpret_cast<uint8_t*>(&subnet_be) + 4);

  // Add gateway (network byte order)
  uint32_t gateway_be = htonl(default_gateway_);
  data.insert(data.end(), reinterpret_cast<uint8_t*>(&gateway_be),
              reinterpret_cast<uint8_t*>(&gateway_be) + 4);

  return data;
}

// BlinkLEDBlock implementation
std::vector<uint8_t> BlinkLEDBlock::serialize() const
{
  std::vector<uint8_t> data;

  // Add block qualifier
  data.insert(data.end(), block_qualifier_.begin(), block_qualifier_.end());

  // Add LED blink value
  data.insert(data.end(), led_value_.begin(), led_value_.end());

  return data;
}

// ResetToFactoryBlock implementation
std::vector<uint8_t> ResetToFactoryBlock::serialize() const
{
  std::vector<uint8_t> data;

  // Add block qualifier
  data.insert(data.end(), block_qualifier_.begin(), block_qualifier_.end());

  // Add reset mode
  data.insert(data.end(), reset_mode_.begin(), reset_mode_.end());

  return data;
}

// EndTransactionBlock implementation
std::vector<uint8_t> EndTransactionBlock::serialize() const
{
  std::vector<uint8_t> data;
  data.reserve(2);

  // Add block qualifier for end transaction
  data.insert(data.end(), block_qualifier_.begin(), block_qualifier_.end());

  return data;
}

// AllOptionBlock implementation
std::vector<uint8_t> AllOptionBlock::serialize() const
{
  return {}; // No data for ALL option
}

// Response block implementations

bool NameOfStationResponseBlock::parseFromData(const uint8_t* data, uint16_t length)
{
  if (length < 6) // Need at least option+suboption+length+blockerror+blockinfo = 6 bytes
    return false;

  size_t offset = 4; // Skip option+suboption+length which are already parsed

  // BlockInfo
  memcpy(&block_info_, data + offset, sizeof(block_info_));
  block_info_ = ntohl(block_info_);
  offset += sizeof(block_info_);

  // Remaining data contains block qualifier + name
  uint16_t payload_length = length - offset;

  // Extract name (remaining bytes)
  if (payload_length > 0)
  {
    name_.assign(reinterpret_cast<const char*>(data + offset), payload_length);
    // Remove null terminators
    while (!name_.empty() && name_.back() == '\0')
    {
      name_.pop_back();
    }
  }

#ifdef DEBUG
  std::cout << "NameOfStationResponseBlock: BlockError=" << (int)block_error_
            << ", BlockInfo=" << (int)block_info_ << ", Name='" << name_ << "' (length=" << name_.length()
            << ")" << std::endl;
#endif

  return true;
}

bool IPAddressResponseBlock::parseFromData(const uint8_t* data, uint16_t length)
{
  if (length < 18) // Need at least 6 (header) + 2 (qualifier) + 12 (IP data) = 20, but allow 18 for legacy
    return false;

  size_t offset = 4; // Skip option+suboption+length which are already parsed

  // Extract BlockError and BlockInfo
  block_error_ = data[offset++];
  block_info_ = data[offset++];

  // Remaining data contains block qualifier + IP data
  uint16_t payload_length = length - 6;

  if (payload_length >= 14)
  {
    // Standard format with block qualifier
    std::copy(data + offset, data + offset + 2, block_qualifier_.begin());
    offset += 2;

    uint32_t ip_net, subnet_net, gateway_net;
    std::memcpy(&ip_net, data + offset, 4);
    std::memcpy(&subnet_net, data + offset + 4, 4);
    std::memcpy(&gateway_net, data + offset + 8, 4);

    ip_address_ = ntohl(ip_net);
    subnet_mask_ = ntohl(subnet_net);
    default_gateway_ = ntohl(gateway_net);
  }
  else if (payload_length == 12)
  {
    // Legacy format without block qualifier
    block_qualifier_ = {0x00, 0x00};

    uint32_t ip_net, subnet_net, gateway_net;
    std::memcpy(&ip_net, data + offset, 4);
    std::memcpy(&subnet_net, data + offset + 4, 4);
    std::memcpy(&gateway_net, data + offset + 8, 4);

    ip_address_ = ntohl(ip_net);
    subnet_mask_ = ntohl(subnet_net);
    default_gateway_ = ntohl(gateway_net);
  }
  else
  {
    return false;
  }

  return true;
}

// DeviceFamilyResponseBlock implementation
bool DeviceFamilyResponseBlock::parseFromData(const uint8_t* data, uint16_t length)
{
  if (length < 6) // Need at least option+suboption+length+blockerror+blockinfo = 6 bytes
    return false;

  size_t offset = 4; // Skip option+suboption+length which are already parsed

  // Extract BlockError and BlockInfo
  memcpy(&block_info_, data + offset, sizeof(block_info_));
  block_info_ = ntohs(block_info_);
  offset += sizeof(block_info_);

  // Remaining data contains the device family string
  uint16_t payload_length = length - offset;

  if (payload_length > 0)
  {
    device_family_.assign(reinterpret_cast<const char*>(data + offset), payload_length);

    // Remove any null terminators (matching the old parsing behavior)
    while (!device_family_.empty() && device_family_.back() == '\0')
    {
      device_family_.pop_back();
    }

#ifdef DEBUG
    std::cout << "DeviceFamily Block parsed - Family: '" << device_family_ << "'" << std::endl;
#endif
  }

  return true;
}

// DeviceIDResponseBlock implementation
bool DeviceIDResponseBlock::parseFromData(const uint8_t* data, uint16_t length)
{
  if (length < 10) // Need at least option+suboption+length+blockerror+blockinfo+vendorid+deviceid = 10 bytes
    return false;

  size_t offset = 4; // Skip option+suboption+length which are already parsed

  memcpy(&block_info_, data + offset, sizeof(block_info_));
  block_info_ = ntohs(block_info_);
  offset += sizeof(block_info_);

  memcpy(&vendor_id_, data + offset, sizeof(vendor_id_));
  vendor_id_ = ntohs(vendor_id_);
  offset += sizeof(vendor_id_);

  memcpy(&device_id_, data + offset, sizeof(device_id_));
  device_id_ = ntohs(device_id_);

  return true;
}

bool ControlResponseBlock::parseFromData(const uint8_t* data, uint16_t length)
{
  if (length < 6) // Need at least option+suboption+length+blockerror+blockinfo = 6 bytes
    return false;

  size_t offset = 4; // Skip option+suboption+length which are already parsed

  m_block_option = data[offset++];

  m_block_suboption = data[offset++];

  m_block_error = data[offset++];

  return true;
}

// DCPFrame implementation
DCPFrame::DCPFrame()
    : m_frame_type(FrameType::Request), m_service_type(ServiceType::Identify), m_transaction_id(0),
      m_detected_frame_id(ProfinetDCP::FrameID::IDENTIFY_REQUEST)
{
}

MacAddress DCPFrame::getSourceMAC() const { return m_src_mac; }

void DCPFrame::setDestination(const MacAddress& mac)
{
  m_dest_mac = mac;
#ifdef DEBUG
  std::cout << "DCPFrame::setDestination called with: " << mac.toString() << std::endl;
#endif
}

void DCPFrame::setSource(const MacAddress& mac) { m_src_mac = mac; }
void DCPFrame::setFrameType(FrameType type) { m_frame_type = type; }
void DCPFrame::setServiceType(ServiceType service) { m_service_type = service; }
void DCPFrame::setTransactionId(uint32_t id) { m_transaction_id = id; }

void DCPFrame::addAllOption()
{
  AllOptionBlock all_block;
  auto data = all_block.serialize();
  addDCPBlock(all_block.getOption(), all_block.getSuboption(), data);
}

void DCPFrame::addBlinkLEDOption()
{
#ifdef DEBUG
  std::cout << "Adding LED blink option" << std::endl;
#endif

  BlinkLEDBlock blink_block;
  auto data = blink_block.serialize();

#ifdef DEBUG
  std::cout << "LED blink data: ";
  for (size_t i = 0; i < data.size(); i++)
  {
    printf("%02X ", data[i]);
  }
  std::cout << std::endl;
#endif

  addDCPBlock(blink_block.getOption(), blink_block.getSuboption(), data);
}

void DCPFrame::addResetToFactoryOption(const std::array<uint8_t, 2>& reset_mode)
{
#ifdef DEBUG
  std::cout << "Adding reset to factory option with mode: " << std::hex << (int)reset_mode[0] << " "
            << (int)reset_mode[1] << std::dec << std::endl;
#endif

  ResetToFactoryBlock reset_block(reset_mode);
  auto data = reset_block.serialize();

#ifdef DEBUG
  std::cout << "Reset to factory data: ";
  for (size_t i = 0; i < data.size(); i++)
  {
    printf("%02X ", data[i]);
  }
  std::cout << std::endl;
#endif

  addDCPBlock(reset_block.getOption(), reset_block.getSuboption(), data);
}

void DCPFrame::addNameOption(const std::string& name)
{
#ifdef DEBUG
  std::cout << "Adding name option: '" << name << "' (length=" << name.length() << ")" << std::endl;
#endif

  NameOfStationBlock name_block(name);
  name_block.setBlockQualifier(BlockQualifier::STORE_PERMANENT);

  auto name_data = name_block.serialize();

#ifdef DEBUG
  std::cout << "Name data with qualifier: ";
  for (size_t i = 0; i < name_data.size() && i < 20; i++)
  {
    printf("%02X ", name_data[i]);
  }
  std::cout << std::endl;
#endif

  addDCPBlock(name_block.getOption(), name_block.getSuboption(), name_data);
}

void DCPFrame::addIPOption(const IPAddress& ip, const IPAddress& subnet, const IPAddress& gateway)
{
#ifdef DEBUG
  std::cout << "Adding IP option: IP=" << ip.toString() << ", Subnet=" << subnet.toString()
            << ", Gateway=" << gateway.toString() << std::endl;
#endif

  IPAddressBlock ip_block(ip.addr, subnet.addr, gateway.addr);
  ip_block.setBlockQualifier(BlockQualifier::STORE_PERMANENT);

  auto ip_data = ip_block.serialize();

#ifdef DEBUG
  std::cout << "IP data with qualifier: ";
  for (size_t i = 0; i < ip_data.size() && i < 20; i++)
  {
    printf("%02X ", ip_data[i]);
  }
  std::cout << std::endl;
#endif

  addDCPBlock(ip_block.getOption(), ip_block.getSuboption(), ip_data);
}

void DCPFrame::addDCPBlock(uint8_t option, uint8_t suboption, const std::vector<uint8_t>& data)
{
#ifdef DEBUG
  std::cout << "Adding DCP block - Option: " << (int)option << ", Suboption: " << (int)suboption
            << ", Data length: " << data.size() << std::endl;
#endif

  m_block_data.push_back(option);
  m_block_data.push_back(suboption);

  uint16_t length = static_cast<uint16_t>(data.size());
  uint16_t length_be = htons(length);
  m_block_data.insert(m_block_data.end(), reinterpret_cast<uint8_t*>(&length_be),
                      reinterpret_cast<uint8_t*>(&length_be) + 2);

  m_block_data.insert(m_block_data.end(), data.begin(), data.end());

  // Pad to 2-byte boundary
  if ((m_block_data.size() % 2) != 0)
  {
    m_block_data.push_back(0);
#ifdef DEBUG
    std::cout << "Added 1 byte padding for 2-byte alignment" << std::endl;
#endif
  }

#ifdef DEBUG
  std::cout << "Block added - total m_block_data size: " << m_block_data.size() << std::endl;
#endif
}

std::vector<uint8_t> DCPFrame::serialize() const
{
  std::vector<uint8_t> frame;
  frame.reserve(MAX_FRAME_SIZE);

  // Ethernet header
  frame.insert(frame.end(), m_dest_mac.addr.begin(), m_dest_mac.addr.end());
  frame.insert(frame.end(), m_src_mac.addr.begin(), m_src_mac.addr.end());

#ifdef DEBUG
  std::cout << "Creating DCP frame: dest=" << m_dest_mac.toString() << ", src=" << m_src_mac.toString()
            << std::endl;
#endif

  // Add 802.1Q VLAN tag
  uint16_t vlan_ethertype_be = htons(ETHERTYPE_8021Q);
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&vlan_ethertype_be),
               reinterpret_cast<uint8_t*>(&vlan_ethertype_be) + 2);

  // VLAN: prio 6, VID 0
  uint16_t vlan_tag = htons(0x6000); // Priority 6, VLAN 0
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&vlan_tag), reinterpret_cast<uint8_t*>(&vlan_tag) + 2);

  // Inner EtherType for DCP
  uint16_t ethertype_be = htons(ETHERTYPE_PROFINET);
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&ethertype_be),
               reinterpret_cast<uint8_t*>(&ethertype_be) + 2);

  // DCP header: FrameID, ServiceID, ServiceType, XID, ResponseDelay, Length

  // FrameID by service type
  uint16_t frame_id_host;
  if (m_service_type == ServiceType::Identify)
  {
    frame_id_host = 0xfefe; // IDENTIFY_REQUEST
  }
  else
  {
    frame_id_host = 0xfefd; // GET_SET (for SET and GET operations)
  }
  uint16_t frame_id = htons(frame_id_host);
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&frame_id), reinterpret_cast<uint8_t*>(&frame_id) + 2);

  // ServiceID
  frame.push_back(static_cast<uint8_t>(m_service_type));

  // ServiceType
  frame.push_back(static_cast<uint8_t>(m_frame_type));

  // XID (Transaction ID)
  uint32_t xid_be = htonl(m_transaction_id);
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&xid_be), reinterpret_cast<uint8_t*>(&xid_be) + 4);

  // ResponseDelay: 0x0080 for multicast IDENTIFY, 0x0000 for unicast SET/GET
  uint16_t response_delay_value = 0x0000; // Default for unicast requests
  if (m_service_type == ServiceType::Identify &&
      std::memcmp(m_dest_mac.addr.data(), PROFINET_MULTICAST_MAC_IDENTIFY.data(), 6) == 0)
  {
    response_delay_value = 0x0080; // Only for multicast identify
  }
  uint16_t response_delay = htons(response_delay_value);
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&response_delay),
               reinterpret_cast<uint8_t*>(&response_delay) + 2);

  // Length (no padding)
  uint16_t data_length = static_cast<uint16_t>(m_block_data.size());
  uint16_t data_length_be = htons(data_length);
  frame.insert(frame.end(), reinterpret_cast<uint8_t*>(&data_length_be),
               reinterpret_cast<uint8_t*>(&data_length_be) + 2);

  // Options (no padding)
  frame.insert(frame.end(), m_block_data.begin(), m_block_data.end());

#ifdef DEBUG
  // Print frame (debug)
  std::cout << "DCP Frame (" << frame.size() << " bytes): ";
  for (size_t i = 0; i < std::min(frame.size(), size_t(64)); ++i)
  {
    printf("%02X ", frame[i]);
    if ((i + 1) % 16 == 0)
      printf("\n");
  }
  if (frame.size() > 64)
    printf("... (truncated)");
  printf("\n");
#endif

  return frame;
}

bool DCPFrame::deserialize(const std::vector<uint8_t>& data)
{
#ifdef DEBUG
  std::cout << "DCPFrame::deserialize: frame size = " << data.size() << std::endl;
#endif

  // Bounds check
  const size_t MIN_DCP_FRAME_SIZE = 30; // Ethernet + VLAN + DCP header minimum
  if (data.size() < MIN_DCP_FRAME_SIZE)
  {
#ifdef DEBUG
    std::cout << "DCPFrame::deserialize: frame too small (" << data.size() << " < " << MIN_DCP_FRAME_SIZE
              << ")" << std::endl;
#endif
    return false;
  }

  // Upper bound check
  if (data.size() > MAX_FRAME_SIZE)
  {
#ifdef DEBUG
    std::cout << "DCPFrame::deserialize: frame too large (" << data.size() << " > " << MAX_FRAME_SIZE << ")"
              << std::endl;
#endif
    return false;
  }

  size_t offset = 0;

  // Ethernet header
  std::copy(data.begin() + offset, data.begin() + offset + 6, m_dest_mac.addr.begin());
  offset += 6;
  std::copy(data.begin() + offset, data.begin() + offset + 6, m_src_mac.addr.begin());
  offset += 6;

  // Check VLAN tag
  uint16_t first_ethertype_be;
  std::memcpy(&first_ethertype_be, &data[offset], 2);
  uint16_t first_ethertype = ntohs(first_ethertype_be);
  offset += 2;

  uint16_t ethertype;
  if (first_ethertype == ETHERTYPE_8021Q)
  {
    // Skip Priority, DEI, ID
    offset += 2;

    // Inner EtherType
    uint16_t ethertype_be;
    std::memcpy(&ethertype_be, &data[offset], 2);
    ethertype = ntohs(ethertype_be);
    offset += 2;

#ifdef DEBUG
    std::cout << "DCPFrame::deserialize: found VLAN tag, inner ethertype = 0x" << std::hex << ethertype
              << std::dec << std::endl;
#endif
  }
  else
  {
    // No VLAN tag: direct EtherType
    ethertype = first_ethertype;
#ifdef DEBUG
    std::cout << "DCPFrame::deserialize: no VLAN tag, ethertype = 0x" << std::hex << ethertype << std::dec
              << std::endl;
#endif
  }

#ifdef DEBUG
  std::cout << "DCPFrame::deserialize: ethertype = 0x" << std::hex << ethertype << std::dec << " (expected 0x"
            << std::hex << ETHERTYPE_PROFINET << std::dec << ")" << std::endl;
#endif

  if (ethertype != ETHERTYPE_PROFINET)
  {
#ifdef DEBUG
    std::cout << "DCPFrame::deserialize: wrong ethertype, not a DCP frame" << std::endl;
#endif
    return false;
  }

  // DCP header

  // Read FrameID
  uint16_t frame_id_be;
  std::memcpy(&frame_id_be, &data[offset], 2);
  uint16_t frame_id = ntohs(frame_id_be);
  m_detected_frame_id = static_cast<ProfinetDCP::FrameID>(frame_id);
  offset += 2;

#ifdef DEBUG
  std::cout << "DCPFrame::deserialize: detected FrameID = 0x" << std::hex << frame_id << std::dec;
  switch (m_detected_frame_id)
  {
  case ProfinetDCP::FrameID::IDENTIFY_REQUEST:
    std::cout << " (Identify Request)";
    break;
  case ProfinetDCP::FrameID::IDENTIFY_RESPONSE:
    std::cout << " (Identify Response)";
    break;
  case ProfinetDCP::FrameID::GET_SET:
    std::cout << " (Get/Set)";
    break;
  default:
    std::cout << " (Unknown)";
    break;
  }
  std::cout << std::endl;
#endif

  // ServiceID
  m_service_type = static_cast<ServiceType>(data[offset++]);

  // ServiceType
  m_frame_type = static_cast<FrameType>(data[offset++]);

  // XID
  uint32_t xid_be;
  std::memcpy(&xid_be, &data[offset], 4);
  m_transaction_id = ntohl(xid_be);
  offset += 4;

  // Skip ResponseDelay
  offset += 2;

  // Length
  uint16_t data_length_be;
  std::memcpy(&data_length_be, &data[offset], 2);
  uint16_t data_length = ntohs(data_length_be);
  offset += 2;

  if (offset + data_length > data.size())
    return false;

  // Clear parsed blocks
  m_parsed_blocks.clear();

  // Parse DCP blocks
  return parseDCPBlocksToObjects(data.data() + offset, data_length);
}

std::vector<const ControlResponseBlock*> DCPFrame::getControlBlocks() const
{
  std::vector<const ProfinetDCP::ControlResponseBlock*> control_blocks;
  for (const auto& block : m_parsed_blocks)
  {
    if (auto control_block = dynamic_cast<const ProfinetDCP::ControlResponseBlock*>(block.get()))
    {
      control_blocks.push_back(control_block);
    }
  }
  return control_blocks;
}

bool DCPFrame::hasControlBlockErrors() const
{
  auto control_blocks = getControlBlocks();
  return std::any_of(control_blocks.begin(), control_blocks.end(),
                     [](const auto* control_block) { return control_block->getBlockError() != 0; });
}

std::vector<std::string> DCPFrame::getControlBlockErrors() const
{
  std::vector<std::string> errors;
  auto control_blocks = getControlBlocks();

  for (const auto* control_block : control_blocks)
  {
    uint8_t block_error = control_block->getBlockError();
    if (block_error != 0)
    {
      char hex_buffer[16];
      snprintf(hex_buffer, sizeof(hex_buffer), "0x%02X", block_error);
      std::string error_msg = "Control block error " + std::string(hex_buffer);

      snprintf(hex_buffer, sizeof(hex_buffer), "0x%02X", control_block->getOption());
      error_msg += " (Option: " + std::string(hex_buffer);

      snprintf(hex_buffer, sizeof(hex_buffer), "0x%02X", control_block->getSuboption());
      error_msg += ", SubOption: " + std::string(hex_buffer) + ")";

      // Add human-readable error descriptions for common error codes
      switch (block_error)
      {
      case 0x01:
        error_msg += " - Option not supported";
        break;
      case 0x02:
        error_msg += " - Suboption not supported or no DataSet available";
        break;
      case 0x03:
        error_msg += " - Suboption not set";
        break;
      case 0x04:
        error_msg += " - Resource Error";
        break;
      case 0x05:
        error_msg += " - SET not possible by local reasons";
        break;
      case 0x06:
        error_msg += " - In operation, SET not possible";
        break;
      default:
        error_msg += " - Unknown error code";
        break;
      }

      errors.push_back(error_msg);
    }
  }
  return errors;
}

bool DCPFrame::parseDCPBlocksToObjects(const uint8_t* data, size_t length)
{
  size_t offset = 0;

#ifdef DEBUG
  std::cout << "Parsing DCP blocks to objects, data length: " << length << std::endl;
#endif

  while (offset + 6 <= length) // Need at least option+suboption+length+blockerror+blockinfo
  {
    uint8_t option = data[offset++];
    uint8_t suboption = data[offset++];

    uint16_t dcp_block_length_be;
    std::memcpy(&dcp_block_length_be, &data[offset], 2);
    uint16_t dcp_block_length = ntohs(dcp_block_length_be);
    offset += 2;

    // Bounds check for this block
    if (offset + dcp_block_length > length)
    {
#ifdef DEBUG
      std::cout << "DCP Block extends beyond available data, breaking" << std::endl;
#endif
      break;
    }

    // Build full block (header + payload)
    std::vector<uint8_t> full_block_data;
    full_block_data.push_back(option);
    full_block_data.push_back(suboption);

    // Add length (network order)
    full_block_data.insert(full_block_data.end(), reinterpret_cast<const uint8_t*>(&dcp_block_length_be),
                           reinterpret_cast<const uint8_t*>(&dcp_block_length_be) + 2);

    // Add payload
    full_block_data.insert(full_block_data.end(), data + offset, data + offset + dcp_block_length);

#ifdef DEBUG
    std::cout << "Parsing DCP Block: Option=" << (int)option << ", SubOption=" << (int)suboption
              << ", Length=" << dcp_block_length << std::endl;
#endif

    // Create block by option/suboption
    std::unique_ptr<ProfinetDCP::DCPDataBlock> block;

    switch (option)
    {
    case DCP_OPTION_DEVICE_PROPERTIES:
      if (suboption == DCP_OPTION_DEVICE_PROPERTIES_SUB_NAMEOFSTATION)
      {
        auto name_block = std::make_unique<ProfinetDCP::NameOfStationResponseBlock>();
        if (name_block->parseFromData(full_block_data.data(), full_block_data.size()))
        {
          block = std::move(name_block);
        }
      }
      else if (suboption == DCP_OPTION_DEVICE_PROPERTIES_SUB_DEVICEID)
      {
        auto device_id_block = std::make_unique<ProfinetDCP::DeviceIDResponseBlock>();
        if (device_id_block->parseFromData(full_block_data.data(), full_block_data.size()))
        {
          block = std::move(device_id_block);
        }
      }
      break;

    case DCP_OPTION_IP:
      if (suboption == DCP_OPTION_IP_SUB_FULL_IP)
      {
        auto ip_block = std::make_unique<ProfinetDCP::IPAddressResponseBlock>();
        if (ip_block->parseFromData(full_block_data.data(), full_block_data.size()))
        {
          block = std::move(ip_block);
        }
      }
      break;

    case DCP_OPTION_CONTROL:
    {
      auto control_block = std::make_unique<ProfinetDCP::ControlResponseBlock>(suboption);
      if (control_block->parseFromData(full_block_data.data(), full_block_data.size()))
      {
        block = std::move(control_block);
      }
    }
    break;

    default:
#ifdef DEBUG
      std::cout << "Unknown DCP block option: " << (int)option << std::endl;
#endif
      break;
    }

    // Store parsed block
    if (block)
    {
      m_parsed_blocks.push_back(std::move(block));
    }

    // Next block: payload + padding to even boundary
    offset += dcp_block_length;
    if (offset % 2 != 0)
      offset++;
  }

#ifdef DEBUG
  std::cout << "Parsed " << m_parsed_blocks.size() << " DCP blocks" << std::endl;
#endif

  return true;
}

} // namespace ProfinetDCP