/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef pn_dcp_tool_h
#define pn_dcp_tool_h

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <memory>
#include <chrono>
#include <optional>
#include <map>
#include <functional>
#include "dcp_protocol.h"

namespace ProfinetDCP
{

// Forward declarations
class NetworkInterface;

// Logging callback system
typedef std::function<void(const std::string&)> LogCallback;
void registerLogCallback(LogCallback callback);

struct DCPDeviceInfo
{
  MacAddress mac_address;
  IPAddress ip_address;
  IPAddress subnet_mask;
  IPAddress default_gateway;
  std::string device_name;
  std::string type_of_station;
  uint16_t vendor_id;
  uint16_t device_id;
  uint8_t device_role;

  DCPDeviceInfo() : vendor_id(0), device_id(0), device_role(0) {}
};

enum class DCPResult
{
  Success,
  Timeout,
  NetworkError,
  InvalidParameter,
  DeviceNotFound,
  AccessDenied,
  InvalidResponse,
  NotImplemented
};

// Callback types for GUI updates
using DeviceDiscoveredCallback = std::function<void(const DCPDeviceInfo&)>;
using DeviceUpdatedCallback = std::function<void(const DCPDeviceInfo&)>;
using OperationCompleteCallback = std::function<void(DCPResult, const std::string&)>;
using ProgressCallback = std::function<void(int percent, const std::string& message)>;

class ProfinetDCPTool
{
public:
  ProfinetDCPTool();
  ~ProfinetDCPTool();

  // Initialization
  DCPResult initialize(const std::string& interface_name);
  void shutdown();

  // Synchronous operations

  static DCPResult getDeviceInfo(const MacAddress& mac, DCPDeviceInfo& info,
                                 std::chrono::milliseconds timeout = std::chrono::milliseconds(1000));

  DCPResult setDeviceName(const MacAddress& mac, const std::string& name,
                          std::chrono::milliseconds timeout = std::chrono::milliseconds(1000));

  DCPResult setIPConfiguration(const MacAddress& mac, const IPAddress& ip, const IPAddress& subnet,
                               const IPAddress& gateway,
                               std::chrono::milliseconds timeout = std::chrono::milliseconds(1000));

  DCPResult resetToFactory(const MacAddress& mac,
                           std::chrono::milliseconds timeout = std::chrono::milliseconds(5000));

  DCPResult resetToFactory(const MacAddress& mac, const std::array<uint8_t, 2>& reset_mode,
                           std::chrono::milliseconds timeout = std::chrono::milliseconds(5000));

  // Convenience methods for specific factory reset types
  DCPResult resetApplicationData(const MacAddress& mac,
                                 std::chrono::milliseconds timeout = std::chrono::milliseconds(5000));
  DCPResult resetCommunication(const MacAddress& mac,
                               std::chrono::milliseconds timeout = std::chrono::milliseconds(5000));
  DCPResult resetEngineering(const MacAddress& mac,
                             std::chrono::milliseconds timeout = std::chrono::milliseconds(5000));
  DCPResult resetAllData(const MacAddress& mac,
                         std::chrono::milliseconds timeout = std::chrono::milliseconds(10000));
  DCPResult resetDevice(const MacAddress& mac,
                        std::chrono::milliseconds timeout = std::chrono::milliseconds(15000));
  DCPResult resetAndRestore(const MacAddress& mac,
                            std::chrono::milliseconds timeout = std::chrono::milliseconds(20000));

  DCPResult blinkLED(const MacAddress& mac, bool enable = true,
                     std::chrono::milliseconds timeout = std::chrono::milliseconds(1000));

  // Asynchronous operations for GUI
  void discoverDevicesAsync(DeviceDiscoveredCallback device_callback,
                            OperationCompleteCallback complete_callback,
                            ProgressCallback progress_callback = nullptr,
                            std::chrono::milliseconds timeout = std::chrono::milliseconds(7000));

  // Utility functions
  static std::vector<std::string> getAvailableInterfaces();
  std::string getInterfaceName() const;
  MacAddress getInterfaceMAC() const;

  static std::string dcpResultToString(DCPResult result);
  static std::string vendorIdToString(uint16_t vendor_id);
  static std::string vendorIdWithHexToString(uint16_t vendor_id);
  static std::string deviceRoleToString(uint8_t role);
  static void getDeviceInfo(uint16_t vendor_id, uint16_t device_id, std::string& device_name,
                            std::string& device_type, std::string& device_description);
  static std::string deviceIdToString(uint16_t vendor_id, uint16_t device_id);
  static std::string deviceIdWithHexToString(uint16_t vendor_id, uint16_t device_id);

  // Device management

private:
  class Impl;
  std::unique_ptr<Impl> pImpl;
};

} // namespace ProfinetDCP

#endif // pn_dcp_tool_h