/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>

#include <algorithm>
#include <arpa/inet.h>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <netdb.h>
#include <optional>
#include <random>
#include <set>
#include <sstream>
#include <sys/socket.h>

#include "topology-crawler.h"

static std::string val_to_str(const netsnmp_variable_list* var)
{
  char buf[1024];
  snprint_value(buf, sizeof(buf), var->name, var->name_length, var);
  return std::string(buf);
}

// Convert raw octet address stored as OID suffix into IP string (IPv4 and IPv6)
static std::optional<std::string> decode_addr_from_oid_suffix(const oid* arr, size_t arr_len, size_t start)
{
  // LLDP management address format in OID:
  // ...<ifSubtype>.<addrLen>.<addr_byte1>.<addr_byte2>...
  // For IPv4: ifSubtype=1, addrLen=4, followed by 4 address bytes
  // For IPv6: ifSubtype=2, addrLen=16, followed by 16 address bytes

  if (start + 2 >= arr_len)
    return std::nullopt;

  size_t pos = start;

  // Look for IPv4 pattern: ifSubtype + addrLen + addr_bytes
  // ifSubtype can be 1 (IPv4) or 3 (IPv4 address) depending on device implementation
  if (pos + 2 <= arr_len && (arr[pos] == 1 || arr[pos] == 3))
  {
    size_t addr_len = arr[pos + 1];

    // Standard IPv4: length=4
    if (addr_len == 4 && pos + 6 <= arr_len)
    {
      std::ostringstream s;
      s << (int)arr[pos + 2] << "." << (int)arr[pos + 3] << "." << (int)arr[pos + 4] << "."
        << (int)arr[pos + 5];
      return s.str();
    }

    // Some devices encode IPv4 differently (e.g., length=10 for "10.254.3.114")
    // Try to find 4 consecutive values that form a valid IPv4 address
    if (addr_len > 4 && pos + 2 + addr_len <= arr_len)
    {
      for (size_t i = 0; i <= addr_len - 4; ++i)
      {
        // Check if 4 consecutive bytes form a reasonable IPv4 address
        if (arr[pos + 2 + i] > 0 && arr[pos + 2 + i] <= 255 && arr[pos + 3 + i] <= 255 &&
            arr[pos + 4 + i] <= 255 && arr[pos + 5 + i] <= 255)
        {
          std::ostringstream s;
          s << (int)arr[pos + 2 + i] << "." << (int)arr[pos + 3 + i] << "." << (int)arr[pos + 4 + i] << "."
            << (int)arr[pos + 5 + i];
          return s.str();
        }
      }
    }
  }

  // Look for pattern: ifSubtype(2) + addrLen(16) + 16 bytes for IPv6
  if (pos + 18 <= arr_len && arr[pos] == 2 && arr[pos + 1] == 16)
  {
    std::ostringstream s;
    s << std::hex;
    for (size_t i = 0; i < 16; i += 2)
    {
      if (i > 0)
        s << ":";
      unsigned int val = (arr[pos + 2 + i] << 8) | arr[pos + 2 + i + 1];
      s << val;
    }
    return s.str();
  }

  // Fallback: try to find any 4-byte sequence that looks like an IPv4 address
  // Prefer sequences that start with common private network ranges (10.x, 172.x, 192.x)
  std::string best_ip;
  int best_score = -1;

  for (size_t p = start; p + 4 <= arr_len; ++p)
  {
    bool valid_ipv4 = true;
    for (size_t j = 0; j < 4; ++j)
    {
      if (arr[p + j] > 255)
      {
        valid_ipv4 = false;
        break;
      }
    }
    if (valid_ipv4)
    {
      // Additional check: make sure it's not all zeros or looks reasonable
      if (arr[p] > 0 && (arr[p] != arr[p + 1] || arr[p + 1] != arr[p + 2] || arr[p + 2] != arr[p + 3]))
      {
        std::ostringstream s;
        s << (int)arr[p] << "." << (int)arr[p + 1] << "." << (int)arr[p + 2] << "." << (int)arr[p + 3];
        std::string candidate = s.str();

        // Score based on how likely this is a real IP address
        int score = 0;
        if (arr[p] == 10)
          score += 3; // 10.x.x.x networks
        else if (arr[p] == 172)
          score += 2; // 172.x.x.x networks
        else if (arr[p] == 192)
          score += 2; // 192.x.x.x networks
        else if (arr[p] >= 1 && arr[p] <= 223)
          score += 1; // Valid unicast range

        // Prefer addresses where bytes look reasonable (not too small)
        if (arr[p + 1] > 0)
          score++;
        if (arr[p + 2] > 0)
          score++;
        if (arr[p + 3] > 0)
          score++;

        if (score > best_score)
        {
          best_score = score;
          best_ip = candidate;
        }
      }
    }
  }

  if (!best_ip.empty())
  {
    return best_ip;
  }

  return std::nullopt;
}

// Walk a base OID and return the variable list (collected)
std::vector<netsnmp_variable_list*> snmp_walk_vars(netsnmp_session* ss, const char* base_oid_str)
{
  oid base_oid[MAX_OID_LEN];
  size_t base_len = MAX_OID_LEN;
  if (!read_objid(base_oid_str, base_oid, &base_len))
  {
    // Note: This is a static function, can't use log_message here
    // Error will be handled by caller
    return {};
  }

  oid cur[MAX_OID_LEN];
  size_t cur_len = base_len;
  memcpy(cur, base_oid, base_len * sizeof(oid));

  std::vector<netsnmp_variable_list*> collected;

  while (true)
  {
    netsnmp_pdu* pdu = snmp_pdu_create(SNMP_MSG_GETNEXT);
    snmp_add_null_var(pdu, cur, cur_len);
    netsnmp_pdu* response = nullptr;
    int status = snmp_synch_response(ss, pdu, &response);
    if (status != STAT_SUCCESS || !response)
    {
      if (response)
        snmp_free_pdu(response);
      break;
    }
    if (response->errstat != SNMP_ERR_NOERROR)
    {
      snmp_free_pdu(response);
      break;
    }
    if (!response->variables)
    {
      snmp_free_pdu(response);
      break;
    }

    // If next OID is not under the base subtree -> stop
    if (snmp_oid_compare(base_oid, base_len, response->variables->name, base_len) != 0)
    {
      // not in subtree (comparison uses first base_len elements)
      snmp_free_pdu(response);
      break;
    }

    // Copy the varbind (we must duplicate because response freed later)
    netsnmp_variable_list* v = snmp_clone_varbind(response->variables);
    if (v)
      collected.push_back(v);

    // Set cur to returned OID
    memcpy(cur, response->variables->name, response->variables->name_length * sizeof(oid));
    cur_len = response->variables->name_length;

    snmp_free_pdu(response);
  }

  return collected;
}

// Parse LLDP data from varbinds into map keyed by (timeMark, localPortNum,
// remIndex)
std::map<Key, Neighbor> parse_lldp_vars(const std::vector<netsnmp_variable_list*>& vars)
{
  std::map<Key, Neighbor> m;

  // base for lldpRemEntry fields: .1.0.8802.1.1.2.1.4.1.1  (field id follows)
  // We'll detect fields by checking the field id present right after the base.
  // But instead of hard-coding base length, compute from a sample OID prefix
  // where available. We'll just inspect each var's name[] array directly.

  for (const auto* v : vars)
  {
    const oid* arr = v->name;
    size_t alen = v->name_length;

    // we need at least field id + 3 indexes => field + timeMark + local + rem
    if (alen < 4)
      continue;

    // Find the position of the LLDP '...1.4.1.1' pattern inside OID.
    // Simpler approach: walk from the end to extract last 3 index ints
    // (timeMark, localPortNum, remIndex). LLDP's lldpRemEntry indexes are the
    // LAST three components of the OID for lldpRemEntry.* fields. So remIndex =
    // arr[alen-1], localPortNum = arr[alen-2], timeMark = arr[alen-3]
    int remIndex = (int)arr[alen - 1];
    int localPortNum = (int)arr[alen - 2];
    int timeMark = (int)arr[alen - 3];

    Key k = std::make_tuple(timeMark, localPortNum, remIndex);
    Neighbor& n = m[k]; // creates default if missing
    n.timeMark = timeMark;
    n.localPortNum = localPortNum;
    n.remIndex = remIndex;

    // identify the field id (the component BEFORE the three indexes)
    int fieldId = (int)arr[alen - 4];

    // field mapping (from LLDP-MIB lldpRemEntry definitions)
    // 4 = lldpRemLocalPortNum (local port number field)
    // More importantly known fields:
    // 5 = lldpRemChassisId
    // 6 = lldpRemChassisIdSubtype
    // 7 = lldpRemPortId
    // 8 = lldpRemPortDesc
    // 9 = lldpRemSysName
    // 10 = lldpRemSysDesc
    // 11 = lldpRemSysCapSupported
    // 12 = lldpRemSysCapEnabled

    switch (fieldId)
    {
    case 5:
    {
      // chassis id may be Hex-STRING (MAC) or printable
      if (v->type == ASN_OCTET_STR)
      {
        unsigned char* bytes = static_cast<unsigned char*>(v->val.string);
        size_t len = v->val_len;
        // print as hex MAC if length is 6
        if (len == 6)
        {
          std::ostringstream oss;
          for (size_t i = 0; i < len; ++i)
          {
            if (i)
              oss << ":";
            oss << std::hex << std::setw(2) << std::setfill('0') << (int)bytes[i];
          }
          n.chassis_id = oss.str();
        }
        else
        {
          // fallback: printable string
          n.chassis_id = std::string(reinterpret_cast<char*>(bytes), len);
        }
      }
      else
      {
        n.chassis_id = val_to_str(v);
      }
    }
    break;
    case 7:
    {
      n.port_id = val_to_str(v);
    }
    break;
    case 8:
    {
      n.port_desc = val_to_str(v);
    }
    break;
    case 9:
    {
      n.sys_name = val_to_str(v);
    }
    break;
    case 10:
    {
      n.sys_desc = val_to_str(v);
    }
    break;
    default:
      // ignore other fields here
      break;
    }
  }

  return m;
}

// Debug function to print OID for troubleshooting
// Parse lldpRemManAddrTable varbinds and attach mgmt addrs to corresponding
// neighbors. The lldpRemManAddrTable entries have indexes that include the
// management address bytes — tricky to parse, but the last three indexes are
// still (timeMark, localPortNum, remIndex) somewhere near the front. We'll
// attempt to find the corresponding (timeMark, localPortNum, remIndex) by
// searching the varbind OID.
void attach_manaddrs(std::map<Key, Neighbor>& m, const std::vector<netsnmp_variable_list*>& vars)
{
  for (const auto* v : vars)
  {
    const oid* arr = v->name;
    size_t alen = v->name_length;
    if (alen < 6)
      continue;

    // Uncomment for debugging: debug_oid(arr, alen, "ManAddr ");

    // LLDP Management Address table OID structure:
    // .1.0.8802.1.1.2.1.4.2.1.<field>.<timeMark>.<localPort>.<remIndex>.<ifSubtype>.<addrLen>.<addr_bytes>
    // We need to find the field position first, then extract the indexes

    // Look for the lldpRemManAddrTable base (.1.0.8802.1.1.2.1.4.2.1)
    // and then extract field + 3 indexes + address info

    // Try different positions to find timeMark, localPort, remIndex pattern
    for (size_t p = 0; p + 6 <= alen; ++p) // need at least field + 3 indexes + ifSubtype + addrLen
    {
      // Skip field value - not used in this function
      int tm = arr[p + 1];
      int lp = arr[p + 2];
      int ri = arr[p + 3];

      Key k = std::make_tuple(tm, lp, ri);
      if (m.find(k) != m.end())
      {
        // Found matching neighbor, try to decode address starting after the 3 indexes
        auto opt = decode_addr_from_oid_suffix(arr, alen, p + 4);
        if (opt)
        {
          // Skip IPv6 addresses (contain colons)
          bool is_ipv6 = (opt->find(':') != std::string::npos);
          if (!is_ipv6)
          {
            // Check if this address is already in the list to avoid duplicates
            bool already_exists = std::any_of(m[k].mgmt_addrs.begin(), m[k].mgmt_addrs.end(),
                                              [&opt](const auto& existing) { return existing == *opt; });
            if (!already_exists)
            {
              m[k].mgmt_addrs.push_back(*opt);
            }
          }
          break;
        }
      }
    }

    // Uncomment for debugging:
    // if (!matched)
    // {
    //   std::cout << "  -> Failed to match management address OID" <<
    //   std::endl;
    // }
  }
}

LldpSnmpClient::LldpSnmpClient(std::string community) : community_(std::move(community))
{
  init_snmp("lldp_crawler");
  SOCK_STARTUP;
}

LldpSnmpClient::~LldpSnmpClient() { SOCK_CLEANUP; }

void LldpSnmpClient::set_log_callback(LogCallback callback) { log_callback_ = callback; }

void LldpSnmpClient::log_message(const std::string& message)
{
  if (log_callback_)
  {
    log_callback_(message);
  }
  else
  {
    // Fallback to stderr for SNMP client errors
    std::cerr << message << std::endl;
  }
}

std::string LldpSnmpClient::get_device_name(const std::string& ip)
{
  snmp_session session{};
  snmp_sess_init(&session);
  session.peername = strdup(ip.c_str());
  session.version = SNMP_VERSION_1; // Many Profinet devices use SNMPv1
  session.community = reinterpret_cast<u_char*>(const_cast<char*>(community_.c_str()));
  session.community_len = community_.size();
  session.timeout = 300000; // 0.3 seconds (was 1 second)
  session.retries = 0;      // No retries for faster crawling (was 1)

  netsnmp_session* ss = snmp_open(&session);
  if (!ss)
  {
    // Try SNMPv2c as fallback
    session.version = SNMP_VERSION_2c;
    ss = snmp_open(&session);
    if (!ss)
      return "";
  }

  std::string device_name;

  // 1. First try LLDP Local System Name (.1.0.8802.1.1.2.1.3.3.0)
  oid lldp_sysname_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 3, 0};
  size_t lldp_sysname_oid_len = sizeof(lldp_sysname_oid) / sizeof(oid);

  netsnmp_pdu* pdu = snmp_pdu_create(SNMP_MSG_GET);
  snmp_add_null_var(pdu, lldp_sysname_oid, lldp_sysname_oid_len);

  netsnmp_pdu* response = nullptr;
  int status = snmp_synch_response(ss, pdu, &response);

  if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR)
  {
    if (response->variables && response->variables->type == ASN_OCTET_STR)
    {
      device_name =
          std::string(reinterpret_cast<char*>(response->variables->val.string), response->variables->val_len);
    }
  }

  if (response)
    snmp_free_pdu(response);

  // 2. If empty, try standard sysName (.1.3.6.1.2.1.1.5.0)
  if (device_name.empty())
  {
    oid sysname_oid[] = {1, 3, 6, 1, 2, 1, 1, 5, 0};
    size_t sysname_oid_len = sizeof(sysname_oid) / sizeof(oid);

    pdu = snmp_pdu_create(SNMP_MSG_GET);
    snmp_add_null_var(pdu, sysname_oid, sysname_oid_len);

    status = snmp_synch_response(ss, pdu, &response);
    if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR)
    {
      if (response->variables && response->variables->type == ASN_OCTET_STR)
      {
        device_name = std::string(reinterpret_cast<char*>(response->variables->val.string),
                                  response->variables->val_len);
      }
    }

    if (response)
      snmp_free_pdu(response);
  }

  // 3. Fallback to LLDP Local Chassis ID (.1.0.8802.1.1.2.1.3.2.0)
  if (device_name.empty())
  {
    oid lldp_chassis_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 2, 0};
    size_t lldp_chassis_oid_len = sizeof(lldp_chassis_oid) / sizeof(oid);

    pdu = snmp_pdu_create(SNMP_MSG_GET);
    snmp_add_null_var(pdu, lldp_chassis_oid, lldp_chassis_oid_len);

    status = snmp_synch_response(ss, pdu, &response);

    if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR)
    {
      if (response->variables && response->variables->type == ASN_OCTET_STR)
      {
        device_name = std::string(reinterpret_cast<char*>(response->variables->val.string),
                                  response->variables->val_len);
      }
    }

    if (response)
      snmp_free_pdu(response);
  }

  snmp_close(ss);
  return device_name;
}

// Get local system description for a device (LLDP Local System Description)
std::string LldpSnmpClient::get_system_description(const std::string& ip)
{
  snmp_session session{};
  snmp_sess_init(&session);
  session.peername = strdup(ip.c_str());
  session.version = SNMP_VERSION_1;
  session.community = reinterpret_cast<u_char*>(const_cast<char*>(community_.c_str()));
  session.community_len = community_.size();
  session.timeout = 300000; // 0.3 seconds (was 1 second)
  session.retries = 0;      // No retries for faster crawling (was 1)

  netsnmp_session* ss = snmp_open(&session);
  if (!ss)
  {
    // Try SNMPv2c as fallback
    session.version = SNMP_VERSION_2c;
    ss = snmp_open(&session);
    if (!ss)
      return "";
  }

  std::string sys_desc;

  // Query LLDP Local System Description (.1.0.8802.1.1.2.1.3.4.0)
  oid lldp_sys_desc_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 4, 0};
  size_t lldp_sys_desc_oid_len = sizeof(lldp_sys_desc_oid) / sizeof(oid);

  netsnmp_pdu* pdu = snmp_pdu_create(SNMP_MSG_GET);
  snmp_add_null_var(pdu, lldp_sys_desc_oid, lldp_sys_desc_oid_len);

  netsnmp_pdu* response = nullptr;
  int status = snmp_synch_response(ss, pdu, &response);

  if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR)
  {
    if (response->variables && response->variables->type == ASN_OCTET_STR)
    {
      sys_desc =
          std::string(reinterpret_cast<char*>(response->variables->val.string), response->variables->val_len);
    }
  }

  if (response)
    snmp_free_pdu(response);

  // If LLDP system description didn't work, try standard sysDescr (.1.3.6.1.2.1.1.1.0)
  if (sys_desc.empty())
  {
    oid sys_descr_oid[] = {1, 3, 6, 1, 2, 1, 1, 1, 0};
    size_t sys_descr_oid_len = sizeof(sys_descr_oid) / sizeof(oid);

    pdu = snmp_pdu_create(SNMP_MSG_GET);
    snmp_add_null_var(pdu, sys_descr_oid, sys_descr_oid_len);

    status = snmp_synch_response(ss, pdu, &response);

    if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR)
    {
      if (response->variables && response->variables->type == ASN_OCTET_STR)
      {
        sys_desc = std::string(reinterpret_cast<char*>(response->variables->val.string),
                               response->variables->val_len);
      }
    }

    if (response)
      snmp_free_pdu(response);
  }

  snmp_close(ss);
  return sys_desc;
}

// Get local port information for a device
std::map<int, PortInfo> LldpSnmpClient::get_local_ports(const std::string& ip)
{
  std::map<int, PortInfo> ports;

  snmp_session session{};
  snmp_sess_init(&session);
  session.peername = strdup(ip.c_str());
  session.version = SNMP_VERSION_1;
  session.community = reinterpret_cast<u_char*>(const_cast<char*>(community_.c_str()));
  session.community_len = community_.size();
  session.timeout = 300000; // 0.3 seconds (was 1 second)
  session.retries = 0;      // No retries for faster crawling (was 1)

  netsnmp_session* ss = snmp_open(&session);
  if (!ss)
  {
    session.version = SNMP_VERSION_2c;
    ss = snmp_open(&session);
    if (!ss)
      return ports;
  }

  // Smart approach: First get ports that actually have neighbors by parsing remote entries
  // This is more efficient than querying all possible ports
  auto remote_vars = snmp_walk_vars(ss, ".1.0.8802.1.1.2.1.4.1.1");
  std::set<int> ports_with_neighbors;

  // Extract local port numbers from remote neighbor entries
  for (const auto* v : remote_vars)
  {
    const oid* arr = v->name;
    size_t alen = v->name_length;

    if (alen >= 3)
    {
      // Local port number is the second-to-last component in LLDP remote entry OIDs
      int local_port = static_cast<int>(arr[alen - 2]);
      ports_with_neighbors.insert(local_port);
    }
  }

  // Free remote variables
  for (auto* v : remote_vars)
    snmp_free_var(v);

  // Start with ports that have neighbors, then add some common ports
  std::set<int> available_ports = ports_with_neighbors;

  // Add common port numbers 1-12 to catch any we might have missed
  for (int i = 1; i <= 12; ++i)
  {
    available_ports.insert(i);
  }

  // Now get port information for each discovered port
  // Walk LLDP local port table
  // Port ID: .1.0.8802.1.1.2.1.3.7.1.3.x (lldpLocPortId)
  // Port Desc: .1.0.8802.1.1.2.1.3.7.1.4.x (lldpLocPortDesc)
  oid port_id_base_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 7, 1, 3};
  oid port_desc_base_oid[] = {1, 0, 8802, 1, 1, 2, 1, 3, 7, 1, 4};

  // Query each discovered port
  for (int port_num : available_ports)
  {
    PortInfo port_info;
    port_info.port_num = port_num;

    // Get port ID
    oid port_id_oid[12];
    memcpy(port_id_oid, port_id_base_oid, sizeof(port_id_base_oid));
    port_id_oid[11] = port_num;

    netsnmp_pdu* pdu = snmp_pdu_create(SNMP_MSG_GET);
    snmp_add_null_var(pdu, port_id_oid, 12);

    netsnmp_pdu* response = nullptr;
    int status = snmp_synch_response(ss, pdu, &response);

    if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR && response->variables)
    {
      if (response->variables->type == ASN_OCTET_STR)
      {
        port_info.port_id = std::string(reinterpret_cast<char*>(response->variables->val.string),
                                        response->variables->val_len);
      }
    }

    if (response)
      snmp_free_pdu(response);

    // Get port description (regardless of whether port_id was found)
    oid port_desc_oid[12];
    memcpy(port_desc_oid, port_desc_base_oid, sizeof(port_desc_base_oid));
    port_desc_oid[11] = port_num;

    pdu = snmp_pdu_create(SNMP_MSG_GET);
    snmp_add_null_var(pdu, port_desc_oid, 12);

    status = snmp_synch_response(ss, pdu, &response);

    if (status == STAT_SUCCESS && response && response->errstat == SNMP_ERR_NOERROR && response->variables &&
        response->variables->type == ASN_OCTET_STR)
    {
      port_info.port_desc =
          std::string(reinterpret_cast<char*>(response->variables->val.string), response->variables->val_len);

      // Extract port type from description (e.g., "Ethernet Port" from full desc)
      if (port_info.port_desc.find("Ethernet Port") != std::string::npos)
        port_info.port_type = "Ethernet Port";
    }

    if (response)
      snmp_free_pdu(response);

    // Always add the port info, even if we don't have complete information
    // If port_id is empty, we'll generate a default one later
    if (port_info.port_id.empty())
    {
      port_info.port_id = "port-" + std::to_string(port_num);
    }

    ports[port_num] = port_info;
  }

  snmp_close(ss);
  return ports;
}

// Query a device and return a vector of Neighbor objects
std::vector<Neighbor> LldpSnmpClient::fetch_neighbors(const std::string& ip)
{
  std::vector<Neighbor> out;
  snmp_session session{};
  snmp_sess_init(&session);
  session.peername = strdup(ip.c_str());
  session.version = SNMP_VERSION_1; // Try SNMPv1 first for Profinet devices
  session.community = reinterpret_cast<u_char*>(const_cast<char*>(community_.c_str()));
  session.community_len = community_.size();
  session.timeout = 300000; // 0.3 seconds (was 1 second)
  session.retries = 0;      // No retries for faster crawling (was 1)

  netsnmp_session* ss = snmp_open(&session);
  if (!ss)
  {
    // Fallback to SNMPv2c
    session.version = SNMP_VERSION_2c;
    ss = snmp_open(&session);
    if (!ss)
    {
      log_message("SNMP connection failed to " + ip + " (tried both v1 and v2c)");
      return out;
    }
  }

  // Get local port information first
  auto local_ports = this->get_local_ports(ip);

  // Walk lldpRemEntry fields
  auto remVars = snmp_walk_vars(ss, ".1.0.8802.1.1.2.1.4.1.1");
  auto lldpMap = parse_lldp_vars(remVars);

  if (lldpMap.empty())
  {
    log_message("No LLDP data found on " + ip + " (device may not support LLDP)");
  }

  // Walk lldpRemManAddrTable and attach any management addresses
  auto manVars = snmp_walk_vars(ss, ".1.0.8802.1.1.2.1.4.2.1");
  attach_manaddrs(lldpMap, manVars);

  // Enhance neighbors with local port information and move into vector
  for (auto& [k, n] : lldpMap)
  {
    // Add local port information
    auto local_port_it = local_ports.find(n.localPortNum);
    if (local_port_it != local_ports.end())
    {
      n.local_port = local_port_it->second;
    }

    // Set remote port information from existing fields
    n.remote_port.port_id = n.port_id;
    n.remote_port.port_desc = n.port_desc;

    out.push_back(n);
  }

  // cleanup vars
  for (auto* v : remVars)
    snmp_free_var(v);
  for (auto* v : manVars)
    snmp_free_var(v);
  snmp_close(ss);
  return out;
}

TopologyCrawler::TopologyCrawler(std::string community) : client_(std::move(community)) {}

void TopologyCrawler::crawl_from(const std::string& seed_ip) { crawl(seed_ip); }

void TopologyCrawler::crawl_from_multiple(const std::vector<std::string>& seed_ips)
{
  log_message("Starting topology crawl from " + std::to_string(seed_ips.size()) + " seed devices...");
  for (const auto& ip : seed_ips)
  {
    if (!visited_.count(ip))
    {
      log_message("Starting crawl from seed: " + ip);
      crawl(ip);
    }
    else
    {
      log_message("Skipping " + ip + " (already visited)");
    }
  }
}

void TopologyCrawler::crawl_from_profinet_devices(const std::vector<TopologyDeviceInfo>& profinet_devices)
{
  log_message("Starting PROFINET-aware topology crawl from " + std::to_string(profinet_devices.size()) +
              " devices...");

  // Store PROFINET devices for subnet filtering
  profinet_devices_ = profinet_devices;
  subnet_filtering_enabled_ = true;

  // Build allowed subnets from PROFINET devices
  allowed_subnets_.clear();
  for (const auto& device : profinet_devices_)
  {
    if (!device.ip_address.empty() && !device.subnet_mask.empty())
    {
      allowed_subnets_.insert(device.ip_address + "/" + device.subnet_mask);
    }
  }

  log_message("Configured " + std::to_string(allowed_subnets_.size()) +
              " allowed subnets for PROFINET topology");

  // Start crawling from PROFINET device IPs
  for (const auto& device : profinet_devices_)
  {
    if (!device.ip_address.empty() && device.ip_address != "0.0.0.0")
    {
      if (!visited_.count(device.ip_address))
      {
        log_message("Starting crawl from PROFINET device: " + device.device_name + " (" + device.ip_address +
                    ")");
        crawl_filtered(device.ip_address);
      }
    }
  }
}

// void TopologyCrawler::crawl_from_multiple(const std::vector<std::string>& seed_ips)
// {
//   log_message("Starting topology crawl from " + std::to_string(seed_ips.size()) + " seed devices...");
//   for (const auto& ip : seed_ips)
//   {
//     if (!visited_.count(ip))
//     {
//       log_message("Starting crawl from seed: " + ip);
//       crawl(ip);
//     }
//     else
//     {
//       log_message("Skipping " + ip + " (already visited)");
//     }
//   }
// }

void TopologyCrawler::print_topology() const
{
  std::cout << "\n=== TOPOLOGY ===\n";
  for (const auto& [ip, device_info] : topology_)
  {
    std::cout << ip;
    if (!device_info.device_name.empty())
    {
      std::cout << " (" << device_info.device_name << ")";
    }
    std::cout << ":\n";

    for (const auto& n : device_info.neighbors)
    {
      // Display local port information
      std::cout << "  Local Port: ";
      if (!n.local_port.port_id.empty())
      {
        std::cout << n.local_port.port_id;
        if (!n.local_port.port_desc.empty())
          std::cout << " (" << n.local_port.port_desc << ")";
      }
      else
      {
        std::cout << "port-" << n.localPortNum;
      }

      // Display connection arrow and remote device
      std::cout << " -> ";

      // Display remote device name or chassis ID
      std::string remote_device = n.sys_name.empty() ? n.chassis_id : n.sys_name;
      std::cout << remote_device;

      // Display remote port information
      std::cout << " [Remote Port: ";
      if (!n.remote_port.port_id.empty())
      {
        std::cout << n.remote_port.port_id;
        if (!n.remote_port.port_desc.empty())
          std::cout << " - " << n.remote_port.port_desc;
      }
      else
      {
        std::cout << n.port_id;
      }
      std::cout << "]";

      // Display management addresses
      if (!n.mgmt_addrs.empty())
      {
        std::cout << " (Mgmt: ";
        bool first = true;
        for (const auto& a : n.mgmt_addrs)
        {
          if (!first)
            std::cout << ", ";
          std::cout << a;
          first = false;
        }
        std::cout << ")";
      }
      std::cout << "\n";
    }
  }
}

const std::map<std::string, TopologyDeviceInfo>& TopologyCrawler::get_topology() const { return topology_; }

// Log callback implementation
void TopologyCrawler::set_log_callback(LogCallback callback)
{
  log_callback_ = callback;
  // Also set the callback on the SNMP client
  client_.set_log_callback(callback);
}

void TopologyCrawler::log_message(const std::string& message)
{
  if (log_callback_)
  {
    log_callback_(message);
  }
  else
  {
    // Fallback to stdout if no callback is registered
    std::cout << message << std::endl;
  }
}

// Print summary statistics
void TopologyCrawler::print_summary() const
{
  std::cout << "\n=== TOPOLOGY SUMMARY ===\n";
  std::cout << "Total devices discovered: " << topology_.size() << "\n";

  size_t total_connections = 0;
  for (const auto& [ip, device_info] : topology_)
  {
    total_connections += device_info.neighbors.size();
  }
  std::cout << "Total LLDP connections: " << total_connections << "\n";

  std::cout << "Devices with LLDP neighbors:\n";
  for (const auto& [ip, device_info] : topology_)
  {
    if (!device_info.neighbors.empty())
    {
      std::cout << "  " << ip;
      if (!device_info.device_name.empty())
      {
        std::cout << " (" << device_info.device_name << ")";
      }
      std::cout << ": " << device_info.neighbors.size() << " neighbors\n";
    }
  }
}

// Helper function to add device to topology with deduplication
void TopologyCrawler::add_device_to_topology(const std::string& ip, const std::string& device_name,
                                             const std::string& sys_desc, const std::vector<Neighbor>& neighs)
{
  // Create DeviceInfo with all required fields
  TopologyDeviceInfo device_info;
  device_info.device_name = device_name;
  device_info.sys_desc = sys_desc;
  device_info.neighbors = neighs;
  device_info.ip_address = ip; // Store the IP address that was used to discover this device

  // Use device name as key for deduplication (fall back to IP if no device name)
  std::string device_key = device_name.empty() ? ip : device_name;

  // Check if we already have this device under a different IP
  auto existing_device = std::find_if(topology_.begin(), topology_.end(),
                                      [&device_key, &ip](const auto& pair)
                                      {
                                        const std::string& existing_key = pair.second.device_name.empty()
                                                                              ? pair.first
                                                                              : pair.second.device_name;
                                        return existing_key == device_key && pair.first != ip;
                                      });

  if (existing_device != topology_.end())
  {
    // Merge neighbors from this IP with existing device entry
    log_message("Merging duplicate device: " + device_name + " (IP: " + ip + " -> " + existing_device->first +
                ")");

    // Add new neighbors to existing device, avoiding duplicates
    for (const auto& new_neighbor : neighs)
    {
      bool duplicate = false;
      for (const auto& existing_neighbor : existing_device->second.neighbors)
      {
        // Consider neighbors the same if they have the same chassis_id or sys_name
        if ((!new_neighbor.chassis_id.empty() && new_neighbor.chassis_id == existing_neighbor.chassis_id) ||
            (!new_neighbor.sys_name.empty() && new_neighbor.sys_name == existing_neighbor.sys_name))
        {
          duplicate = true;
          break;
        }
      }
      if (!duplicate)
      {
        existing_device->second.neighbors.push_back(new_neighbor);
      }
    }

    // Don't add this IP as a separate device
    return;
  }

  topology_[ip] = device_info;
}

// Private method implementation
void TopologyCrawler::crawl(const std::string& ip)
{
  if (visited_.count(ip))
    return;
  visited_.insert(ip);
  log_message("Querying " + ip + " ...");

  auto neighs = client_.fetch_neighbors(ip);
  std::string device_name = client_.get_device_name(ip);

  std::string msg = "Found " + std::to_string(neighs.size()) + " LLDP neighbors";
  if (!device_name.empty())
  {
    msg += ", device name: " + device_name;
  }
  log_message(msg);

  // Fetch system description for tooltip display
  std::string sys_desc = client_.get_system_description(ip);

  // Add device to topology with deduplication
  add_device_to_topology(ip, device_name, sys_desc, neighs);

  for (const auto& n : neighs)
  {
    // prefer mgmt address if available
    if (!n.mgmt_addrs.empty())
    {
      for (const auto& mgmt : n.mgmt_addrs)
      {
        // Skip all IPv6 addresses (contain colons) and already visited
        bool is_ipv6 = (mgmt.find(':') != std::string::npos);
        if (!visited_.count(mgmt) && !is_ipv6)
        {
          crawl(mgmt);
        }
      }
    }
    else if (!n.chassis_id.empty())
    {
      // fallback: try resolving chassis_id as hostname (not guaranteed)
      // We'll attempt a DNS resolution only if it looks like a name (contains
      // dot or letters)
      bool looks_like_name = false;
      for (char c : n.chassis_id)
      {
        if (std::isalpha((unsigned char)c) || c == '.')
        {
          looks_like_name = true;
          break;
        }
      }
      if (looks_like_name)
      {
        // naive gethostbyname
        struct hostent* h = gethostbyname(n.chassis_id.c_str());
        if (h && h->h_addr_list && h->h_addr_list[0])
        {
          char buf[64];
          inet_ntop(h->h_addrtype, h->h_addr_list[0], buf, sizeof(buf));
          std::string resolved(buf);
          if (!visited_.count(resolved))
            crawl(resolved);
        }
      }
    }
  }
}

// Filtered crawl method that respects subnet filtering
void TopologyCrawler::crawl_filtered(const std::string& ip)
{
  if (visited_.count(ip))
    return;
  visited_.insert(ip);
  log_message("Querying " + ip + " ...");

  auto neighs = client_.fetch_neighbors(ip);
  std::string device_name = client_.get_device_name(ip);

  std::string msg = "Found " + std::to_string(neighs.size()) + " LLDP neighbors";
  if (!device_name.empty())
  {
    msg += ", device name: " + device_name;
  }
  log_message(msg);

  // Fetch system description for tooltip display
  std::string sys_desc = client_.get_system_description(ip);

  // Add device to topology with deduplication
  add_device_to_topology(ip, device_name, sys_desc, neighs);

  for (const auto& n : neighs)
  {
    // prefer mgmt address if available
    if (!n.mgmt_addrs.empty())
    {
      for (const auto& mgmt : n.mgmt_addrs)
      {
        // Skip IPv6 addresses and already visited
        bool is_ipv6 = (mgmt.find(':') != std::string::npos);
        if (!visited_.count(mgmt) && !is_ipv6)
        {
          // Try all management addresses - no subnet filtering
          log_message("Crawling remote management address: " + mgmt);
          crawl_filtered(mgmt);
        }
      }
    }
    else if (!n.chassis_id.empty())
    {
      // DNS resolution fallback (less reliable for subnet filtering)
      bool looks_like_name = false;
      for (char c : n.chassis_id)
      {
        if (std::isalpha((unsigned char)c) || c == '.')
        {
          looks_like_name = true;
          break;
        }
      }
      if (looks_like_name)
      {
        struct hostent* h = gethostbyname(n.chassis_id.c_str());
        if (h && h->h_addr_list && h->h_addr_list[0])
        {
          char buf[64];
          inet_ntop(h->h_addrtype, h->h_addr_list[0], buf, sizeof(buf));
          std::string resolved(buf);
          if (!visited_.count(resolved))
          {
            log_message("Crawling resolved hostname: " + resolved);
            crawl_filtered(resolved);
          }
        }
      }
    }
  }
}

// Check if IP is in any of the allowed PROFINET subnets
bool TopologyCrawler::is_ip_in_allowed_subnets(const std::string& ip) const
{
  if (!subnet_filtering_enabled_ || profinet_devices_.empty())
    return true;

  for (const auto& device : profinet_devices_)
  {
    if (!device.ip_address.empty() && !device.subnet_mask.empty())
    {
      if (is_same_subnet(ip, device.ip_address, device.subnet_mask))
      {
        return true;
      }
    }
  }
  return false;
}

// Check if two IPs are in the same subnet
bool TopologyCrawler::is_same_subnet(const std::string& ip1, const std::string& ip2,
                                     const std::string& subnet_mask) const
{
  struct in_addr addr1, addr2, mask;

  if (inet_aton(ip1.c_str(), &addr1) == 0 || inet_aton(ip2.c_str(), &addr2) == 0 ||
      inet_aton(subnet_mask.c_str(), &mask) == 0)
  {
    return false;
  }

  // Apply subnet mask to both IPs and compare
  return (addr1.s_addr & mask.s_addr) == (addr2.s_addr & mask.s_addr);
}

#ifdef LLDP_STANDALONE_TOOL
int main(int argc, char** argv)
{
  if (argc < 2)
  {
    std::cerr << "Usage: " << argv[0] << " <seed-ip> [community]\n";
    std::cerr << "   or: " << argv[0] << " --batch <ip1,ip2,ip3,...> [community]\n";
    std::cerr << "\n";
    std::cerr << "Examples:\n";
    std::cerr << "  " << argv[0] << " 10.248.0.5 public\n";
    std::cerr << "  " << argv[0] << " --batch 10.248.0.5,10.248.0.10,10.248.0.11 public\n";
    return 1;
  }

  std::string community = (argc >= 3) ? argv[argc - 1] : "public";

  TopologyCrawler crawler(community);

  // Check for batch mode (multiple seed IPs)
  if (std::string(argv[1]) == "--batch" && argc >= 3)
  {
    std::string ip_list = argv[2];
    std::vector<std::string> seed_ips;

    // Parse comma-separated IP list
    std::stringstream ss(ip_list);
    std::string ip;
    while (std::getline(ss, ip, ','))
    {
      seed_ips.push_back(ip);
    }

    crawler.crawl_from_multiple(seed_ips);
  }
  else
  {
    // Single seed mode
    std::string seed = argv[1];
    crawler.crawl_from(seed);
  }

  crawler.print_topology();
  crawler.print_summary();

  return 0;
}
#endif // LLDP_STANDALONE_TOOL
