/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#pragma once

#include <map>
#include <string>
#include <tuple>
#include <vector>
#include <set>
#include <functional>

// Log callback function type
using LogCallback = std::function<void(const std::string&)>;

struct PortInfo
{
  std::string port_id;
  std::string port_desc;
  std::string port_type; // e.g., "Ethernet Port"
  uint64_t speed_bps{0}; // Speed in bits per second
  int port_num{};
};

struct Neighbor
{
  int timeMark{};
  int localPortNum{};
  int remIndex{};
  std::string chassis_id; // could be MAC hex string or textual
  std::string port_id;
  std::string port_desc;
  std::string sys_name;
  std::string sys_desc;
  std::vector<std::string> mgmt_addrs; // e.g., "10.248.0.10"

  // Enhanced port information
  PortInfo local_port;
  PortInfo remote_port;
};

using Key = std::tuple<int, int, int>; // timeMark, localPortNum, remIndex

struct TopologyDeviceInfo
{
  std::string device_name;
  std::string sys_desc;      // LLDP Local System Description for tooltips
  std::string device_type;   // If available as MIB, otherwise from DCP tool
  std::string device_vendor; // If available as MIB, otherwise from DCP tool
  std::vector<Neighbor> neighbors;

  // Additional fields for subnet filtering (from DCP tool)
  std::string ip_address;
  std::string subnet_mask;
  uint16_t vendor_id{0};
  uint16_t device_id{0};
  std::string mac_address;
};

// Forward declaration for net-snmp
struct snmp_session;

// LLDP SNMP client for device discovery
class LldpSnmpClient
{
public:
  explicit LldpSnmpClient(std::string community = "public");
  ~LldpSnmpClient();

  std::string get_device_name(const std::string& ip);
  std::string get_system_description(const std::string& ip);
  std::vector<Neighbor> fetch_neighbors(const std::string& ip);
  std::map<int, PortInfo> get_local_ports(const std::string& ip);

  // Log callback support
  void set_log_callback(LogCallback callback);
  void log_message(const std::string& message);

private:
  std::string community_;
  LogCallback log_callback_;
};

// Main topology crawler class
class TopologyCrawler
{
public:
  explicit TopologyCrawler(std::string community = "public");

  void crawl_from(const std::string& seed_ip);
  void crawl_from_multiple(const std::vector<std::string>& seed_ips);

  // Enhanced crawling with PROFINET device list and subnet filtering
  void crawl_from_profinet_devices(const std::vector<TopologyDeviceInfo>& profinet_devices);

  void print_topology() const;
  void print_summary() const;

  const std::map<std::string, TopologyDeviceInfo>& get_topology() const;

  // Log callback registration
  void set_log_callback(LogCallback callback);
  void log_message(const std::string& message);

private:
  void crawl(const std::string& ip);
  void crawl_filtered(const std::string& ip);

  // Device deduplication helper
  void add_device_to_topology(const std::string& ip, const std::string& device_name,
                              const std::string& sys_desc, const std::vector<Neighbor>& neighs);

  // Subnet filtering helpers
  bool is_ip_in_allowed_subnets(const std::string& ip) const;
  bool is_same_subnet(const std::string& ip1, const std::string& ip2, const std::string& subnet_mask) const;

  LldpSnmpClient client_;
  std::map<std::string, TopologyDeviceInfo> topology_;
  std::set<std::string> visited_;
  LogCallback log_callback_;

  // Subnet filtering data
  std::vector<TopologyDeviceInfo> profinet_devices_;
  std::set<std::string> allowed_subnets_; // Cached subnet ranges
  bool subnet_filtering_enabled_{false};
};