/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef rt_errh_h
#define rt_errh_h

#include "rt_errh_types.h"
#include "co_log_severity.h"
#include "co_logger.h"

#if defined __cplusplus
extern "C"
{
#endif

  /*! \file rt_errh.h
      \brief Include file for \ref Errh.
  */

  /** \addtogroup Errh */
  /** @{ */

#ifndef errh_Bugcheck
#define errh_Bugcheck(sts, str)                                                                              \
  (errh_Fatal("pwr bugcheck: <%s>, in file %s, at line %d\n%m", (str), __FILE__, __LINE__, sts), (exit(sts)))
#endif

#ifndef errh_ReturnOrBugcheck
#define errh_ReturnOrBugcheck(a, sts, lsts, str)                                                             \
  return (                                                                                                   \
      ((long int)(sts) ? ((*sts) = (lsts)) : (EVEN(lsts) ? (errh_Bugcheck(lsts, (str)), (lsts)) : (lsts))),  \
      a)
#endif

  /** \defgroup Errh_DS Errh Data Structures
   *  @{
   */

#define errh_SeveritySuccess(sts) (((sts) & 7) == 3)
#define errh_SeverityInfo(sts) (((sts) & 7) == 1)
#define errh_SeverityWarning(sts) (((sts) & 7) == 0)
#define errh_SeverityError(sts) (((sts) & 7) == 2)
#define errh_SeverityFatal(sts) (((sts) & 7) == 4)

  /**
   * Severity enumeration - now using common ProviewR severity
   */
  typedef pwr_eSeverity errh_eSeverity;

/* Compatibility definitions for existing code */
#define errh_eSeverity_Null pwr_eSeverity_Null
#define errh_eSeverity_Success pwr_eSeverity_Success
#define errh_eSeverity_Info pwr_eSeverity_Info
#define errh_eSeverity_Warning pwr_eSeverity_Warning
#define errh_eSeverity_Error pwr_eSeverity_Error
#define errh_eSeverity_Fatal pwr_eSeverity_Fatal

  /** @} */

  /** \defgroup Errh_FC Errh Functions
   *  @{
   */

  /* NOTE! errh_Init MUST always be called before any other
           errh-function is called.  */

  pwr_tStatus errh_Init(const char* programName, errh_eAnix anix);

  // Application info functions
  errh_eAnix errh_Anix(void);
  void errh_SetAnix(errh_eAnix anix);
  void errh_SetName(char* name);
  void errh_AnixName(errh_eAnix anix, char* name);
  void errh_SetStatus(pwr_tStatus sts);

  // Interactive mode
  void errh_Interactive(void);

  // Logging functions
  char* errh_GetMsg(const pwr_tStatus sts, char* buf, int bufSize);
  char* errh_GetError(const pwr_tStatus sts, char* buf, int bufSize);
  char* errh_GetText(const pwr_tStatus sts, char* buf, int bufSize);
  char* errh_Log(char* buff, char severity, const char* msg, ...);

  // Standard log functions
  void errh_Fatal(const char* msg, ...);
  void errh_Error(const char* msg, ...);
  void errh_Warning(const char* msg, ...);
  void errh_Info(const char* msg, ...);
  void errh_Success(const char* msg, ...);
  void errh_LogFatal(errh_sLog*, const char* msg, ...);
  void errh_LogError(errh_sLog*, const char* msg, ...);
  void errh_LogWarning(errh_sLog*, const char* msg, ...);
  void errh_LogInfo(errh_sLog*, const char* msg, ...);
  void errh_LogSuccess(errh_sLog*, const char* msg, ...);

  // Extended log functions
  void* errh_ErrArgMsg(pwr_tStatus sts);
  void* errh_ErrArgAF(char* s);
  void* errh_ErrArgL(int val);
  void errh_CErrLog(pwr_tStatus sts, ...);
  char* errh_Message(char* string, char severity, char* msg, ...);

  // Utility functions
  errh_eSeverity errh_Severity(pwr_tStatus);

#if defined __cplusplus
}
#endif

#endif

/** @}*/
/** @}*/
