/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/* configured_devices.cpp -- Read and manage configured PROFINET devices from XML */

#include "configured_devices.h"
#include <iostream>
#include "co_dcli.h"

namespace ProfinetDCP
{

ConfiguredDeviceReader::ConfiguredDeviceReader()
  : m_devices_loaded(false)
{
}

ConfiguredDeviceReader::~ConfiguredDeviceReader()
{
}

std::string ConfiguredDeviceReader::getConfigFilePath(const std::string& interface_name)
{
  char translated_path[256];
  std::string config_path = "$pwrp_load/pwr_pnviewer_" + interface_name + ".xml";
  dcli_translate_filename(translated_path, config_path.c_str());
  return std::string(translated_path);
}

bool ConfiguredDeviceReader::loadConfiguredDevices(const std::string& interface_name)
{
  if (interface_name.empty()) {
    return false;
  }

  m_current_interface = interface_name;
  m_devices_loaded = false;

  std::string config_file = getConfigFilePath(interface_name);
  
  // Try to load XML file
  pugi::xml_parse_result result = m_xml_doc.load_file(config_file.c_str());
  
  if (!result) {
    // File doesn't exist or parse error - log message about distributing the file
    logMissingFileMessage(interface_name);
    return false;
  }

  // Validate XML structure
  pugi::xml_node devices_node = m_xml_doc.child("ProfinetDevices");
  if (!devices_node) {
    std::cerr << "Invalid XML structure in " << config_file << " - missing ProfinetDevices root node" << std::endl;
    return false;
  }

  m_devices_loaded = true;
  return true;
}

void ConfiguredDeviceReader::logMissingFileMessage(const std::string& interface_name) const
{
  if (m_activity_log_callback) {
    m_activity_log_callback("No configuration file found for interface " + interface_name);
    m_activity_log_callback("To configure devices for this interface, create: $pwrp_load/pwr_pnviewer_" + interface_name + ".xml");
  }
}

} // namespace ProfinetDCP