/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

// #define DEBUG

#include "pn_dcp_tool.h"
#include "dcp_protocol.h"
#include "co_pugixml.hpp"
#include "co_dcli.h"
#include <sys/socket.h>
#include <linux/if_packet.h>
#include <net/ethernet.h>
#include <netinet/ether.h>
#include <arpa/inet.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <cstring>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <iostream>
#include <cerrno>
#include <cstdio>
#include <cctype>
#include <set>
#include <functional>
#include <memory>

namespace ProfinetDCP
{

// Logging callback system
typedef std::function<void(const std::string&)> LogCallback;
static LogCallback g_log_callback = nullptr;

void registerLogCallback(LogCallback callback) { g_log_callback = callback; }

void logMessage(const std::string& message)
{
  if (g_log_callback)
  {
    g_log_callback(message);
  }
}

// XML cache to avoid reloading per lookup
static pugi::xml_document* g_device_xml_cache = nullptr;
static std::string g_cached_xml_filename;

static void cleanupDeviceXML()
{
  if (g_device_xml_cache)
  {
    delete g_device_xml_cache;
    g_device_xml_cache = nullptr;
  }
  g_cached_xml_filename.clear();
}

static bool loadDeviceXML()
{
  pwr_tFileName fname;
  dcli_translate_filename(fname, "$pwr_exe/profinet_devices.xml");

#ifdef DEBUG
  std::cout << "Loading XML from: " << fname << std::endl;
#endif

  // Use cache if same file
  if (g_device_xml_cache && g_cached_xml_filename == fname)
  {
#ifdef DEBUG
    std::cout << "Using cached XML document" << std::endl;
#endif
    return true;
  }

  // Clean up existing cache
  cleanupDeviceXML();

  // Load new file
  g_device_xml_cache = new pugi::xml_document();
  pugi::xml_parse_result result = g_device_xml_cache->load_file(fname);

  if (result.status == pugi::status_ok)
  {
    g_cached_xml_filename = fname;
#ifdef DEBUG
    std::cout << "Successfully loaded XML device database" << std::endl;
#endif
    return true;
  }
  else
  {
#ifdef DEBUG
    std::cout << "Failed to load XML: " << result.description() << " at offset " << result.offset
              << std::endl;
#endif
    delete g_device_xml_cache;
    g_device_xml_cache = nullptr;
    return false;
  }
}

// Vendor ID to name via XML
static std::string vendorIdToString(uint16_t vendorId)
{
  try
  {
    if (loadDeviceXML() && g_device_xml_cache)
    {
      // Look for vendor with matching ID
      std::string xpath = "//Vendor[@ID='" + std::to_string(vendorId) + "']";
      pugi::xpath_node vendor_node = g_device_xml_cache->select_node(xpath.c_str());

      if (vendor_node.node())
      {
        const char* name = vendor_node.node().attribute("Name").value();
        if (name && strlen(name) > 0)
        {
          return std::string(name);
        }
      }
    }
  }
  catch (const std::exception& e)
  {
#ifdef DEBUG
    std::cout << "Exception in XML vendor lookup: " << e.what() << std::endl;
#endif
  }

  // Fallback to hardcoded mapping for common vendors
  switch (vendorId)
  {
  case 42:
    return "Siemens AG";
  case 674:
    return "Phoenix Contact";
  case 283:
    return "Beckhoff Automation";
  case 637:
    return "Weidmüller Interface GmbH";
  default:
    return "Unknown Vendor (" + std::to_string(vendorId) + ")";
  }
}

// Device ID to name via XML
static std::string deviceIdToString(uint16_t vendorId, uint16_t deviceId)
{
  try
  {
    if (loadDeviceXML() && g_device_xml_cache)
    {
      // Look for device with matching vendor and device ID
      std::string xpath =
          "//Vendor[@ID='" + std::to_string(vendorId) + "']//Device[@ID='" + std::to_string(deviceId) + "']";
      pugi::xpath_node device_node = g_device_xml_cache->select_node(xpath.c_str());

      if (device_node.node())
      {
        const char* name = device_node.node().attribute("Name").value();
        if (name && strlen(name) > 0)
        {
          return std::string(name);
        }
      }
    }
  }
  catch (const std::exception& e)
  {
#ifdef DEBUG
    std::cout << "Exception in XML device lookup: " << e.what() << std::endl;
#endif
  }

  // Fallback to device ID number
  return std::to_string(deviceId);
}

// DCP multicast MAC (keeping for local convenience)
static const MacAddress DCP_MULTICAST_MAC{0x01, 0x0E, 0xCF, 0x00, 0x00, 0x00};

// Use constants from dcp_protocol
using ProfinetDCP::DCP_BLOCK_ERROR_OK;
using ProfinetDCP::ETHERTYPE_8021Q;
using ProfinetDCP::ETHERTYPE_PROFINET;
using ProfinetDCP::MAX_FRAME_SIZE;

// Use DCP option constants from dcp_protocol
using ProfinetDCP::DCP_OPTION_ALL;
using ProfinetDCP::DCP_OPTION_ALL_SUB_ALL;
using ProfinetDCP::DCP_OPTION_CONTROL;
using ProfinetDCP::DCP_OPTION_CONTROL_SUB_RESPONSE;
using ProfinetDCP::DCP_OPTION_DEVICE_PROPERTIES;
using ProfinetDCP::DCP_OPTION_DEVICE_PROPERTIES_SUB_DEVICEID;
using ProfinetDCP::DCP_OPTION_DEVICE_PROPERTIES_SUB_NAMEOFSTATION;
using ProfinetDCP::DCP_OPTION_IP;
using ProfinetDCP::DCP_OPTION_IP_SUB_FULL_IP;

// Use DCPFrame from dcp_protocol
using ProfinetDCP::DCPFrame;

class NetworkInterface
{
public:
  explicit NetworkInterface(const std::string& name);
  ~NetworkInterface();

  DCPResult open();
  void close();

  DCPResult sendFrame(const DCPFrame& frame);
  DCPResult receiveFrame(DCPFrame& frame, std::chrono::milliseconds timeout);

  MacAddress getInterfaceMAC() const { return m_interface_mac; }
  std::string getInterfaceName() const { return m_interface_name; }

  bool isInterfaceUp() const;
  DCPResult checkInterfaceConnection();

private:
  std::string m_interface_name;
  int m_socket_fd;
  MacAddress m_interface_mac;

  DCPResult setupSocket();
  DCPResult getInterfaceInfo();
};

// Main implementation class
class ProfinetDCPTool::Impl
{
public:
  Impl();
  ~Impl();

  DCPResult initialize(const std::string& interface_name);
  void shutdown();

  std::unique_ptr<NetworkInterface> network_interface;
  std::atomic<uint32_t> transaction_counter{0};
  std::map<MacAddress, DCPDeviceInfo> known_devices;
  std::mutex devices_mutex;

  // Async discovery
  std::atomic<bool> discovery_running{false};
  std::thread discovery_thread;
  DeviceDiscoveredCallback device_discovered_cb;
  DeviceUpdatedCallback device_updated_cb;

  uint32_t getNextTransactionId() { return ++transaction_counter; }

  void discoveryThreadFunc(std::chrono::milliseconds interval);
  DCPResult sendRequestAndWaitResponse(const DCPFrame& request, DCPFrame& response,
                                       std::chrono::milliseconds timeout);
};

// String conversion implementations
std::string MacAddress::toString() const
{
  std::ostringstream oss;
  oss << std::hex << std::setfill('0');
  for (size_t i = 0; i < addr.size(); ++i)
  {
    if (i > 0)
      oss << ":";
    oss << std::setw(2) << static_cast<int>(addr[i]);
  }
  return oss.str();
}

bool MacAddress::fromString(const std::string& str)
{
  if (str.length() != 17)
    return false;

  for (int i = 0; i < 6; ++i)
  {
    std::string byte_str = str.substr(i * 3, 2);
    try
    {
      addr[i] = static_cast<uint8_t>(std::stoi(byte_str, nullptr, 16));
    }
    catch (...)
    {
      return false;
    }
    if (i < 5 && str[i * 3 + 2] != ':')
      return false;
  }
  return true;
}

std::string IPAddress::toString() const
{
  std::ostringstream oss;
  oss << ((addr >> 24) & 0xFF) << "." << ((addr >> 16) & 0xFF) << "." << ((addr >> 8) & 0xFF) << "."
      << (addr & 0xFF);
  return oss.str();
}

bool IPAddress::fromString(const std::string& str)
{
  struct in_addr in_addr;
  if (inet_aton(str.c_str(), &in_addr) == 0)
  {
    return false;
  }
  addr = ntohl(in_addr.s_addr);
  return true;
}

// Helper function to parse device info from DCP frame (tool layer)
static bool parseDeviceInfoFromFrame(const DCPFrame& frame, DCPDeviceInfo& info)
{
  // Use parsed blocks from frame
  const auto& blocks = frame.getParsedBlocks();
  if (blocks.empty())
  {
    return false;
  }

  // Extract device info from parsed blocks
  for (const auto& block : blocks)
  {
    if (auto name_block = dynamic_cast<const ProfinetDCP::NameOfStationResponseBlock*>(block.get()))
    {
      info.device_name = name_block->getName();
    }
    else if (auto ip_block = dynamic_cast<const ProfinetDCP::IPAddressResponseBlock*>(block.get()))
    {
      info.ip_address = IPAddress(ip_block->getIP());
      info.subnet_mask = IPAddress(ip_block->getSubnet());
      info.default_gateway = IPAddress(ip_block->getGateway());
    }
    else if (auto device_id_block = dynamic_cast<const ProfinetDCP::DeviceIDResponseBlock*>(block.get()))
    {
      info.vendor_id = device_id_block->getVendorID();
      info.device_id = device_id_block->getDeviceID();
    }
  }

  info.mac_address = frame.getSourceMAC();

  // Populate type_of_station from XML using device_id
  if (info.vendor_id != 0 && info.device_id != 0)
  {
    std::string device_name, device_type, device_description;
    ProfinetDCPTool::getDeviceInfo(info.vendor_id, info.device_id, device_name, device_type,
                                   device_description);
    info.type_of_station = device_type;
  }

  return true;
}

// NetworkInterface implementation
NetworkInterface::NetworkInterface(const std::string& name) : m_interface_name(name), m_socket_fd(-1) {}

NetworkInterface::~NetworkInterface() { close(); }

DCPResult NetworkInterface::open()
{
  if (m_socket_fd >= 0)
  {
    close();
  }

  auto result = setupSocket();
  if (result != DCPResult::Success)
  {
    return result;
  }

  return getInterfaceInfo();
}

void NetworkInterface::close()
{
  if (m_socket_fd >= 0)
  {
    ::close(m_socket_fd);
    m_socket_fd = -1;
  }
}

DCPResult NetworkInterface::setupSocket()
{
#ifdef DEBUG
  std::cout << "Setting up socket for interface: " << m_interface_name << std::endl;
#endif

  m_socket_fd = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_8021Q));
  // m_socket_fd = socket(AF_PACKET, SOCK_DGRAM, htons(ETH_P_ALL));
  if (m_socket_fd < 0)
  {
    std::cerr << "Failed to create raw socket: " << strerror(errno) << std::endl;
    return DCPResult::NetworkError;
  }

#ifdef DEBUG
  std::cout << "Socket created successfully, fd=" << m_socket_fd << std::endl;
#endif

  struct ifreq ifr;
  std::strncpy(ifr.ifr_name, m_interface_name.c_str(), IFNAMSIZ - 1);
  ifr.ifr_name[IFNAMSIZ - 1] = '\0';

  if (ioctl(m_socket_fd, SIOCGIFINDEX, &ifr) < 0)
  {
    std::cerr << "Failed to get interface index for " << m_interface_name << ": " << strerror(errno)
              << std::endl;
    ::close(m_socket_fd);
    m_socket_fd = -1;
    return DCPResult::NetworkError;
  }

#ifdef DEBUG
  std::cout << "Interface index: " << ifr.ifr_ifindex << std::endl;
#endif

  struct sockaddr_ll sll;
  std::memset(&sll, 0, sizeof(sll));
  sll.sll_family = AF_PACKET;
  sll.sll_protocol = htons(ETH_P_ALL); // Receive all, filter in application
  sll.sll_ifindex = ifr.ifr_ifindex;

  if (bind(m_socket_fd, reinterpret_cast<struct sockaddr*>(&sll), sizeof(sll)) < 0)
  {
    std::cerr << "Failed to bind socket: " << strerror(errno) << std::endl;
    ::close(m_socket_fd);
    m_socket_fd = -1;
    return DCPResult::NetworkError;
  }

#ifdef DEBUG
  std::cout << "Socket bound successfully to interface " << m_interface_name << std::endl;
#endif

  return DCPResult::Success;
}

DCPResult NetworkInterface::getInterfaceInfo()
{
  struct ifreq ifr;
  std::strncpy(ifr.ifr_name, m_interface_name.c_str(), IFNAMSIZ - 1);
  ifr.ifr_name[IFNAMSIZ - 1] = '\0';

  if (ioctl(m_socket_fd, SIOCGIFHWADDR, &ifr) < 0)
  {
    return DCPResult::NetworkError;
  }

  std::copy(reinterpret_cast<uint8_t*>(ifr.ifr_hwaddr.sa_data),
            reinterpret_cast<uint8_t*>(ifr.ifr_hwaddr.sa_data) + 6, m_interface_mac.addr.begin());

  return DCPResult::Success;
}

DCPResult NetworkInterface::sendFrame(const DCPFrame& frame)
{
  if (m_socket_fd < 0)
  {
    std::cerr << "Socket not open for sending" << std::endl;
    return DCPResult::NetworkError;
  }

  // Check interface connection before trying to send
  auto connection_result = checkInterfaceConnection();
  if (connection_result != DCPResult::Success)
    return connection_result;

  auto frame_data = frame.serialize();
#ifdef DEBUG
  std::cout << "Sending DCP frame, size: " << frame_data.size() << " bytes" << std::endl;
#endif

  ssize_t sent = send(m_socket_fd, frame_data.data(), frame_data.size(), 0);
  if (sent < 0)
  {
    std::cerr << "Failed to send frame: " << strerror(errno) << std::endl;
    // Check if the error is due to interface going down
    if (errno == ENETDOWN || errno == ENETUNREACH || errno == EHOSTUNREACH)
    {
      logMessage("Network interface appears to be down");
#ifdef DEBUG
      std::cerr << "Network interface appears to be down" << std::endl;
#endif
    }
    return DCPResult::NetworkError;
  }
  else if (static_cast<size_t>(sent) != frame_data.size())
  {
    std::cerr << "Partial send: " << sent << " of " << frame_data.size() << " bytes" << std::endl;
    return DCPResult::NetworkError;
  }

#ifdef DEBUG
  std::cout << "DCP frame sent successfully (" << sent << " bytes)" << std::endl;
#endif
  return DCPResult::Success;
}

DCPResult NetworkInterface::receiveFrame(DCPFrame& frame, std::chrono::milliseconds timeout)
{
  if (m_socket_fd < 0)
  {
#ifdef DEBUG
    std::cout << "receiveFrame: socket not open" << std::endl;
#endif
    return DCPResult::NetworkError;
  }

  // Check interface connection
  auto connection_result = checkInterfaceConnection();
  if (connection_result != DCPResult::Success)
    return connection_result;

  fd_set read_fds;
  FD_ZERO(&read_fds);
  FD_SET(m_socket_fd, &read_fds);

  struct timeval tv;
  tv.tv_sec = timeout.count() / 1000;
  tv.tv_usec = (timeout.count() % 1000) * 1000;

#ifdef DEBUG
  std::cout << "receiveFrame: waiting for data with timeout " << timeout.count() << "ms" << std::endl;
#endif
  int ready = select(m_socket_fd + 1, &read_fds, nullptr, nullptr, &tv);
  if (ready <= 0)
  {
    if (ready == 0)
    {
#ifdef DEBUG
      std::cout << "receiveFrame: timeout" << std::endl;
#endif
    }
    else
    {
#ifdef DEBUG
      std::cout << "receiveFrame: select error: " << strerror(errno) << std::endl;
#endif
    }
    return (ready == 0) ? DCPResult::Timeout : DCPResult::NetworkError;
  }

#ifdef DEBUG
  std::cout << "receiveFrame: data available, reading..." << std::endl;
#endif
  std::vector<uint8_t> buffer(MAX_FRAME_SIZE);
  ssize_t received = recv(m_socket_fd, buffer.data(), buffer.size(), 0);

  if (received <= 0)
  {
#ifdef DEBUG
    std::cout << "receiveFrame: recv failed: " << strerror(errno) << std::endl;
#endif
    // Check if the error is due to interface going down
    if (errno == ENETDOWN || errno == ENETUNREACH || errno == EHOSTUNREACH)
    {
      logMessage("Network interface appears to be down during receive");
#ifdef DEBUG
      std::cerr << "Network interface appears to be down during receive" << std::endl;
#endif
    }
    return DCPResult::NetworkError;
  }

#ifdef DEBUG
  std::cout << "receiveFrame: received " << received << " bytes" << std::endl;
#endif

#ifdef DEBUG
  // Print received frame (debug)
  std::cout << "Received frame: ";
  for (int i = 0; i < std::min(received, (ssize_t)32); i++)
  {
    printf("%02X ", buffer[i]);
  }
  std::cout << std::endl;
#endif

  buffer.resize(received);

  // Since socket is configured for 802.1Q only, we can make assumptions:
  // - All frames are VLAN-tagged (802.1Q)
  // - Frame structure: [Ethernet Header (14)] + [VLAN Tag (4)] + [Payload]
  // - PROFINET header starts at offset 18

  if (received < 20) // Minimum: 14 (Ethernet) + 4 (VLAN) + 2 (FrameID)
  {
#ifdef DEBUG
    std::cout << "receiveFrame: VLAN frame too small (" << received << " bytes)" << std::endl;
#endif
    return DCPResult::Timeout;
  }

  // Extract EtherType from VLAN-tagged frame (offset 12 since kernel strips Ethernet preamble and priority)
  uint16_t ethertype_be;
  std::memcpy(&ethertype_be, buffer.data() + 12, 2);
  uint16_t ethertype = ntohs(ethertype_be);

  // Quick EtherType filter - reject non-PROFINET frames
  if (ethertype != ETHERTYPE_PROFINET)
  {
#ifdef DEBUG
    std::cout << "receiveFrame: ignoring non-PROFINET frame (ethertype=0x" << std::hex << ethertype
              << std::dec << ")" << std::endl;
#endif
    return DCPResult::Timeout;
  }

  // Extract FrameID from PROFINET header (always at offset 14 for 802.1Q)
  uint16_t frame_id_be;
  std::memcpy(&frame_id_be, buffer.data() + 14, 2);
  uint16_t frame_id = ntohs(frame_id_be);

  // Filter FrameIDs - only accept DCP frames
  if (frame_id != static_cast<uint16_t>(FrameID::GET_SET) &&
      frame_id != static_cast<uint16_t>(FrameID::IDENTIFY_REQUEST) &&
      frame_id != static_cast<uint16_t>(FrameID::IDENTIFY_RESPONSE))
  {
#ifdef DEBUG
    std::cout << "receiveFrame: ignoring non-DCP PROFINET frame (FrameID=0x" << std::hex << frame_id
              << std::dec << "), filtering out cyclic data" << std::endl;
#endif
    return DCPResult::Timeout; // Continue waiting for DCP frames
  }

#ifdef DEBUG
  std::cout << "receiveFrame: DCP frame detected (FrameID=0x" << std::hex << frame_id << std::dec
            << "), proceeding with deserialization" << std::endl;
#endif

  if (!frame.deserialize(buffer))
  {
#ifdef DEBUG
    std::cout << "receiveFrame: failed to deserialize DCP frame" << std::endl;
#endif
    return DCPResult::InvalidResponse;
  }

#ifdef DEBUG
  std::cout << "receiveFrame: successfully deserialized DCP frame" << std::endl;
#endif
  return DCPResult::Success;
}

bool NetworkInterface::isInterfaceUp() const
{
  struct ifreq ifr;
  int temp_fd = socket(AF_INET, SOCK_DGRAM, 0);
  if (temp_fd < 0)
    return false;

  strncpy(ifr.ifr_name, m_interface_name.c_str(), IFNAMSIZ - 1);
  ifr.ifr_name[IFNAMSIZ - 1] = '\0';

  bool is_up = false;
  if (ioctl(temp_fd, SIOCGIFFLAGS, &ifr) == 0)
  {
    is_up = (ifr.ifr_flags & IFF_UP) && (ifr.ifr_flags & IFF_RUNNING);
  }

  ::close(temp_fd);
  return is_up;
}

DCPResult NetworkInterface::checkInterfaceConnection()
{
  if (!isInterfaceUp())
  {
    logMessage("Interface " + m_interface_name + " is down or not running");
#ifdef DEBUG
    std::cerr << "Interface " << m_interface_name << " is down or not running" << std::endl;
#endif
    return DCPResult::NetworkError;
  }
  return DCPResult::Success;
}

// ProfinetDCPTool::Impl implementation
ProfinetDCPTool::Impl::Impl() = default;

ProfinetDCPTool::Impl::~Impl() { shutdown(); }

DCPResult ProfinetDCPTool::Impl::initialize(const std::string& interface_name)
{
  shutdown(); // Clean up any existing state

  network_interface = std::make_unique<NetworkInterface>(interface_name);
  return network_interface->open();
}

void ProfinetDCPTool::Impl::shutdown()
{
  if (discovery_running)
  {
    discovery_running = false;
    if (discovery_thread.joinable())
    {
      discovery_thread.join();
    }
  }

  if (network_interface)
  {
    network_interface->close();
    network_interface.reset();
  }

  std::lock_guard<std::mutex> lock(devices_mutex);
  known_devices.clear();
}

DCPResult ProfinetDCPTool::Impl::sendRequestAndWaitResponse(const DCPFrame& request, DCPFrame& response,
                                                            std::chrono::milliseconds timeout)
{
  if (!network_interface)
    return DCPResult::NetworkError;

  auto result = network_interface->sendFrame(request);
  if (result != DCPResult::Success)
  {
    return result;
  }

  auto start_time = std::chrono::steady_clock::now();

  while (std::chrono::steady_clock::now() - start_time < timeout)
  {
    auto remaining_time = timeout - std::chrono::duration_cast<std::chrono::milliseconds>(
                                        std::chrono::steady_clock::now() - start_time);

    result = network_interface->receiveFrame(response, remaining_time);
    if (result == DCPResult::Success)
    {
      // Check if this is a response for our transaction
      if (response.getTransactionId() == request.getTransactionId())
      {
#ifdef DEBUG
        std::cout << "Received matching DCP response for transaction " << request.getTransactionId()
                  << std::endl;
#endif
        return DCPResult::Success;
      }
      else
      {
        std::cout << "Received DCP frame with different transaction ID (got " << response.getTransactionId()
                  << ", expected " << request.getTransactionId() << "), continuing to wait" << std::endl;
        continue;
      }
    }
    else if (result == DCPResult::Timeout)
    {
      continue; // Keep waiting, might have been a non-DCP frame
    }
    else
    {
      return result;
    }
  }

  return DCPResult::Timeout;
}

// Main class implementation
ProfinetDCPTool::ProfinetDCPTool() : pImpl(std::make_unique<Impl>()) {}

ProfinetDCPTool::~ProfinetDCPTool() { cleanupDeviceXML(); }

DCPResult ProfinetDCPTool::initialize(const std::string& interface_name)
{
  return pImpl->initialize(interface_name);
}

void ProfinetDCPTool::shutdown() { pImpl->shutdown(); }

DCPResult ProfinetDCPTool::setDeviceName(const MacAddress& mac, const std::string& name,
                                         std::chrono::milliseconds timeout)
{
  if (!pImpl->network_interface)
    return DCPResult::NetworkError;

  // Send simple SET request
  DCPFrame request;
  request.setDestination(mac);
  request.setSource(pImpl->network_interface->getInterfaceMAC());
  request.setFrameType(DCPFrame::FrameType::Request);
  request.setServiceType(DCPFrame::ServiceType::Set);
  request.setTransactionId(pImpl->getNextTransactionId());
  request.addNameOption(name);

  DCPFrame response;
  DCPResult result = pImpl->sendRequestAndWaitResponse(request, response, timeout);

  // On response: check control block errors
  if (result == DCPResult::Success)
  {
    // Check for control block errors first (most important for SET operations)
    if (response.hasControlBlockErrors())
    {
      auto errors = response.getControlBlockErrors();
      std::string error_details = "SET operation failed:";
      for (const auto& error : errors)
      {
        error_details += "\n  - " + error;
      }
      logMessage("✗ " + error_details);
      result = DCPResult::AccessDenied; // or InvalidParameter depending on error code
    }
    else
    {
      logMessage("✓ Device name set successfully");
      result = DCPResult::Success;
    }
  }

  return result;
}
DCPResult ProfinetDCPTool::setIPConfiguration(const MacAddress& mac, const IPAddress& ip,
                                              const IPAddress& subnet, const IPAddress& gateway,
                                              std::chrono::milliseconds timeout)
{
  if (!pImpl->network_interface)
    return DCPResult::NetworkError;

  // Send simple SET request (single block, like Python implementation)
  DCPFrame request;
  request.setDestination(mac);
  request.setSource(pImpl->network_interface->getInterfaceMAC());
  request.setFrameType(DCPFrame::FrameType::Request);
  request.setServiceType(DCPFrame::ServiceType::Set);
  request.setTransactionId(pImpl->getNextTransactionId());
  request.addIPOption(ip, subnet, gateway);

  DCPFrame response;
  DCPResult result = pImpl->sendRequestAndWaitResponse(request, response, timeout);

  // On response: check control block errors
  if (result == DCPResult::Success)
  {
    // Check for control block errors first (most important for SET operations)
    if (response.hasControlBlockErrors())
    {
      auto errors = response.getControlBlockErrors();
      std::string error_details = "SET IP configuration failed:";
      for (const auto& error : errors)
      {
        error_details += "\n  - " + error;
      }
      logMessage("✗ " + error_details);
      result = DCPResult::AccessDenied; // or InvalidParameter depending on error code
    }
    else
    {
      logMessage("✓ IP configuration set successfully");
      result = DCPResult::Success;
    }
  }

  return result;
}

void ProfinetDCPTool::discoverDevicesAsync(DeviceDiscoveredCallback device_callback,
                                           OperationCompleteCallback complete_callback,
                                           ProgressCallback progress_callback,
                                           std::chrono::milliseconds timeout)
{
  if (!pImpl->network_interface)
  {
    if (complete_callback)
    {
      complete_callback(DCPResult::NetworkError, "Network interface not available");
    }
    return;
  }

  // Start discovery in a separate thread to avoid blocking the UI
  std::thread(
      [this, device_callback, complete_callback, progress_callback, timeout]()
      {
        try
        {
          // Send broadcast identify request
          DCPFrame request;
          request.setDestination(DCP_MULTICAST_MAC);
          request.setSource(pImpl->network_interface->getInterfaceMAC());
          request.setFrameType(DCPFrame::FrameType::Request);
          request.setServiceType(DCPFrame::ServiceType::Identify);
          request.setTransactionId(pImpl->getNextTransactionId());
          request.addAllOption();

          if (progress_callback)
          {
            progress_callback(5, "Sending discovery request...");
          }

          // Send the request
          DCPResult send_result = pImpl->network_interface->sendFrame(request);
          if (send_result != DCPResult::Success)
          {
            if (complete_callback)
            {
              complete_callback(send_result, "Failed to send discovery request");
            }
            return;
          }

          if (progress_callback)
          {
            progress_callback(10, "Listening for responses...");
          }

          // Process responses as they come in
          auto start_time = std::chrono::steady_clock::now();
          auto last_progress_update = start_time;
          std::set<MacAddress> discovered_devices;
          int device_count = 0;

          while (true)
          {
            auto current_time = std::chrono::steady_clock::now();
            auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(current_time - start_time);

            if (elapsed >= timeout)
            {
              break;
            }

            // Calculate remaining timeout
            auto remaining = timeout - elapsed;

            // Try to receive a response with shorter timeout to allow progress updates
            DCPFrame response;
            DCPResult result = pImpl->network_interface->receiveFrame(
                response, std::min(remaining, std::chrono::milliseconds(100)));

            if (result == DCPResult::Success)
            {
              // Check if this is an identify response
              if (response.getFrameType() == DCPFrame::FrameType::Response &&
                  response.getServiceType() == DCPFrame::ServiceType::Identify)
              {

                MacAddress device_mac = response.getSourceMAC();

                // Only process new devices
                auto [it, inserted] = discovered_devices.insert(device_mac);
                if (inserted)
                {
                  device_count++;

                  // Parse device information from the response
                  DCPDeviceInfo device_info;
                  if (parseDeviceInfoFromFrame(response, device_info))
                  {
                    // Call the device discovered callback immediately
                    if (device_callback)
                    {
                      device_callback(device_info);
                    }

                    // Update progress immediately when device found
                    if (progress_callback)
                    {
                      double time_progress =
                          static_cast<double>(elapsed.count()) / static_cast<double>(timeout.count());
                      double progress = 0.10 + (0.85 * time_progress); // 10% to 95%
                      int percent = static_cast<int>(std::min(progress * 100, 95.0));

                      std::string message = "Found " + std::to_string(device_count) + " device(s)";
                      progress_callback(percent, message);

                      last_progress_update = current_time; // Update the timer
                    }
                  }
                }
              }
            }
            else if (result != DCPResult::Timeout)
            {
              // Real error occurred
              if (complete_callback)
              {
                complete_callback(result, "Error receiving responses");
              }
              return;
            }

            // Update progress smoothly every 200ms
            auto time_since_last_update =
                std::chrono::duration_cast<std::chrono::milliseconds>(current_time - last_progress_update);

            if (progress_callback && time_since_last_update >= std::chrono::milliseconds(200))
            {
              // Calculate progress as percentage of time elapsed (10% to 95%)
              double time_progress =
                  static_cast<double>(elapsed.count()) / static_cast<double>(timeout.count());
              double progress = 0.10 + (0.85 * time_progress);                // Scale from 10% to 95%
              int percent = static_cast<int>(std::min(progress * 100, 95.0)); // Cap at 95% until complete

              std::string message = "Listening... Found " + std::to_string(device_count) + " device(s)";
              progress_callback(percent, message);

              last_progress_update = current_time;
            }
          }

          // Discovery complete
          if (progress_callback)
          {
            progress_callback(100,
                              "Discovery complete - Found " + std::to_string(device_count) + " device(s)");
          }

          if (complete_callback)
          {
            complete_callback(DCPResult::Success, "Discovery completed successfully");
          }
        }
        catch (const std::exception& e)
        {
          if (complete_callback)
          {
            complete_callback(DCPResult::NetworkError,
                              std::string("Exception during discovery: ") + e.what());
          }
        }
      })
      .detach(); // Detach the thread so it runs independently
}

std::vector<std::string> ProfinetDCPTool::getAvailableInterfaces()
{
  std::vector<std::string> interfaces;

  struct ifaddrs* ifaddr;
  if (getifaddrs(&ifaddr) == -1)
  {
    return interfaces;
  }

  for (struct ifaddrs* ifa = ifaddr; ifa != nullptr; ifa = ifa->ifa_next)
  {
    if (ifa->ifa_addr && ifa->ifa_addr->sa_family == AF_PACKET)
    {
      std::string name = ifa->ifa_name;
      if (std::find(interfaces.begin(), interfaces.end(), name) == interfaces.end())
      {
        interfaces.push_back(name);
      }
    }
  }

  freeifaddrs(ifaddr);
  std::sort(interfaces.begin(), interfaces.end());

  return interfaces;
}

std::string ProfinetDCPTool::getInterfaceName() const
{
  return pImpl->network_interface ? pImpl->network_interface->getInterfaceName() : "";
}

MacAddress ProfinetDCPTool::getInterfaceMAC() const
{
  return pImpl->network_interface ? pImpl->network_interface->getInterfaceMAC() : MacAddress{};
}

std::string ProfinetDCPTool::dcpResultToString(DCPResult result)
{
  switch (result)
  {
  case DCPResult::Success:
    return "Success";
  case DCPResult::Timeout:
    return "Timeout";
  case DCPResult::NetworkError:
    return "Network Error";
  case DCPResult::InvalidParameter:
    return "Invalid Parameter";
  case DCPResult::DeviceNotFound:
    return "Device Not Found";
  case DCPResult::AccessDenied:
    return "Access Denied";
  case DCPResult::InvalidResponse:
    return "Invalid Response";
  case DCPResult::NotImplemented:
    return "Not Implemented";
  default:
    return "Unknown Error";
  }
}

std::string ProfinetDCPTool::vendorIdToString(uint16_t vendor_id)
{
  return ::ProfinetDCP::vendorIdToString(vendor_id);
}

std::string ProfinetDCPTool::vendorIdWithHexToString(uint16_t vendor_id)
{
  std::string vendor_name = ::ProfinetDCP::vendorIdToString(vendor_id);

  // If name missing, use fallback
  if (vendor_name.find("Unknown Vendor") == 0)
  {
    // Already includes the ID in parentheses, just add hex format
    char hex_buffer[16];
    snprintf(hex_buffer, sizeof(hex_buffer), "Unknown Vendor (0x%04X)", vendor_id);
    return hex_buffer;
  }
  else
  {
    // Add hex format to known vendor name
    char hex_buffer[16];
    snprintf(hex_buffer, sizeof(hex_buffer), " (0x%04X)", vendor_id);
    return vendor_name + hex_buffer;
  }
}

void ProfinetDCPTool::getDeviceInfo(uint16_t vendor_id, uint16_t device_id, std::string& device_name,
                                    std::string& device_type, std::string& device_description)
{
  if (!loadDeviceXML())
  {
    device_name = "Unknown Device";
    device_type = "Unknown Type";
    device_description = "";
    return;
  }

  pugi::xml_node devices = g_device_xml_cache->child("ProfinetDevices");
  pugi::xpath_variable_set vars;
  vars.add("VendorID", pugi::xpath_type_number);
  vars.add("DeviceID", pugi::xpath_type_number);
  vars.set("VendorID", static_cast<double>(vendor_id));
  vars.set("DeviceID", static_cast<double>(device_id));
  pugi::xml_node device =
      devices.select_node("Vendor[@ID = number($VendorID)]/Device[@ID = number($DeviceID)]", &vars).node();

  if (device)
  {
    device_name = device.attribute("Name").as_string();
    device_type = device.attribute("Type").as_string();
    device_description = device.attribute("Description").as_string();
    return;
  }

  // Fallback if device not found
  device_name = "Unknown Device";
  device_type = "Unknown Type";
  device_description = "";
}

std::string ProfinetDCPTool::deviceIdToString(uint16_t vendor_id, uint16_t device_id)
{
  return ::ProfinetDCP::deviceIdToString(vendor_id, device_id);
}

std::string ProfinetDCPTool::deviceIdWithHexToString(uint16_t vendor_id, uint16_t device_id)
{
  std::string device_name = ::ProfinetDCP::deviceIdToString(vendor_id, device_id);

  // Detect name vs numeric ID
  bool is_numeric_only = true;
  for (char c : device_name)
  {
    if (!std::isdigit(c))
    {
      is_numeric_only = false;
      break;
    }
  }

  // If name exists, show name + hex
  if (!is_numeric_only && device_name != std::to_string(device_id))
  {
    char hex_buffer[16];
    snprintf(hex_buffer, sizeof(hex_buffer), " (0x%04X)", device_id);
    return device_name + hex_buffer;
  }
  else
  {
    // Just show hex format if no device name found
    char hex_buffer[16];
    snprintf(hex_buffer, sizeof(hex_buffer), "0x%04X", device_id);
    return hex_buffer;
  }
}

std::string ProfinetDCPTool::deviceRoleToString(uint8_t role)
{
  switch (role & 0x03)
  {
  case 0x00:
    return "IO Device";
  case 0x01:
    return "IO Controller";
  case 0x02:
    return "IO Multidevice";
  case 0x03:
    return "IO Supervisor";
  default:
    return "Unknown";
  }
}

// Async operations (simplified for now)
DCPResult ProfinetDCPTool::getDeviceInfo(const MacAddress& mac, DCPDeviceInfo& info,
                                         std::chrono::milliseconds timeout)
{
  return DCPResult::NotImplemented;
}

DCPResult ProfinetDCPTool::resetToFactory(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_COMMUNICATION, timeout);
}

DCPResult ProfinetDCPTool::resetToFactory(const MacAddress& mac, const std::array<uint8_t, 2>& reset_mode,
                                          std::chrono::milliseconds timeout)
{
  if (!pImpl->network_interface)
    return DCPResult::NetworkError;

#ifdef DEBUG
  std::cout << "Performing factory reset with mode: 0x" << std::hex << (int)reset_mode[0]
            << (int)reset_mode[1] << std::dec << std::endl;
#endif

  DCPFrame request;
  request.setDestination(mac);
  request.setSource(pImpl->network_interface->getInterfaceMAC());
  request.setFrameType(DCPFrame::FrameType::Request);
  request.setServiceType(DCPFrame::ServiceType::Set);
  request.setTransactionId(pImpl->getNextTransactionId());
  request.addResetToFactoryOption(reset_mode);

  DCPFrame response;
  DCPResult result = pImpl->sendRequestAndWaitResponse(request, response, timeout);

  // On response: check control block errors
  if (result == DCPResult::Success)
  {
    // Check for control block errors first (most important for SET operations)
    if (response.hasControlBlockErrors())
    {
      auto errors = response.getControlBlockErrors();
      std::string error_details = "Factory reset failed:";
      for (const auto& error : errors)
      {
        error_details += "\n  - " + error;
      }
      logMessage("✗ " + error_details);
      result = DCPResult::AccessDenied; // or InvalidParameter depending on error code
    }
    else
    {
      logMessage(
          "✓ Factory reset command sent successfully. Device may be unresponsive for several seconds.");
      result = DCPResult::Success;
#ifdef DEBUG
      std::cout << "Factory reset command sent successfully. Device may be unresponsive for several seconds."
                << std::endl;
#endif
    }
  }

  return result;
}

// Convenience methods for specific factory reset types
DCPResult ProfinetDCPTool::resetApplicationData(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_APPLICATION_DATA, timeout);
}

DCPResult ProfinetDCPTool::resetCommunication(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_COMMUNICATION, timeout);
}

DCPResult ProfinetDCPTool::resetEngineering(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_ENGENEERING, timeout);
}

DCPResult ProfinetDCPTool::resetAllData(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_ALL_DATA, timeout);
}

DCPResult ProfinetDCPTool::resetDevice(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_DEVICE, timeout);
}

DCPResult ProfinetDCPTool::resetAndRestore(const MacAddress& mac, std::chrono::milliseconds timeout)
{
  return resetToFactory(mac, ResetFactoryModes::RESET_AND_RESTORE, timeout);
}

DCPResult ProfinetDCPTool::blinkLED(const MacAddress& mac, bool enable, std::chrono::milliseconds timeout)
{
  if (!pImpl->network_interface)
    return DCPResult::NetworkError;

  DCPFrame request;
  request.setDestination(mac);
  request.setSource(pImpl->network_interface->getInterfaceMAC());
  request.setFrameType(DCPFrame::FrameType::Request);
  request.setServiceType(DCPFrame::ServiceType::Set);
  request.setTransactionId(pImpl->getNextTransactionId());
  request.addBlinkLEDOption();

  DCPFrame response;
  DCPResult result = pImpl->sendRequestAndWaitResponse(request, response, timeout);

  // On response: parse
  if (result == DCPResult::Success)
  {
    DCPDeviceInfo dummy_info;
    bool parse_result = parseDeviceInfoFromFrame(response, dummy_info);

    if (parse_result)
    {
      logMessage("✓ LED blink command sent successfully");
      result = DCPResult::Success;
    }
    else
    {
      logMessage("✗ Failed to parse device response");
      result = DCPResult::InvalidResponse;
    }
  }

  return result;
}

} // namespace ProfinetDCP