/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/* rt_io_m_ssab_remoterack.c -- io methods for ssab remote rack objects. */

#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#include "co_cdh.h"
#include "pwr_basecomponentclasses.h"
#include "pwr_ssaboxclasses.h"
#include "rt_io_base.h"
#include "rt_io_rack_init.h"
#include "rt_io_m_ssab_locals.h"
#include "rt_io_msg.h"

#define BFB_COMMERR_SOFT_LIMIT 15
#define BFB_COMMERR_HARD_LIMIT 50
#define BFB_COMMERR_LINK_FASTTRACK (BFB_COMMERR_HARD_LIMIT + 1)

static void udp_reset(int socket);
static void udp_reset_inputs(io_sRackLocal* local);
static int udp_is_link_send_error(int errnum);

/*----------------------------------------------------------------------------*\

\*----------------------------------------------------------------------------*/
static pwr_tStatus IoRackInitSwap(io_tCtx ctx, io_sAgent* ap, io_sRack* rp)
{
  io_sRackLocal* local;
  pwr_sClass_Ssab_RemoteRack* op;
  int sts;

  op = (pwr_sClass_Ssab_RemoteRack*)rp->op;
  local = calloc(1, sizeof(*local));
  rp->Local = local;

  /* Create socket, store in local struct */

  local->s = socket(AF_INET, SOCK_DGRAM, 0);
  if (local->s < 0) {
    errh_Error(
        "Error creating socket for IO remote rack %s, %d", rp->Name, local->s);
    op->Status = IO__INITFAIL;
    return IO__ERRINIDEVICE;
  }

  /* Initialize remote address structure */

  local->rem_addr.sin_family = AF_INET;
  local->rem_addr.sin_port = htons(op->RemotePort);
  local->rem_addr.sin_addr.s_addr = inet_addr((char*)&(op->Address));

  /* Connect to remote address */

  sts = connect(
      local->s, (struct sockaddr*)&local->rem_addr, sizeof(local->rem_addr));
  if (sts != 0) {
    errh_Error(
        "Error binding remote socket for IO remote rack %s, %d", rp->Name, sts);
    op->Status = IO__INITFAIL;
    return IO__ERRINIDEVICE;
  }

  local->next_read_req_item = 0;
  local->next_write_req_item = 0;
  local->comm_error_count = 0;

  op->RX_packets = 0;
  op->TX_packets = 0;

  /* Log initialization */

  errh_Info("Init of IO remote rack %s/%s:%d", rp->Name,
      inet_ntoa(local->rem_addr.sin_addr), ntohs(local->rem_addr.sin_port));
  op->Status = IO__NORMAL;
  return IO__SUCCESS;
}
/*----------------------------------------------------------------------------*\

\*----------------------------------------------------------------------------*/

static pwr_tStatus IoRackInit(io_tCtx ctx, io_sAgent* ap, io_sRack* rp)
{
  io_sRackLocal* local;
  pwr_sClass_Ssab_RemoteRack* op;
  int sts;

  op = (pwr_sClass_Ssab_RemoteRack*)rp->op;
  local = calloc(1, sizeof(*local));
  rp->Local = local;

  /* Create socket, store in local struct */

  local->s = socket(AF_INET, SOCK_DGRAM, 0);
  if (local->s < 0) {
    errh_Error(
        "Error creating socket for IO remote rack %s, %d", rp->Name, local->s);
    op->Status = IO__INITFAIL;
    return IO__ERRINIDEVICE;
  }

  /* Bind local port if explicitly numbered ( != 0 ) */

  if (op->LocalPort != 0) {
    local->my_addr.sin_family = AF_INET;
    local->my_addr.sin_port = htons(op->LocalPort);
    sts = bind(
        local->s, (struct sockaddr*)&local->my_addr, sizeof(local->my_addr));
    if (sts != 0) {
      errh_Error("Error binding local socket for IO remote rack %s, %d",
          rp->Name, sts);
      op->Status = IO__INITFAIL;
      return IO__ERRINIDEVICE;
    }
  }

  /* Initialize remote address structure */

  local->rem_addr.sin_family = AF_INET;
  local->rem_addr.sin_port = htons(op->RemotePort);
  local->rem_addr.sin_addr.s_addr = inet_addr((char*)&(op->Address));

  /* Connect to remote address */

  sts = connect(
      local->s, (struct sockaddr*)&local->rem_addr, sizeof(local->rem_addr));
  if (sts != 0) {
    errh_Error(
        "Error binding remote socket for IO remote rack %s, %d", rp->Name, sts);
    op->Status = IO__INITFAIL;
    return IO__ERRINIDEVICE;
  }

  local->next_read_req_item = 0;
  local->next_write_req_item = 0;
  local->comm_error_count = 0;

  op->RX_packets = 0;
  op->TX_packets = 0;

  /*
    cardp = rp->cardlist;

    while(cardp) {
      cid = cardp->Class;
      while ( ODD( gdh_GetSuperClass( cid, &cid, cardp->Objid))) ;

      switch (cid) {
        case pwr_cClass_Ssab_BaseAiCard:
          base_ai_card = (pwr_sClass_Ssab_BaseAiCard *) cardp->op;
          break;

      cardp = cardp->next;
    }

    local->next_read_req_item = 0;
    local->next_write_req_item = 0;
  */

  // Calc length and send read request
  local->read_req.service = BFB_SERVICE_READ;
  local->read_req.length = local->next_read_req_item * 4 + 4;
  sts = send(local->s, &local->read_req, local->read_req.length, 0);
  if (sts > 0)
    op->TX_packets++;
  local->next_read_req_item = 0;
  bzero(&local->read_area, sizeof(local->read_area));

  /* Log initialization */

  errh_Info("Init of IO remote rack %s/%s:%d", rp->Name,
      inet_ntoa(local->rem_addr.sin_addr), ntohs(local->rem_addr.sin_port));
  op->Status = IO__NORMAL;
  return IO__SUCCESS;
}

static pwr_tStatus IoRackSwap(
    io_tCtx ctx, io_sAgent* ap, io_sRack* rp, io_eEvent event

    )
{
  io_sRackLocal* local;
  pwr_sClass_Ssab_RemoteRack* op;
  int sts;
  fd_set fds;
  struct timeval tv;
  struct bfb_buf rbuf;
  int size;

  switch (event) {
  case io_eEvent_IoCommSwapInit:
  case io_eEvent_IoCommSwap:

    if (!rp->Local) {
      sts = IoRackInitSwap(ctx, ap, rp);
      if (sts != IO__SUCCESS)
        return IO__ERRINIDEVICE;
    }

    local = (io_sRackLocal*)rp->Local;
    op = (pwr_sClass_Ssab_RemoteRack*)rp->op;

    // Calc length and send read request
    local->read_req.service = BFB_SERVICE_READ;
    local->read_req.length = local->next_read_req_item * 4 + 4;
    sts = send(local->s, &local->read_req, local->read_req.length, 0);
    if (sts > 0)
      op->TX_packets++;
    local->next_read_req_item = 0;
    bzero(&local->read_area, sizeof(local->read_area));

    sts = 1;
    while (sts > 0) {
      FD_ZERO(&fds);
      FD_SET(local->s, &fds);
      tv.tv_sec = 0;
      tv.tv_usec = 0;
      sts = select(32, &fds, NULL, NULL, &tv);
      if (sts > 0) {
        size = recv(local->s, &rbuf, sizeof(rbuf), 0);
        if (size <= 0)
          continue;
        if (rbuf.service == BFB_SERVICE_READ) {
          bzero(&local->read_area, sizeof(local->read_area));
          memcpy(&local->read_area, &rbuf, size);
        } else if (rbuf.service == BFB_SERVICE_WRITE) {
          bzero(&local->write_area, sizeof(local->write_area));
          memcpy(&local->write_area, &rbuf, size);
        }
        op->RX_packets++;
      }
    }
    break;
  default:;
  }

  return IO__SUCCESS;
}

static pwr_tStatus IoRackClose(io_tCtx ctx, io_sAgent* ap, io_sRack* rp)
{
  if (rp->Local)
    free(rp->Local);
  return IO__SUCCESS;
}

static pwr_tStatus IoRackRead(io_tCtx ctx, io_sAgent* ap, io_sRack* rp)
{
  int sts;
  fd_set fds;
  struct timeval tv;
  io_sRackLocal* local = (io_sRackLocal*)rp->Local;
  pwr_sClass_Ssab_RemoteRack* op = (pwr_sClass_Ssab_RemoteRack*)rp->op;
  struct bfb_buf rbuf;
  int size;
  int rx_packets = 0;
  int old_comm_error_count;
  int send_link_error = 0;

  if (ctx->read_reset) {
    udp_reset(local->s);
    return IO__SUCCESS;
  }

  // Calc length and send write request
  local->write_req.service = BFB_SERVICE_WRITE;
  local->write_req.length = local->next_write_req_item * 4 + 4;
  sts = send(local->s, &local->write_req, local->write_req.length, 0);
  if (sts > 0)
    op->TX_packets++;
  else if (sts < 0 && udp_is_link_send_error(errno))
    send_link_error = 1;
  local->next_write_req_item = 0;
  bzero(&local->write_area, sizeof(local->write_area));

  sts = 1;
  while (sts > 0) {
    FD_ZERO(&fds);
    FD_SET(local->s, &fds);
    tv.tv_sec = 0;
    tv.tv_usec = 0;
    sts = select(32, &fds, NULL, NULL, &tv);
    if (sts > 0) {
      size = recv(local->s, &rbuf, sizeof(rbuf), 0);
      if (size <= 0)
        continue;
      if (rbuf.service == BFB_SERVICE_READ) {
        bzero(&local->read_area, sizeof(local->read_area));
        memcpy(&local->read_area, &rbuf, size);
      } else if (rbuf.service == BFB_SERVICE_WRITE) {
        bzero(&local->write_area, sizeof(local->write_area));
        memcpy(&local->write_area, &rbuf, size);
      }
      op->RX_packets++;
      rx_packets++;
    }
  }

  if (rx_packets > 0) {
    local->comm_error_count = 0;
    op->Status = IO__NORMAL;
  } else {
    old_comm_error_count = local->comm_error_count;
    if (send_link_error && local->comm_error_count < BFB_COMMERR_LINK_FASTTRACK)
      local->comm_error_count = BFB_COMMERR_LINK_FASTTRACK;
    else
      local->comm_error_count++;

    if (old_comm_error_count < BFB_COMMERR_SOFT_LIMIT
        && local->comm_error_count >= BFB_COMMERR_SOFT_LIMIT) {
      errh_Error("IO Error soft limit reached on rack '%s'", rp->Name);
      ctx->IOHandler->CardErrorSoftLimit = 1;
      ctx->IOHandler->ErrorSoftLimitObject = cdh_ObjidToAref(rp->Objid);
    }
    if (old_comm_error_count < BFB_COMMERR_HARD_LIMIT
        && local->comm_error_count >= BFB_COMMERR_HARD_LIMIT) {
      errh_Error("IO Error hard limit reached on rack '%s', stall action %d",
          rp->Name, op->StallAction);
      ctx->IOHandler->CardErrorHardLimit = 1;
      ctx->IOHandler->ErrorHardLimitObject = cdh_ObjidToAref(rp->Objid);
    }

    if (local->comm_error_count > BFB_COMMERR_HARD_LIMIT) {
      if (op->StallAction == pwr_eSsabStallAction_ResetInputs)
        udp_reset_inputs(local);
      else if (op->StallAction == pwr_eSsabStallAction_EmergencyBreak)
        ctx->Node->EmergBreakTrue = 1;
    }

    op->Status = IO__ERRDEVICE;
  }

  return IO__SUCCESS;
}

static pwr_tStatus IoRackWrite(io_tCtx ctx, io_sAgent* ap, io_sRack* rp)
{
  int sts;
  io_sRackLocal* local = (io_sRackLocal*)rp->Local;
  pwr_sClass_Ssab_RemoteRack* op = (pwr_sClass_Ssab_RemoteRack*)rp->op;

  // Calc length and send read request
  local->read_req.service = BFB_SERVICE_READ;
  local->read_req.length = local->next_read_req_item * 4 + 4;
  sts = send(local->s, &local->read_req, local->read_req.length, 0);
  if (sts > 0)
    op->TX_packets++;
  else if (sts < 0 && udp_is_link_send_error(errno)
      && local->comm_error_count < BFB_COMMERR_LINK_FASTTRACK)
    local->comm_error_count = BFB_COMMERR_LINK_FASTTRACK;
  local->next_read_req_item = 0;
  bzero(&local->read_area, sizeof(local->read_area));

  return IO__SUCCESS;
}

/* Empty the UDP in buffer */
static void udp_reset(int socket)
{
  int sts;
  fd_set fds;
  struct timeval tv;
  struct bfb_buf rbuf;
  int size;

  sts = 1;
  while (sts > 0) {
    FD_ZERO(&fds);
    FD_SET(socket, &fds);
    tv.tv_sec = 0;
    tv.tv_usec = 0;
    sts = select(32, &fds, NULL, NULL, &tv);
    if (sts > 0)
      size = recv(socket, &rbuf, sizeof(rbuf), 0);
  }
}

static int udp_is_link_send_error(int errnum)
{
  return errnum == ENETDOWN || errnum == ENETUNREACH || errnum == EHOSTUNREACH;
}

/* Build an empty read area from the latest request so input channels are reset
   to zero while communication is stalled. */
static void udp_reset_inputs(io_sRackLocal* local)
{
  int i;
  int item_cnt;
  int max_items = (int)(sizeof(local->read_area.item) / sizeof(local->read_area.item[0]));

  item_cnt = local->read_req.length >= 4 ? (local->read_req.length - 4) / 4 : 0;
  if (item_cnt > max_items)
    item_cnt = max_items;

  bzero(&local->read_area, sizeof(local->read_area));
  local->read_area.service = BFB_SERVICE_READ;
  local->read_area.length = item_cnt * 4 + 4;

  for (i = 0; i < item_cnt; i++)
    local->read_area.item[i].address = local->read_req.item[i].address;
}

/*----------------------------------------------------------------------------*\

\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  Every method to be exported to the workbench should be registred here.
\*----------------------------------------------------------------------------*/

pwr_dExport pwr_BindIoMethods(Ssab_RemoteRack) = { pwr_BindIoMethod(IoRackInit),
  pwr_BindIoMethod(IoRackSwap), pwr_BindIoMethod(IoRackClose),
  pwr_BindIoMethod(IoRackRead), pwr_BindIoMethod(IoRackWrite), pwr_NullMethod };
