/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include <string.h>

#include "co_rfc5424_c.h"
#include "rt_qcom.h"
#include "pwr_remoteclasses.h"
#include "remote.h"

/**
 * @brief Send a log message with RFC 5424 formatting and severity level.
 *
 * This is the recommended function for new code. It formats the message
 * according to RFC 5424 syslog format with the specified severity level.
 *
 * @param identity Log identity number (matches LoggConfig.Identity)
 * @param severity Severity character: 'I' (Info), 'W' (Warning), 'E' (Error),
 *                 'F' (Fatal), 'S' (Success)
 * @param str The log message string
 * @param size Maximum size of the message
 * @return pwr_tStatus Status code
 */
pwr_tStatus remote_logg_rfc5424(int identity, char severity, char* str, int size)
{
  qcom_sPut put;
  qcom_sQid qid;
  char* logmsg;
  char rfc5424_header[256];
  int header_len;
  int msg_len;
  int logsize;
  pwr_tStatus sts;

  /* Format RFC 5424 header with severity */
  header_len = co_rfc5424_format_header_c(severity, "rs_remote", rfc5424_header, sizeof(rfc5424_header));
  if (header_len < 0)
  {
    /* Fallback: use simple header if RFC 5424 formatting fails */
    header_len = 0;
    rfc5424_header[0] = '\0';
  }

  /* Calculate message length (use strnlen to respect size limit) */
  msg_len = strnlen(str, size);

  /* Allocate: identity (4 bytes) + header + space + message + null terminator */
  logsize = sizeof(int) + header_len + 1 + msg_len + 1;

  logmsg = malloc(logsize);
  if (logmsg == NULL)
  {
    return 0; /* Memory allocation failed */
  }

  /* Pack identity at start of buffer */
  *(int*)logmsg = identity;

  /* Copy RFC 5424 header */
  if (header_len > 0)
  {
    memcpy(&logmsg[sizeof(int)], rfc5424_header, header_len);
  }

  /* Append space separator between header and message (RFC 5424 requires space after SD) */
  logmsg[sizeof(int) + header_len] = ' ';

  /* Append message */
  memcpy(&logmsg[sizeof(int) + header_len + 1], str, msg_len);
  logmsg[sizeof(int) + header_len + 1 + msg_len] = '\0';

  put.data = logmsg;
  put.allocate = 1;
  put.size = logsize;
  put.type.b = qcom_eBtype__;
  put.type.s = qcom_eStype__;
  put.reply.qix = 0;
  put.reply.nid = 0;

  qid = qcom_cNQid;
  qid.qix = rs_pwr_logg_qix;

  sts = qcom_Put(&sts, &qid, &put);

  free(logmsg);

  return sts;
}

/**
 * @brief Send a log message (legacy function, maintained for backward compatibility).
 *
 * This function is maintained for backward compatibility with existing code.
 * It now formats messages using RFC 5424 format with INFO severity level.
 * For new code, prefer remote_logg_sev() which allows specifying severity.
 *
 * @param identity Log identity number (matches LoggConfig.Identity)
 * @param str The log message string
 * @param size Maximum size of the message
 * @return pwr_tStatus Status code
 */
pwr_tStatus remote_logg(int identity, char* str, int size)
{
  /* Delegate to new function with INFO severity for backward compatibility */
  return remote_logg_rfc5424(identity, 'I', str, size);
}
