/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/*********************************************************************
**********************************************************************
*
* Filename :	remtrans_utils.c
*
* Modified :	Date	Pgm		Remark
*		950208	Hans Werner	First version
*		950208	CS		Converted from h to c file
*		960222	Hans Werner	Added RemTrans_Logg
*		010330	CJu		RemTrans_Logg to qcom
*		040506	CJu		Changes to V4.0.0
*
* Description :	Remote trans utilities used by all remote transports
*
**********************************************************************
*********************************************************************/

#include <string.h>

#include "co_time.h"
#include "co_cdh.h"
#include "rt_gdh.h"
#include "rt_qcom_msg.h"
#include "rt_qdb_msg.h"
#include "pwr_remoteclasses.h"
#include "remote.h"
#include "remote_remtrans_utils.h"
#include "rs_remote_msg.h"

/* Declare common variables */

qcom_sQid logg_qid;

/*********************************************************************
**********************************************************************
*
* Name :        RemTrans_Logg
*
* Type :        void
*
* Input :       Pointer to struct remtrans_item with objid and pointer
*
* Output :      Log message via remote_logg_rfc5424() to RS_REMOTE_LOGG.
* Description : Check if logging is to be done. Format log message in
*               RFC 5424 format and send via remote_logg_rfc5424().
*
**********************************************************************
*********************************************************************/

void RemTrans_Logg(remtrans_item* remtrans)
{
  pwr_sClass_RemTrans* RemTransP;
  pwr_tStatus sts;
  pwr_tString80 objname;
  char* msgbuf;
  char* bufp;
  char* datap;
  unsigned int i;
  unsigned int data_bytes;
  unsigned int max_data_bytes;
  unsigned int msg_size;
  char severity;

  RemTransP = remtrans->objp;

  /* Check if logging should be done */
  if ((RemTransP->LoggLevel > 1) || ((RemTransP->LoggLevel == 1) && EVEN(RemTransP->LastSts)))
  {

    /* Get object name */
    sts = gdh_ObjidToName(remtrans->objid, objname, sizeof(objname), cdh_mNName);
    if (EVEN(sts))
      return;

    /* Determine how much data to log */
    if (RemTransP->LoggLevel == 4)
      data_bytes = RemTransP->DataLength;
    else if (RemTransP->LoggLevel == 3)
      data_bytes = (RemTransP->DataLength > 48) ? 48 : RemTransP->DataLength;
    else
      data_bytes = 0;
    max_data_bytes = 10000;
    if (data_bytes > max_data_bytes)
      data_bytes = max_data_bytes;

    /* Calculate message size: objname + status info + hex data (3 chars per byte) + margin */
    msg_size = strlen(objname) + 100 + (data_bytes * 3) + 1;

    msgbuf = malloc(msg_size);
    if (!msgbuf)
      return;

    /* Determine severity based on status */
    severity = EVEN(RemTransP->LastSts) ? 'E' : 'I';

    /* Build single-line message */
    bufp = msgbuf;
    bufp += sprintf(bufp, "%s Status=%d Length=%d", objname, RemTransP->LastSts, RemTransP->DataLength);

    /* Append hex data if requested */
    if (data_bytes > 0)
    {
      bufp += sprintf(bufp, " Data=");
      datap = remtrans->datap;
      for (i = 0; i < data_bytes; i++)
      {
        bufp += sprintf(bufp, "%02X", (unsigned char)*datap++);
      }
    }

    /* Send via remote_logg_rfc5424 */
    remote_logg_rfc5424(RS_PWR_LOGG_RemTransId, severity, msgbuf, (int)(bufp - msgbuf));

    free(msgbuf);
  }
}

/*********************************************************************
**********************************************************************
*
* Name :	RemTrans_Init
*
* Type :	pwr_tInt32
*
* Input :	Pointer to struct remnode_item.
*
* Output :	Linked list of remtrans_items
* Description :	Initialize RemTrans-object
*
**********************************************************************
*********************************************************************/

pwr_tInt32 RemTrans_Init(remnode_item* remnode)
{
  remtrans_item* remtrans;
  pwr_tStatus sts;
  pwr_tObjid child_objid, data_objid;
  pwr_tClassId class;
  int mc_found;

  /****** Initialize data in RemNode ******/
  remnode->remtrans = NULL;
  remnode->transbuff = NULL;
  remnode->multicast = NULL;
  mc_found = 0;

  /****** Get first child under RemNode ******/
  sts = gdh_GetChild(remnode->objid, &child_objid);
  while (ODD(sts))
  {
    /****** Test if type remtrans ******/
    sts = gdh_GetObjectClass(child_objid, &class);
    if (class == pwr_cClass_RemTrans)
    {
      /****** Create remtrans_item and link it ******/
      remtrans = malloc(sizeof(remtrans_item));
      if (remtrans == 0)
        exit(REM__NOMEMORY); /* Error exit */
      remtrans->next = (struct remtrans_item*)remnode->remtrans;
      remnode->remtrans = remtrans;

      remtrans->objid = child_objid;
      sts = gdh_ObjidToPointer(child_objid, (pwr_tAddress*)&remtrans->objp);
      remtrans->buffp = NULL;

      /****** Clear data i RemTrans ******/
      remtrans->objp->Buffers = 0;
      remtrans->objp->LastSts = 1;
      remtrans->objp->TransCount = 0;
      remtrans->objp->BuffCount = 0;
      remtrans->objp->LostCount = 0;
      remtrans->objp->ErrCount = 0;
      remtrans->time_since_send = 0;

      /****** Check data object under RemTrans ******/
      sts = gdh_GetChild(child_objid, &data_objid);
      if (EVEN(sts))
      {
        remtrans->objp->MaxLength = 0;
        remtrans->datap = 0;
      } /* END No Data */
      else
      {
        sts = gdh_ObjidToPointer(data_objid, (pwr_tAddress*)&remtrans->datap);
        sts = gdh_GetObjectSize(data_objid, (unsigned int*)&remtrans->objp->MaxLength);
      } /* END Data found */
    } /* END Class RemTrans */

    /* If child is (first) MultiCast object, store pointer to this object in
     * remnode_item */
    if (class == pwr_cClass_MultiCast && mc_found == 0)
    {
      mc_found = 1;
      sts = gdh_ObjidToPointer(child_objid, (pwr_tAddress*)&remnode->multicast);
    }

    /****** Get next child under RemNode ******/
    sts = gdh_GetNextSibling(child_objid, &child_objid);
  } /* END while */
  return STATUS_OK;
} /* END RemTrans_Init */

/*********************************************************************
**********************************************************************
*
* Name :	RemTrans_Cyclic
*
* Type :	pwr_tInt32
*
* Input :	Pointer to struct remnode_item
*
* Description :	Check if there are any free buffers to treat or
*		any transes to send.
*
**********************************************************************
*********************************************************************/

pwr_tInt32 RemTrans_Cyclic(remnode_item* remnode,
                           unsigned int (*remnode_send)(remnode_item* remnode, pwr_sClass_RemTrans* remtrans,
                                                        char* buf, int buf_size))

{
  pwr_tStatus sts = 0;
  remtrans_item* remtrans;
  pwr_sClass_RemTrans* RemTransP;
  rem_t_transbuff *buffp, *nextp;
  remtrans_item* transp;
  pwr_tInt32 buffsize;
  pwr_tStatus SendSts;

  /* Test if there is a buffered trans */
  if (remnode->transbuff)
  {
    buffp = (rem_t_transbuff*)remnode->transbuff;
    transp = (remtrans_item*)buffp->remtrans;
    /* Trans is not to be sent before time-out if buffered in wait for ack */
    if ((transp->time_since_send >= remnode->retransmit_time) || (buffp->ackbuf == 0))
    {
      sts = (remnode_send)(remnode, transp->objp, &buffp->data, buffp->size);
      transp->time_since_send = 0;
      if (ODD(sts))
      {
        remnode->transbuff = (rem_t_transbuff*)buffp->next;
        transp->objp->Buffers--;
        free(buffp);
      }
    }
  }

  /* Loop all remtrans under remnode */
  remtrans = remnode->remtrans;
  while (remtrans)
  {
    RemTransP = remtrans->objp;

    /* Check if buffered receive */
    if (RemTransP->Direction == REMTRANS_IN && RemTransP->Buffers > 0 && !RemTransP->DataValid)
    {
      buffp = (rem_t_transbuff*)remtrans->buffp;
      buffsize = buffp->size;        /* buffersize */
      remtrans->buffp = buffp->next; /* next buffer */

      memcpy(remtrans->datap, &buffp->data, buffsize); /* copy transdata */
      RemTransP->Buffers--;
      RemTransP->DataLength = buffp->size;
      RemTransP->LastSts = STATUS_BUFF;
      RemTrans_Logg(remtrans); /* Logg */
      RemTransP->DataValid = true;

      free(buffp); /* Dispose of buffer */
    } /* END buffered receive */
    /* Treat send trans */
    else if (RemTransP->Direction == REMTRANS_OUT)
    {
      /* Is there new data to send ? */
      if (RemTransP->DataValid)
      {
        if (RemTransP->DataLength > RemTransP->MaxLength)
        {
          RemTransP->ErrCount++;
          RemTransP->LastSts = STATUS_LENGTH;
        } /* END too long data */
        else
        {
          SendSts = 0; /* Assume that we could not send */
          if ((RemTransP->MaxBuffers == 0) || !remnode->transbuff)
          { /* Try to send if no buffers */
            SendSts = (remnode_send)(remnode, RemTransP, remtrans->datap, RemTransP->DataLength);
            remtrans->time_since_send = 0;
            if (ODD(SendSts))
            {
              RemTransP->TransCount++;
              time_GetTime(&RemTransP->TransTime);
              RemTransP->LastSts = STATUS_OK;
            } /* END Send OK */
          } /* END Try to send */
          if (EVEN(SendSts))
          { /* Trans should be buffered */
            if ((RemTransP->MaxBuffers > 0) && (RemTransP->Buffers < RemTransP->MaxBuffers))
            {
              buffp = malloc(RemTransP->DataLength + sizeof(rem_t_transbuff) - 1);
              if (buffp)
              {
                RemTransP->Buffers++;   /* Buffer counter */
                RemTransP->BuffCount++; /* Buffered trans counter */
                buffp->next = 0;
                buffp->remtrans = remtrans;
                buffp->size = RemTransP->DataLength;
                buffp->ackbuf = (SendSts == STATUS_BUFACK) ? 1 : 0;
                memcpy(&buffp->data, remtrans->datap, RemTransP->DataLength);
                if (remnode->transbuff == 0)
                  remnode->transbuff = buffp;
                else
                { /* Put buffer last in queue */
                  nextp = (rem_t_transbuff*)remnode->transbuff;
                  while (nextp->next)
                    nextp = (rem_t_transbuff*)nextp->next;
                  nextp->next = (struct rem_t_transbuff*)buffp;
                } /* END New buffer last in queue */
                RemTransP->TransCount++;
                time_GetTime(&RemTransP->TransTime);
                RemTransP->LastSts = STATUS_BUFF;
              } /* END  Create new bufer */
              else
              {
                RemTransP->ErrCount++;
                if (EVEN(sts))
                  RemTransP->LastSts = sts;
                else
                  RemTransP->LastSts = STATUS_FELSEND;
              } /* END No memory for buffer */
            } /* END Buffering wanted */
            else
            {
              RemTransP->ErrCount++;
              RemTransP->LastSts = STATUS_FELSEND;
            } /* END No more buffers */
          } /* END trans is not sent */
        } /* END Send request for valid trans */
        RemTrans_Logg(remtrans);      /* Logg */
        RemTransP->DataValid = false; /* Trans is treated */
      } /* END Data valid was set */
    } /* END Send direction */
    remtrans = (remtrans_item*)remtrans->next;
  } /* END while */

  return STATUS_OK;
}

/*********************************************************************
**********************************************************************
*
* Name :	RemTrans_Receive
*
* Type :	pwr_tInt32
*
* Input :	Pointer to struct remtrans_item,
*		Pointer to buffer and size of buffer
*
* Description :	Treat received trans that belongs to this remtrans_item.
*
**********************************************************************
*********************************************************************/

pwr_tInt32 RemTrans_Receive(remtrans_item* remtrans, char* buffer, int size)

{
  pwr_sClass_RemTrans* RemTransP;
  rem_t_transbuff *buffp, *nextp;

  RemTransP = remtrans->objp; /* Get remtrans object */
  RemTransP->TransCount++;
  time_GetTime(&RemTransP->TransTime);

  if ((unsigned int)size > RemTransP->MaxLength)
  { /* Too big trans */
    RemTransP->ErrCount++;
    RemTransP->LastSts = STATUS_LENGTH;
    RemTransP->DataLength = size;
    RemTrans_Logg(remtrans); /* Logg */
    return STATUS_LENGTH;
  } /* END Too big trans */
  else
  {
    /* First dispose of buffer if last trans is treated */
    if (!RemTransP->DataValid && (RemTransP->Buffers > 0))
    {
      buffp = (rem_t_transbuff*)remtrans->buffp;
      remtrans->buffp = buffp->next;

      memcpy(remtrans->datap, &buffp->data, buffp->size); /* copy transdata */
      RemTransP->Buffers--;
      RemTransP->DataLength = buffp->size;
      RemTransP->LastSts = STATUS_BUFF;
      RemTransP->DataValid = true;

      free(buffp); /* Dispose of buffer */
    } /* END buffered receive */
    if (!RemTransP->DataValid && RemTransP->Buffers == 0)
    { /* Store directly */
      memcpy(remtrans->datap, buffer, size);
      RemTransP->DataLength = size;
      RemTransP->LastSts = STATUS_OK;
      RemTrans_Logg(remtrans); /* Logg */
      RemTransP->DataValid = true;
      return STATUS_OK;
    } /* END Store trans directly */
    else if ((RemTransP->MaxBuffers > 0) && (RemTransP->Buffers < RemTransP->MaxBuffers))
    {
      buffp = malloc(size + sizeof(rem_t_transbuff) - 1);
      if (buffp)
      {
        RemTransP->Buffers++;   /* Buffer counter */
        RemTransP->BuffCount++; /* Buffered trans counter */
        buffp->next = 0;
        buffp->size = size;
        memcpy(&buffp->data, buffer, size);
        if (remtrans->buffp == 0)
          remtrans->buffp = (struct rem_t_transbuff*)buffp;
        else
        {
          nextp = (rem_t_transbuff*)remtrans->buffp;
          while (nextp->next)
            nextp = (rem_t_transbuff*)nextp->next;
          nextp->next = (struct rem_t_transbuff*)buffp;
        } /* END New buffer last in queue */
        return STATUS_BUFF;
      } /* END  Create new bufer */
      else
      {
        RemTransP->LostCount++;
        RemTransP->LastSts = STATUS_LOST;
        RemTrans_Logg(remtrans); /* Logg */
        return STATUS_LOST;
      } /* END  No memory for buffer*/
    } /* END Try to buffer */
    else
    {
      RemTransP->LostCount++;
      RemTransP->LastSts = STATUS_LOST;
      RemTrans_Logg(remtrans); /* Logg */
      return STATUS_LOST;
    } /* END Buffering not allowed */
  } /* END Treat OK trans  */
}
