/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#include <iostream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <thread>
#include <mutex>
#include <memory>
#include <glib.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#include "pn_dcp_tool_gtk.h"
#include "network_topology_window.h"

namespace ProfinetDCP
{

// Application state
static ProfinetDCPWindow* g_main_window = nullptr;
static std::mutex g_gtk_mutex;

// Core logging callback
void activityLogCallback(const std::string& message)
{
  if (g_main_window)
  {
    g_main_window->addLogMessage(message);
  }
}

// GTK Utils
namespace GTKUtils
{

// Helper function to convert IP string to comparable integer
static guint32 ipStringToInt(const std::string& ip_str)
{
  guint32 result = 0;
  std::istringstream iss(ip_str);
  std::string octet;
  int shift = 24;

  while (std::getline(iss, octet, '.') && shift >= 0)
  {
    result |= (std::stoi(octet) << shift);
    shift -= 8;
  }
  return result;
}

// Custom sort function for IP addresses
static gint compareIPAddresses(GtkTreeModel* model, GtkTreeIter* a, GtkTreeIter* b, gpointer data)
{
  gchar* ip_a = nullptr;
  gchar* ip_b = nullptr;

  gtk_tree_model_get(model, a, COL_IP_ADDRESS, &ip_a, -1);
  gtk_tree_model_get(model, b, COL_IP_ADDRESS, &ip_b, -1);

  if (!ip_a && !ip_b)
    return 0;
  if (!ip_a)
    return -1;
  if (!ip_b)
    return 1;

  guint32 int_a = ipStringToInt(std::string(ip_a));
  guint32 int_b = ipStringToInt(std::string(ip_b));

  g_free(ip_a);
  g_free(ip_b);

  if (int_a < int_b)
    return -1;
  if (int_a > int_b)
    return 1;
  return 0;
}

std::string getEntryText(GtkEntry* entry)
{
  const char* text = gtk_entry_get_text(entry);
  return text ? std::string(text) : std::string();
}

void addDeviceToStore(GtkListStore* store, const DCPDeviceInfo& device)
{
  GtkTreeIter iter;
  gtk_list_store_append(store, &iter);
  updateDeviceInStore(store, &iter, device);
}

void updateDeviceInStore(GtkListStore* store, GtkTreeIter* iter, const DCPDeviceInfo& device)
{
  gtk_list_store_set(store, iter, COL_MAC_ADDRESS, device.mac_address.toString().c_str(), COL_DEVICE_NAME,
                     device.device_name.c_str(), COL_IP_ADDRESS, device.ip_address.toString().c_str(),
                     COL_VENDOR, ProfinetDCPTool::vendorIdToString(device.vendor_id).c_str(), COL_DEVICE_ID,
                     ProfinetDCPTool::deviceIdToString(device.vendor_id, device.device_id).c_str(),
                     COL_DEVICE_PTR,
                     nullptr, // We'll manage this differently
                     -1);
}

void showErrorDialog(GtkWidget* parent, const std::string& title, const std::string& message)
{
  GtkWidget* dialog = gtk_message_dialog_new(
      GTK_WINDOW(parent), static_cast<GtkDialogFlags>(GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT),
      GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, "%s", message.c_str());

  gtk_window_set_title(GTK_WINDOW(dialog), title.c_str());
  gtk_dialog_run(GTK_DIALOG(dialog));
  gtk_widget_destroy(dialog);
}

} // namespace GTKUtils

// Cell data function for conditional coloring of DCP devices
static void dcpDeviceCellDataFunc(GtkTreeViewColumn* column,
                                 GtkCellRenderer* cell,
                                 GtkTreeModel* model,
                                 GtkTreeIter* iter,
                                 gpointer user_data)
{
  auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(user_data);
  
  char* device_name = nullptr;
  char* device_ip = nullptr;
  gtk_tree_model_get(model, iter, 
                     COL_DEVICE_NAME, &device_name,
                     COL_IP_ADDRESS, &device_ip,
                     -1);
  
  if (device_name) {
    std::string configured_ip = gui->getConfiguredDeviceIP(device_name);
    
    if (!configured_ip.empty() && device_ip && configured_ip == device_ip) {
      // Device name and IP match - subtle dark green background with white text
      g_object_set(cell, "background", "#2d5a2d", "foreground", "#ffffff", nullptr);
    } else {
      // Device not configured or IP doesn't match - use default appearance
      g_object_set(cell, "background", nullptr, "foreground", nullptr, nullptr);
    }
  } else {
    // No device name - use default appearance
    g_object_set(cell, "background", nullptr, "foreground", nullptr, nullptr);
  }
  
  g_free(device_name);
  g_free(device_ip);
}

// Selection synchronization callbacks
static void onDCPDeviceSelectionChangedForSync(GtkTreeSelection* selection, gpointer data)
{
  auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(data);
  
  GtkTreeIter iter;
  if (gtk_tree_selection_get_selected(selection, nullptr, &iter)) {
    char* device_name = nullptr;
    gtk_tree_model_get(GTK_TREE_MODEL(gui->getDeviceListStore()), &iter, COL_DEVICE_NAME, &device_name, -1);
    
    if (device_name) {
      gui->syncSelectionToConfiguredList(device_name);
      g_free(device_name);
    }
  }
}

static void onConfiguredDeviceSelectionChangedForSync(GtkTreeSelection* selection, gpointer data)
{
  auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(data);
  
  GtkTreeIter iter;
  if (gtk_tree_selection_get_selected(selection, nullptr, &iter)) {
    char* device_name = nullptr;
    gtk_tree_model_get(GTK_TREE_MODEL(gui->getConfiguredDeviceListStore()), &iter, COL_DEVICE_NAME, &device_name, -1);
    
    if (device_name) {
      gui->syncSelectionToDCPList(device_name);
      g_free(device_name);
    }
  }
}

// ProfinetDCPWindow implementation
ProfinetDCPWindow::ProfinetDCPWindow() : m_main_window(nullptr)
{
  g_main_window = this;
  ProfinetDCP::registerLogCallback(activityLogCallback);
}

ProfinetDCPWindow::~ProfinetDCPWindow()
{
  ProfinetDCP::registerLogCallback(nullptr); // Unregister callback
  if (m_main_window && GTK_IS_WIDGET(m_main_window))
  {
    gtk_widget_destroy(m_main_window);
  }
  m_main_window = nullptr;
  g_main_window = nullptr;
}

bool ProfinetDCPWindow::create()
{
  // Create main window
  m_main_window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title(GTK_WINDOW(m_main_window), "PROFINET DCP Tool");
  gtk_window_set_default_size(GTK_WINDOW(m_main_window), 1000,
                              800); // Increased for better device list visibility

  // Set minimum window size to prevent layout breaking
  gtk_widget_set_size_request(GTK_WIDGET(m_main_window), 900, 600); // Minimum 900x600

  gtk_window_set_position(GTK_WINDOW(m_main_window), GTK_WIN_POS_CENTER);

  // Set window icon
  gtk_window_set_icon_name(GTK_WINDOW(m_main_window), "network-workgroup");

  // Connect destroy signals
  g_signal_connect(m_main_window, "delete-event", G_CALLBACK(onDeleteEvent), this);
  g_signal_connect(m_main_window, "destroy", G_CALLBACK(onDestroy), this);

  // Create GUI controller
  m_gui_controller = std::make_unique<ProfinetDCPGUI>(m_main_window);
  if (!m_gui_controller->initialize())
  {
    return false;
  }

  // Add main widget to window
  GtkWidget* main_widget = m_gui_controller->createMainWidget();
  if (!main_widget)
  {
    return false;
  }

  gtk_container_add(GTK_CONTAINER(m_main_window), main_widget);

  return true;
}

void ProfinetDCPWindow::show()
{
  if (m_main_window)
  {
    gtk_widget_show_all(m_main_window);
  }
}

void ProfinetDCPWindow::run() const
{
  if (m_main_window)
  {
    gtk_main();
  }
}

gboolean ProfinetDCPWindow::onDeleteEvent(GtkWidget* widget, GdkEvent* event, gpointer data)
{
  // Return FALSE to allow the window to be destroyed
  return FALSE;
}

void ProfinetDCPWindow::onDestroy(GtkWidget* widget, gpointer data)
{
  // Shutdown the GUI controller
  auto* window = static_cast<ProfinetDCPWindow*>(data);
  if (window->m_gui_controller)
  {
    window->m_gui_controller->shutdown();
  }

  // Quit the main loop
  gtk_main_quit();
}

ProfinetDCPTool* ProfinetDCPWindow::getDCPTool() const
{
  return m_gui_controller ? m_gui_controller->getDCPTool() : nullptr;
}

void ProfinetDCPWindow::addLogMessage(const std::string& message)
{
  if (m_gui_controller)
  {
    m_gui_controller->addLogMessageWithTimestamp(message);
  }
}

// ProfinetDCPGUI implementation
ProfinetDCPGUI::ProfinetDCPGUI(GtkWidget* parent_window)
    : m_parent_window(parent_window), m_main_widget(nullptr), m_toolbar(nullptr), m_interface_combo(nullptr),
      m_connect_button(nullptr), m_disconnect_button(nullptr), m_discover_button(nullptr),
      m_topology_button(nullptr), m_device_tree_view(nullptr), m_device_list_store(nullptr),
      m_device_selection(nullptr), m_configured_device_tree_view(nullptr), m_configured_device_list_store(nullptr),
      m_configured_device_selection(nullptr), m_details_frame(nullptr), m_details_container(nullptr),
      m_status_bar(nullptr), m_status_context_id(0), m_log_text_view(nullptr), m_log_buffer(nullptr),
      m_progress_bar(nullptr), m_log_scrolled_window(nullptr), m_dcp_tool(nullptr), m_is_connected(false),
      m_discovery_in_progress(false)
{
}

ProfinetDCPGUI::~ProfinetDCPGUI() { shutdown(); }

bool ProfinetDCPGUI::initialize()
{
  m_dcp_tool = std::make_unique<ProfinetDCPTool>();
  m_configured_device_reader = std::make_unique<ConfiguredDeviceReader>();
  
  // Set up activity log callback for configured device reader
  m_configured_device_reader->setActivityLogCallback([this](const std::string& message) {
    if (g_main_window) {
      g_main_window->addLogMessage(message);
    }
  });
  
  return true;
}

void ProfinetDCPGUI::shutdown()
{
  if (m_dcp_tool)
  {
    m_dcp_tool->shutdown();
    m_dcp_tool.reset();
  }
  m_is_connected = false;
}

// Forward declaration for static callback
static void onMainWidgetRealized(GtkWidget* widget, gpointer data);

GtkWidget* ProfinetDCPGUI::createMainWidget()
{
  // Create main vertical box
  m_main_widget = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);

  // Create m_toolbar
  m_toolbar = createToolbar();
  gtk_box_pack_start(GTK_BOX(m_main_widget), m_toolbar, FALSE, FALSE, 0);

  // Create vertical paned container for main content and log
  GtkWidget* vpaned = gtk_paned_new(GTK_ORIENTATION_VERTICAL);
  gtk_box_pack_start(GTK_BOX(m_main_widget), vpaned, TRUE, TRUE, 0);

  // Create horizontal paned container for device lists and details
  GtkWidget* hpaned = gtk_paned_new(GTK_ORIENTATION_HORIZONTAL);
  gtk_paned_pack1(GTK_PANED(vpaned), hpaned, TRUE, TRUE);

  // Create vertical paned container for both device lists
  GtkWidget* device_lists_paned = gtk_paned_new(GTK_ORIENTATION_VERTICAL);
  gtk_paned_pack1(GTK_PANED(hpaned), device_lists_paned, TRUE, TRUE);

  // Create discovered device list (DCP)
  GtkWidget* device_list = createDeviceList();
  gtk_paned_pack1(GTK_PANED(device_lists_paned), device_list, TRUE, TRUE);

  // Create configured device list
  GtkWidget* configured_device_list = createConfiguredDeviceList();
  gtk_paned_pack2(GTK_PANED(device_lists_paned), configured_device_list, TRUE, TRUE);

  // Create details panel
  GtkWidget* details = createDetailsPanel();
  gtk_paned_pack2(GTK_PANED(hpaned), details, FALSE, TRUE); // Allow shrinking but don't resize with window

  // Create log and progress panel
  GtkWidget* log_panel = createLogAndProgressPanel();
  gtk_paned_pack2(GTK_PANED(vpaned), log_panel, FALSE, TRUE);

  // Set proportional positions after widget is realized to work with any window size
  g_signal_connect(m_main_widget, "realize", G_CALLBACK(onMainWidgetRealized), nullptr);

  // Store paned widgets for the realize callback
  g_object_set_data(G_OBJECT(m_main_widget), "vpaned", vpaned);
  g_object_set_data(G_OBJECT(m_main_widget), "hpaned", hpaned);

  // Initialize interface combo
  populateInterfaceCombo();
  updateConnectionStatus();

  // Add initial ready message to log
  addLogMessageWithTimestamp("PROFINET DCP Tool ready");

  return m_main_widget;
}

GtkWidget* ProfinetDCPGUI::createToolbar()
{
  m_toolbar = gtk_toolbar_new();
  gtk_toolbar_set_style(GTK_TOOLBAR(m_toolbar), GTK_TOOLBAR_BOTH);

  // Interface selection
  GtkToolItem* interface_item = gtk_tool_item_new();

  // Create vertical container for proper centering
  GtkWidget* interface_vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);

  // Top spacer for vertical centering
  GtkWidget* top_spacer = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_box_pack_start(GTK_BOX(interface_vbox), top_spacer, TRUE, TRUE, 0);

  // Horizontal container for label and combo
  GtkWidget* interface_hbox = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 8);

  GtkWidget* interface_label = gtk_label_new("Interface:");
  gtk_box_pack_start(GTK_BOX(interface_hbox), interface_label, FALSE, FALSE, 0);

  m_interface_combo = gtk_combo_box_text_new();
  gtk_box_pack_start(GTK_BOX(interface_hbox), m_interface_combo, FALSE, FALSE, 0);
  g_signal_connect(m_interface_combo, "changed", G_CALLBACK(onInterfaceChanged), this);
  gtk_widget_set_tooltip_text(m_interface_combo, "Select network interface for PROFINET communication");

  // Pack the horizontal box in the center
  gtk_box_pack_start(GTK_BOX(interface_vbox), interface_hbox, FALSE, FALSE, 0);

  // Bottom spacer for vertical centering
  GtkWidget* bottom_spacer = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_box_pack_start(GTK_BOX(interface_vbox), bottom_spacer, TRUE, TRUE, 0);

  gtk_container_add(GTK_CONTAINER(interface_item), interface_vbox);
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), interface_item, -1);

  // Separator
  GtkToolItem* sep1 = gtk_separator_tool_item_new();
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), sep1, -1);

  // Connect button
  m_connect_button = GTK_WIDGET(gtk_tool_button_new(nullptr, "Connect"));
  gtk_tool_button_set_icon_name(GTK_TOOL_BUTTON(m_connect_button), "network-connect");
  g_signal_connect(m_connect_button, "clicked", G_CALLBACK(onConnectClicked), this);
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), GTK_TOOL_ITEM(m_connect_button), -1);
  gtk_widget_set_tooltip_text(m_connect_button, "Connect to selected network interface");
  // Add CSS style class
  GtkWidget* connect_btn_widget = gtk_bin_get_child(GTK_BIN(m_connect_button));
  if (connect_btn_widget && GTK_IS_BUTTON(connect_btn_widget))
  {
    gtk_style_context_add_class(gtk_widget_get_style_context(connect_btn_widget), "connect-button");
  }

  // Disconnect button
  m_disconnect_button = GTK_WIDGET(gtk_tool_button_new(nullptr, "Disconnect"));
  gtk_tool_button_set_icon_name(GTK_TOOL_BUTTON(m_disconnect_button), "network-disconnect");
  g_signal_connect(m_disconnect_button, "clicked", G_CALLBACK(onDisconnectClicked), this);
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), GTK_TOOL_ITEM(m_disconnect_button), -1);
  gtk_widget_set_tooltip_text(m_disconnect_button, "Disconnect from network interface");
  // Add CSS style class
  GtkWidget* disconnect_btn_widget = gtk_bin_get_child(GTK_BIN(m_disconnect_button));
  if (disconnect_btn_widget && GTK_IS_BUTTON(disconnect_btn_widget))
  {
    gtk_style_context_add_class(gtk_widget_get_style_context(disconnect_btn_widget), "disconnect-button");
  }

  // Separator
  GtkToolItem* sep2 = gtk_separator_tool_item_new();
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), sep2, -1);

  // Discover button
  m_discover_button = GTK_WIDGET(gtk_tool_button_new(nullptr, "Discover"));
  gtk_tool_button_set_icon_name(GTK_TOOL_BUTTON(m_discover_button), "system-search");
  g_signal_connect(m_discover_button, "clicked", G_CALLBACK(onDiscoverClicked), this);
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), GTK_TOOL_ITEM(m_discover_button), -1);
  gtk_widget_set_tooltip_text(m_discover_button,
                              "Broadcast DCP Identify request to discover all PROFINET devices");

  // Add CSS style class discovery
  GtkWidget* discover_btn_widget = gtk_bin_get_child(GTK_BIN(m_discover_button));
  if (discover_btn_widget && GTK_IS_BUTTON(discover_btn_widget))
  {
    gtk_style_context_add_class(gtk_widget_get_style_context(discover_btn_widget), "discover-button");
  }

  // Separator before topology tools
  GtkToolItem* sep3 = gtk_separator_tool_item_new();
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), sep3, -1);

  // Network Topology button
  m_topology_button = GTK_WIDGET(gtk_tool_button_new(nullptr, "Topology"));
  gtk_tool_button_set_icon_name(GTK_TOOL_BUTTON(m_topology_button), "network-workgroup");
  g_signal_connect(m_topology_button, "clicked", G_CALLBACK(onTopologyClicked), this);
  gtk_toolbar_insert(GTK_TOOLBAR(m_toolbar), GTK_TOOL_ITEM(m_topology_button), -1);
  gtk_widget_set_sensitive(m_topology_button, FALSE); // Initially disabled
  gtk_widget_set_tooltip_text(m_topology_button, "Connect to network interface first");

  // Add CSS style class for topology button
  GtkWidget* topology_btn_widget = gtk_bin_get_child(GTK_BIN(m_topology_button));
  if (topology_btn_widget && GTK_IS_BUTTON(topology_btn_widget))
  {
    gtk_style_context_add_class(gtk_widget_get_style_context(topology_btn_widget), "topology-button");
  }

  return m_toolbar;
}

GtkWidget* ProfinetDCPGUI::createDeviceList()
{
  // Create frame with title
  GtkWidget* frame = gtk_frame_new("Discovered Devices (DCP)");
  gtk_style_context_add_class(gtk_widget_get_style_context(frame), "device-list-frame");

  // Create scrolled window
  GtkWidget* scrolled = gtk_scrolled_window_new(nullptr, nullptr);
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(scrolled), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type(GTK_SCROLLED_WINDOW(scrolled), GTK_SHADOW_IN);

  // Create list store
  m_device_list_store = gtk_list_store_new(NUM_COLUMNS,
                                           G_TYPE_STRING,   // COL_MAC_ADDRESS
                                           G_TYPE_STRING,   // COL_DEVICE_NAME
                                           G_TYPE_STRING,   // COL_IP_ADDRESS
                                           G_TYPE_STRING,   // COL_VENDOR
                                           G_TYPE_STRING,   // COL_DEVICE_ID
                                           G_TYPE_POINTER); // COL_DEVICE_PTR

  // Create tree view
  m_device_tree_view = gtk_tree_view_new_with_model(GTK_TREE_MODEL(m_device_list_store));

  // Headers visible and clickable
  gtk_tree_view_set_headers_visible(GTK_TREE_VIEW(m_device_tree_view), TRUE);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(m_device_tree_view), TRUE);

  // Add columns
  GtkCellRenderer* renderer;
  GtkTreeViewColumn* column;

  // MAC Address column
  renderer = gtk_cell_renderer_text_new();
  column =
      gtk_tree_view_column_new_with_attributes("MAC Address", renderer, "text", COL_MAC_ADDRESS, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_MAC_ADDRESS);
  // Apply cell data function for conditional coloring
  gtk_tree_view_column_set_cell_data_func(column, renderer, dcpDeviceCellDataFunc, this, nullptr);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_device_tree_view), column);

  // Device Name column
  renderer = gtk_cell_renderer_text_new();
  column =
      gtk_tree_view_column_new_with_attributes("Device Name", renderer, "text", COL_DEVICE_NAME, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_DEVICE_NAME);
  // Apply cell data function for conditional coloring
  gtk_tree_view_column_set_cell_data_func(column, renderer, dcpDeviceCellDataFunc, this, nullptr);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_device_tree_view), column);

  // IP Address column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("IP Address", renderer, "text", COL_IP_ADDRESS, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_IP_ADDRESS);
  // Apply cell data function for conditional coloring
  gtk_tree_view_column_set_cell_data_func(column, renderer, dcpDeviceCellDataFunc, this, nullptr);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_device_tree_view), column);

  // Set custom sort function for IP column
  gtk_tree_sortable_set_sort_func(GTK_TREE_SORTABLE(m_device_list_store), COL_IP_ADDRESS,
                                  GTKUtils::compareIPAddresses, nullptr, nullptr);

  // Vendor column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("Vendor", renderer, "text", COL_VENDOR, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_VENDOR);
  // Apply cell data function for conditional coloring
  gtk_tree_view_column_set_cell_data_func(column, renderer, dcpDeviceCellDataFunc, this, nullptr);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_device_tree_view), column);

  // Device ID column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("Device Type", renderer, "text", COL_DEVICE_ID, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_DEVICE_ID);
  // Apply cell data function for conditional coloring
  gtk_tree_view_column_set_cell_data_func(column, renderer, dcpDeviceCellDataFunc, this, nullptr);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_device_tree_view), column);

  // Tree view behavior
  gtk_tree_view_set_fixed_height_mode(GTK_TREE_VIEW(m_device_tree_view), FALSE); // Variable height
  gtk_tree_view_set_enable_search(GTK_TREE_VIEW(m_device_tree_view), TRUE);

  // Selection
  m_device_selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(m_device_tree_view));
  gtk_tree_selection_set_mode(m_device_selection, GTK_SELECTION_SINGLE);
  g_signal_connect(m_device_selection, "changed", G_CALLBACK(onDeviceSelectionChanged), this);
  g_signal_connect(m_device_selection, "changed", G_CALLBACK(onDCPDeviceSelectionChangedForSync), this);

  // Double-click
  g_signal_connect(m_device_tree_view, "row-activated", G_CALLBACK(onDeviceDoubleClick), this);

  // Right-click
  g_signal_connect(m_device_tree_view, "button-press-event", G_CALLBACK(onDeviceRightClick), this);

  gtk_container_add(GTK_CONTAINER(scrolled), m_device_tree_view);
  gtk_container_add(GTK_CONTAINER(frame), scrolled);

  return frame;
}

GtkWidget* ProfinetDCPGUI::createConfiguredDeviceList()
{
  // Create frame with title
  GtkWidget* frame = gtk_frame_new("Configured Devices in ProviewR");
  gtk_style_context_add_class(gtk_widget_get_style_context(frame), "configured-device-list-frame");

  // Create scrolled window
  GtkWidget* scrolled = gtk_scrolled_window_new(nullptr, nullptr);
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(scrolled), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type(GTK_SCROLLED_WINDOW(scrolled), GTK_SHADOW_IN);

  // Create list store - using same columns as DCP device list for consistency
  m_configured_device_list_store = gtk_list_store_new(NUM_COLUMNS,
                                                      G_TYPE_STRING,   // COL_MAC_ADDRESS
                                                      G_TYPE_STRING,   // COL_DEVICE_NAME
                                                      G_TYPE_STRING,   // COL_IP_ADDRESS
                                                      G_TYPE_STRING,   // COL_VENDOR
                                                      G_TYPE_STRING,   // COL_DEVICE_ID
                                                      G_TYPE_POINTER); // COL_DEVICE_PTR (will be xml_node)

  // Create tree view
  m_configured_device_tree_view = gtk_tree_view_new_with_model(GTK_TREE_MODEL(m_configured_device_list_store));

  // Headers visible and clickable
  gtk_tree_view_set_headers_visible(GTK_TREE_VIEW(m_configured_device_tree_view), TRUE);
  gtk_tree_view_set_headers_clickable(GTK_TREE_VIEW(m_configured_device_tree_view), TRUE);

  // Add columns - same as DCP device list
  GtkCellRenderer* renderer;
  GtkTreeViewColumn* column;

  // MAC Address column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("MAC Address", renderer, "text", COL_MAC_ADDRESS, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_MAC_ADDRESS);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_configured_device_tree_view), column);

  // Device Name column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("Device Name", renderer, "text", COL_DEVICE_NAME, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_DEVICE_NAME);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_configured_device_tree_view), column);

  // IP Address column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("IP Address", renderer, "text", COL_IP_ADDRESS, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_IP_ADDRESS);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_configured_device_tree_view), column);

  // Vendor column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("Vendor", renderer, "text", COL_VENDOR, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_VENDOR);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_configured_device_tree_view), column);

  // Device Type column
  renderer = gtk_cell_renderer_text_new();
  column = gtk_tree_view_column_new_with_attributes("Device Type", renderer, "text", COL_DEVICE_ID, nullptr);
  gtk_tree_view_column_set_resizable(column, TRUE);
  gtk_tree_view_column_set_sort_column_id(column, COL_DEVICE_ID);
  gtk_tree_view_append_column(GTK_TREE_VIEW(m_configured_device_tree_view), column);

  // Tree view behavior
  gtk_tree_view_set_fixed_height_mode(GTK_TREE_VIEW(m_configured_device_tree_view), FALSE);
  gtk_tree_view_set_enable_search(GTK_TREE_VIEW(m_configured_device_tree_view), TRUE);

  // Selection
  m_configured_device_selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(m_configured_device_tree_view));
  gtk_tree_selection_set_mode(m_configured_device_selection, GTK_SELECTION_SINGLE);
  g_signal_connect(m_configured_device_selection, "changed", G_CALLBACK(onConfiguredDeviceSelectionChangedForSync), this);

  // Right-click context menu
  g_signal_connect(m_configured_device_tree_view, "button-press-event", G_CALLBACK(onConfiguredDeviceRightClick), this);

  gtk_container_add(GTK_CONTAINER(scrolled), m_configured_device_tree_view);
  gtk_container_add(GTK_CONTAINER(frame), scrolled);

  return frame;
}

GtkWidget* ProfinetDCPGUI::createDetailsPanel()
{
  m_details_frame = gtk_frame_new("Device Details");
  gtk_style_context_add_class(gtk_widget_get_style_context(m_details_frame), "details-frame");

  // Create a container for the details content
  m_details_container = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  gtk_style_context_add_class(gtk_widget_get_style_context(m_details_container), "details-container");
  gtk_container_add(GTK_CONTAINER(m_details_frame), m_details_container);

  // Empty state - populated on selection
  GtkWidget* empty_label = gtk_label_new("Select a device to view details");
  gtk_container_add(GTK_CONTAINER(m_details_container), empty_label);

  return m_details_frame;
}

GtkWidget* ProfinetDCPGUI::createLogAndProgressPanel()
{
  // Frame for log and progress
  GtkWidget* frame = gtk_frame_new("Activity Log");
  gtk_style_context_add_class(gtk_widget_get_style_context(frame), "log-frame");

  // VBox for progress and log
  GtkWidget* vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 5);
  gtk_style_context_add_class(gtk_widget_get_style_context(vbox), "log-container");
  gtk_container_add(GTK_CONTAINER(frame), vbox);

  // Progress bar (hidden)
  m_progress_bar = gtk_progress_bar_new();
  gtk_progress_bar_set_show_text(GTK_PROGRESS_BAR(m_progress_bar), TRUE);
  gtk_widget_set_no_show_all(m_progress_bar, TRUE); // Don't show by default
  gtk_box_pack_start(GTK_BOX(vbox), m_progress_bar, FALSE, FALSE, 0);

  // Scrolled window for text view
  m_log_scrolled_window = gtk_scrolled_window_new(nullptr, nullptr);
  gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(m_log_scrolled_window), GTK_POLICY_AUTOMATIC,
                                 GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type(GTK_SCROLLED_WINDOW(m_log_scrolled_window), GTK_SHADOW_IN);

  // Text view for log messages
  m_log_text_view = gtk_text_view_new();
  gtk_text_view_set_editable(GTK_TEXT_VIEW(m_log_text_view), FALSE);
  gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(m_log_text_view), FALSE);
  gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(m_log_text_view), GTK_WRAP_WORD);

  // Text buffer
  m_log_buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(m_log_text_view));

  gtk_container_add(GTK_CONTAINER(m_log_scrolled_window), m_log_text_view);
  gtk_box_pack_start(GTK_BOX(vbox), m_log_scrolled_window, TRUE, TRUE, 0);

  // Welcome message
  addLogMessageWithTimestamp("PROFINET DCP Tool initialized. Ready to discover devices.");

  return frame;
}

void ProfinetDCPGUI::populateInterfaceCombo()
{
  // Clear existing items
  gtk_combo_box_text_remove_all(GTK_COMBO_BOX_TEXT(m_interface_combo));

  auto interfaces = ProfinetDCPTool::getAvailableInterfaces();
  for (const auto& iface : interfaces)
  {
    gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(m_interface_combo), iface.c_str());
  }

  if (!interfaces.empty())
  {
    gtk_combo_box_set_active(GTK_COMBO_BOX(m_interface_combo), 0);
  }
}

std::string ProfinetDCPGUI::getSelectedInterface()
{
  char* text = gtk_combo_box_text_get_active_text(GTK_COMBO_BOX_TEXT(m_interface_combo));
  std::string result = text ? std::string(text) : std::string();
  if (text)
    g_free(text);
  return result;
}

void ProfinetDCPGUI::updateConnectionStatus()
{
  bool connected = m_is_connected;

  gtk_widget_set_sensitive(m_interface_combo, !connected);
  gtk_widget_set_sensitive(m_connect_button, !connected);
  gtk_widget_set_sensitive(m_disconnect_button, connected);
  gtk_widget_set_sensitive(m_discover_button, connected);

  // Update topology button state based on connection and devices
  updateTopologyButtonState();

  if (connected)
  {
    addLogMessageWithTimestamp("Connected to " + getSelectedInterface());
  }
  else
  {
    addLogMessageWithTimestamp("Disconnected from network interface");
  }
}

void ProfinetDCPGUI::updateTopologyButtonState()
{
  // Enable topology button only if connected and have devices
  bool should_enable = m_is_connected && !m_current_devices.empty();
  gtk_widget_set_sensitive(m_topology_button, should_enable);

  // Update tooltip based on state
  if (!m_is_connected)
  {
    gtk_widget_set_tooltip_text(m_topology_button, "Connect to network interface first");
  }
  else if (m_current_devices.empty())
  {
    gtk_widget_set_tooltip_text(m_topology_button, "Discover devices first to show topology");
  }
  else
  {
    gtk_widget_set_tooltip_text(m_topology_button, "Show network topology visualization");
  }
}

// Status bar removed - using log window instead
/*
void ProfinetDCPGUI::updateStatus(const std::string& message)
{
  gtk_statusbar_pop(GTK_STATUSBAR(m_status_bar), m_status_context_id);
  gtk_statusbar_push(GTK_STATUSBAR(m_status_bar), m_status_context_id, message.c_str());
}
*/

void ProfinetDCPGUI::addLogMessage(const std::string& message)
{
  if (!m_log_buffer)
    return;

  GtkTextIter iter;
  gtk_text_buffer_get_end_iter(m_log_buffer, &iter);

  std::string msg = message + "\n";
  gtk_text_buffer_insert(m_log_buffer, &iter, msg.c_str(), -1);

  // Auto-scroll to bottom
  GtkTextMark* mark = gtk_text_buffer_get_insert(m_log_buffer);
  gtk_text_view_scroll_mark_onscreen(GTK_TEXT_VIEW(m_log_text_view), mark);
}

void ProfinetDCPGUI::addLogMessageWithTimestamp(const std::string& message)
{
  // Get current time
  auto now = std::chrono::system_clock::now();
  auto time_t = std::chrono::system_clock::to_time_t(now);
  auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()) % 1000;

  std::ostringstream oss;
  oss << std::put_time(std::localtime(&time_t), "%H:%M:%S");
  oss << "." << std::setfill('0') << std::setw(3) << ms.count();
  oss << " " << message;

  addLogMessage(oss.str());
}

void ProfinetDCPGUI::scrollLogToBottom()
{
  if (m_log_text_view && m_log_buffer && m_log_scrolled_window)
  {
    // Force layout update first
    gtk_widget_queue_resize(m_log_text_view);
    gtk_widget_queue_resize(m_log_scrolled_window);

    // Process events to ensure resize happens
    while (gtk_events_pending())
      gtk_main_iteration();

    // Method 1: Try text view mark scrolling
    GtkTextIter end_iter;
    gtk_text_buffer_get_end_iter(m_log_buffer, &end_iter);
    GtkTextMark* end_mark = gtk_text_buffer_create_mark(m_log_buffer, nullptr, &end_iter, FALSE);
    gtk_text_view_scroll_mark_onscreen(GTK_TEXT_VIEW(m_log_text_view), end_mark);
    gtk_text_buffer_delete_mark(m_log_buffer, end_mark);

    // Method 2: Also try scrolled window adjustment
    GtkAdjustment* vadj = gtk_scrolled_window_get_vadjustment(GTK_SCROLLED_WINDOW(m_log_scrolled_window));
    if (vadj)
    {
      double upper = gtk_adjustment_get_upper(vadj);
      double page_size = gtk_adjustment_get_page_size(vadj);
      gtk_adjustment_set_value(vadj, upper - page_size);
    }
  }
}

void ProfinetDCPGUI::updateProgress(double fraction, const std::string& text)
{
  if (!m_progress_bar)
    return;

  gtk_progress_bar_set_fraction(GTK_PROGRESS_BAR(m_progress_bar), fraction);
  if (!text.empty())
  {
    gtk_progress_bar_set_text(GTK_PROGRESS_BAR(m_progress_bar), text.c_str());
  }
}

void ProfinetDCPGUI::showProgress()
{
  if (m_progress_bar)
  {
    gtk_widget_show(m_progress_bar);
  }
}
void ProfinetDCPGUI::hideProgress()
{
  if (m_progress_bar)
  {
    gtk_widget_hide(m_progress_bar);

    // Force immediate layout recalculation and scroll
    if (m_log_scrolled_window)
    {
      gtk_widget_queue_resize(m_log_scrolled_window);

      // Process pending GTK events to ensure layout is updated
      while (gtk_events_pending())
        gtk_main_iteration();

      // Now scroll - layout should be recalculated
      scrollLogToBottom();
    }
  }
} // Event handlers (simplified for this example)
void ProfinetDCPGUI::onInterfaceChanged(GtkComboBox* combo, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);
  std::string selected_interface = gui->getSelectedInterface();
  if (!selected_interface.empty())
  {
    // Load configured devices for the selected interface
    gui->loadConfiguredDevices();
    
    // Refresh DCP device list coloring based on new configured device list
    gui->refreshDCPDeviceColoring();
  }
}

void ProfinetDCPGUI::onConnectClicked(GtkButton* button, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);

  std::string interface = gui->getSelectedInterface();
  if (interface.empty())
  {
    GTKUtils::showErrorDialog(gui->m_parent_window, "Error", "Please select a network interface");
    return;
  }

  gui->addLogMessageWithTimestamp("Connecting to interface: " + interface);

  auto result = gui->m_dcp_tool->initialize(interface);
  if (result == DCPResult::Success)
  {
    gui->m_is_connected = true;
    gui->updateConnectionStatus();
    gui->addLogMessageWithTimestamp("Successfully connected to " + interface);
  }
  else
  {
    std::string error_msg =
        "Failed to connect to interface " + interface + ": " + ProfinetDCPTool::dcpResultToString(result);
    gui->addLogMessageWithTimestamp(error_msg);

    GTKUtils::showErrorDialog(gui->m_parent_window, "Connection Error",
                              "Failed to connect to interface: " +
                                  ProfinetDCPTool::dcpResultToString(result));
  }
}

void ProfinetDCPGUI::onDisconnectClicked(GtkButton* button, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);

  gui->addLogMessageWithTimestamp("Disconnecting from " + gui->getSelectedInterface());
  gui->m_dcp_tool->shutdown();
  gui->m_is_connected = false;

  gui->clearDeviceList();
  gui->updateConnectionStatus();
  gui->addLogMessageWithTimestamp("Disconnected. Device list cleared.");
}

void ProfinetDCPGUI::onDiscoverClicked(GtkButton* button, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);

  if (!gui->m_is_connected)
    return;

  // Prevent parallel discoveries
  if (gui->m_discovery_in_progress)
  {
    gui->addLogMessageWithTimestamp("Discovery already in progress...");
    return;
  }

  gui->m_discovery_in_progress = true;
  gui->addLogMessageWithTimestamp("Starting device discovery on " + gui->getSelectedInterface());

  // Show progress and start discovery
  gui->showProgress();
  gui->updateProgress(0.0, "Initializing discovery...");

  // Disable controls during discovery
  gtk_widget_set_sensitive(GTK_WIDGET(button), FALSE);
  gtk_widget_set_sensitive(gui->m_device_tree_view, FALSE);

  // Clear current devices
  gui->m_current_devices.clear();
  gui->clearDeviceList();           // Clear GTK list directly instead of updateDeviceList()
  gui->updateTopologyButtonState(); // Update button state after clearing devices

  // Device discovered callback
  auto device_callback = [gui](const DCPDeviceInfo& device)
  {
    // Use g_idle_add to safely update GUI from background thread
    struct DeviceCallbackData
    {
      ProfinetDCPGUI* gui;
      DCPDeviceInfo device;
    };

    auto* device_data = new DeviceCallbackData{gui, device};
    g_idle_add(
        [](gpointer data) -> gboolean
        {
          auto* callback_data = static_cast<DeviceCallbackData*>(data);
          auto* gui = callback_data->gui;

          // Add to list and store
          gui->m_current_devices.push_back(callback_data->device);
          gui->addDeviceToList(callback_data->device); // Add directly instead of rebuilding

          // Log discovered device
          std::string device_log = "  Found: " + callback_data->device.device_name + " [" +
                                   callback_data->device.mac_address.toString() + "] " +
                                   callback_data->device.ip_address.toString();
          gui->addLogMessage(device_log);

          delete callback_data;
          return G_SOURCE_REMOVE;
        },
        device_data);
  };

  // Progress callback
  auto progress_callback = [gui](int percent, const std::string& message)
  {
    struct ProgressCallbackData
    {
      ProfinetDCPGUI* gui;
      int percent;
      std::string message;
    };

    auto* progress_data = new ProgressCallbackData{gui, percent, message};
    g_idle_add(
        [](gpointer data) -> gboolean
        {
          auto* callback_data = static_cast<ProgressCallbackData*>(data);
          auto* gui = callback_data->gui;

          double progress = callback_data->percent / 100.0;
          gui->updateProgress(progress, callback_data->message);

          delete callback_data;
          return G_SOURCE_REMOVE;
        },
        progress_data);
  };

  // Complete callback
  auto complete_callback = [gui, button](DCPResult result, const std::string& message)
  {
    // Use g_idle_add to safely update GUI from background thread
    struct CompleteData
    {
      ProfinetDCPGUI* gui;
      GtkButton* button;
      DCPResult result;
      std::string message;
    };

    auto* complete_data = new CompleteData{gui, button, result, message};

    g_idle_add(
        [](gpointer data) -> gboolean
        {
          auto* complete_info = static_cast<CompleteData*>(data);
          auto* gui = complete_info->gui;
          auto* button = complete_info->button;

          gui->m_discovery_in_progress = false;
          gtk_widget_set_sensitive(GTK_WIDGET(button), TRUE);
          gtk_widget_set_sensitive(gui->m_device_tree_view, TRUE);

          // Hide progress bar
          gui->hideProgress();

          if (complete_info->result == DCPResult::Success)
          {
            std::string summary =
                "Discovery complete - found " + std::to_string(gui->m_current_devices.size()) + " devices";
            gui->addLogMessageWithTimestamp(summary);
          }
          else
          {
            std::string error_msg = "Discovery failed: " + complete_info->message;
            gui->addLogMessageWithTimestamp(error_msg);

            GTKUtils::showErrorDialog(gui->m_parent_window, "Discovery Error",
                                      "Failed to discover devices: " + complete_info->message);
          }

          // Update topology button state after discovery completes
          gui->updateTopologyButtonState();

          // Refresh DCP device coloring based on configured devices
          gui->refreshDCPDeviceColoring();

          // Refresh tree view layout
          gtk_tree_view_columns_autosize(GTK_TREE_VIEW(gui->m_device_tree_view));

          // Refresh scrolled window and tree view
          GtkWidget* scrolled_parent = gtk_widget_get_parent(gui->m_device_tree_view);
          if (scrolled_parent)
          {
            gtk_widget_queue_resize(scrolled_parent);
            gtk_widget_queue_draw(scrolled_parent);
          }

          gtk_widget_queue_resize(gui->m_device_tree_view);
          gtk_widget_queue_draw(gui->m_device_tree_view);

          delete complete_info;
          return G_SOURCE_REMOVE;
        },
        complete_data);
  };

  // Start async discovery with real-time callbacks
  gui->m_dcp_tool->discoverDevicesAsync(device_callback, complete_callback, progress_callback,
                                        std::chrono::milliseconds(7000));
}

void ProfinetDCPGUI::onTopologyClicked(GtkButton* button, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);

  if (!gui->m_is_connected)
  {
    GTKUtils::showErrorDialog(gui->m_parent_window, "Error", "Please connect to a network interface first");
    return;
  }

  if (gui->m_current_devices.empty())
  {
    GTKUtils::showErrorDialog(gui->m_parent_window, "No Devices",
                              "Please discover devices first to show topology");
    return;
  }

  gui->addLogMessageWithTimestamp("Opening network topology visualization");

  // Create and show topology window
  auto topology_window =
      std::make_unique<NetworkTopologyWindow>(gui->m_parent_window, gui->m_current_devices);
  topology_window->show();

  // Keep window alive - it will manage its own lifecycle
  topology_window.release();
}

void ProfinetDCPGUI::onDeviceSelectionChanged(GtkTreeSelection* selection, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);

  // Clear configured device selection when DCP device is selected
  gtk_tree_selection_unselect_all(gui->m_configured_device_selection);

  DCPDeviceInfo* device = gui->getSelectedDevice();
  if (device)
  {
    // Device selection logging removed as requested
  }
  gui->updateDeviceDetails(device);

  // Ensure header layout
  gtk_tree_view_columns_autosize(GTK_TREE_VIEW(gui->m_device_tree_view));
}

void ProfinetDCPGUI::onDeviceDoubleClick(GtkTreeView* tree_view, GtkTreePath* path, GtkTreeViewColumn* column,
                                         gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);

  DCPDeviceInfo* device = gui->getSelectedDevice();
  if (device)
  {
    // Open config dialog
    DeviceConfigDialog dialog(gui->m_parent_window, *device);
    dialog.setDCPTool(gui->m_dcp_tool.get());
    dialog.show();
  }
}

void ProfinetDCPGUI::onConfiguredDeviceSelectionChanged(GtkTreeSelection* selection, gpointer data)
{
  auto* gui = static_cast<ProfinetDCPGUI*>(data);
  
  // Clear DCP device selection when configured device is selected
  gtk_tree_selection_unselect_all(gui->m_device_selection);
}

gboolean ProfinetDCPGUI::onDeviceRightClick(GtkWidget* widget, GdkEventButton* event, gpointer data)
{
  if (event->type == GDK_BUTTON_PRESS && event->button == 3)
  {
    auto* gui = static_cast<ProfinetDCPGUI*>(data);

    // Select row under cursor
    GtkTreePath* path;
    if (gtk_tree_view_get_path_at_pos(GTK_TREE_VIEW(widget), event->x, event->y, &path, nullptr, nullptr,
                                      nullptr))
    {
      gtk_tree_selection_select_path(gui->m_device_selection, path);
      gtk_tree_path_free(path);
    }

    DCPDeviceInfo* device = gui->getSelectedDevice();
    if (device)
    {
      gui->showDeviceContextMenu(event, device);
    }

    return TRUE;
  }
  return FALSE;
}

// Static callback function for main widget realize signal
static void onMainWidgetRealized(GtkWidget* widget, gpointer data)
{
  auto* vpaned = static_cast<GtkWidget*>(g_object_get_data(G_OBJECT(widget), "vpaned"));
  auto* hpaned = static_cast<GtkWidget*>(g_object_get_data(G_OBJECT(widget), "hpaned"));

  if (vpaned && hpaned)
  {
    // Set horizontal position to 60% for device list, 40% for details
    int width = gtk_widget_get_allocated_width(hpaned);
    gtk_paned_set_position(GTK_PANED(hpaned), (int)(width * 0.6));

    // Set vertical position to 70% for main area, 30% for log
    int height = gtk_widget_get_allocated_height(vpaned);
    gtk_paned_set_position(GTK_PANED(vpaned), (int)(height * 0.70));
  }
}

// Static callback functions for context menu
static void onMenuConfigureActivate(GtkMenuItem* item, gpointer data)
{
  auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(data);
  ProfinetDCP::DCPDeviceInfo* device = gui->getSelectedDevice();
  if (device)
  {
    gui->addLogMessageWithTimestamp("Opening configuration dialog for device: " + device->device_name);
    ProfinetDCP::DeviceConfigDialog dialog(gui->getParentWindow(), *device);
    dialog.setDCPTool(gui->getDCPTool());
    dialog.show();
  }
}

static void onMenuCopyMacActivate(GtkMenuItem* item, gpointer data)
{
  // Check if we have a DCPDeviceInfo object (for discovered devices)
  auto* info = static_cast<const ProfinetDCP::DCPDeviceInfo*>(g_object_get_data(G_OBJECT(item), "device"));
  if (info)
  {
    auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(g_object_get_data(G_OBJECT(item), "gui"));
    GtkClipboard* clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
    gtk_clipboard_set_text(clipboard, info->mac_address.toString().c_str(), -1);
    if (gui)
    {
      gui->addLogMessageWithTimestamp("Copied MAC address: " + info->mac_address.toString());
    }
  }
  else
  {
    // Check if we have a simple text string (for configured devices)
    const char* text = static_cast<const char*>(g_object_get_data(G_OBJECT(item), "text"));
    if (text)
    {
      GtkClipboard* clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
      gtk_clipboard_set_text(clipboard, text, -1);
    }
  }
}

static void onMenuCopyIpActivate(GtkMenuItem* item, gpointer data)
{
  // Check if we have a DCPDeviceInfo object (for discovered devices)
  auto* info = static_cast<const ProfinetDCP::DCPDeviceInfo*>(g_object_get_data(G_OBJECT(item), "device"));
  if (info)
  {
    auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(g_object_get_data(G_OBJECT(item), "gui"));
    GtkClipboard* clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
    gtk_clipboard_set_text(clipboard, info->ip_address.toString().c_str(), -1);
    if (gui)
    {
      gui->addLogMessageWithTimestamp("Copied IP address: " + info->ip_address.toString());
    }
  }
  else
  {
    // Check if we have a simple text string (for configured devices)
    const char* text = static_cast<const char*>(g_object_get_data(G_OBJECT(item), "text"));
    if (text)
    {
      GtkClipboard* clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
      gtk_clipboard_set_text(clipboard, text, -1);
    }
  }
}

static void onMenuCopyTextActivate(GtkMenuItem* item, gpointer data)
{
  const char* text = static_cast<const char*>(g_object_get_data(G_OBJECT(item), "text"));
  if (text)
  {
    GtkClipboard* clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
    gtk_clipboard_set_text(clipboard, text, -1);
  }
}

static void onMenuCopyNameActivate(GtkMenuItem* item, gpointer data)
{
  auto* info = static_cast<const ProfinetDCP::DCPDeviceInfo*>(g_object_get_data(G_OBJECT(item), "device"));
  auto* gui = static_cast<ProfinetDCP::ProfinetDCPGUI*>(g_object_get_data(G_OBJECT(item), "gui"));
  if (info)
  {
    GtkClipboard* clipboard = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
    gtk_clipboard_set_text(clipboard, info->device_name.c_str(), -1);
    if (gui)
    {
      gui->addLogMessageWithTimestamp("Copied device name: " + info->device_name);
    }
  }
}

void ProfinetDCPGUI::showDeviceContextMenu(GdkEventButton* event, const DCPDeviceInfo* device)
{
  GtkWidget* menu = gtk_menu_new();

  GtkWidget* configure_item = gtk_menu_item_new_with_label("Configure...");
  g_signal_connect(configure_item, "activate", G_CALLBACK(onMenuConfigureActivate), this);
  gtk_menu_shell_append(GTK_MENU_SHELL(menu), configure_item);

  GtkWidget* separator = gtk_separator_menu_item_new();
  gtk_menu_shell_append(GTK_MENU_SHELL(menu), separator);

  GtkWidget* copy_mac_item = gtk_menu_item_new_with_label("Copy MAC Address");
  g_signal_connect(copy_mac_item, "activate", G_CALLBACK(onMenuCopyMacActivate), nullptr);
  g_object_set_data(G_OBJECT(copy_mac_item), "device", const_cast<DCPDeviceInfo*>(device));
  g_object_set_data(G_OBJECT(copy_mac_item), "gui", this);
  gtk_menu_shell_append(GTK_MENU_SHELL(menu), copy_mac_item);

  GtkWidget* copy_ip_item = gtk_menu_item_new_with_label("Copy IP Address");
  g_signal_connect(copy_ip_item, "activate", G_CALLBACK(onMenuCopyIpActivate), nullptr);
  g_object_set_data(G_OBJECT(copy_ip_item), "device", const_cast<DCPDeviceInfo*>(device));
  g_object_set_data(G_OBJECT(copy_ip_item), "gui", this);
  gtk_menu_shell_append(GTK_MENU_SHELL(menu), copy_ip_item);

  GtkWidget* copy_name_item = gtk_menu_item_new_with_label("Copy Device Name");
  g_signal_connect(copy_name_item, "activate", G_CALLBACK(onMenuCopyNameActivate), nullptr);
  g_object_set_data(G_OBJECT(copy_name_item), "device", const_cast<DCPDeviceInfo*>(device));
  g_object_set_data(G_OBJECT(copy_name_item), "gui", this);
  gtk_menu_shell_append(GTK_MENU_SHELL(menu), copy_name_item);

  gtk_widget_show_all(menu);
  gtk_menu_popup_at_pointer(GTK_MENU(menu), reinterpret_cast<GdkEvent*>(event));
}

gboolean ProfinetDCPGUI::onConfiguredDeviceRightClick(GtkWidget* widget, GdkEventButton* event, gpointer data)
{
  if (event->type == GDK_BUTTON_PRESS && event->button == 3)
  {
    auto* gui = static_cast<ProfinetDCPGUI*>(data);

    // Select row under cursor
    GtkTreePath* path;
    if (gtk_tree_view_get_path_at_pos(GTK_TREE_VIEW(widget), event->x, event->y, &path, nullptr, nullptr,
                                      nullptr))
    {
      gtk_tree_selection_select_path(gui->m_configured_device_selection, path);
      gtk_tree_path_free(path);

      // Get the selected item
      GtkTreeIter iter;
      if (gtk_tree_selection_get_selected(gui->m_configured_device_selection, nullptr, &iter))
      {
        gui->showConfiguredDeviceContextMenu(event, &iter);
      }
    }
    return TRUE;
  }
  return FALSE;
}

void ProfinetDCPGUI::showConfiguredDeviceContextMenu(GdkEventButton* event, GtkTreeIter* iter)
{
  GtkWidget* menu = gtk_menu_new();

  // Get device data from the tree model
  char* mac_address;
  char* ip_address;
  char* device_name;
  char* device_type;
  char* vendor_id;

  gtk_tree_model_get(GTK_TREE_MODEL(m_configured_device_list_store), iter,
                     COL_MAC_ADDRESS, &mac_address,
                     COL_IP_ADDRESS, &ip_address,
                     COL_DEVICE_NAME, &device_name,
                     COL_DEVICE_ID, &device_type,
                     COL_VENDOR, &vendor_id,
                     -1);

  // Copy MAC Address menu item
  if (mac_address && strlen(mac_address) > 0) {
    GtkWidget* copy_mac_item = gtk_menu_item_new_with_label("Copy MAC Address");
    g_signal_connect(copy_mac_item, "activate", G_CALLBACK(onMenuCopyMacActivate), nullptr);
    g_object_set_data_full(G_OBJECT(copy_mac_item), "text", g_strdup(mac_address), g_free);
    gtk_menu_shell_append(GTK_MENU_SHELL(menu), copy_mac_item);
  }

  // Copy IP Address menu item
  if (ip_address && strlen(ip_address) > 0) {
    GtkWidget* copy_ip_item = gtk_menu_item_new_with_label("Copy IP Address");
    g_signal_connect(copy_ip_item, "activate", G_CALLBACK(onMenuCopyIpActivate), nullptr);
    g_object_set_data_full(G_OBJECT(copy_ip_item), "text", g_strdup(ip_address), g_free);
    gtk_menu_shell_append(GTK_MENU_SHELL(menu), copy_ip_item);
  }

  // Copy Device Name menu item
  if (device_name && strlen(device_name) > 0) {
    GtkWidget* copy_name_item = gtk_menu_item_new_with_label("Copy Device Name");
    g_signal_connect(copy_name_item, "activate", G_CALLBACK(onMenuCopyTextActivate), nullptr);
    g_object_set_data_full(G_OBJECT(copy_name_item), "text", g_strdup(device_name), g_free);
    gtk_menu_shell_append(GTK_MENU_SHELL(menu), copy_name_item);
  }

  // Free the strings
  g_free(mac_address);
  g_free(ip_address);
  g_free(device_name);
  g_free(device_type);
  g_free(vendor_id);

  gtk_widget_show_all(menu);
  gtk_menu_popup_at_pointer(GTK_MENU(menu), reinterpret_cast<GdkEvent*>(event));
}

void ProfinetDCPGUI::addDeviceToList(const DCPDeviceInfo& device)
{
  GTKUtils::addDeviceToStore(m_device_list_store, device);
}

void ProfinetDCPGUI::clearDeviceList() { gtk_list_store_clear(m_device_list_store); }

// Configured device list management

void ProfinetDCPGUI::loadConfiguredDevices()
{
  std::string interface_name = getSelectedInterface();
  if (interface_name.empty()) {
    clearConfiguredDeviceList();
    return;
  }

  clearConfiguredDeviceList();

  if (m_configured_device_reader->loadConfiguredDevices(interface_name)) {
    populateConfiguredDeviceList();
  }
}

void ProfinetDCPGUI::populateConfiguredDeviceList()
{
  if (!m_configured_device_reader->hasLoadedDevices()) {
    return;
  }

  const pugi::xml_document& doc = m_configured_device_reader->getXMLDocument();
  pugi::xml_node devices_node = doc.child("ProfinetDevices");
  
  if (!devices_node) {
    return;
  }

  for (pugi::xml_node device : devices_node.children("Device")) {
    GtkTreeIter iter;
    gtk_list_store_append(m_configured_device_list_store, &iter);
    
    // Get attributes from XML
    std::string name = device.attribute("name").as_string();
    std::string type = device.attribute("type").as_string();
    std::string ip_address = device.attribute("ip_address").as_string();
    std::string mac_address = device.attribute("mac_address").as_string();
    
    // Read vendor_id and device_id as integers directly from XML
    uint16_t vendor_id = device.attribute("vendor_id").as_uint();
    uint16_t device_id = device.attribute("device_id").as_uint();
    
    // Use the same conversion functions as the DCP device list
    std::string vendor_text = ProfinetDCPTool::vendorIdToString(vendor_id);
    std::string device_text = ProfinetDCPTool::deviceIdToString(vendor_id, device_id);

    // Set values in the list store
    gtk_list_store_set(m_configured_device_list_store, &iter,
                       COL_MAC_ADDRESS, mac_address.c_str(),
                       COL_DEVICE_NAME, name.c_str(),
                       COL_IP_ADDRESS, ip_address.c_str(),
                       COL_VENDOR, vendor_text.c_str(),
                       COL_DEVICE_ID, device_text.c_str(),
                       COL_DEVICE_PTR, nullptr, // Could store xml_node if needed later
                       -1);
  }
}

void ProfinetDCPGUI::clearConfiguredDeviceList() 
{ 
  gtk_list_store_clear(m_configured_device_list_store); 
}

bool ProfinetDCPGUI::isDeviceConfigured(const std::string& device_name) const
{
  if (!m_configured_device_reader || !m_configured_device_reader->hasLoadedDevices()) {
    return false;
  }

  const pugi::xml_document& doc = m_configured_device_reader->getXMLDocument();
  pugi::xml_node devices_node = doc.child("ProfinetDevices");
  
  if (!devices_node) {
    return false;
  }

  // Search for device name in configured devices
  for (pugi::xml_node device : devices_node.children("Device")) {
    std::string configured_name = device.attribute("name").as_string();
    if (configured_name == device_name) {
      return true;
    }
  }
  
  return false;
}

std::string ProfinetDCPGUI::getConfiguredDeviceIP(const std::string& device_name) const
{
  if (!m_configured_device_reader || !m_configured_device_reader->hasLoadedDevices()) {
    return "";
  }

  const pugi::xml_document& doc = m_configured_device_reader->getXMLDocument();
  pugi::xml_node devices_node = doc.child("ProfinetDevices");
  
  if (!devices_node) {
    return "";
  }

  // Search for device name and return its IP address
  for (pugi::xml_node device : devices_node.children("Device")) {
    std::string configured_name = device.attribute("name").as_string();
    if (configured_name == device_name) {
      return device.attribute("ip_address").as_string();
    }
  }
  
  return "";
}

void ProfinetDCPGUI::refreshDCPDeviceColoring()
{
  if (m_device_tree_view) {
    // Force tree view to redraw with updated coloring
    gtk_widget_queue_draw(m_device_tree_view);
  }
}

void ProfinetDCPGUI::syncSelectionToConfiguredList(const std::string& device_name)
{
  if (!m_configured_device_list_store || !m_configured_device_selection) {
    return;
  }
  
  // Temporarily block the selection changed signal to avoid infinite recursion
  g_signal_handlers_block_by_func(m_configured_device_selection, (gpointer)onConfiguredDeviceSelectionChangedForSync, this);
  
  // Find matching device in configured list
  GtkTreeIter iter;
  gboolean valid = gtk_tree_model_get_iter_first(GTK_TREE_MODEL(m_configured_device_list_store), &iter);
  
  while (valid) {
    char* configured_name = nullptr;
    gtk_tree_model_get(GTK_TREE_MODEL(m_configured_device_list_store), &iter, COL_DEVICE_NAME, &configured_name, -1);
    
    if (configured_name && device_name == configured_name) {
      gtk_tree_selection_select_iter(m_configured_device_selection, &iter);
      g_free(configured_name);
      break;
    }
    
    g_free(configured_name);
    valid = gtk_tree_model_iter_next(GTK_TREE_MODEL(m_configured_device_list_store), &iter);
  }
  
  // Unblock the signal
  g_signal_handlers_unblock_by_func(m_configured_device_selection, (gpointer)onConfiguredDeviceSelectionChangedForSync, this);
}

void ProfinetDCPGUI::syncSelectionToDCPList(const std::string& device_name)
{
  if (!m_device_list_store || !m_device_selection) {
    return;
  }
  
  // Temporarily block the selection changed signal to avoid infinite recursion
  g_signal_handlers_block_by_func(m_device_selection, (gpointer)onDCPDeviceSelectionChangedForSync, this);
  
  // Find matching device in DCP list
  GtkTreeIter iter;
  gboolean valid = gtk_tree_model_get_iter_first(GTK_TREE_MODEL(m_device_list_store), &iter);
  
  while (valid) {
    char* dcp_name = nullptr;
    gtk_tree_model_get(GTK_TREE_MODEL(m_device_list_store), &iter, COL_DEVICE_NAME, &dcp_name, -1);
    
    if (dcp_name && device_name == dcp_name) {
      gtk_tree_selection_select_iter(m_device_selection, &iter);
      g_free(dcp_name);
      break;
    }
    
    g_free(dcp_name);
    valid = gtk_tree_model_iter_next(GTK_TREE_MODEL(m_device_list_store), &iter);
  }
  
  // Unblock the signal
  g_signal_handlers_unblock_by_func(m_device_selection, (gpointer)onDCPDeviceSelectionChangedForSync, this);
}

DCPDeviceInfo* ProfinetDCPGUI::getSelectedDevice()
{
  GtkTreeIter iter;
  if (gtk_tree_selection_get_selected(m_device_selection, nullptr, &iter))
  {
    char* mac_str;
    gtk_tree_model_get(GTK_TREE_MODEL(m_device_list_store), &iter, COL_MAC_ADDRESS, &mac_str, -1);

    if (mac_str)
    {
      MacAddress mac;
      bool valid_mac = mac.fromString(mac_str);
      g_free(mac_str); // Free immediately after use

      if (valid_mac)
      {
        // Find in current devices
        auto it = std::find_if(m_current_devices.begin(), m_current_devices.end(),
                               [&mac](const DCPDeviceInfo& info) { return info.mac_address == mac; });
        if (it != m_current_devices.end())
        {
          return &(*it);
        }
      }
    }
  }
  return nullptr;
}

// Helper function to create left-aligned labels
static GtkWidget* createLeftAlignedLabel(const char* text)
{
  GtkWidget* label = gtk_label_new(text);
  gtk_widget_set_halign(label, GTK_ALIGN_START);
  gtk_label_set_selectable(GTK_LABEL(label), TRUE); // Make it selectable for copying
  return label;
}

// Helper function to create right-aligned labels
static GtkWidget* createRightAlignedLabel(const char* text)
{
  GtkWidget* label = gtk_label_new(text);
  gtk_widget_set_halign(label, GTK_ALIGN_END);
  // gtk_label_set_selectable(GTK_LABEL(label), TRUE); // Make it selectable for copying
  return label;
}

void ProfinetDCPGUI::updateDeviceDetails(const DCPDeviceInfo* device)
{
  // Clear existing content
  GList* children = gtk_container_get_children(GTK_CONTAINER(m_details_container));
  for (GList* iter = children; iter != NULL; iter = g_list_next(iter))
  {
    gtk_widget_destroy(GTK_WIDGET(iter->data));
  }
  g_list_free(children);

  if (!device)
  {
    GtkWidget* empty_label = gtk_label_new("Select a device to view details");
    gtk_container_add(GTK_CONTAINER(m_details_container), empty_label);
    gtk_widget_show_all(m_details_container);
    return;
  }

  // Create general info page
  GtkWidget* info_grid = gtk_grid_new();
  gtk_grid_set_row_spacing(GTK_GRID(info_grid), 6);
  gtk_grid_set_column_spacing(GTK_GRID(info_grid), 12);
  gtk_style_context_add_class(gtk_widget_get_style_context(info_grid), "info-grid");

  int row = 0;

  // MAC Address
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("MAC Address:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid), createLeftAlignedLabel(device->mac_address.toString().c_str()), 1,
                  row++, 1, 1);

  // Device Name
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Device Name:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid), createLeftAlignedLabel(device->device_name.c_str()), 1, row++, 1, 1);

  // IP Address
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("IP Address:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid), createLeftAlignedLabel(device->ip_address.toString().c_str()), 1,
                  row++, 1, 1);

  // Subnet Mask
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Subnet Mask:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid), createLeftAlignedLabel(device->subnet_mask.toString().c_str()), 1,
                  row++, 1, 1);

  // Gateway
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Gateway:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid), createLeftAlignedLabel(device->default_gateway.toString().c_str()), 1,
                  row++, 1, 1);

  // Vendor
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Vendor:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid),
                  createLeftAlignedLabel(ProfinetDCPTool::vendorIdWithHexToString(device->vendor_id).c_str()),
                  1, row++, 1, 1);

  // Device ID
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Device ID:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid),
                  createLeftAlignedLabel(
                      ProfinetDCPTool::deviceIdWithHexToString(device->vendor_id, device->device_id).c_str()),
                  1, row++, 1, 1);

  // Device Type
  if (!device->type_of_station.empty())
  {
    gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Device Type:"), 0, row, 1, 1);
    gtk_grid_attach(GTK_GRID(info_grid), createLeftAlignedLabel(device->type_of_station.c_str()), 1, row++, 1,
                    1);
  }

  // Device Description (from XML)
  if (device->vendor_id != 0 && device->device_id != 0)
  {
    std::string device_name, device_type, device_description;
    ProfinetDCPTool::getDeviceInfo(device->vendor_id, device->device_id, device_name, device_type,
                                   device_description);
    if (!device_description.empty())
    {
      // Label for "Description:"
      gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Description:"), 0, row, 1, 1);

      // Multi-line wrapping label for description text
      GtkWidget* desc_text = gtk_label_new(device_description.c_str());
      gtk_widget_set_halign(desc_text, GTK_ALIGN_START);
      gtk_widget_set_hexpand(desc_text, FALSE);
      gtk_label_set_selectable(GTK_LABEL(desc_text), TRUE);
      gtk_label_set_line_wrap(GTK_LABEL(desc_text), TRUE);
      gtk_label_set_line_wrap_mode(GTK_LABEL(desc_text), PANGO_WRAP_WORD);
      gtk_label_set_max_width_chars(GTK_LABEL(desc_text), 40);
      gtk_label_set_xalign(GTK_LABEL(desc_text), 0.0); // Align text to left edge
      gtk_grid_attach(GTK_GRID(info_grid), desc_text, 1, row++, 1, 1);
    }
  }

  // Device Role
  gtk_grid_attach(GTK_GRID(info_grid), createRightAlignedLabel("Device Role:"), 0, row, 1, 1);
  gtk_grid_attach(GTK_GRID(info_grid),
                  createLeftAlignedLabel(ProfinetDCPTool::deviceRoleToString(device->device_role).c_str()), 1,
                  row++, 1, 1);

  // Add the info grid directly to the container (no tabs)
  gtk_container_add(GTK_CONTAINER(m_details_container), info_grid);

  // Show the content
  gtk_widget_show_all(m_details_container);
}

// DeviceConfigDialog implementation
DeviceConfigDialog::DeviceConfigDialog(GtkWidget* parent, const DCPDeviceInfo& device)
    : m_parent_window(parent), m_dialog(nullptr), m_dcp_tool(nullptr), m_current_device(device),
      m_name_entry(nullptr), m_mac_label(nullptr), m_vendor_label(nullptr), m_device_id_label(nullptr),
      m_role_label(nullptr), m_ip_entry(nullptr), m_subnet_entry(nullptr), m_gateway_entry(nullptr),
      m_identify_button(nullptr), m_reset_button(nullptr), m_save_config_button(nullptr),
      m_status_label(nullptr), m_progress_bar(nullptr)
{
  // Get DCP tool instance from main window
  if (g_main_window)
  {
    m_dcp_tool = g_main_window->getDCPTool();
  }
}

DeviceConfigDialog::~DeviceConfigDialog()
{
  if (m_dialog && GTK_IS_WIDGET(m_dialog))
  {
    gtk_widget_destroy(m_dialog);
    m_dialog = nullptr;
  }
}

void DeviceConfigDialog::show()
{
  m_dialog = gtk_dialog_new_with_buttons("PROFINET Device Configuration", GTK_WINDOW(m_parent_window),
                                         GTK_DIALOG_MODAL, "_Close", GTK_RESPONSE_CANCEL, "_Apply",
                                         GTK_RESPONSE_APPLY, nullptr);

  gtk_window_set_default_size(GTK_WINDOW(m_dialog), 500, 400);
  gtk_window_set_resizable(GTK_WINDOW(m_dialog), FALSE);

  // Add CSS style classes to m_dialog buttons
  GtkWidget* apply_button = gtk_dialog_get_widget_for_response(GTK_DIALOG(m_dialog), GTK_RESPONSE_APPLY);
  if (apply_button)
  {
    gtk_style_context_add_class(gtk_widget_get_style_context(apply_button), "dialog-apply-button");
  }

  // Create main content area
  GtkWidget* content = gtk_dialog_get_content_area(GTK_DIALOG(m_dialog));
  GtkWidget* notebook = gtk_notebook_new();
  gtk_container_add(GTK_CONTAINER(content), notebook);

  // Create tabs
  createGeneralTab(notebook);
  createNetworkTab(notebook);
  createAdvancedTab(notebook);

  // Connect signals
  g_signal_connect(m_dialog, "response", G_CALLBACK(onDialogResponse), this);

  gtk_widget_show_all(m_dialog);

  gtk_dialog_run(GTK_DIALOG(m_dialog));

  // Safely destroy dialog
  if (m_dialog && GTK_IS_WIDGET(m_dialog))
  {
    gtk_widget_destroy(m_dialog);
  }
  m_dialog = nullptr;
}

void DeviceConfigDialog::createGeneralTab(GtkWidget* notebook)
{
  GtkWidget* grid = gtk_grid_new();
  gtk_grid_set_row_spacing(GTK_GRID(grid), 10);
  gtk_grid_set_column_spacing(GTK_GRID(grid), 10);
  gtk_style_context_add_class(gtk_widget_get_style_context(grid), "m_dialog-grid");

  int row = 0;

  // Device Name
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("Device Name:"), 0, row, 1, 1);
  m_name_entry = gtk_entry_new();
  gtk_entry_set_text(GTK_ENTRY(m_name_entry), m_current_device.device_name.c_str());
  gtk_grid_attach(GTK_GRID(grid), m_name_entry, 1, row++, 1, 1);

  // MAC Address (read-only)
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("MAC Address:"), 0, row, 1, 1);
  m_mac_label = gtk_label_new(m_current_device.mac_address.toString().c_str());
  gtk_widget_set_halign(m_mac_label, GTK_ALIGN_START);
  gtk_grid_attach(GTK_GRID(grid), m_mac_label, 1, row++, 1, 1);

  // Vendor
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("Vendor:"), 0, row, 1, 1);
  m_vendor_label = gtk_label_new(ProfinetDCPTool::vendorIdToString(m_current_device.vendor_id).c_str());
  gtk_widget_set_halign(m_vendor_label, GTK_ALIGN_START);
  gtk_grid_attach(GTK_GRID(grid), m_vendor_label, 1, row++, 1, 1);

  // Device Type
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("Device Type:"), 0, row, 1, 1);
  m_device_id_label = gtk_label_new(
      ProfinetDCPTool::deviceIdToString(m_current_device.vendor_id, m_current_device.device_id).c_str());
  gtk_widget_set_halign(m_device_id_label, GTK_ALIGN_START);
  gtk_grid_attach(GTK_GRID(grid), m_device_id_label, 1, row++, 1, 1);

  gtk_notebook_append_page(GTK_NOTEBOOK(notebook), grid, gtk_label_new("General"));
}

void DeviceConfigDialog::createNetworkTab(GtkWidget* notebook)
{
  GtkWidget* grid = gtk_grid_new();
  gtk_grid_set_row_spacing(GTK_GRID(grid), 10);
  gtk_grid_set_column_spacing(GTK_GRID(grid), 10);
  gtk_style_context_add_class(gtk_widget_get_style_context(grid), "m_dialog-grid");

  int row = 0;

  // IP Address
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("IP Address:"), 0, row, 1, 1);
  m_ip_entry = gtk_entry_new();
  gtk_entry_set_text(GTK_ENTRY(m_ip_entry), m_current_device.ip_address.toString().c_str());
  gtk_grid_attach(GTK_GRID(grid), m_ip_entry, 1, row++, 1, 1);

  // Subnet Mask
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("Subnet Mask:"), 0, row, 1, 1);
  m_subnet_entry = gtk_entry_new();
  gtk_entry_set_text(GTK_ENTRY(m_subnet_entry), m_current_device.subnet_mask.toString().c_str());
  gtk_grid_attach(GTK_GRID(grid), m_subnet_entry, 1, row++, 1, 1);

  // Gateway
  gtk_grid_attach(GTK_GRID(grid), createRightAlignedLabel("Default Gateway:"), 0, row, 1, 1);
  m_gateway_entry = gtk_entry_new();
  gtk_entry_set_text(GTK_ENTRY(m_gateway_entry), m_current_device.default_gateway.toString().c_str());
  gtk_grid_attach(GTK_GRID(grid), m_gateway_entry, 1, row++, 1, 1);

  gtk_notebook_append_page(GTK_NOTEBOOK(notebook), grid, gtk_label_new("Network"));
}

void DeviceConfigDialog::createAdvancedTab(GtkWidget* notebook)
{
  GtkWidget* vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 10);
  gtk_style_context_add_class(gtk_widget_get_style_context(vbox), "m_dialog-content");

  // Blink LED button
  GtkWidget* blink_button = gtk_button_new_with_label("Blink Device LED");
  g_signal_connect(blink_button, "clicked", G_CALLBACK(onBlinkLEDClicked), this);
  gtk_box_pack_start(GTK_BOX(vbox), blink_button, FALSE, FALSE, 0);

  // Reset to factory button
  m_reset_button = gtk_button_new_with_label("Reset to Factory Defaults");
  g_signal_connect(m_reset_button, "clicked", G_CALLBACK(onResetClicked), this);
  gtk_box_pack_start(GTK_BOX(vbox), m_reset_button, FALSE, FALSE, 0);

  // Status area
  GtkWidget* status_frame = gtk_frame_new("Status");
  m_status_label = gtk_label_new("Ready");
  gtk_container_add(GTK_CONTAINER(status_frame), m_status_label);
  gtk_box_pack_start(GTK_BOX(vbox), status_frame, FALSE, FALSE, 0);

  gtk_notebook_append_page(GTK_NOTEBOOK(notebook), vbox, gtk_label_new("Advanced"));
}

void DeviceConfigDialog::onDialogResponse(GtkDialog* dialog, gint response_id, gpointer data)
{
  auto* config_dialog = static_cast<DeviceConfigDialog*>(data);

  switch (response_id)
  {
  case GTK_RESPONSE_APPLY:
    config_dialog->applyConfiguration();
    break;
  case GTK_RESPONSE_CANCEL:
  default:
    // Dialog will be destroyed by show() method, just break
    break;
  }
}

void DeviceConfigDialog::applyConfiguration()
{
  if (!m_dcp_tool)
  {
    GTKUtils::showErrorDialog(m_parent_window, "Error", "No DCP tool available");
    return;
  }

  // Get values from entries
  std::string new_name = GTKUtils::getEntryText(GTK_ENTRY(m_name_entry));
  std::string new_ip = GTKUtils::getEntryText(GTK_ENTRY(m_ip_entry));
  std::string new_subnet = GTKUtils::getEntryText(GTK_ENTRY(m_subnet_entry));
  std::string new_gateway = GTKUtils::getEntryText(GTK_ENTRY(m_gateway_entry));

  // Validate inputs
  IPAddress ip, subnet, gateway;
  if (!ip.fromString(new_ip) || !subnet.fromString(new_subnet) || !gateway.fromString(new_gateway))
  {
    GTKUtils::showErrorDialog(m_parent_window, "Invalid Input", "Please enter valid IP addresses");
    return;
  }

  gtk_label_set_text(GTK_LABEL(m_status_label), "Applying configuration...");

  // Apply device name if changed
  if (new_name != m_current_device.device_name)
  {
    if (g_main_window)
    {
      g_main_window->addLogMessage("Changing device name from '" + m_current_device.device_name + "' to '" +
                                   new_name + "' for device [" + m_current_device.ip_address.toString() +
                                   "]");
    }
    auto result = m_dcp_tool->setDeviceName(m_current_device.mac_address, new_name);
    if (result == DCPResult::Success)
    {
      if (g_main_window)
      {
        g_main_window->addLogMessage("✓ Device name change successful for device [" +
                                     m_current_device.ip_address.toString() + "]");
      }
    }
    else
    {
      if (g_main_window)
      {
        g_main_window->addLogMessage("✗ Device name change failed for device [" +
                                     m_current_device.ip_address.toString() + "] - " +
                                     ProfinetDCPTool::dcpResultToString(result));
      }
      GTKUtils::showErrorDialog(m_parent_window, "Error",
                                "Failed to set device name: " + ProfinetDCPTool::dcpResultToString(result));
      return;
    }
  }

  // Apply IP configuration if changed
  if (ip.addr != m_current_device.ip_address.addr || subnet.addr != m_current_device.subnet_mask.addr ||
      gateway.addr != m_current_device.default_gateway.addr)
  {
    if (g_main_window)
    {
      g_main_window->addLogMessage("Changing IP configuration for device '" + m_current_device.device_name +
                                   "' from [IP: " + m_current_device.ip_address.toString() +
                                   ", Subnet: " + m_current_device.subnet_mask.toString() + ", GW: " +
                                   m_current_device.default_gateway.toString() + "] to [IP: " + new_ip +
                                   ", Subnet: " + new_subnet + ", GW: " + new_gateway + "]");
    }
    auto result = m_dcp_tool->setIPConfiguration(m_current_device.mac_address, ip, subnet, gateway);
    if (result == DCPResult::Success)
    {
      if (g_main_window)
      {
        g_main_window->addLogMessage("✓ IP configuration change successful for device '" +
                                     m_current_device.device_name + "'");
      }
    }
    else
    {
      if (g_main_window)
      {
        g_main_window->addLogMessage("✗ IP configuration change failed for device '" +
                                     m_current_device.device_name + "' - " +
                                     ProfinetDCPTool::dcpResultToString(result));
      }
      GTKUtils::showErrorDialog(m_parent_window, "Error",
                                "Failed to set IP configuration: " +
                                    ProfinetDCPTool::dcpResultToString(result));
      return;
    }
  }

  gtk_label_set_text(GTK_LABEL(m_status_label), "Configuration applied successfully");
  // Success is logged to activity log, no need for dialog
}

void DeviceConfigDialog::blinkLED()
{
  if (!m_dcp_tool)
  {
    GTKUtils::showErrorDialog(m_parent_window, "Error", "No DCP tool available");
    return;
  }

  if (g_main_window)
  {
    g_main_window->addLogMessage("Blinking LED for device: " + m_current_device.device_name + " [" +
                                 m_current_device.ip_address.toString() + "]");
  }

  gtk_label_set_text(GTK_LABEL(m_status_label), "Blinking device LED...");

  auto result = m_dcp_tool->blinkLED(m_current_device.mac_address);
  if (result == DCPResult::Success)
  {
    if (g_main_window)
    {
      g_main_window->addLogMessage("✓ LED blink command successful for device: " +
                                   m_current_device.device_name);
    }
    gtk_label_set_text(GTK_LABEL(m_status_label), "LED blink command sent");
    // Success is logged to activity log, no need for dialog
  }
  else
  {
    if (g_main_window)
    {
      g_main_window->addLogMessage("✗ LED blink command failed for device: " + m_current_device.device_name +
                                   " - " + ProfinetDCPTool::dcpResultToString(result));
    }
    gtk_label_set_text(GTK_LABEL(m_status_label), "LED blink failed");
    GTKUtils::showErrorDialog(m_parent_window, "Error",
                              "Failed to blink LED: " + ProfinetDCPTool::dcpResultToString(result));
  }
}

void DeviceConfigDialog::resetToFactory()
{
  if (!m_dcp_tool)
  {
    GTKUtils::showErrorDialog(m_parent_window, "Error", "No DCP tool available");
    return;
  }

  // Create factory reset selection dialog
  GtkWidget* selection_dialog =
      gtk_dialog_new_with_buttons("Factory Reset Selection", GTK_WINDOW(m_dialog), GTK_DIALOG_MODAL, "_Close",
                                  GTK_RESPONSE_CANCEL, "_Reset", GTK_RESPONSE_ACCEPT, nullptr);

  if (!selection_dialog)
  {
    GTKUtils::showErrorDialog(m_parent_window, "Error", "Failed to create factory reset m_dialog");
    return;
  }

  // Add CSS style class to reset button (destructive action)
  GtkWidget* reset_accept_button =
      gtk_dialog_get_widget_for_response(GTK_DIALOG(selection_dialog), GTK_RESPONSE_ACCEPT);
  if (reset_accept_button)
  {
    gtk_style_context_add_class(gtk_widget_get_style_context(reset_accept_button), "destructive-action");
  }

  GtkWidget* content_area = gtk_dialog_get_content_area(GTK_DIALOG(selection_dialog));
  gtk_style_context_add_class(gtk_widget_get_style_context(content_area), "m_dialog-main-content");

  // Warning label
  GtkWidget* warning_label = gtk_label_new(nullptr);
  gtk_label_set_markup(
      GTK_LABEL(warning_label),
      "<span weight=\"bold\" foreground=\"red\">WARNING: This will reset the device!</span>\n"
      "Choose the appropriate reset mode for your needs:");
  gtk_label_set_line_wrap(GTK_LABEL(warning_label), TRUE);
  gtk_widget_set_margin_bottom(warning_label, 12);
  gtk_box_pack_start(GTK_BOX(content_area), warning_label, FALSE, FALSE, 0);

  // Create radio buttons for reset modes
  GSList* radio_group = nullptr;
  GtkWidget* radio_buttons[6];

  // Create first radio button (establishes the group)
  radio_buttons[0] = gtk_radio_button_new_with_label(
      nullptr, "Application Data - Reset application parameters only (least disruptive)");
  radio_group = gtk_radio_button_get_group(GTK_RADIO_BUTTON(radio_buttons[0]));

  // Create remaining buttons and add them to the same group
  radio_buttons[1] = gtk_radio_button_new_with_label(
      radio_group, "Communication - Reset IP address and communication settings (most common)");
  radio_group = gtk_radio_button_get_group(GTK_RADIO_BUTTON(radio_buttons[1]));

  radio_buttons[2] =
      gtk_radio_button_new_with_label(radio_group, "Engineering - Reset engineering/configuration data");
  radio_group = gtk_radio_button_get_group(GTK_RADIO_BUTTON(radio_buttons[2]));

  radio_buttons[3] =
      gtk_radio_button_new_with_label(radio_group, "All Data - Reset all configuration data (comprehensive)");
  radio_group = gtk_radio_button_get_group(GTK_RADIO_BUTTON(radio_buttons[3]));

  radio_buttons[4] = gtk_radio_button_new_with_label(
      radio_group, "Device - Full device reset including firmware settings (device restart)");
  radio_group = gtk_radio_button_get_group(GTK_RADIO_BUTTON(radio_buttons[4]));

  radio_buttons[5] = gtk_radio_button_new_with_label(
      radio_group, "Reset and Restore - Complete reset with restore capability (maximum reset)");

  // Set Communication as default (most common case)
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(radio_buttons[1]), TRUE);

  // Add radio buttons to dialog
  for (int i = 0; i < 6; i++)
  {
    gtk_widget_set_margin_start(radio_buttons[i], 12);
    gtk_widget_set_margin_bottom(radio_buttons[i], 4);
    gtk_box_pack_start(GTK_BOX(content_area), radio_buttons[i], FALSE, FALSE, 0);
  }

  // Add informational label
  GtkWidget* info_label =
      gtk_label_new("\nNote: Switch/infrastructure device resets may cause temporary network disconnection.\n"
                    "Recovery times vary: Light resets (5s), Device resets (15-20s).");
  gtk_label_set_line_wrap(GTK_LABEL(info_label), TRUE);
  gtk_widget_set_margin_top(info_label, 12);
  gtk_box_pack_start(GTK_BOX(content_area), info_label, FALSE, FALSE, 0);

  gtk_widget_show_all(content_area);

  gint response = gtk_dialog_run(GTK_DIALOG(selection_dialog));

  // Determine which reset mode was selected before destroying dialog
  int selected_mode = 1; // default to Communication
  if (response == GTK_RESPONSE_ACCEPT)
  {
    for (int i = 0; i < 6; i++)
    {
      if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(radio_buttons[i])))
      {
        selected_mode = i;
        break;
      }
    }
  }

  // Always destroy the m_dialog before proceeding
  gtk_widget_destroy(selection_dialog);

  // Check if user cancelled
  if (response != GTK_RESPONSE_ACCEPT)
  {
    return;
  }

  // Show final confirmation with specific reset type
  std::string reset_type_names[] = {"Application Data", "Communication", "Engineering",
                                    "All Data",         "Device",        "Reset and Restore"};

  std::string confirm_message =
      "Are you sure you want to perform a \"" + reset_type_names[selected_mode] + "\" factory reset?\n\n";

  if (selected_mode >= 3) // All Data, Device, or Reset and Restore
  {
    confirm_message += "⚠️  This is a comprehensive reset that may require significant reconfiguration!\n";
  }

  if (selected_mode >= 4) // Device or Reset and Restore
  {
    confirm_message += "⚠️  This will restart the device and may cause network disruption!\n";
  }

  GtkWidget* final_confirm =
      gtk_message_dialog_new(GTK_WINDOW(m_dialog), GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_YES_NO,
                             "%s", confirm_message.c_str());

  if (!final_confirm)
  {
    GTKUtils::showErrorDialog(m_parent_window, "Error", "Failed to create confirmation m_dialog");
    return;
  }

  gint final_response = gtk_dialog_run(GTK_DIALOG(final_confirm));
  gtk_widget_destroy(final_confirm);

  if (final_response != GTK_RESPONSE_YES)
    return;

  // Log factory reset action
  if (g_main_window)
  {
    g_main_window->addLogMessage("Performing " + reset_type_names[selected_mode] +
                                 " factory reset for device: " + m_current_device.device_name + " [" +
                                 m_current_device.ip_address.toString() + "]");
  }

  // Perform the selected factory reset
  gtk_label_set_text(GTK_LABEL(m_status_label),
                     ("Performing " + reset_type_names[selected_mode] + " factory reset...").c_str());

  DCPResult result;
  switch (selected_mode)
  {
  case 0:
    result = m_dcp_tool->resetApplicationData(m_current_device.mac_address);
    break;
  case 1:
    result = m_dcp_tool->resetCommunication(m_current_device.mac_address);
    break;
  case 2:
    result = m_dcp_tool->resetEngineering(m_current_device.mac_address);
    break;
  case 3:
    result = m_dcp_tool->resetAllData(m_current_device.mac_address);
    break;
  case 4:
    result = m_dcp_tool->resetDevice(m_current_device.mac_address);
    break;
  case 5:
    result = m_dcp_tool->resetAndRestore(m_current_device.mac_address);
    break;
  default:
    result = m_dcp_tool->resetCommunication(m_current_device.mac_address);
  }

  if (result == DCPResult::Success)
  {
    if (g_main_window)
    {
      g_main_window->addLogMessage("✓ " + reset_type_names[selected_mode] +
                                   " factory reset successful for device: " + m_current_device.device_name);
    }
    gtk_label_set_text(GTK_LABEL(m_status_label), "Factory reset completed successfully");

    // Success is logged to activity log, no need for dialog
  }
  else
  {
    if (g_main_window)
    {
      g_main_window->addLogMessage("✗ " + reset_type_names[selected_mode] +
                                   " factory reset failed for device: " + m_current_device.device_name +
                                   " - " + ProfinetDCPTool::dcpResultToString(result));
    }

    gtk_label_set_text(GTK_LABEL(m_status_label), "Factory reset failed");

    std::string error_message = "Failed to perform " + reset_type_names[selected_mode] +
                                " factory reset: " + ProfinetDCPTool::dcpResultToString(result);

    if (result == DCPResult::NetworkError)
    {
      error_message +=
          "\n\nThis may be due to network interface issues (e.g., switch restart causing interface down).";
    }

    GTKUtils::showErrorDialog(m_parent_window, "Factory Reset Failed", error_message);
  }
}

void DeviceConfigDialog::onBlinkLEDClicked(GtkButton* button, gpointer data)
{
  auto* config_dialog = static_cast<DeviceConfigDialog*>(data);
  config_dialog->blinkLED();
}

void DeviceConfigDialog::onResetClicked(GtkButton* button, gpointer data)
{
  auto* config_dialog = static_cast<DeviceConfigDialog*>(data);
  config_dialog->resetToFactory();
}

// AboutDialog stub
void AboutDialog::show(GtkWidget* parent)
{
  gtk_show_about_dialog(GTK_WINDOW(parent), "program-name", "PROFINET DCP Tool", "version", "1.0.0",
                        "copyright", "Copyright © 2024 SSAB EMEA AB", "comments",
                        "PROFINET Discovery and Configuration Protocol Tool for ProviewR", "website",
                        "https://www.proview.se", "logo-icon-name", "network-workgroup", nullptr);
}

} // namespace ProfinetDCP