/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2024 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#pragma once

#include <gtk/gtk.h>
#include <memory>
#include <string>
#include <vector>
#include <chrono>

#include "../src/pn_dcp_tool.h"
#include "../src/configured_devices.h"

namespace ProfinetDCP
{

// Forward declarations
class ProfinetDCPGUI;

// Main window
class ProfinetDCPWindow
{
public:
  ProfinetDCPWindow();
  ~ProfinetDCPWindow();

  bool create();
  void show();
  void run() const;

  GtkWidget* getWidget() { return m_main_window; }
  ProfinetDCPTool* getDCPTool() const;
  void addLogMessage(const std::string& message);

private:
  GtkWidget* m_main_window;
  std::unique_ptr<ProfinetDCPGUI> m_gui_controller;

  // Window management
  static gboolean onDeleteEvent(GtkWidget* widget, GdkEvent* event, gpointer data);
  static void onDestroy(GtkWidget* widget, gpointer data);
};

// GUI controller
class ProfinetDCPGUI
{
public:
  explicit ProfinetDCPGUI(GtkWidget* parent_window);
  ~ProfinetDCPGUI();

  bool initialize();
  void shutdown();

  GtkWidget* createMainWidget();

  // Public accessors for callback functions
  DCPDeviceInfo* getSelectedDevice();
  GtkWidget* getParentWindow() const { return m_parent_window; }
  ProfinetDCPTool* getDCPTool() const { return m_dcp_tool.get(); }

private:
  GtkWidget* m_parent_window;
  GtkWidget* m_main_widget;

  // Main UI components
  GtkWidget* m_toolbar;
  GtkWidget* m_interface_combo;
  GtkWidget* m_connect_button;
  GtkWidget* m_disconnect_button;
  GtkWidget* m_discover_button;
  GtkWidget* m_topology_button;

  // Device list
  GtkWidget* m_device_tree_view;
  GtkListStore* m_device_list_store;
  GtkTreeSelection* m_device_selection;

  // Configured device list
  GtkWidget* m_configured_device_tree_view;
  GtkListStore* m_configured_device_list_store;
  GtkTreeSelection* m_configured_device_selection;

  // Device details panel
  GtkWidget* m_details_frame;
  GtkWidget* m_details_container;

  // Status bar and log
  GtkWidget* m_status_bar;
  guint m_status_context_id;

  // Text log and progress
  GtkWidget* m_log_text_view;
  GtkTextBuffer* m_log_buffer;
  GtkWidget* m_progress_bar;
  GtkWidget* m_log_scrolled_window;

  // DCP Tool instance
  std::unique_ptr<ProfinetDCPTool> m_dcp_tool;
  bool m_is_connected;
  bool m_discovery_in_progress;

  // Configured device reader
  std::unique_ptr<ConfiguredDeviceReader> m_configured_device_reader;

  // Device tracking
  std::vector<DCPDeviceInfo> m_current_devices;
  std::chrono::steady_clock::time_point m_last_discovery;

public:
  // UI Creation methods
  GtkWidget* createToolbar();
  GtkWidget* createDeviceList();
  GtkWidget* createConfiguredDeviceList();
  GtkWidget* createDetailsPanel();
  GtkWidget* createStatusBar();
  GtkWidget* createLogAndProgressPanel();

  // Log and progress management
  void addLogMessage(const std::string& message);
  void addLogMessageWithTimestamp(const std::string& message);
  void scrollLogToBottom();
  void updateProgress(double fraction, const std::string& text = "");
  void hideProgress();
  void showProgress();

  // Device list management
  void addDeviceToList(const DCPDeviceInfo& device);
  void clearDeviceList();
  GtkTreeIter* findDeviceInList(const MacAddress& mac);

  // Configured device list management
  void loadConfiguredDevices();
  void populateConfiguredDeviceList();
  void clearConfiguredDeviceList();

  // Device details
  void updateDeviceDetails(const DCPDeviceInfo* device);
  void clearDeviceDetails();

  // Status management
  void updateStatus(const std::string& message);
  void updateConnectionStatus();
  void updateTopologyButtonState();

  // Event handlers
  static void onInterfaceChanged(GtkComboBox* combo, gpointer data);
  static void onConnectClicked(GtkButton* button, gpointer data);
  static void onDisconnectClicked(GtkButton* button, gpointer data);
  static void onDiscoverClicked(GtkButton* button, gpointer data);
  static void onTopologyClicked(GtkButton* button, gpointer data);
  static void onDeviceSelectionChanged(GtkTreeSelection* selection, gpointer data);
  static void onDeviceDoubleClick(GtkTreeView* tree_view, GtkTreePath* path, GtkTreeViewColumn* column,
                                  gpointer data);
  static void onConfiguredDeviceSelectionChanged(GtkTreeSelection* selection, gpointer data);

  // Context menu
  static gboolean onDeviceRightClick(GtkWidget* widget, GdkEventButton* event, gpointer data);
  void showDeviceContextMenu(GdkEventButton* event, const DCPDeviceInfo* device);
  static gboolean onConfiguredDeviceRightClick(GtkWidget* widget, GdkEventButton* event, gpointer data);
  void showConfiguredDeviceContextMenu(GdkEventButton* event, GtkTreeIter* iter);

  // Helper methods
  void populateInterfaceCombo();
  std::string getSelectedInterface();

  // Async operation tracking
  struct PendingOperation
  {
    std::string description;
    MacAddress target_device;
    std::chrono::steady_clock::time_point start_time;
  };

  std::vector<PendingOperation> m_pending_operations;

  void addPendingOperation(const std::string& desc, const MacAddress& mac);
  void removePendingOperation(const MacAddress& mac);
  void updatePendingOperations();
};

// Device config dialog
class DeviceConfigDialog
{
public:
  DeviceConfigDialog(GtkWidget* parent, const DCPDeviceInfo& device);
  ~DeviceConfigDialog();

  void show();
  void setDCPTool(ProfinetDCPTool* tool) { m_dcp_tool = tool; }

private:
  GtkWidget* m_parent_window;
  GtkWidget* m_dialog;

  ProfinetDCPTool* m_dcp_tool;
  DCPDeviceInfo m_current_device;

  // General tab widgets
  GtkWidget* m_name_entry;
  GtkWidget* m_mac_label;
  GtkWidget* m_vendor_label;
  GtkWidget* m_device_id_label;
  GtkWidget* m_role_label;

  // IP Configuration tab widgets
  GtkWidget* m_ip_entry;
  GtkWidget* m_subnet_entry;
  GtkWidget* m_gateway_entry;

  // Actions tab widgets
  GtkWidget* m_identify_button;
  GtkWidget* m_reset_button;
  GtkWidget* m_save_config_button;

  // Status widgets
  GtkWidget* m_status_label;
  GtkWidget* m_progress_bar;

  void createGeneralTab(GtkWidget* notebook);
  void createNetworkTab(GtkWidget* notebook);
  void createAdvancedTab(GtkWidget* notebook);

  // Event handlers
  static void onDialogResponse(GtkDialog* dialog, gint response_id, gpointer data);
  static void onBlinkLEDClicked(GtkButton* button, gpointer data);
  static void onResetClicked(GtkButton* button, gpointer data);

  // Helper methods
  void applyConfiguration();
  void blinkLED();
  void resetToFactory();
};

// About dialog
class AboutDialog
{
public:
  static void show(GtkWidget* parent);

private:
  static void onResponse(GtkDialog* dialog, gint response_id, gpointer data);
};

// GTK utility functions
namespace GTKUtils
{
// String conversion helpers
std::string getEntryText(GtkEntry* entry);

// List store helpers
void addDeviceToStore(GtkListStore* store, const DCPDeviceInfo& device);
void updateDeviceInStore(GtkListStore* store, GtkTreeIter* iter, const DCPDeviceInfo& device);

// Error dialogs
void showErrorDialog(GtkWidget* parent, const std::string& title, const std::string& message);

// Threading helpers (GTK is not thread-safe)
void executeInMainThread(std::function<void()> func);
} // namespace GTKUtils

// Device list columns
enum DeviceListColumns
{
  COL_MAC_ADDRESS = 0,
  COL_DEVICE_NAME,
  COL_IP_ADDRESS,
  COL_VENDOR,
  COL_DEVICE_ID,
  COL_DEVICE_PTR, // Hidden column storing DCPDeviceInfo*
  NUM_COLUMNS
};

// Context menu items
enum ContextMenuItems
{
  MENU_CONFIGURE = 1,
  MENU_IDENTIFY,
  MENU_RESET,
  MENU_SAVE_CONFIG,
  MENU_SEPARATOR,
  MENU_COPY_MAC,
  MENU_COPY_IP
};

} // namespace ProfinetDCP