#!/bin/bash
#
set -e
# Added by build.sh :
# ver=""
# pwre_target=""
#
echo "Here in postinst..."
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/pwrtest -a -d /usr/share/doc/pwrtest ]; then
                ln -sf ../share/doc/pwrtest /usr/doc/pwrtest
        fi
fi
# End automatically added section

aroot="/usr/pwrp/adm"
export pwra_db=$aroot/db

echo "Change owner of files to pwrp"
chown -R pwrp:pwrp /usr/pwrp/pwrdemo$ver

# Register volume
if [ -e $aroot/db/pwr_volumelist.dat ]; then
  set +e
  ptst=`eval grep "'\bVolPwrDemo\b'" $aroot/db/pwr_volumelist.dat | grep "\bpwrdemo\b"`
  set -e
  if [ "$ptst" = "" ]; then
    echo "	 VolPwrDemo 0.254.254.200 pwrdemo" >> $aroot/db/pwr_volumelist.dat
  fi
fi

# Insert base in projectlist
if [ -e $aroot/db/pwr_projectlist.dat ]; then
  set +e
  ptst=`eval grep "'\bpwrdemo$ver\b'" $aroot/db/pwr_projectlist.dat`
  set -e
  if [ "$ptst" = "" ]; then
    echo "pwrdemo$ver V${ver:0:1}.${ver:1:1} /usr/pwrp/pwrdemo$ver pwrdemo$ver \"\" " >> $aroot/db/pwr_projectlist.dat
  fi
fi

# Insert nodename in DirectoryVolume and create bootfile
nodename=`eval uname -n`
initsh=/tmp/pwrdemo_init.sh
initpwrc=/tmp/pwrdemo_init.pwr_com

# Create a shellscript that attaches to projects and runs wb_cmd
cat > $initsh <<EOF
#!/bin/bash

source $aroot/db/pwr_setup.sh
source \$pwr_exe/pwrp_env.sh set project pwrdemo$ver

wb_cmd @$initpwrc
EOF

chmod a+x $initsh

# Create a wb_cmd script that inserts nodename and creates bootfile
cat > $initpwrc <<EOF
  set attr/name=Bus999-DemoNode/attr=NodeName/value="$nodename"/noconf
  save
  create boot/node=DemoNode
  exit
EOF

# Execute shellscript
sudo -u pwrp $initsh

rm $initsh
rm $initpwrc

cp /usr/pwr$ver/$pwre_target/exp/web/* /usr/pwrp/pwrdemo$ver/bld/common/web/

if [ -e /home/pwrp/Desktop ]; then
  cp /usr/pwrp/pwrdemo$ver/cnf/proviewdemo$ver.desktop /home/pwrp/Desktop/
  chown pwrp:pwrp /home/pwrp/Desktop/proviewdemo$ver.desktop
  chmod a+x /home/pwrp/Desktop/proviewdemo$ver.desktop
fi

#
# Add pwrdemo web directories to Apache
#
if [ -e /etc/apache2/apache2.conf ]; then
  if ! egrep -q "Alias[ ]+/pwrdemo/" /etc/apache2/apache2.conf; then
    cat >> /etc/apache2/apache2.conf <<-EOF

	#
	# Proview alias pwrdemo, added by ProviewR installation
	#
	Alias /pwrdemo/ /usr/pwrp/pwrdemo$ver/bld/common/web/

	<Directory /usr/pwrp/pwrdemo$ver/bld/common/web>
	    AllowOverride None
	    Require all granted
	</Directory>
EOF
  fi
fi

# Add directories to nginx
if [ -e /etc/nginx/sites-available/default ]; then
  if ! egrep -q "location /pwrpdemo/" /etc/nginx/sites-available/default; then
    awk -v ver=$ver '
BEGIN {
  inserver = 0;
  done = 0;
}
{
  if ( !done) {
    if ( substr( $0, 1, 1) != "#") {
      if ( $0 == "server {") {
        inserver = 1;
      }
      if ( inserver) {
        if ( $0 == "}") {
          printf("        # Pwrdemo directory\n");
          printf("        location /pwrdemo/ {\n");
          printf("          alias /usr/pwrp/pwrdemo%s/bld/common/web/;\n", ver);
          printf("        }\n");
          printf("}\n");

          inserver = 0;
          done = 1;
        }
        else
          printf( "%s\n", $0);
      }
      else
        printf( "%s\n", $0);
    }
    else
      printf( "%s\n", $0);
  }
  else
    printf( "%s\n", $0);
}' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default.new

    cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old
    mv /etc/nginx/sites-available/default.new /etc/nginx/sites-available/default
    if [ -e /etc/nginx/sites-enabled/default ]; then
      rm -f /etc/nginx/sites-enabled/default
    fi
    ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
  fi
fi



