/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#if defined PWRE_CONF_RDKAFKA

#include "pwr.h"
#include "pwr_baseclasses.h"
#include "rt_gdh.h"
#include "rt_gdh_msg.h"
#include "co_cdh.h"
#include "export_rtdb_avro.h"
#include "export_rtdb_gdh.h"

const bool MAKE_VALUES_OPTIONAL = true;

// This function converts from latin1 encoding to utf8
static std::string to_utf8(char* s)
{
  std::string res = "";
  std::string str(s);
  for (int i = 0; i < str.size(); i++)
  {
    unsigned char in = str[i];
    if (in < 128)
    {
      res += in;
    }
    else
    {
      res += 0xc2 + (in > 0xbf);
      res += (in & 0x3f) + 0x80;
    }
  }
  return res;
}

template <typename T> T attr_to_val(pwr_sAttrRef* aref, void* val)
{
  T a;
  a = *(T*)val;
  return a;
}

int encode_val(AvroEncoder& enc, pwr_eType type_id, bool is_ptr, pwr_sAttrRef* aref, void* val)
{
  // Check if this is an array
  if (aref && aref->Flags.b.Array)
  {
    int element_count = get_array_element_count(aref, type_id);
    if (element_count > 0)
    {
      if (MAKE_VALUES_OPTIONAL)
      {
        enc.encodeUnionIndex(1); // Select non-null union branch
      }

      enc.setItemCount(element_count);

      // Encode each array element
      int element_size = aref->Size / element_count;
      uint8_t* array_ptr = (uint8_t*)val;

      for (int i = 0; i < element_count; i++)
      {
        void* element_ptr = array_ptr + (i * element_size);

        // Recursively encode each element (without array flag)
        pwr_sAttrRef element_aref = *aref;
        element_aref.Flags.b.Array = 0;
        element_aref.Size = element_size;

        pwr_tStatus sts = encode_val(enc, type_id, is_ptr, &element_aref, element_ptr);
        if (EVEN(sts))
          return sts;
      }

      enc.arrayEnd();
      return GDH__SUCCESS;
    }
  }

  if (MAKE_VALUES_OPTIONAL && type_id < pwr_eType_Void)
  {
    enc.encodeUnionIndex(1);
  }
  switch (type_id)
  {
  case pwr_eType_Boolean:
  {
    pwr_tBoolean a = attr_to_val<pwr_tBoolean>(aref, val);
    enc.encodeBool(a ? true : false);
    break;
  }
  case pwr_eType_Float32:
  {
    enc.encodeFloat(attr_to_val<pwr_tFloat32>(aref, val));
    break;
  }
  case pwr_eType_Float64:
  {
    enc.encodeDouble(attr_to_val<pwr_tFloat64>(aref, val));
    break;
  }
  case pwr_eType_Char:
  {
    enc.encodeInt(attr_to_val<pwr_tChar>(aref, val));
    break;
  }
  case pwr_eType_Int8:
  {
    enc.encodeInt(attr_to_val<pwr_tInt8>(aref, val));
    break;
  }
  case pwr_eType_Int16:
  {
    enc.encodeInt(attr_to_val<pwr_tInt16>(aref, val));
    break;
  }
  case pwr_eType_Int32:
  {
    enc.encodeInt(attr_to_val<pwr_tInt32>(aref, val));
    break;
  }
  case pwr_eType_Int64:
  {
    enc.encodeLong(attr_to_val<pwr_tInt64>(aref, val));
    break;
  }
  case pwr_eType_UInt8:
  {
    enc.encodeInt(attr_to_val<pwr_tUInt8>(aref, val));
    break;
  }
  case pwr_eType_UInt16:
  {
    enc.encodeInt(attr_to_val<pwr_tUInt16>(aref, val));
    break;
  }
  case pwr_eType_UInt32:
  case pwr_eType_Mask:
  case pwr_eType_DisableAttr:
  case pwr_eType_Enum:
  case pwr_eType_NetStatus:
  case pwr_eType_Status:
  {
    enc.encodeInt(attr_to_val<pwr_tUInt32>(aref, val));
    break;
  }
  case pwr_eType_UInt64:
  {
    enc.encodeLong(attr_to_val<pwr_tUInt64>(aref, val));
    break;
  }
  case pwr_eType_String:
  {
    pwr_tString80 a;
    strcpy(a, *(pwr_tString80*)val);
    a[79] = 0;
    enc.encodeString(to_utf8(a));
    break;
  }
  case pwr_eType_Text:
  {
    pwr_tString256 a;
    strcpy(a, *(pwr_tText*)val);
    pwr_tString256 str;
    char* s;
    char* t;
    for (s = (char*)a, t = str; *s != 10 && *s != 0; s++, t++)
    {
      *t = *s;
    }
    *t = 0;
    str[255] = 0;
    enc.encodeString(to_utf8(str));
    break;
  }
  case pwr_eType_Objid:
  {
    pwr_tObjid a = attr_to_val<pwr_tObjid>(aref, val);
    enc.encodeBytes((uint8_t*)&a, sizeof(a));
    break;
  }
  case pwr_eType_AttrRef:
  {
    pwr_sAttrRef attrref;
    attrref = *(pwr_sAttrRef*)val;
    enc.encodeBytes((uint8_t*)&attrref, sizeof(attrref));
    break;
  }
  case pwr_eType_DataRef:
  {
    pwr_tDataRef dataref;
    dataref = *(pwr_tDataRef*)val;
    enc.encodeBytes((uint8_t*)&dataref, sizeof(dataref));
    break;
  }
  case pwr_eType_Time:
  {
    pwr_tTime a = attr_to_val<pwr_tTime>(aref, val);
    uint8_t tmp[sizeof(a.tv_sec) + sizeof(a.tv_nsec)];
    for (int i = 0; i < sizeof(a.tv_sec); i++)
    {
      tmp[i] = ((a.tv_sec >> (8 * i)) & 0xFF);
    }
    for (int i = 0; i < sizeof(a.tv_nsec); i++)
    {
      tmp[i + sizeof(a.tv_sec)] = ((a.tv_nsec >> (8 * i)) & 0xFF);
    }
    enc.encodeBytes(tmp, sizeof(a.tv_sec) + sizeof(a.tv_nsec));
    break;
  }
  case pwr_eType_DeltaTime:
  {
    pwr_tDeltaTime a = attr_to_val<pwr_tDeltaTime>(aref, val);
    uint8_t tmp[sizeof(a.tv_sec) + sizeof(a.tv_nsec)];
    for (int i = 0; i < sizeof(a.tv_sec); i++)
    {
      tmp[i] = ((a.tv_sec >> (8 * i)) & 0xFF);
    }
    for (int i = 0; i < sizeof(a.tv_nsec); i++)
    {
      tmp[i + sizeof(a.tv_sec)] = ((a.tv_nsec >> (8 * i)) & 0xFF);
    }
    enc.encodeBytes(tmp, sizeof(a.tv_sec) + sizeof(a.tv_nsec));
    break;
  }
  case pwr_eType_ObjectIx:
  {
    pwr_tObjectIx a = attr_to_val<pwr_tObjectIx>(aref, val);
    enc.encodeBytes((uint8_t*)&a, sizeof(a));
    break;
  }
  case pwr_eType_ClassId:
  {
    pwr_tClassId a = attr_to_val<pwr_tClassId>(aref, val);
    enc.encodeBytes((uint8_t*)&a, sizeof(a));
    break;
  }
  case pwr_eType_TypeId:
  case pwr_eType_CastId:
  {
    pwr_tTypeId a = attr_to_val<pwr_tTypeId>(aref, val);
    enc.encodeBytes((uint8_t*)&a, sizeof(a));
    break;
  }
  case pwr_eType_VolumeId:
  {
    pwr_tVolumeId a = attr_to_val<pwr_tVolumeId>(aref, val);
    enc.encodeBytes((uint8_t*)&a, sizeof(a));
    break;
  }
  case pwr_eType_RefId:
  {
    pwr_tSubid a = attr_to_val<pwr_tSubid>(aref, val);
    enc.encodeBytes((uint8_t*)&a, sizeof(a));
    break;
  }
  default:
    fprintf(stderr, "Not handling type %d\n", type_id);
    return GDH__CONVERT;
  }
  return GDH__SUCCESS;
}

// Get array element count based on aref Size and element type size
int get_array_element_count(pwr_sAttrRef* aref, pwr_eType element_type)
{
  if (!aref || !(aref->Flags.b.Array))
    return 0;

  int element_size = 0;
  switch (element_type)
  {
  case pwr_eType_Boolean:
  case pwr_eType_Int8:
  case pwr_eType_UInt8:
  case pwr_eType_Char:
    element_size = 1;
    break;
  case pwr_eType_Int16:
  case pwr_eType_UInt16:
    element_size = 2;
    break;
  case pwr_eType_Int32:
  case pwr_eType_UInt32:
  case pwr_eType_Float32:
  case pwr_eType_Enum:
  case pwr_eType_Mask:
  case pwr_eType_Status:
  case pwr_eType_NetStatus:
  case pwr_eType_DisableAttr:
    element_size = 4;
    break;
  case pwr_eType_Int64:
  case pwr_eType_UInt64:
  case pwr_eType_Float64:
    element_size = 8;
    break;
  case pwr_eType_String:
    element_size = 80;
    break;
  case pwr_eType_Text:
    element_size = 256;
    break;
  case pwr_eType_Objid:
    element_size = sizeof(pwr_tObjid);
    break;
  case pwr_eType_AttrRef:
    element_size = sizeof(pwr_sAttrRef);
    break;
  case pwr_eType_Time:
  case pwr_eType_DeltaTime:
    element_size = sizeof(pwr_tTime);
    break;
  default:
    return 0;
  }

  return (element_size > 0) ? (aref->Size / element_size) : 0;
}

// Convert ProviewR type to cJSON Avro schema type object
cJSON* pwr_eType_to_json(pwr_eType tid, pwr_sAttrRef* aref)
{
  const char* base_type = NULL;

  switch (tid)
  {
  case pwr_eType_Boolean:
    base_type = "boolean";
    break;
  case pwr_eType_Float32:
    base_type = "float";
    break;
  case pwr_eType_Float64:
    base_type = "double";
    break;
  case pwr_eType_Char:
    base_type = "bytes";
    break;
  case pwr_eType_Int8:
  case pwr_eType_Int16:
  case pwr_eType_Int32:
  case pwr_eType_UInt8:
  case pwr_eType_UInt16:
  case pwr_eType_UInt32:
  case pwr_eType_Mask:
  case pwr_eType_DisableAttr:
  case pwr_eType_Enum:
  case pwr_eType_NetStatus:
  case pwr_eType_Status:
    base_type = "int";
    break;
  case pwr_eType_Int64:
  case pwr_eType_UInt64:
    base_type = "long";
    break;
  case pwr_eType_String:
  case pwr_eType_Text:
    base_type = "string";
    break;
  case pwr_eType_Objid:
  case pwr_eType_AttrRef:
  case pwr_eType_DataRef:
  case pwr_eType_ObjectIx:
  case pwr_eType_ClassId:
  case pwr_eType_TypeId:
  case pwr_eType_CastId:
  case pwr_eType_VolumeId:
  case pwr_eType_RefId:
  case pwr_eType_Time:
  case pwr_eType_DeltaTime:
    base_type = "bytes";
    break;
  default:
    return cJSON_CreateString("");
  }

  // Check if this is an array
  if (aref && aref->Flags.b.Array)
  {
    int element_count = get_array_element_count(aref, tid);
    if (element_count > 0)
    {
      // Create array type: {"type": "array", "items": <base_type>}
      cJSON* array_type = cJSON_CreateObject();
      cJSON_AddStringToObject(array_type, "type", "array");
      cJSON_AddStringToObject(array_type, "items", base_type);

      if (MAKE_VALUES_OPTIONAL)
      {
        // Return ["null", {array_type}]
        cJSON* union_array = cJSON_CreateArray();
        cJSON_AddItemToArray(union_array, cJSON_CreateString("null"));
        cJSON_AddItemToArray(union_array, array_type);
        return union_array;
      }
      return array_type;
    }
  }

  // Non-array type
  if (MAKE_VALUES_OPTIONAL)
  {
    // Return ["null", "base_type"]
    cJSON* union_array = cJSON_CreateArray();
    cJSON_AddItemToArray(union_array, cJSON_CreateString("null"));
    cJSON_AddItemToArray(union_array, cJSON_CreateString(base_type));
    return union_array;
  }

  return cJSON_CreateString(base_type);
}

#endif
