/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2026 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/* xtt_clog_gtk.cpp -- Console log in xtt */

#include <stdlib.h>

#include "pwr_baseclasses.h"

#include "co_cdh.h"
#include "co_log_severity.h"
#include "co_string.h"
#include "co_syi.h"
#include "co_time.h"

#include "rt_gdh.h"
#include "rt_xnav_msg.h"

#include "cow_wow_gtk.h"

#include "xtt_clog_gtk.h"
#include "xtt_clognav_gtk.h"

static gint delete_event(GtkWidget* w, GdkEvent* event, gpointer data)
{
  CLogGtk::activate_exit(w, data);
  return TRUE;
}

static void destroy_event(GtkWidget* w, gpointer data) {}

CLogGtk::CLogGtk(void* clog_parent_ctx, GtkWidget* clog_parent_wid, const char* clog_name,
                 pwr_tStatus* status)
    : CLog(clog_parent_ctx, clog_name, status), parent_wid(clog_parent_wid), clock_cursor(0)
{
  toplevel = (GtkWidget*)g_object_new(GTK_TYPE_WINDOW, "default-height", 800, "default-width", 1200, "title",
                                      CoWowGtk::translate_utf8(clog_name), NULL);

  g_signal_connect(toplevel, "delete_event", G_CALLBACK(delete_event), this);
  g_signal_connect(toplevel, "destroy", G_CALLBACK(destroy_event), this);
  g_signal_connect(toplevel, "focus-in-event", G_CALLBACK(action_inputfocus), this);

  CoWowGtk::SetWindowIcon(toplevel);

  GtkWidget* vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);

  // Menu
  // Accelerators
  GtkAccelGroup* accel_g = (GtkAccelGroup*)g_object_new(GTK_TYPE_ACCEL_GROUP, NULL);
  gtk_window_add_accel_group(GTK_WINDOW(toplevel), accel_g);

  GtkMenuBar* menu_bar = (GtkMenuBar*)g_object_new(GTK_TYPE_MENU_BAR, NULL);

  // File entry

  GtkWidget* file_select_file = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Select File"));
  g_signal_connect(file_select_file, "activate", G_CALLBACK(activate_select_file), this);

  GtkWidget* file_next_file = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Next File"));
  g_signal_connect(file_next_file, "activate", G_CALLBACK(activate_next_file), this);
  gtk_widget_add_accelerator(file_next_file, "activate", accel_g, 'n', GdkModifierType(GDK_CONTROL_MASK),
                             GTK_ACCEL_VISIBLE);

  GtkWidget* file_prev_file = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Previous File"));
  g_signal_connect(file_prev_file, "activate", G_CALLBACK(activate_prev_file), this);
  gtk_widget_add_accelerator(file_prev_file, "activate", accel_g, 'p', GdkModifierType(GDK_CONTROL_MASK),
                             GTK_ACCEL_VISIBLE);

  GtkWidget* file_update = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Update"));
  g_signal_connect(file_update, "activate", G_CALLBACK(activate_update), this);
  gtk_widget_add_accelerator(file_update, "activate", accel_g, 'u', GdkModifierType(GDK_CONTROL_MASK),
                             GTK_ACCEL_VISIBLE);

  GtkWidget* file_print = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Print"));
  g_signal_connect(file_print, "activate", G_CALLBACK(activate_print), this);

  GtkWidget* file_close = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Close"));
  g_signal_connect(file_close, "activate", G_CALLBACK(activate_exit), this);
  gtk_widget_add_accelerator(file_close, "activate", accel_g, 'w', GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  GtkMenu* file_menu = (GtkMenu*)g_object_new(GTK_TYPE_MENU, NULL);
  gtk_menu_shell_append(GTK_MENU_SHELL(file_menu), file_select_file);
  gtk_menu_shell_append(GTK_MENU_SHELL(file_menu), file_next_file);
  gtk_menu_shell_append(GTK_MENU_SHELL(file_menu), file_prev_file);
  gtk_menu_shell_append(GTK_MENU_SHELL(file_menu), file_update);
  gtk_menu_shell_append(GTK_MENU_SHELL(file_menu), file_print);
  gtk_menu_shell_append(GTK_MENU_SHELL(file_menu), file_close);

  GtkWidget* file = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_File"));
  gtk_menu_shell_append(GTK_MENU_SHELL(menu_bar), file);
  gtk_menu_item_set_submenu(GTK_MENU_ITEM(file), GTK_WIDGET(file_menu));

  // View menu
  GtkWidget* view_zoom_in = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("Zoom _In"));
  g_signal_connect(view_zoom_in, "activate", G_CALLBACK(activate_zoom_in), this);
  gtk_widget_add_accelerator(view_zoom_in, "activate", accel_g, 'i', GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  GtkWidget* view_zoom_out = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("Zoom _Out"));
  g_signal_connect(view_zoom_out, "activate", G_CALLBACK(activate_zoom_out), this);
  gtk_widget_add_accelerator(view_zoom_out, "activate", accel_g, 'o', GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  GtkWidget* view_zoom_reset = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("Zoom _Reset"));
  g_signal_connect(view_zoom_reset, "activate", G_CALLBACK(activate_zoom_reset), this);

  GtkMenu* view_menu = (GtkMenu*)g_object_new(GTK_TYPE_MENU, NULL);
  gtk_menu_shell_append(GTK_MENU_SHELL(view_menu), view_zoom_in);
  gtk_menu_shell_append(GTK_MENU_SHELL(view_menu), view_zoom_out);
  gtk_menu_shell_append(GTK_MENU_SHELL(view_menu), view_zoom_reset);

  GtkWidget* view = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_View"));
  gtk_menu_shell_append(GTK_MENU_SHELL(menu_bar), view);
  gtk_menu_item_set_submenu(GTK_MENU_ITEM(view), GTK_WIDGET(view_menu));

  // Menu Help
  GtkWidget* help_help =
      gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Help on System Messages"));
  g_signal_connect(help_help, "activate", G_CALLBACK(activate_help), this);
  gtk_widget_add_accelerator(help_help, "activate", accel_g, 'h', GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

  GtkWidget* help_msg =
      gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("Help on _Selected Message"));
  g_signal_connect(help_msg, "activate", G_CALLBACK(activate_helpmsg), this);

  GtkMenu* help_menu = (GtkMenu*)g_object_new(GTK_TYPE_MENU, NULL);
  gtk_menu_shell_append(GTK_MENU_SHELL(help_menu), help_help);
  gtk_menu_shell_append(GTK_MENU_SHELL(help_menu), help_msg);

  GtkWidget* help = gtk_menu_item_new_with_mnemonic(CoWowGtk::translate_utf8("_Help"));
  gtk_menu_shell_append(GTK_MENU_SHELL(menu_bar), help);
  gtk_menu_item_set_submenu(GTK_MENU_ITEM(help), GTK_WIDGET(help_menu));

  // Create toolbar with filtering controls
  toolbar = gtk_toolbar_new();
  gtk_toolbar_set_style(GTK_TOOLBAR(toolbar), GTK_TOOLBAR_BOTH_HORIZ);
  gtk_toolbar_set_icon_size(GTK_TOOLBAR(toolbar), GTK_ICON_SIZE_SMALL_TOOLBAR);

  // Text Filter Section
  GtkWidget* filter_label = gtk_label_new("Text Filter:");
  gtk_widget_set_margin_start(filter_label, 8);
  gtk_widget_set_margin_end(filter_label, 4);
  GtkToolItem* label_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(label_item), filter_label);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), label_item, -1);

  filter_entry = gtk_entry_new();
  gtk_entry_set_placeholder_text(GTK_ENTRY(filter_entry), "Search messages...");
  gtk_widget_set_size_request(filter_entry, 250, 32);
  gtk_widget_set_margin_end(filter_entry, 8);
  g_signal_connect(filter_entry, "activate", G_CALLBACK(toolbar_filter_entry_activate), this);
  GtkToolItem* entry_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(entry_item), filter_entry);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), entry_item, -1);

  // Checkboxes without separators or extra labels
  success_toggle = gtk_check_button_new_with_label("Success");
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(success_toggle), TRUE);
  gtk_widget_set_margin_start(success_toggle, 4);
  gtk_widget_set_margin_end(success_toggle, 4);
  GtkToolItem* success_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(success_item), success_toggle);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), success_item, -1);

  info_toggle = gtk_check_button_new_with_label("Info");
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(info_toggle), TRUE);
  gtk_widget_set_margin_start(info_toggle, 4);
  gtk_widget_set_margin_end(info_toggle, 4);
  GtkToolItem* info_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(info_item), info_toggle);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), info_item, -1);

  warning_toggle = gtk_check_button_new_with_label("Warning");
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(warning_toggle), TRUE);
  gtk_widget_set_margin_start(warning_toggle, 4);
  gtk_widget_set_margin_end(warning_toggle, 4);
  GtkToolItem* warning_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(warning_item), warning_toggle);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), warning_item, -1);

  error_toggle = gtk_check_button_new_with_label("Error");
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(error_toggle), TRUE);
  gtk_widget_set_margin_start(error_toggle, 4);
  gtk_widget_set_margin_end(error_toggle, 4);
  GtkToolItem* error_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(error_item), error_toggle);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), error_item, -1);

  fatal_toggle = gtk_check_button_new_with_label("Fatal");
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(fatal_toggle), TRUE);
  gtk_widget_set_margin_start(fatal_toggle, 4);
  gtk_widget_set_margin_end(fatal_toggle, 4);
  GtkToolItem* fatal_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(fatal_item), fatal_toggle);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), fatal_item, -1);

  text_toggle = gtk_check_button_new_with_label("Text");
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(text_toggle), TRUE);
  gtk_widget_set_margin_start(text_toggle, 4);
  gtk_widget_set_margin_end(text_toggle, 4);
  GtkToolItem* text_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(text_item), text_toggle);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), text_item, -1);

  // Clear button without separator
  GtkWidget* clear_button = gtk_button_new_with_label("Clear All");
  gtk_widget_set_size_request(clear_button, 80, 28);
  gtk_widget_set_margin_start(clear_button, 12);
  gtk_widget_set_margin_end(clear_button, 8);
  g_signal_connect(clear_button, "clicked", G_CALLBACK(toolbar_clear_filter), this);

  // Style the clear button to stand out
  GtkStyleContext* clear_context = gtk_widget_get_style_context(clear_button);
  gtk_style_context_add_class(clear_context, "destructive-action");

  GtkToolItem* clear_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(clear_item), clear_button);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), clear_item, -1); // Apply button
  GtkWidget* apply_button = gtk_button_new_with_label("Apply Filter");
  gtk_widget_set_size_request(apply_button, 100, 28);
  gtk_widget_set_margin_start(apply_button, 8);
  gtk_widget_set_margin_end(apply_button, 12);
  g_signal_connect(apply_button, "clicked", G_CALLBACK(toolbar_apply_filter), this);

  // Style the apply button as a primary action
  GtkStyleContext* apply_context = gtk_widget_get_style_context(apply_button);
  gtk_style_context_add_class(apply_context, "suggested-action");

  GtkToolItem* apply_item = gtk_tool_item_new();
  gtk_container_add(GTK_CONTAINER(apply_item), apply_button);
  gtk_toolbar_insert(GTK_TOOLBAR(toolbar), apply_item, -1);
  clognav = new CLogNavGtk(this, vbox, &clognav_widget);

  // Initialize toolbar with current filter settings
  bool success, info, warning, error, fatal, text;
  clognav->get_filter(&success, &info, &warning, &error, &fatal, &text);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(success_toggle), success);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(info_toggle), info);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(warning_toggle), warning);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(error_toggle), error);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(fatal_toggle), fatal);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(text_toggle), text);

  gtk_box_pack_start(GTK_BOX(vbox), GTK_WIDGET(menu_bar), FALSE, FALSE, 0);
  gtk_box_pack_start(GTK_BOX(vbox), toolbar, FALSE, FALSE, 0);
  gtk_box_pack_end(GTK_BOX(vbox), GTK_WIDGET(clognav_widget), TRUE, TRUE, 0);

  gtk_container_add(GTK_CONTAINER(toplevel), vbox);
  gtk_widget_show_all(toplevel);

  wow = new CoWowGtk(toplevel);

  *status = 1;
}

//
//  Delete clog
//
CLogGtk::~CLogGtk()
{
  free_cursor();
  delete clognav;
  gtk_widget_destroy(toplevel);
}

void CLogGtk::pop() { gtk_window_present(GTK_WINDOW(toplevel)); }

void CLogGtk::set_clock_cursor()
{
  if (!clock_cursor)
    clock_cursor = gdk_cursor_new_for_display(gtk_widget_get_display(toplevel), GDK_WATCH);

  gdk_window_set_cursor(gtk_widget_get_window(toplevel), clock_cursor);
  gdk_display_flush(gtk_widget_get_display(toplevel));
}

void CLogGtk::reset_cursor() { gdk_window_set_cursor(gtk_widget_get_window(toplevel), NULL); }

void CLogGtk::free_cursor()
{
  if (clock_cursor)
    g_object_unref(clock_cursor);
}

gboolean CLogGtk::action_inputfocus(GtkWidget* w, GdkEvent* event, gpointer data)
{
  CLogGtk* clog = (CLogGtk*)data;

  if (clog && clog->clog_displayed)
    clog->clognav->set_input_focus();

  return FALSE;
}

void CLogGtk::activate_exit(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  if (clog->close_cb)
    (clog->close_cb)(clog->parent_ctx);
  else
    delete clog;
}

void CLogGtk::activate_zoom_in(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->clognav->zoom(1.2);
}

void CLogGtk::activate_zoom_out(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->clognav->zoom(5.0 / 6);
}

void CLogGtk::activate_zoom_reset(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->clognav->unzoom();
}

void CLogGtk::activate_select_file(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;
  char* s;
  pwr_tString80* str;

  str = (pwr_tString80*)calloc(clog->clognav->file_list.size() + 1, sizeof(*str));
  for (int i = 0; i < (int)clog->clognav->file_list.size(); i++)
  {
    time_AtoAscii(&clog->clognav->file_list[i].time, time_eFormat_ComprDateAndTime, str[i], sizeof(str[i]));
    str[i][17] = 0;
    strcat(str[i], "    ");
    s = strrchr(clog->clognav->file_list[i].name, '/');
    if (s)
      strcat(str[i], s + 1);
    else
      strcat(str[i], clog->clognav->file_list[i].name);
  }
  clog->wow->CreateList("Select File", (char*)str, 80, file_selected_cb, 0, clog);

  free(str);
}

void CLogGtk::file_selected_cb(void* ctx, char* text, int ok_pressed)
{
  CLog* clog = (CLog*)ctx;
  int idx = -1;
  char* s;

  // Indentify the index of the selected text
  for (int i = 0; i < (int)clog->clognav->file_list.size(); i++)
  {
    s = strrchr(clog->clognav->file_list[i].name, '/');
    if (s)
      s++;
    else
      s = clog->clognav->file_list[i].name;
    if (streq(s, &text[21]))
    {
      idx = i + 1;
      break;
    }
  }
  if (idx == -1)
    return;

  clog->set_clock_cursor();
  clog->clognav->read(&idx, 1);
  clog->reset_cursor();
}

void CLogGtk::activate_next_file(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->activate_next_file();
}

void CLogGtk::activate_prev_file(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->activate_prev_file();
}

void CLogGtk::activate_update(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->set_clock_cursor();
  clog->clognav->update();
  clog->reset_cursor();
}

void CLogGtk::activate_print(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->activate_print();
}

void CLogGtk::activate_help(GtkWidget* w, gpointer data)
{
  CLog* clog = (CLog*)data;

  clog->activate_help();
}

void CLogGtk::activate_helpmsg(GtkWidget* w, gpointer data) {}

void CLogGtk::print()
{
  char nodename[80];
  pwr_tStatus sts;
  char title[80];

  strcpy(title, Lng::translate("System Messages"));
  syi_NodeName(&sts, nodename, sizeof(nodename));
  if (ODD(sts))
  {
    strcat(title, " ");
    strcat(title, nodename);
  }

  wow->CreateBrowPrintDialog(title, clognav->brow->ctx, flow_eOrientation_Landscape, 1.0, parent_wid, &sts);
  if (sts == WOW__PRINTDIALOGDISABLED)
    wow->DisplayError("Disabled", "Print Dialog is disabled");
}

void CLogGtk::toolbar_apply_filter(GtkWidget* w, gpointer data)
{
  CLogGtk* clog = (CLogGtk*)data;

  // Get filter text
  const char* filter_text = gtk_entry_get_text(GTK_ENTRY(clog->filter_entry));

  // Get severity filter settings from toolbar toggles
  bool success = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(clog->success_toggle));
  bool info = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(clog->info_toggle));
  bool warning = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(clog->warning_toggle));
  bool error = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(clog->error_toggle));
  bool fatal = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(clog->fatal_toggle));
  bool text = gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(clog->text_toggle));

  // Apply filter using existing CLogNav method
  clog->set_clock_cursor();
  clog->clognav->set_filter(success, info, warning, error, fatal, text, filter_text);
  clog->reset_cursor();
}
void CLogGtk::toolbar_clear_filter(GtkWidget* w, gpointer data)
{
  CLogGtk* clog = (CLogGtk*)data;

  // Clear filter text entry
  gtk_entry_set_text(GTK_ENTRY(clog->filter_entry), "");

  // Reset all severity toggles to active
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(clog->success_toggle), TRUE);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(clog->info_toggle), TRUE);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(clog->warning_toggle), TRUE);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(clog->error_toggle), TRUE);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(clog->fatal_toggle), TRUE);
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(clog->text_toggle), TRUE);

  // Clear filter using existing CLogNav method
  clog->set_clock_cursor();
  clog->clognav->set_filter(true, true, true, true, true, true, "");
  clog->reset_cursor();
}
void CLogGtk::toolbar_filter_entry_activate(GtkWidget* w, gpointer data)
{
  // When user presses Enter in filter entry, apply the filter
  toolbar_apply_filter(w, data);
}
